# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#     Copyright (c) 2014+ Type Network
#
#     T N  B I T S
#     No distribution without permission.
#
# -----------------------------------------------------------------------------
#
#    opentype.py
#

class OpenType:

    ##########
    # OPENTYPE
    ##########

#    OPENTYPE_LANGUAGE_TAGS = {'ABA': 'Abaza', 'ABK': 'Abkhazian', 'ADY': 'Adyghe', 'AFK': 'Afrikaans', 'AFR': 'Afar', 'AGW': 'Agaw', 'ALS': 'Alsatian', 'ALT': 'Altai', 'AMH': 'Amharic', 'ARA': 'Arabic', 'ARI': 'Aari', 'ARK': 'Arakanese', 'ASM': 'Assamese', 'ATH': 'Athapaskan', 'AVR': 'Avar', 'AWA': 'Awadhi', 'AYM': 'Aymara', 'AZE': 'Azeri', 'BAD': 'Badaga', 'BAG': 'Baghelkhandi', 'BAL': 'Balkar', 'BAU': 'Baule', 'BBR': 'Berber', 'BCH': 'Bench', 'BCR': 'Bible Cree', 'BEL': 'Belarussian', 'BEM': 'Bemba', 'BEN': 'Bengali', 'BGR': 'Bulgarian', 'BHI': 'Bhili', 'BHO': 'Bhojpuri', 'BIK': 'Bikol', 'BIL': 'Bilen', 'BIS': 'Bislama', 'BKF': 'Blackfoot', 'BLI': 'Balochi', 'BLN': 'Balante', 'BLT': 'Balti', 'BMB': 'Bambara', 'BML': 'Bamileke', 'BOS': 'Bosnian', 'BRE': 'Breton', 'BRH': 'Brahui', 'BRI': 'Braj Bhasha', 'BRM': 'Burmese', 'BSH': 'Bashkir', 'BTI': 'Beti', 'CAT': 'Catalan', 'CEB': 'Cebuano', 'CHE': 'Chechen', 'CHG': 'Chaha Gurage', 'CHH': 'Chattisgarhi', 'CHI': 'Chichewa', 'CHK': 'Chukchi', 'CHP': 'Chipewyan', 'CHR': 'Cherokee', 'CHU': 'Chuvash', 'CMR': 'Comorian', 'COP': 'Coptic', 'COS': 'Corsican', 'CRE': 'Cree', 'CRR': 'Carrier', 'CRT': 'Crimean Tatar', 'CSL': 'Church Slavonic', 'CSY': 'Czech', 'DAN': 'Danish', 'DAR': 'Dargwa', 'DCR': 'Woods Cree', 'DEU': 'German', 'dflt': 'Default', 'DGR': 'Dogri', 'DIV': 'Divehi', 'DJR': 'Djerma', 'DNG': 'Dangme', 'DNK': 'Dinka', 'DRI': 'Dari', 'DUN': 'Dungan', 'DZN': 'Dzongkha', 'EBI': 'Ebira', 'ECR': 'Eastern Cree', 'EDO': 'Edo', 'EFI': 'Efik', 'ELL': 'Greek', 'ENG': 'English', 'ERZ': 'Erzya', 'ESP': 'Spanish', 'ETI': 'Estonian', 'EUQ': 'Basque', 'EVK': 'Evenki', 'EVN': 'Even', 'EWE': 'Ewe', 'FAN': 'French Antillean', 'FAR': 'Farsi', 'FIN': 'Finnish', 'FJI': 'Fijian', 'FLE': 'Flemish', 'FNE': 'Forest Nenets', 'FON': 'Fon', 'FOS': 'Faroese', 'FRA': 'French', 'FRI': 'Frisian', 'FRL': 'Friulian', 'FTA': 'Futa', 'FUL': 'Fulani', 'GAD': 'Ga', 'GAE': 'Gaelic', 'GAG': 'Gagauz', 'GAL': 'Galician', 'GAR': 'Garshuni', 'GAW': 'Garhwali', 'GEZ': "Ge'ez", 'GIL': 'Gilyak', 'GMZ': 'Gumuz', 'GON': 'Gondi', 'GRN': 'Greenlandic', 'GRO': 'Garo', 'GUA': 'Guarani', 'GUJ': 'Gujarati', 'HAI': 'Haitian', 'HAL': 'Halam', 'HAR': 'Harauti', 'HAU': 'Hausa', 'HAW': 'Hawaiian', 'HBN': 'Hammer-Banna', 'HIL': 'Hiligaynon', 'HIN': 'Hindi', 'HMA': 'High Mari', 'HND': 'Hindko', 'HO': 'Ho', 'HRI': 'Harari', 'HRV': 'Croatian', 'HUN': 'Hungarian', 'HYE': 'Armenian', 'IBO': 'Igbo', 'IJO': 'Ijo', 'ILO': 'Ilokano', 'IND': 'Indonesian', 'ING': 'Ingush', 'INU': 'Inuktitut', 'IRI': 'Irish', 'IRT': 'Irish Traditional', 'ISL': 'Icelandic', 'ISM': 'Inari Sami', 'ITA': 'Italian', 'IWR': 'Hebrew', 'JAV': 'Javanese', 'JII': 'Yiddish', 'JAN': 'Japanese', 'JUD': 'Judezmo', 'JUL': 'Jula', 'KAB': 'Kabardian', 'KAC': 'Kachchi', 'KAL': 'Kalenjin', 'KAN': 'Kannada', 'KAR': 'Karachay', 'KAT': 'Georgian', 'KAZ': 'Kazakh', 'KEB': 'Kebena', 'KGE': 'Khutsuri Georgian', 'KHA': 'Khakass', 'KHK': 'Khanty-Kazim', 'KHM': 'Khmer', 'KHS': 'Khanty-Shurishkar', 'KHV': 'Khanty-Vakhi', 'KHW': 'Khowar', 'KIK': 'Kikuyu', 'KIR': 'Kirghiz', 'KIS': 'Kisii', 'KKN': 'Kokni', 'KLM': 'Kalmyk', 'KMB': 'Kamba', 'KMN': 'Kumaoni', 'KMO': 'Komo', 'KMS': 'Komso', 'KNR': 'Kanuri', 'KOD': 'Kodagu', 'KOH': 'Korean Old Hangul', 'KOK': 'Konkani', 'KON': 'Kikongo', 'KOP': 'Komi-Permyak', 'KOR': 'Korean', 'KOZ': 'Komi-Zyrian', 'KPL': 'Kpelle', 'KRI': 'Krio', 'KRK': 'Karakalpak', 'KRL': 'Karelian', 'KRM': 'Karaim', 'KRN': 'Karen', 'KRT': 'Koorete', 'KSH': 'Kashmiri', 'KSI': 'Khasi', 'KSM': 'Kildin Sami', 'KUI': 'Kui', 'KUL': 'Kulvi', 'KUM': 'Kumyk', 'KUR': 'Kurdish', 'KUU': 'Kurukh', 'KUY': 'Kuy', 'KYK': 'Koryak', 'LAD': 'Ladin', 'LAH': 'Lahuli', 'LAK': 'Lak', 'LAM': 'Lambani', 'LAO': 'Lao', 'LAT': 'Latin', 'LAZ': 'Laz', 'LCR': 'L-Cree', 'LDK': 'Ladakhi', 'LEZ': 'Lezgi', 'LIN': 'Lingala', 'LMA': 'Low Mari', 'LMB': 'Limbu', 'LMW': 'Lomwe', 'LSB': 'Lower Sorbian', 'LSM': 'Lule Sami', 'LTH': 'Lithuanian', 'LTZ': 'Luxembourgish', 'LUB': 'Luba', 'LUG': 'Luganda', 'LUH': 'Luhya', 'LUO': 'Luo', 'LVI': 'Latvian', 'MAJ': 'Majang', 'MAK': 'Makua', 'MAL': 'Malayalam Traditional', 'MAN': 'Mansi', 'MAP': 'Mapudungun', 'MAR': 'Marathi', 'MAW': 'Marwari', 'MBN': 'Mbundu', 'MCH': 'Manchu', 'MCR': 'Moose Cree', 'MDE': 'Mende', 'MEN': "Me'en", 'MIZ': 'Mizo', 'MKD': 'Macedonian', 'MLE': 'Male', 'MLG': 'Malagasy', 'MLN': 'Malinke', 'MLR': 'Malayalam Reformed', 'MLY': 'Malay', 'MND': 'Mandinka', 'MNG': 'Mongolian', 'MNI': 'Manipuri', 'MNK': 'Maninka', 'MNX': 'Manx Gaelic', 'MOH': 'Mohawk', 'MOK': 'Moksha', 'MOL': 'Moldavian', 'MON': 'Mon', 'MOR': 'Moroccan', 'MRI': 'Maori', 'MTH': 'Maithili', 'MTS': 'Maltese', 'MUN': 'Mundari', 'NAG': 'Naga-Assamese', 'NAN': 'Nanai', 'NAS': 'Naskapi', 'NCR': 'N-Cree', 'NDB': 'Ndebele', 'NDG': 'Ndonga', 'NEP': 'Nepali', 'NEW': 'Newari', 'NGR': 'Nagari', 'NHC': 'Norway House Cree', 'NIS': 'Nisi', 'NIU': 'Niuean', 'NKL': 'Nkole', 'NKO': "N'ko", 'NLD': 'Dutch', 'NOG': 'Nogai', 'NOR': 'Norwegian', 'NSM': 'Northern Sami', 'NTA': 'Northern Tai', 'NTO': 'Esperanto', 'NYN': 'Nynorsk', 'OCI': 'Occitan', 'OCR': 'Oji-Cree', 'OJB': 'Ojibway', 'ORI': 'Oriya', 'ORO': 'Oromo', 'OSS': 'Ossetian', 'PAA': 'Palestinian Aramaic', 'PAL': 'Pali', 'PAN': 'Punjabi', 'PAP': 'Palpa', 'PAS': 'Pashto', 'PGR': 'Polytonic Greek', 'PIL': 'Pilipino', 'PLG': 'Palaung', 'PLK': 'Polish', 'PRO': 'Provencal', 'PTG': 'Portuguese', 'QIN': 'Chin', 'RAJ': 'Rajasthani', 'RCR': 'R-Cree', 'RBU': 'Russian Buriat', 'RIA': 'Riang', 'RMS': 'Rhaeto-Romanic', 'ROM': 'Romanian', 'ROY': 'Romany', 'RSY': 'Rusyn', 'RUA': 'Ruanda', 'RUS': 'Russian', 'SAD': 'Sadri', 'SAN': 'Sanskrit', 'SAT': 'Santali', 'SAY': 'Sayisi', 'SEK': 'Sekota', 'SEL': 'Selkup', 'SGO': 'Sango', 'SHN': 'Shan', 'SIB': 'Sibe', 'SID': 'Sidamo', 'SIG': 'Silte Gurage', 'SKS': 'Skolt Sami', 'SKY': 'Slovak', 'SLA': 'Slavey', 'SLV': 'Slovenian', 'SML': 'Somali', 'SMO': 'Samoan', 'SNA': 'Sena', 'SND': 'Sindhi', 'SNH': 'Sinhalese', 'SNK': 'Soninke', 'SOG': 'Sodo Gurage', 'SOT': 'Sotho', 'SQI': 'Albanian', 'SRB': 'Serbian', 'SRK': 'Saraiki', 'SRR': 'Serer', 'SSL': 'South Slavey', 'SSM': 'Southern Sami', 'SUR': 'Suri', 'SVA': 'Svan', 'SVE': 'Swedish', 'SWA': 'Swadaya Aramaic', 'SWK': 'Swahili', 'SWZ': 'Swazi', 'SXT': 'Sutu', 'SYR': 'Syriac', 'TAB': 'Tabasaran', 'TAJ': 'Tajiki', 'TAM': 'Tamil', 'TAT': 'Tatar', 'TCR': 'TH-Cree', 'TEL': 'Telugu', 'TGN': 'Tongan', 'TGR': 'Tigre', 'TGY': 'Tigrinya', 'THA': 'Thai', 'THT': 'Tahitian', 'TIB': 'Tibetan', 'TKM': 'Turkmen', 'TMN': 'Temne', 'TNA': 'Tswana', 'TNE': 'Tundra Nenets', 'TNG': 'Tonga', 'TOD': 'Todo', 'TRK': 'Turkish', 'TSG': 'Tsonga', 'TUA': 'Turoyo Aramaic', 'TUL': 'Tulu', 'TUV': 'Tuvin', 'TWI': 'Twi', 'UDM': 'Udmurt', 'UKR': 'Ukrainian', 'URD': 'Urdu', 'USB': 'Upper Sorbian', 'UYG': 'Uyghur', 'UZB': 'Uzbek', 'VEN': 'Venda', 'VIT': 'Vietnamese', 'WA': 'Wa', 'WAG': 'Wagdi', 'WCR': 'West-Cree', 'WEL': 'Welsh', 'WLF': 'Wolof', 'XBD': 'Tai Lue', 'XHS': 'Xhosa', 'YAK': 'Yakut', 'YBA': 'Yoruba', 'YCR': 'Y-Cree', 'YIC': 'Yi Classic', 'YIM': 'Yi Modern', 'ZHH': 'Chinese Hong Kong', 'ZHP': 'Chinese Phonetic', 'ZHS': 'Chinese Simplified', 'ZHT': 'Chinese Traditional', 'ZND': 'Zande', 'ZUL': 'Zulu'}
    OPENTYPE_LANGUAGE_TAGS = {'ABA': 'Abaza', 'ABK': 'Abkhazian', 'ACH': 'Acholi', 'ACR': 'Achi', 'ADY': 'Adyghe', 'AFK': 'Afrikaans', 'AFR': 'Afar', 'AGW': 'Agaw', 'AIO': 'Aiton', 'AKA': 'Akan', 'ALS': 'Alsatian', 'ALT': 'Altai', 'AMH': 'Amharic', 'ANG': 'Anglo-Saxon', 'APPH': 'Phonetic transcription—Americanist conventions', 'ARA': 'Arabic', 'ARG': 'Aragonese', 'ARI': 'Aari', 'ARK': 'Rakhine', 'ASM': 'Assamese', 'AST': 'Asturian', 'ATH': 'Athapaskan', 'AVR': 'Avar', 'AWA': 'Awadhi', 'AYM': 'Aymara', 'AZB': 'Torki', 'AZE': 'Azerbaijani', 'BAD': 'Badaga', 'BAD0': 'Banda', 'BAG': 'Baghelkhandi', 'BAL': 'Balkar', 'BAN': 'Balinese', 'BAR': 'Bavarian', 'BAU': 'Baulé', 'BBC': 'Batak Toba', 'BBR': 'Berber', 'BCH': 'Bench', 'BCR': 'Bible Cree', 'BDY': 'Bandjalang', 'BEL': 'Belarussian', 'BEM': 'Bemba', 'BEN': 'Bengali', 'BGC': 'Haryanvi', 'BGQ': 'Bagri', 'BGR': 'Bulgarian', 'BHI': 'Bhili', 'BHO': 'Bhojpuri', 'BIK': 'Bikol', 'BIL': 'Bilen', 'BIS': 'Bislama', 'BJJ': 'Kanauji', 'BKF': 'Blackfoot', 'BLI': 'Baluchi', 'BLK': 'Pao Karen', 'BLN': 'Balante', 'BLT': 'Balti', 'BMB': 'Bambara (Bamanankan)', 'BML': 'Bamileke', 'BOS': 'Bosnian', 'BPY': 'Bishnupriya Manipuri', 'BRE': 'Breton', 'BRH': 'Brahui', 'BRI': 'Braj Bhasha', 'BRM': 'Burmese', 'BRX': 'Bodo', 'BSH': 'Bashkir', 'BTI': 'Beti', 'BTS': 'Batak Simalungun', 'BUG': 'Bugis', 'CAK': 'Kaqchikel', 'CAT': 'Catalan', 'CBK': 'Zamboanga Chavacano', 'CEB': 'Cebuano', 'CHE': 'Chechen', 'CHG': 'Chaha Gurage', 'CHH': 'Chattisgarhi', 'CHI': 'Chichewa (Chewa, Nyanja)', 'CHK': 'Chukchi', 'CHK0': 'Chuukese', 'CHO': 'Choctaw', 'CHP': 'Chipewyan', 'CHR': 'Cherokee', 'CHA': 'Chamorro', 'CHU': 'Chuvash', 'CHY': 'Cheyenne', 'CGG': 'Chiga', 'CMR': 'Comorian', 'COP': 'Coptic', 'COR': 'Cornish', 'COS': 'Corsican', 'CPP': 'Creoles', 'CRE': 'Cree', 'CRR': 'Carrier', 'CRT': 'Crimean Tatar', 'CSB': 'Kashubian', 'CSL': 'Church Slavonic', 'CSY': 'Czech', 'CTG': 'Chittagonian', 'CUK': 'San Blas Kuna', 'DAN': 'Danish', 'DAR': 'Dargwa', 'DAX': 'Dayi', 'DCR': 'Woods Cree', 'DEU': 'German', 'DGO': 'Dogri', 'DGR': 'Dogri', 'DHG': 'Dhangu', 'DIQ': 'Dimli', 'DIV': 'Divehi (Dhivehi, Maldivian)', 'DJR': 'Zarma', 'DJR0': 'Djambarrpuyngu', 'DNG': 'Dangme', 'DNJ': 'Dan', 'DNK': 'Dinka', 'DRI': 'Dari', 'DUJ': 'Dhuwal', 'DUN': 'Dungan', 'DZN': 'Dzongkha', 'EBI': 'Ebira', 'ECR': 'Eastern Cree', 'EDO': 'Edo', 'EFI': 'Efik', 'ELL': 'Greek', 'EMK': 'Eastern Maninkakan', 'ENG': 'English', 'ERZ': 'Erzya', 'ESP': 'Spanish', 'ESU': 'Central Yupik', 'ETI': 'Estonian', 'EUQ': 'Basque', 'EVK': 'Evenki', 'EVN': 'Even', 'EWE': 'Ewe', 'FAN': 'French Antillean', 'FAN0': 'Fang', 'FAR': 'Persian', 'FAT': 'Fanti', 'FIN': 'Finnish', 'FJI': 'Fijian', 'FLE': 'Dutch (Flemish)', 'FNE': 'Forest Nenets', 'FON': 'Fon', 'FOS': 'Faroese', 'FRA': 'French', 'FRC': 'Cajun French', 'FRI': 'Frisian', 'FRL': 'Friulian', 'FRP': 'Arpitan', 'FTA': 'Futa', 'FUL': 'Fulah', 'FUV': 'Nigerian Fulfulde', 'GAD': 'Ga', 'GAE': 'Scottish Gaelic (Gaelic)', 'GAG': 'Gagauz', 'GAL': 'Galician', 'GAR': 'Garshuni', 'GAW': 'Garhwali', 'GEZ': 'Geez', 'GIH': 'Githabul', 'GIL': 'Gilyak', 'GIL0': 'Kiribati (Gilbertese)', 'GKP': 'Kpelle (Guinea)', 'GLK': 'Gilaki', 'GMZ': 'Gumuz', 'GNN': 'Gumatj', 'GOG': 'Gogo', 'GON': 'Gondi', 'GRN': 'Greenlandic', 'GRO': 'Garo', 'GUA': 'Guarani', 'GUC': 'Wayuu', 'GUF': 'Gupapuyngu', 'GUJ': 'Gujarati', 'GUZ': 'Gusii', 'HAI': 'Haitian (Haitian Creole)', 'HAL': 'Halam', 'HAR': 'Harauti', 'HAU': 'Hausa', 'HAW': 'Hawaiian', 'HAY': 'Haya', 'HAZ': 'Hazaragi', 'HBN': 'Hammer-Banna', 'HER': 'Herero', 'HIL': 'Hiligaynon', 'HIN': 'Hindi', 'HMA': 'High Mari', 'HMN': 'Hmong', 'HMO': 'Hiri Motu', 'HND': 'Hindko', 'HO': 'Ho', 'HRI': 'Harari', 'HRV': 'Croatian', 'HUN': 'Hungarian', 'HYE': 'Armenian', 'HYE0': 'Armenian East', 'IBA': 'Iban', 'IBB': 'Ibibio', 'IBO': 'Igbo', 'IJO': 'Ijo languages', 'IDO': 'Ido', 'ILE': 'Interlingue', 'ILO': 'Ilokano', 'INA': 'Interlingua', 'IND': 'Indonesian', 'ING': 'Ingush', 'INU': 'Inuktitut', 'IPK': 'Inupiat', 'IPPH': 'Phonetic transcription—IPA conventions', 'IRI': 'Irish', 'IRT': 'Irish Traditional', 'ISL': 'Icelandic', 'ISM': 'Inari Sami', 'ITA': 'Italian', 'IWR': 'Hebrew', 'JAM': 'Jamaican Creole', 'JAN': 'Japanese', 'JAV': 'Javanese', 'JBO': 'Lojban', 'JII': 'Yiddish', 'JUD': 'Ladino', 'JUL': 'Jula', 'KAB': 'Kabardian', 'KAB0': 'Kabyle', 'KAC': 'Kachchi', 'KAL': 'Kalenjin', 'KAN': 'Kannada', 'KAR': 'Karachay', 'KAT': 'Georgian', 'KAZ': 'Kazakh', 'KDE': 'Makonde', 'KEA': 'Kabuverdianu (Crioulo)', 'KEB': 'Kebena', 'KEK': 'Kekchi', 'KGE': 'Khutsuri Georgian', 'KHA': 'Khakass', 'KHK': 'Khanty-Kazim', 'KHM': 'Khmer', 'KHS': 'Khanty-Shurishkar', 'KHT': 'Khamti Shan', 'KHV': 'Khanty-Vakhi', 'KHW': 'Khowar', 'KIK': 'Kikuyu (Gikuyu)', 'KIR': 'Kirghiz (Kyrgyz)', 'KIS': 'Kisii', 'KIU': 'Kirmanjki', 'KJD': 'Southern Kiwai', 'KJP': 'Eastern Pwo Karen', 'KKN': 'Kokni', 'KLM': 'Kalmyk', 'KMB': 'Kamba', 'KMN': 'Kumaoni', 'KMO': 'Komo', 'KMS': 'Komso', 'KNR': 'Kanuri', 'KOD': 'Kodagu', 'KOH': 'Korean Old Hangul', 'KOK': 'Konkani', 'KON': 'Kikongo', 'KOM': 'Komi', 'KON0': 'Kongo', 'KOP': 'Komi-Permyak', 'KOR': 'Korean', 'KOS': 'Kosraean', 'KOZ': 'Komi-Zyrian', 'KPL': 'Kpelle', 'KRI': 'Krio', 'KRK': 'Karakalpak', 'KRL': 'Karelian', 'KRM': 'Karaim', 'KRN': 'Karen', 'KRT': 'Koorete', 'KSH': 'Kashmiri', 'KSH0': 'Ripuarian', 'KSI': 'Khasi', 'KSM': 'Kildin Sami', 'KSW': 'S’gaw Karen', 'KUA': 'Kuanyama', 'KUI': 'Kui', 'KUL': 'Kulvi', 'KUM': 'Kumyk', 'KUR': 'Kurdish', 'KUU': 'Kurukh', 'KUY': 'Kuy', 'KYK': 'Koryak', 'KYU': 'Western Kayah', 'LAD': 'Ladin', 'LAH': 'Lahuli', 'LAK': 'Lak', 'LAM': 'Lambani', 'LAO': 'Lao', 'LAT': 'Latin', 'LAZ': 'Laz', 'LCR': 'L-Cree', 'LDK': 'Ladakhi', 'LEZ': 'Lezgi', 'LIJ': 'Ligurian', 'LIM': 'Limburgish', 'LIN': 'Lingala', 'LIS': 'Lisu', 'LJP': 'Lampung', 'LKI': 'Laki', 'LMA': 'Low Mari', 'LMB': 'Limbu', 'LMO': 'Lombard', 'LMW': 'Lomwe', 'LOM': 'Loma', 'LRC': 'Luri', 'LSB': 'Lower Sorbian', 'LSM': 'Lule Sami', 'LTH': 'Lithuanian', 'LTZ': 'Luxembourgish', 'LUA': 'Luba-Lulua', 'LUB': 'Luba-Katanga', 'LUG': 'Ganda', 'LUH': 'Luyia', 'LUO': 'Luo', 'LVI': 'Latvian', 'MAD': 'Madura', 'MAG': 'Magahi', 'MAH': 'Marshallese', 'MAJ': 'Majang', 'MAK': 'Makhuwa', 'MAL': 'Malayalam', 'MAM': 'Mam', 'MAN': 'Mansi', 'MAP': 'Mapudungun', 'MAR': 'Marathi', 'MAW': 'Marwari', 'MBN': 'Mbundu', 'MCH': 'Manchu', 'MCR': 'Moose Cree', 'MDE': 'Mende', 'MDR': 'Mandar', 'MEN': 'Meen', 'MER': 'Meru', 'MFE': 'Morisyen', 'MIN': 'Minangkabau', 'MIZ': 'Mizo', 'MKD': 'Macedonian', 'MKR': 'Makasar', 'MKW': 'Kituba', 'MLE': 'Male', 'MLG': 'Malagasy', 'MLN': 'Malinke', 'MLR': 'Malayalam Reformed', 'MLY': 'Malay', 'MND': 'Mandinka', 'MNG': 'Mongolian', 'MNI': 'Manipuri', 'MNK': 'Maninka', 'MNX': 'Manx', 'MOH': 'Mohawk', 'MOK': 'Moksha', 'MOL': 'Moldavian', 'MON': 'Mon', 'MOR': 'Moroccan', 'MOS': 'Mossi', 'MRI': 'Maori', 'MTH': 'Maithili', 'MTS': 'Maltese', 'MUN': 'Mundari', 'MUS': 'Muscogee', 'MWL': 'Mirandese', 'MWW': 'Hmong Daw', 'MYN': 'Mayan', 'MZN': 'Mazanderani', 'NAG': 'Naga-Assamese', 'NAH': 'Nahuatl', 'NAN': 'Nanai', 'NAP': 'Neapolitan', 'NAS': 'Naskapi', 'NAU': 'Nauruan', 'NAV': 'Navajo', 'NCR': 'N-Cree', 'NDB': 'Ndebele', 'NDC': 'Ndau', 'NDG': 'Ndonga', 'NDS': 'Low Saxon', 'NEP': 'Nepali', 'NEW': 'Newari', 'NGA': 'Ngbaka', 'NGR': 'Nagari', 'NHC': 'Norway House Cree', 'NIS': 'Nisi', 'NIU': 'Niuean', 'NKL': 'Nyankole', 'NKO': 'NKo', 'NLD': 'Dutch', 'NOE': 'Nimadi', 'NOG': 'Nogai', 'NOR': 'Norwegian', 'NOV': 'Novial', 'NSM': 'Northern Sami', 'NSO': 'Sotho, Northern', 'NTA': 'Northern Tai', 'NTO': 'Esperanto', 'NYM': 'Nyamwezi', 'NYN': 'Norwegian Nynorsk (Nynorsk, Norwegian)', 'OCI': 'Occitan', 'OCR': 'Oji-Cree', 'OJB': 'Ojibway', 'ORI': 'Odia (formerly Oriya)', 'ORO': 'Oromo', 'OSS': 'Ossetian', 'PAA': 'Palestinian Aramaic', 'PAG': 'Pangasinan', 'PAL': 'Pali', 'PAM': 'Pampangan', 'PAN': 'Punjabi', 'PAP': 'Palpa', 'PAP0': 'Papiamentu', 'PAS': 'Pashto', 'PAU': 'Palauan', 'PCC': 'Bouyei', 'PCD': 'Picard', 'PDC': 'Pennsylvania German', 'PGR': 'Polytonic Greek', 'PHK': 'Phake', 'PIH': 'Norfolk', 'PIL': 'Filipino', 'PLG': 'Palaung', 'PLK': 'Polish', 'PMS': 'Piemontese', 'PNB': 'Western Panjabi', 'POH': 'Pocomchi', 'PON': 'Pohnpeian', 'PRO': 'Provencal', 'PTG': 'Portuguese', 'PWO': 'Western Pwo Karen', 'QIN': 'Chin', 'QUC': 'K’iche’', 'QUH': 'Quechua (Bolivia)', 'QUZ': 'Quechua', 'QVI': 'Quechua (Ecuador)', 'QWH': 'Quechua (Peru)', 'RAJ': 'Rajasthani', 'RAR': 'Rarotongan', 'RBU': 'Russian Buriat', 'RCR': 'R-Cree', 'REJ': 'Rejang', 'RIA': 'Riang', 'RIF': 'Tarifit', 'RIT': 'Ritarungo', 'RKW': 'Arakwal', 'RMS': 'Romansh', 'RMY': 'Vlax Romani', 'ROM': 'Romanian', 'ROY': 'Romany', 'RSY': 'Rusyn', 'RTM': 'Rotuman', 'RUA': 'Kinyarwanda', 'RUN': 'Rundi', 'RUP': 'Aromanian', 'RUS': 'Russian', 'SAD': 'Sadri', 'SAN': 'Sanskrit', 'SAS': 'Sasak', 'SAT': 'Santali', 'SAY': 'Sayisi', 'SCN': 'Sicilian', 'SCO': 'Scots', 'SEK': 'Sekota', 'SEL': 'Selkup', 'SGA': 'Old Irish', 'SGO': 'Sango', 'SGS': 'Samogitian', 'SHI': 'Tachelhit', 'SHN': 'Shan', 'SIB': 'Sibe', 'SID': 'Sidamo', 'SIG': 'Silte Gurage', 'SKS': 'Skolt Sami', 'SKY': 'Slovak', 'SLA': 'Slavey', 'SLV': 'Slovenian', 'SML': 'Somali', 'SMO': 'Samoan', 'SNA': 'Sena', 'SNA0': 'Shona', 'SND': 'Sindhi', 'SNH': 'Sinhala (Sinhalese)', 'SNK': 'Soninke', 'SOG': 'Sodo Gurage', 'SOP': 'Songe', 'SOT': 'Sotho, Southern', 'SQI': 'Albanian', 'SRB': 'Serbian', 'SRD': 'Sardinian', 'SRK': 'Saraiki', 'SRR': 'Serer', 'SSL': 'South Slavey', 'SSM': 'Southern Sami', 'STQ': 'Saterland Frisian', 'SUK': 'Sukuma', 'SUN': 'Sundanese', 'SUR': 'Suri', 'SVA': 'Svan', 'SVE': 'Swedish', 'SWA': 'Swadaya Aramaic', 'SWK': 'Swahili', 'SWZ': 'Swati', 'SXT': 'Sutu', 'SXU': 'Upper Saxon', 'SYL': 'Sylheti', 'SYR': 'Syriac', 'SZL': 'Silesian', 'TAB': 'Tabasaran', 'TAJ': 'Tajiki', 'TAM': 'Tamil', 'TAT': 'Tatar', 'TCR': 'TH-Cree', 'TDD': 'Dehong Dai', 'TEL': 'Telugu', 'TET': 'Tetum', 'TGL': 'Tagalog', 'TGN': 'Tongan', 'TGR': 'Tigre', 'TGY': 'Tigrinya', 'THA': 'Thai', 'THT': 'Tahitian', 'TIB': 'Tibetan', 'TIV': 'Tiv', 'TKM': 'Turkmen', 'TMH': 'Tamashek', 'TMN': 'Temne', 'TNA': 'Tswana', 'TNE': 'Tundra Nenets', 'TNG': 'Tonga', 'TOD': 'Todo', 'TOD0': 'Toma', 'TPI': 'Tok Pisin', 'TRK': 'Turkish', 'TSG': 'Tsonga', 'TUA': 'Turoyo Aramaic', 'TUL': 'Tulu', 'TUV': 'Tuvin', 'TVL': 'Tuvalu', 'TWI': 'Twi', 'TYZ': 'Tày', 'TZM': 'Tamazight', 'TZO': 'Tzotzil', 'UDM': 'Udmurt', 'UKR': 'Ukrainian', 'UMB': 'Umbundu', 'URD': 'Urdu', 'USB': 'Upper Sorbian', 'UYG': 'Uyghur', 'UZB': 'Uzbek', 'VEC': 'Venetian', 'VEN': 'Venda', 'VIT': 'Vietnamese', 'VOL': 'Volapük', 'VRO': 'Võro', 'WA': 'Wa', 'WAG': 'Wagdi', 'WAR': 'Waray-Waray', 'WCR': 'West-Cree', 'WEL': 'Welsh', 'WLN': 'Walloon', 'WLF': 'Wolof', 'XBD': 'Lü', 'XHS': 'Xhosa', 'XJB': 'Minjangbal', 'XOG': 'Soga', 'XPE': 'Kpelle (Liberia)', 'YAK': 'Sakha', 'YAO': 'Yao', 'YAP': 'Yapese', 'YBA': 'Yoruba', 'YCR': 'Y-Cree', 'YIC': 'Yi Classic', 'YIM': 'Yi Modern', 'ZEA': 'Zealandic', 'ZGH': 'Standard Morrocan Tamazigh', 'ZHA': 'Zhuang', 'ZHH': 'Chinese, Hong Kong SAR', 'ZHP': 'Chinese Phonetic', 'ZHS': 'Chinese Simplified', 'ZHT': 'Chinese Traditional', 'ZND': 'Zande', 'ZUL': 'Zulu', 'ZZA': 'Zazaki'}

    OPENTYPE_SCRIPT_TAGS = {
        'arab': 'Arabic',
        'armn': 'Armenian',
        'bali': 'Balinese',
        'beng': 'Bengali',
        'bopo': 'Bopomofo',
        'brai': 'Braille',
        'bugi': 'Buginese',
        'buhd': 'Buhid',
        'byzm': 'Byzantine Music',
        'cans': 'Canadian Syllabics',
        'cher': 'Cherokee',
        'hani': 'CJK Ideographic',
        'copt': 'Coptic',
        'cprt': 'Cypriot Syllabary',
        'cyrl': 'Cyrillic',
        'DFLT': 'Default',
        'dsrt': 'Deseret',
        'deva': 'Devanagari',
        'ethi': 'Ethiopic',
        'geor': 'Georgian',
        'glag': 'Glagolitic',
        'goth': 'Gothic',
        'grek': 'Greek',
        'gujr': 'Gujarati',
        'guru': 'Gurmukhi',
        'jamo': 'Hangul Jamo',
        'hang': 'Hangul',
        'hano': 'Hanunoo',
        'hebr': 'Hebrew',
        'kana': 'Hiragana and Katakana',
        'java': 'Javanese',
        'knda': 'Kannada',
        'khar': 'Kharosthi',
        'khmr': 'Khmer',
        'lao': 'Lao',
        'latn': 'Latin',
        'limb': 'Limbu',
        'linb': 'Linear B',
        'mlym': 'Malayalam',
        'math': 'Mathematical Alphanumeric Symbols',
        'mong': 'Mongolian',
        'musc': 'Musical Symbols',
        'mymr': 'Myanmar',
        'nko': "N'ko",
        'ogam': 'Ogham',
        'ital': 'Old Italic',
        'xpeo': 'Old Persian Cuneiform',
        'orya': 'Oriya',
        'osma': 'Osmanya',
        'phag': 'Phags-pa',
        'phnx': 'Phoenician',
        'runr': 'Runic',
        'shaw': 'Shavian',
        'sinh': 'Sinhala',
        'xsux': 'Sumero-Akkadian Cuneiform',
        'sylo': 'Syloti Nagri',
        'syrc': 'Syriac',
        'tglg': 'Tagalog',
        'tagb': 'Tagbanwa',
        'tale': 'Tai Le',
        'talu': 'Tai Lu',
        'taml': 'Tamil',
        'telu': 'Telugu',
        'thaa': 'Thaana',
        'thai': 'Thai',
        'tibt': 'Tibetan',
        'tfng': 'Tifinagh',
        'ugar': 'Ugaritic Cuneiform',
        'yi': 'Yi',
        }


    OPENTYPE_FEATURE_TAGS = {
    "aalt": "Access All Alternates",
    "abvf": "Above-base Forms",
    "abvm": "Above-base Mark Positioning",
    "abvs": "Above-base Substitutions",
    "afrc": "Alternative Fractions",
    "akhn": "Akhands",
    "blwf": "Below-base Forms",
    "blwm": "Below-base Mark Positioning",
    "blws": "Below-base Substitutions",
    "calt": "Contextual Alternates",
    "case": "Case-Sensitive Forms",
    "ccmp": "Glyph Composition / Decomposition",
    "cfar": "Conjunct Form After Ro",
    "cjct": "Conjunct Forms",
    "clig": "Contextual Ligatures",
    "cpct": "Centered CJK Punctuation",
    "cpsp": "Capital Spacing",
    "cswh": "Contextual Swash",
    "curs": "Cursive Positioning",
    "c2pc": "Petite Capitals From Capitals",
    "c2sc": "Small Capitals From Capitals",
    "dist": "Distances",
    "dlig": "Discretionary Ligatures",
    "dnom": "Denominators",
    "expt": "Expert Forms",
    "falt": "Final Glyph on Line Alternates",
    "fin2": "Terminal Forms #2",
    "fin3": "Terminal Forms #3",
    "fina": "Terminal Forms",
    "frac": "Fractions",
    "fwid": "Full Widths",
    "half": "Half Forms",
    "haln": "Halant Forms",
    "halt": "Alternate Half Widths",
    "hist": "Historical Forms",
    "hkna": "Horizontal Kana Alternates",
    "hlig": "Historical Ligatures",
    "hngl": "Hangul",
    "hojo": "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)",
    "hwid": "Half Widths",
    "init": "Initial Forms",
    "isol": "Isolated Forms",
    "ital": "Italics",
    "jalt": "Justification Alternates",
    "jp78": "JIS78 Forms",
    "jp83": "JIS83 Forms",
    "jp90": "JIS90 Forms",
    "jp04": "JIS2004 Forms",
    "kern": "Kerning",
    "lfbd": "Left Bounds",
    "liga": "Standard Ligatures",
    "ljmo": "Leading Jamo Forms",
    "lnum": "Lining Figures",
    "locl": "Localized Forms",
    "ltra": "Left-to-right alternates",
    "ltrm": "Left-to-right mirrored forms",
    "mark": "Mark Positioning",
    "med2": "Medial Forms #2",
    "medi": "Medial Forms",
    "mgrk": "Mathematical Greek",
    "mkmk": "Mark to Mark Positioning",
    "mset": "Mark Positioning via Substitution",
    "nalt": "Alternate Annotation Forms",
    "nlck": "NLC Kanji Forms",
    "nukt": "Nukta Forms",
    "numr": "Numerators",
    "onum": "Oldstyle Figures",
    "opbd": "Optical Bounds",
    "ordn": "Ordinals",
    "ornm": "Ornaments",
    "palt": "Proportional Alternate Widths",
    "pcap": "Petite Capitals",
    "pkna": "Proportional Kana",
    "pnum": "Proportional Figures",
    "pref": "Pre-Base Forms",
    "pres": "Pre-base Substitutions",
    "pstf": "Post-base Forms",
    "psts": "Post-base Substitutions",
    "pwid": "Proportional Widths",
    "qwid": "Quarter Widths",
    "rand": "Randomize",
    "rkrf": "Rakar Forms",
    "rlig": "Required Ligatures",
    "rphf": "Reph Forms",
    "rtbd": "Right Bounds",
    "rtla": "Right-to-left alternates",
    "rtlm": "Right-to-left mirrored forms",
    "ruby": "Ruby Notation Forms",
    "salt": "Stylistic Alternates",
    "sinf": "Scientific Inferiors",
    "size": "Optical size",
    "smcp": "Small Capitals",
    "smpl": "Simplified Forms",
    "ss01": "Stylistic Set 1",
    "ss02": "Stylistic Set 2",
    "ss03": "Stylistic Set 3",
    "ss04": "Stylistic Set 4",
    "ss05": "Stylistic Set 5",
    "ss06": "Stylistic Set 6",
    "ss07": "Stylistic Set 7",
    "ss08": "Stylistic Set 8",
    "ss09": "Stylistic Set 9",
    "ss10": "Stylistic Set 10",
    "ss11": "Stylistic Set 11",
    "ss12": "Stylistic Set 12",
    "ss13": "Stylistic Set 13",
    "ss14": "Stylistic Set 14",
    "ss15": "Stylistic Set 15",
    "ss16": "Stylistic Set 16",
    "ss17": "Stylistic Set 17",
    "ss18": "Stylistic Set 18",
    "ss19": "Stylistic Set 19",
    "ss20": "Stylistic Set 20",
    "subs": "Subscript",
    "sups": "Superscript",
    "swsh": "Swash",
    "titl": "Titling",
    "tjmo": "Trailing Jamo Forms",
    "tnam": "Traditional Name Forms",
    "tnum": "Tabular Figures",
    "trad": "Traditional Forms",
    "twid": "Third Widths",
    "unic": "Unicase",
    "valt": "Alternate Vertical Metrics",
    "vatu": "Vattu Variants",
    "vert": "Vertical Writing",
    "vhal": "Alternate Vertical Half Metrics",
    "vjmo": "Vowel Jamo Forms",
    "vkna": "Vertical Kana Alternates",
    "vkrn": "Vertical Kerning",
    "vpal": "Proportional Alternate Vertical Metrics",
    "vrt2": "Vertical Alternates and Rotation",
    "zero": "Slashed Zero",
}
#    "cv01-cv99": "Character Variants",




    # ---------------------------------------------------------------------------------------------------------
    #     T A B L E S

    TABLE_MAXP = 'maxp'
    TABLE_CVT = 'cvt ' # With space!
    TABLE_PREP = 'prep'
    TABLE_FPGM = 'fpgm'
    TABLE_GLYF = 'glyf'


