# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Copyright (c) 2023+ TYPETR
#     Usage by MIT License
# ..............................................................................
#
#   glyphSet_anchors.py
#
#   These are standard sets of glyphs + their most common anchor names.

class AnchorData:

    # Add needed anchors
    _TOP = '_top' # Initial underscore must be imported by their name, not by *
    TOP_ = 'top'
    _BOTTOM = '_bottom'
    BOTTOM_ = 'bottom'
    _RING = '_ring'
    RING_ = 'ring'
    _OGONEK = '_ogonek'
    OGONEK_ = 'ogonek'
    _VERT = '_vert'
    VERT_ = 'vert'
    _DOT = '_dot'
    DOT_ = 'dot'
    _TILDE = '_tilde'
    TILDE_ = 'tilde'
    _TONOS = '_tonos'
    TONOS_ = 'tonos_'
    _HORN = '_horn'
    HORN_ = 'horn'
    _MIDDLE = '_middle'
    MIDDLE_ = 'middle'

    CONNECTED_ANCHORS = {
        _TOP: TOP_,
        _BOTTOM: BOTTOM_,
        _RING: RING_,
        _OGONEK: OGONEK_,
        _VERT: VERT_,
        _DOT: DOT_,
        _TILDE: TILDE_,
        _TONOS: TONOS_, # Also anchor of the other -uc accents
        _HORN: HORN_,
        _MIDDLE: MIDDLE_,

    } 
    DIACRITICS_ANCHORS = [] # List of _<anchorName> as used in diacritics positioning
    # Make X-ref
    for key, value in list(CONNECTED_ANCHORS.items()):
        CONNECTED_ANCHORS[value] = key
        DIACRITICS_ANCHORS.append(key)

    # Colors for anchor positions, separate for each type of anchor
    GUESS_ANCHOR_COLORS = {
        TOP_:       (1, 0, 0, 1),
        _TOP:       (0.5, 0, 0, 1),
        BOTTOM_:    (0, 0.5, 0, 17),
        _BOTTOM:    (0, 0.25, 0, 1),
        MIDDLE_:    (0, 0, 1, 1),
        _MIDDLE:    (0, 0, 0.5, 1),
        DOT_:       (0, 0, 1, 1),
        _DOT:       (0, 0, 0.5, 1),
        VERT_:      (1, 0, 1, 1),
        _VERT:      (0.5, 0, 0.5, 1),
        OGONEK_:    (1, 0.5, 0, 1),
        _OGONEK:    (0.5, 0.25, 0, 1),
        TONOS_:     (0, 0.5, 1, 1),
        _TONOS:     (0, 0.25, 0.5, 1),
        HORN_:      (0, 0.5, 1, 1),
        _HORN:      (0, 0.25, 0.5, 1),
    }
    # Method names that are implenented to guess the position of anchors.
    GUESS_ANCHOR_ZERO_WIDTH_X = 'guessAnchorZeroWidthX'
    GUESS_ANCHOR_BASE_X = 'guessAnchorBaseX'
    GUESS_ANCHOR_CENTER_WIDTH = 'guessAnchorCenterWidth'
    GUESS_ANCHOR_BOX_CENTER_X = 'guessAnchorBoxCenterX'
    GUESS_ANCHOR_OGONEK_X = 'guessAnchorOgonekX'
    GUESS_ANCHOR_DOT_X = 'guessAnchorDotX'
    GUESS_ANCHOR_VERT_X = 'guessAnchorVertX'
    GUESS_ANCHOR_TONOS_X = 'guessAnchorTonosX'
    GUESS_ANCHOR_X = 'guessAnchorX' # Default behavior is to answer the x position of the current anchor

    GUESS_ANCHOR_BASE_Y = 'guessAnchorBaseY'
    GUESS_ANCHOR_BASELINE = 'guessAnchorBaseline'
    GUESS_ANCHOR_VERT_Y = 'guessAnchorVertY'
    GUESS_ANCHOR_VERT_ASCENDER_Y = 'guessAnchorVertAscenderY'
    GUESS_ANCHOR_HEIGHT = 'guessAnchorHeight'
    GUESS_ANCHOR_BOX_TOP = 'guessAnchorBoxTop' # Depending on the glyph on capHeight or xHeigt
    GUESS_ANCHOR_ASCENDER = 'guessAnchorAscender'
    GUESS_ANCHOR_MIDDLE_Y = 'guessAnchorMiddleY'
    GUESS_ANCHOR_DESCENDER = 'guessAnchorDescender'
    GUESS_ANCHOR_BOX_BOTTOM = 'guessAnchorBoxBottom'

    GUESS_PAIRS_TOP = (
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_HEIGHT), 
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_BOX_TOP), 
        (GUESS_ANCHOR_BASE_X, GUESS_ANCHOR_BASE_Y), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_HEIGHT), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_BOX_TOP), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_HEIGHT), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_BOX_TOP), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_HEIGHT), # Take current x of the anchor, italicized to another y
        (GUESS_ANCHOR_X, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_BOX_TOP), 
    )
    GUESS_PAIRS_MIDDLE = (
        (GUESS_ANCHOR_BASE_X, GUESS_ANCHOR_BASE_Y), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_MIDDLE_Y), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_MIDDLE_Y), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_MIDDLE_Y), 
    )
    GUESS_PAIRS_DOT = (
        (GUESS_ANCHOR_BASE_X, GUESS_ANCHOR_BASE_Y), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_MIDDLE_Y), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_MIDDLE_Y), 
        (GUESS_ANCHOR_DOT_X, GUESS_ANCHOR_BOX_TOP), 
        (GUESS_ANCHOR_DOT_X, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_DOT_X, GUESS_ANCHOR_HEIGHT), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_BOX_TOP), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_ASCENDER), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_HEIGHT), 
    )
    GUESS_PAIRS_BOTTOM = (
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_BASELINE), 
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_DESCENDER), 
        (GUESS_ANCHOR_ZERO_WIDTH_X, GUESS_ANCHOR_BOX_BOTTOM), 
        (GUESS_ANCHOR_BASE_X, GUESS_ANCHOR_BASE_Y), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_BASELINE), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_DESCENDER), 
        (GUESS_ANCHOR_CENTER_WIDTH, GUESS_ANCHOR_BOX_BOTTOM), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_BASELINE), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_DESCENDER), 
        (GUESS_ANCHOR_BOX_CENTER_X, GUESS_ANCHOR_BOX_BOTTOM), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_BASELINE), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_DESCENDER), 
        (GUESS_ANCHOR_X, GUESS_ANCHOR_BOX_BOTTOM), 
    )
    GUESS_PAIRS_VERT = (
        (GUESS_ANCHOR_VERT_X, GUESS_ANCHOR_VERT_Y),
        (GUESS_ANCHOR_VERT_X, GUESS_ANCHOR_VERT_ASCENDER_Y),
        (GUESS_ANCHOR_VERT_X, GUESS_ANCHOR_ASCENDER),
        (GUESS_ANCHOR_VERT_X, GUESS_ANCHOR_BOX_TOP),
        (GUESS_ANCHOR_VERT_X, GUESS_ANCHOR_HEIGHT),
    )
    GUESS_PAIRS_TONOS = (
        (GUESS_ANCHOR_TONOS_X, GUESS_ANCHOR_ASCENDER),
        (GUESS_ANCHOR_TONOS_X, GUESS_ANCHOR_BOX_TOP),
        (GUESS_ANCHOR_TONOS_X, GUESS_ANCHOR_HEIGHT),
    )
    GUESS_PAIRS_OGONEK = (
        (GUESS_ANCHOR_OGONEK_X, GUESS_ANCHOR_BOX_BOTTOM),
        (GUESS_ANCHOR_OGONEK_X, GUESS_ANCHOR_BASELINE),
    )
    AUTO_PLACED_ANCHORS = { # List of pairs of method names to find guessed anchors positions that are responsive to auto-placement.
        TOP_: GUESS_PAIRS_TOP,
        _TOP: GUESS_PAIRS_TOP,
        MIDDLE_: GUESS_PAIRS_MIDDLE,
        _MIDDLE: GUESS_PAIRS_MIDDLE,
        BOTTOM_: GUESS_PAIRS_BOTTOM,
        _BOTTOM: GUESS_PAIRS_BOTTOM,
        DOT_: GUESS_PAIRS_DOT,
        _DOT: GUESS_PAIRS_DOT,
        VERT_: GUESS_PAIRS_VERT,
        _VERT: GUESS_PAIRS_VERT,
        TONOS_: GUESS_PAIRS_TONOS,
        _TONOS: GUESS_PAIRS_TONOS,
        OGONEK_: GUESS_PAIRS_OGONEK, 
        _OGONEK: GUESS_PAIRS_OGONEK,
    }

    # Default offset positions for guessed anchor positions. Can be redefined in the MasterData for each master UFO.
    ANCHOR_ASCENDER_OFFSET = 120 # Offset down, will be made negative.
    ANCHOR_BOXTOP_OFFSET = 120 # Offset down, will be made negative.
    ANCHOR_CAP_OFFSET = 78 # Offset down, will be made negative.
    ANCHOR_OFFSET = 16 # Default amount for vertical anchor offset, avoiding them to collide with baseline, xHeight, etc.
    ANCHOR_OGONEK_OFFSET = ANCHOR_OFFSET
    ANCHOR_BOXBOTTOM_OFFSET = 64
    ANCHOR_DESCENDER_OFFSET = 64

    CENTERING_ANCHORS = [ # List of anchors that do center on width. Ignore TONOS, HORN, OGONEK, VERT
        TOP_, BOTTOM_, RING_, DOT_, TILDE_, MIDDLE_,
    ]
    # Diacritics to show a subset-cloud by the contours part.
    EXAMPLE_DIACRITICS = {
        TOP_: ('gravecomb', 'acutecomb', 'circumflexcomb', 'macroncomb', 'dotaccentcomb', 'dieresiscomb', 'tildecomb',
               'gravecmb', 'acutecmb', 'circumflexcmb', 'macroncmb', 'dotaccentcmb', 'dieresiscmb', 'tildecmb',),
        BOTTOM_: ('plusbelowcomb', 'ringbelowcomb', 'cedillacomb', 
                  'plusbelowcmb', 'ringbelowcmb', 'cedillacmb'),
        MIDDLE_: ('slashshortcomb', 'slashshortcmb'),
        OGONEK_: ('ogonekcomb', 'ogonekcmb'),
        TONOS_: ('tonoscomb', 'tonoscmb', 'tonos-uc',),
        VERT_: ('caronvert.component',),
        DOT_: ('dotmiddle.component',),
    }

    ACCENT_DATA = {
        'acutecmb': _TOP,
        'brevecmb': _TOP,
        'caroncmb': _TOP,
        'caroncmb.vert': _VERT,
        'cedillacmb': _BOTTOM,
        'circumflexcmb': _TOP,
        'macroncmb': _TOP,
        'ogonekcmb': _OGONEK,
        'eogonekcmb': _OGONEK,
        'dieresiscmb': _TOP,
        'dotaccentcmb': _TOP,
        'gravecmb': _TOP,
        'hungarumlautcmb': _TOP,
        'ringcmb': _TOP,
        'ringacutecmb': _TOP,
        'tildecmb': _TOP,
        'dotmiddlecmb': _MIDDLE,
        'commabelowcmb': _BOTTOM,
        'commaturnedabovecmb': _TOP,
        #'commaaccenttopcmb': TOP,

        'acutecmb.uc': _TOP,
        'brevecmb.uc': _TOP,
        'caroncmb.uc': _TOP,
        'circumflexcmb.uc': _TOP,
        'macroncmb.uc': _TOP,
        'dieresiscmb.uc': _TOP,
        'dotaccentcmb.uc': _TOP,
        'gravecmb.uc': _TOP,
        'hungarumlautcmb.uc': _TOP,
        'ringcmb.uc': _TOP,
        'ringacutecmb.uc': _TOP,
        'tildecmb.uc': _TOP,
        'commaturnedabovecmb.uc': _TOP,

        # Segoe naming
        'ogonekcomb': _OGONEK,
        'eogonekcomb': _OGONEK,
        'ogonekcomb': _OGONEK,

        'acutecomb': _TOP,
        'brevecomb': _TOP,
        'caroncomb': _TOP,
        'caroncomb.vert': _VERT,
        'cedillacomb': _BOTTOM,
        'circumflexcomb': _TOP,
        'macroncomb': _TOP,
        'dieresiscomb': _TOP,
        'dotaccentcomb': _TOP,
        'gravecomb': _TOP,
        'hungarumlautcomb': _TOP,
        'ringcomb': _TOP,
        'ringacutecomb': _TOP,
        'tildecomb': _TOP,
        'commaturnedabovecomb': _TOP,
        'overlinecomb': _TOP, 
        'hookabovecomb': _TOP,
        'verticallineabovecomb': _TOP,
        'dblverticallineabovecomb': _TOP,
        'dblgravecomb': _TOP,
        'candrabinducomb': _TOP,
        'commaabovecomb': _TOP,
        'koronis': _TOP,
        'dasia': _TOP,
        'commareversedabovecomb': _TOP,
        'commaaboverightcomb': _TOP,
        'leftangleabovecomb': _TOP,
        'horncomb': _TOP,
        'xabovecomb': _TOP,
        'tildeverticalcomb': _TOP,
        'dbloverlinecomb': _TOP,
        'gravetonecomb': _TOP,
        'acutetonecomb': _TOP,
        'perispomenicomb': _TOP,
        'koroniscomb': _TOP,
        'dialytikatonoscomb': _TOP,
        'dialytikaoxia': _TOP,
        'gbridgeabovecomb': _TOP,
        'nottildeabovecomb': _TOP, 
        'homotheticabovecomb': _TOP, 
        'almostequaltoabovecomb': _TOP,
        'arrowheadrightabovecomb': _TOP,
        'lefthalfringabovecomb': _TOP,
        'fermatacomb': _TOP,
        'righthalfringabovecomb': _TOP,
        'dotaboverightcomb': _TOP,
        'zigzagabovecomb': _TOP,
        'doublebrevecomb': _TOP,
        'doublebrevecomb': _TOP,
        'tildedoublecomb': _TOP,
        'breveinverteddoublecomb': _TOP,
        'acomb': _TOP,
        'ecomb': _TOP,
        'icomb': _TOP,
        'ocomb': _TOP,
        'ucomb': _TOP,
        'ccomb': _TOP,
        'dcomb': _TOP,
        'hcomb': _TOP,
        'mcomb': _TOP,
        'rcomb': _TOP,
        'tcomb': _TOP,
        'vcomb': _TOP,
        'xcomb': _TOP,
        'dasiapneumatacomb-cy': _TOP,
        'psilipneumatacomb-cy': _TOP,
        'gravedottedcomb': _TOP,
        'acutedottedcomb': _TOP,
        'suspensioncomb': _TOP,
        'firsttonechinese': _TOP,
        'macronacutecomb': _TOP,
        'gravemacroncomb': _TOP,
        'gravecomb.component1': _TOP,
        'acutecomb.component1': _TOP,
        'macrongravecomb': _TOP,
        'acutemacroncomb': _TOP,
        'acutegraveacutecomb': _TOP,
        'arrowheadleftabovecomb': _TOP,
        'asteriskabovecomb': _TOP,
        'titlocomb-cy': _TOP,
        'palatalizationcomb-cy': _TOP,
        'pokrytiecomb-cy': _TOP,
        'hardsigncomb-cy': _TOP,
        'softsigncomb-cy': _TOP,
        'acutecomb.component': _TOP,
        'tildecomb.component': _TOP,
        'macroncomb.component': _TOP,
        'brevecomb.component': _TOP,
        'hookabovecomb.component': _TOP,
        'asteriskabovecomb': _TOP,
        'hardsigncomb-cy': _TOP,
        'perispomeni': _TOP,
        'dialytikaperispomeni': _TOP,
        'macroncomb.component1': _TOP,
        'gravecomb.component3': _TOP,
        'acutecomb.component3': _TOP,
        'gravecomb.component': _TOP,
        'acutegraveacutecomb': _TOP,
        'varia': _TOP,

        'commabelowcomb': _BOTTOM,
        'gravebelowcomb': _BOTTOM,
        'acutebelowcomb': _BOTTOM,
        'lefttackbelowcomb': _BOTTOM,
        'righttackbelowcomb': _BOTTOM,
        'ringhalfleftbelowcomb': _BOTTOM,
        'uptackbelowcomb': _BOTTOM,
        'downtackbelowcomb': _BOTTOM,
        'plusbelowcomb': _BOTTOM,
        'minusbelowcomb': _BOTTOM,
        'palatalhookcomb': _BOTTOM,
        'retroflexhookcomb': _BOTTOM,
        'dotbelowcomb': _BOTTOM,
        'ringbelowcomb': _BOTTOM,
        'commaaccentcomb': _BOTTOM,
        'cedillacomb': _BOTTOM,
        'verticallinebelowcomb': _BOTTOM,
        'bridgebelowcomb': _BOTTOM,
        'dblarchinvertedbelowcomb': _BOTTOM,
        'caronbelowcomb': _BOTTOM,
        'circumflexbelowcomb': _BOTTOM,
        'breveinvertedbelowcomb': _BOTTOM,
        'macronbelowcomb': _BOTTOM,
        'lowlinecomb': _BOTTOM,
        'dbllowlinecomb': _BOTTOM,
        'tildeoverlaycomb': _BOTTOM,
        'strokeshortcomb': _BOTTOM,
        'strokelongcomb': _BOTTOM,
        'slashshortcomb': _BOTTOM,
        'slashlongcomb': _BOTTOM,
        'ringhalfrightbelowcomb': _BOTTOM,
        'bridgeinvertedbelowcomb': _BOTTOM,
        'squarebelowcomb': _BOTTOM,
        'seagullbelowcomb': _BOTTOM,
        'ypogegrammenicomb': _BOTTOM,
        'equalbelowcomb': _BOTTOM,
        'doubleverticallinebelowcomb': _BOTTOM,
        'arrowleftrightbelowcomb': _BOTTOM,
        'arrowupbelowcomb': _BOTTOM,
        'graphemejoinercomb': _BOTTOM,
        'arrowheadleftbelowcomb': _BOTTOM,
        'arrowheadrightbelowcomb': _BOTTOM,
        'arrowheadrightheadupbelowcomb': _BOTTOM,
        'asteriskbelowcomb': _BOTTOM,
        'doubleringbelowcomb': _BOTTOM,
        'doublebrevebelowcomb': _BOTTOM,
        'dblmacronbelowcomb': _BOTTOM,
        'arrowdoublerightbelowcomb': _BOTTOM,
        'snakebelowcomb': _BOTTOM,
        'graveacutegravecomb': _BOTTOM,
        'rbelowcomb brevebelowcomb': _BOTTOM,
        
        'dotmiddlecomb': _MIDDLE,
        'uptackmod': _MIDDLE, 
        'downtackmod': _MIDDLE,
        'plusmod': _MIDDLE,

        'dasiavaria-uc': _TONOS,
    }

    # Tables below are mainly use to export _export/Exported_Glyphset.py, etc. or to initialize in GlyphData contruction.

    TOP_ANCHORS = {'A', 'A-cy', 'AE', 'AEacute', 'AEmacron', 'Aacute', 'Abreve', 'Abreve-cy', 'Abreve.component', 'Abreve.component1', 'Abreve.component2', 
        'Abreve.component3', 'Abreveacute', 'Abrevedotbelow', 'Abrevegrave', 'Abrevehookabove', 'Abrevetilde', 'Acaron', 'Acircumflex', 'Acircumflexacute', 
        'Acircumflexdotbelow', 'Acircumflexgrave', 'Acircumflexhookabove', 'Acircumflextilde', 'Adblgrave', 'Adieresis', 'Adieresis-cy', 'Adieresismacron', 
        'Adotaccent', 'Adotbelow', 'Adotmacron', 'Agrave', 'Ahookabove', 'Aie-cy', 'Ainvertedbreve', 'Alpha', 'Alphadasia', 'Alphadasiaoxia', 
        'Alphadasiaoxiaprosgegrammeni', 'Alphadasiaperispomeni', 'Alphadasiaperispomeniprosgegrammeni', 'Alphadasiaprosgegrammeni', 'Alphadasiavaria', 
        'Alphadasiavariaprosgegrammeni', 'Alphamacron', 'Alphaoxia', 'Alphaprosgegrammeni', 'Alphapsili', 'Alphapsilioxia', 'Alphapsilioxiaprosgegrammeni', 
        'Alphapsiliperispomeni', 'Alphapsiliperispomeniprosgegrammeni', 'Alphapsiliprosgegrammeni', 'Alphapsilivaria', 'Alphapsilivariaprosgegrammeni', 
        'Alphatonos', 'Alphavaria', 'Alphavrachy', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Aringbelow', 'Astroke', 'Atilde', 'B', 'Bdotaccent', 'Bdotbelow', 
        'Beta', 'Blinebelow', 'Bstroke', 'C', 'Cacute', 'Cbar', 'Ccaron', 'Ccedilla', 'Ccedillaacute', 'Ccircumflex', 'Cdotaccent', 'Che-cy', 'Chedieresis-cy', 
        'Cheverticalstroke-cy', 'Chi', 'Chi-latin', 'Csmall', 'Cstroke', 'D', 'DZ', 'DZcaron', 'Dcaron', 'Dcedilla', 'Dcircumflexbelow', 'Ddotaccent', 'Ddotbelow', 
        'Dlinebelow', 'Dz', 'Dzcaron', 'Dze-cy', 'E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecedilla', 'Ecedillabreve', 'Ecircumflex', 'Ecircumflexacute', 'Ecircumflexbelow', 
        'Ecircumflexdotbelow', 'Ecircumflexgrave', 'Ecircumflexhookabove', 'Ecircumflextilde', 'Edblgrave', 'Edieresis', 'Edieresis-cy', 'Edotaccent', 'Edotbelow', 
        'Egrave', 'Ehookabove', 'Einvertedbreve', 'Em-cy', 'Emacron', 'Emacronacute', 'Emacrongrave', 'Emtail-cy', 'En-cy', 'Entail-cy', 'Eogonek', 'Epsilon', 'Epsilondasia', 
        'Epsilondasiaoxia', 'Epsilondasiavaria', 'Epsilonoxia', 'Epsilonpsili', 'Epsilonpsilioxia', 'Epsilonpsilivaria', 'Epsilontonos', 'Epsilonvaria', 'Er-cy', 
        'Ereversed-cy', 'EreversedOpen', 'Es-cy', 'Estroke', 'Eta', 'Etadasia', 'Etadasiaoxia', 'Etadasiaoxiaprosgegrammeni', 'Etadasiaperispomeni', 
        'Etadasiaperispomeniprosgegrammeni', 'Etadasiaprosgegrammeni', 'Etadasiavaria', 'Etadasiavariaprosgegrammeni', 'Etaoxia', 'Etaprosgegrammeni', 
        'Etapsili', 'Etapsilioxia', 'Etapsilioxiaprosgegrammeni', 'Etapsiliperispomeni', 'Etapsiliperispomeniprosgegrammeni', 'Etapsiliprosgegrammeni', 
        'Etapsilivaria', 'Etapsilivariaprosgegrammeni', 'Etatonos', 'Etavaria', 'Etilde', 'Etildebelow', 'Ezh', 'Ezhcaron', 'F', 'Fdotaccent', 'G', 'Gacute', 
        'Gamma', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent', 'Ge-cy', 'Gje-cy', 'Gmacron', 'Gobliquestroke', 'H', 'Ha-cy', 'Hbrevebelow', 
        'Hcaron', 'Hcedilla', 'Hcircumflex', 'Hdieresis', 'Hdotaccent', 'Hdotbelow', 'I', 'I-cy', 'IJ', 'Iacute', 'Ibreve', 'Icaron', 'Icircumflex', 'Idblgrave', 
        'Idieresis', 'Idieresis-cy', 'Idieresis.component', 'Idieresisacute', 'Idotaccent', 'Idotbelow', 'Ie-cy', 'Iebreve-cy', 'Iegrave-cy', 'Igrave', 'Ihookabove', 
        'Ii-cy', 'Iigrave-cy', 'Iinvertedbreve', 'Iishort-cy', 'Imacron', 'Imacron-cy', 'Io-cy', 'Iogonek', 'Iota', 'Iotadasia', 'Iotadasiaoxia', 'Iotadasiaperispomeni', 
        'Iotadasiavaria', 'Iotadieresis', 'Iotamacron', 'Iotaoxia', 'Iotapsili', 'Iotapsilioxia', 'Iotapsiliperispomeni', 'Iotapsilivaria', 'Iotatonos', 'Iotavaria', 
        'Iotavrachy', 'Itilde', 'Itildebelow', 'Izhitsa-cy', 'Izhitsadblgrave-cy', 'J', 'Jcircumflex', 'Je-cy', 'Jstroke', 'K', 'Ka-cy', 'Kacute', 'Kappa', 'Kcaron', 
        'Kcommaaccent', 'Kdiagonalstroke', 'Kdotbelow', 'Kje-cy', 'Klinebelow', 'Kobliquestroke', 'Ksmall', 'Kstroke', 'Kstrokediagonalstroke', 'L', 'LJ', 'Lacute', 
        'Lbar', 'Lcaron', 'Lcircumflexbelow', 'Lcommaaccent', 'Ldot', 'Ldotbelow', 'Ldotbelowmacron', 'Ldoublebar', 'Lj', 'Llinebelow', 'Lmiddletilde', 'M', 'Macute', 
        'Mdotaccent', 'Mdotbelow', 'Mu', 'N', 'NJ', 'Nacute', 'Ncaron', 'Ncircumflexbelow', 'Ncommaaccent', 'Ndescender', 'Ndotaccent', 'Ndotbelow', 'Ngrave', 'Nj', 
        'Nlinebelow', 'Nobliquestroke', 'NreversedSmall', 'Ntilde', 'Nu', 'O', 'O-cy', 'OE', 'Oacute', 'Obarred-cy', 'Obarreddieresis-cy', 'Obreve', 'Ocaron', 
        'Ocircumflex', 'Ocircumflexacute', 'Ocircumflexdotbelow', 'Ocircumflexgrave', 'Ocircumflexhookabove', 'Ocircumflextilde', 'Odblgrave', 'Odieresis', 'Odieresis-cy', 
        'Odieresismacron', 'Odotaccent', 'Odotaccentmacron', 'Odotbelow', 'Ograve', 'Ohm', 'Ohookabove', 'Ohorn', 'Ohornacute', 'Ohorndotbelow', 'Ohorngrave', 'Ohornhookabove', 
        'Ohorntilde', 'Ohungarumlaut', 'Oinvertedbreve', 'Olongstroke', 'Omacron', 'Omacronacute', 'Omacrongrave', 'Omega', 'Omega-cy', 'Omegadasia', 'Omegadasiaoxia', 
        'Omegadasiaoxiaprosgegrammeni', 'Omegadasiaperispomeni', 'Omegadasiaperispomeniprosgegrammeni', 'Omegadasiaprosgegrammeni', 'Omegadasiavaria', 
        'Omegadasiavariaprosgegrammeni', 'Omegaoxia', 'Omegaprosgegrammeni', 'Omegapsili', 'Omegapsilioxia', 'Omegapsilioxiaprosgegrammeni', 'Omegapsiliperispomeni', 
        'Omegapsiliperispomeniprosgegrammeni', 'Omegapsiliprosgegrammeni', 'Omegapsilivaria', 'Omegapsilivariaprosgegrammeni', 'Omegatonos', 'Omegavaria', 'Omicron', 
        'Omicrondasia', 'Omicrondasiaoxia', 'Omicrondasiavaria', 'Omicronoxia', 'Omicronpsili', 'Omicronpsilioxia', 'Omicronpsilivaria', 'Omicrontonos', 'Omicronvaria', 
        'Oogonek', 'Oogonekmacron', 'Oslash', 'Oslashacute', 'Osmall', 'Otilde', 'Otilde.component', 'Otilde.component1', 'Otildeacute', 'Otildedieresis', 'Otildemacron', 
        'P', 'Pacute', 'Palochka-cy', 'Pamphyliandigamma', 'Pdotaccent', 'Pstroke', 'Pstrokethroughdescender', 'Q', 'Qstrokethroughdescender', 'R', 'Racute', 'Rcaron', 
        'Rcommaaccent', 'Rdblgrave', 'Rdotaccent', 'Rdotbelow', 'Rdotbelowmacron', 'Rho', 'Rhodasia', 'Rinvertedbreve', 'Rlinebelow', 'Robliquestroke', 'Rstroke', 
        'S', 'Sacute', 'Sacute.component', 'Sacutedotaccent', 'Scaron', 'Scaron.component', 'Scarondotaccent', 'Scedilla', 'Schwa', 'Schwa-cy', 
        'Schwadieresis-cy', 'Scircumflex', 'Scommaaccent', 'Sdotaccent', 'Sdotbelow', 'Sdotbelowdotaccent', 'SigmaLunateDottedSymbol', 'Sobliquestroke', 'T', 'Tau', 
        'Tcaron', 'Tcedilla', 'Tcircumflexbelow', 'Tcommaaccent', 'Tdiagonalstroke', 'Tdotaccent', 'Tdotbelow', 'Te-cy', 'ThetaSymbol', 'Tlinebelow', 'U', 'U-cy', 
        'Uacute', 'Ubar', 'Ubreve', 'Ucaron', 'Ucircumflex', 'Ucircumflexbelow', 'Udblgrave', 'Udieresis', 'Udieresis-cy', 'Udieresis.component', 'Udieresisacute', 
        'Udieresisbelow', 'Udieresiscaron', 'Udieresisgrave', 'Udieresismacron', 'Udotbelow', 'Ugrave', 'Uhookabove', 'Uhorn', 'Uhornacute', 'Uhorndotbelow', 
        'Uhorngrave', 'Uhornhookabove', 'Uhorntilde', 'Uhungarumlaut', 'Uhungarumlaut-cy', 'Uinvertedbreve', 'Umacron', 'Umacron-cy', 'Umacron.component', 'Umacrondieresis', 
        'Uogonek', 'Upsilon', 'UpsilonacutehookSymbol', 'Upsilondasia', 'Upsilondasiaoxia', 'Upsilondasiaperispomeni', 'Upsilondasiavaria', 'Upsilondieresis', 
        'UpsilondieresishookSymbol', 'UpsilonhookSymbol', 'Upsilonmacron', 'Upsilonoxia', 'Upsilontonos', 'Upsilonvaria', 'Upsilonvrachy', 'Uring', 'Ushort-cy', 
        'Ustrait-cy', 'Utilde', 'Utildeacute', 'Utildebelow', 'V', 'Vdiagonalstroke', 'Vdotbelow', 'Ve-cy', 'Vsmall', 'Vtilde', 'W', 'Wacute', 'Wcircumflex', 'Wdieresis', 
        'Wdotaccent', 'Wdotbelow', 'Wgrave', 'Wsmall', 'X', 'Xdieresis', 'Xdotaccent', 'Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ydotaccent', 'Ydotbelow', 'Yeru-cy', 
        'Yerudieresis-cy', 'Ygrave', 'Yhook', 'Yhookabove', 'Yi-cy', 'Ymacron', 'Yot', 'Ystroke', 'Ytilde', 'Z', 'Zacute', 'Zcaron', 'Zcircumflex', 'Zdotaccent', 
        'Zdotbelow', 'Ze-cy', 'Zedieresis-cy', 'Zeta', 'Zhe-cy', 'Zhebreve-cy', 'Zhedieresis-cy', 'Zlinebelow', 'Zsmall', 'a', 'a-cy', 'aacute', 'abreve', 'abreve-cy', 
        'abreve.component', 'abreve.component1', 'abreve.component2', 'abreve.component3', 'abreveacute', 'abrevedotbelow', 'abrevegrave', 'abrevehookabove', 'abrevetilde', 
        'acaron', 'acircumflex', 'acircumflexacute', 'acircumflexdotbelow', 'acircumflexgrave', 'acircumflexhookabove', 'acircumflextilde', 'acomb', 'acutecomb', 
        'acutecomb.component', 'acutecomb.component1', 'acutecomb.component3', 'acutecomb.component5', 'acutedottedcomb', 'acutegraveacutecomb', 
        'acutemacroncomb', 'acutetonecomb', 'adblgrave', 'adieresis', 'adieresis-cy', 'adieresismacron', 'adotaccent', 'adotbelow', 'adotmacron', 'ae', 'aeacute', 'aemacron', 
        'agrave', 'ahookabove', 'aie-cy', 'ainvertedbreve', 'almostequaltoabovecomb', 'alpha', 'alphadasia', 'alphadasiaoxia', 'alphadasiaoxiaypogegrammeni', 
        'alphadasiaperispomeni', 'alphadasiaperispomeniypogegrammeni', 'alphadasiavaria', 'alphadasiavariaypogegrammeni', 'alphadasiaypogegrammeni', 'alphamacron', 
        'alphaoxia', 'alphaoxiaypogegrammeni', 'alphaperispomeni', 'alphaperispomeniypogegrammeni', 'alphapsili', 'alphapsilioxia', 'alphapsilioxiaypogegrammeni', 
        'alphapsiliperispomeni', 'alphapsiliperispomeniypogegrammeni', 'alphapsilivaria', 'alphapsilivariaypogegrammeni', 'alphapsiliypogegrammeni', 'alphatonos', 
        'alphavaria', 'alphavariaypogegrammeni', 'alphavrachy', 'alphaypogegrammeni', 'amacron', 'aogonek', 'aretroflexhook',  
        'arighthalfring', 'aring', 'aringacute', 'aringbelow', 'arrowheadleftabovecomb', 'arrowheadrightabovecomb', 'asteriskabovecomb', 'astroke', 'atilde', 'b', 
        'bdotaccent', 'bdotbelow', 'blinebelow', 'bmiddletilde', 'bpalatalhook', 'brevecomb', 'brevecomb.component', 
        'breveinvertedcomb', 'breveinverteddoublecomb', 'c', 'cPalatalhook', 'cacute', 'candrabinducomb', 'caroncomb', 'cbar', 'ccaron', 'ccedilla', 
        'ccedillaacute', 'ccircumflex', 'ccomb', 'cdotaccent', 'che-cy', 'chedieresis-cy', 'cheverticalstroke-cy', 'circumflexcomb', 'commaabovecomb', 
        'commaaboverightcomb', 'commareversedabovecomb', 'commaturnedabovecomb', 'cstroke', 'd', 'dasia', 'dasiaoxia', 'dasiaperispomeni', 'dasiapneumatacomb-cy', 'dasiavaria', 
        'dblgravecomb', 'dbloverlinecomb', 'dblverticallineabovecomb', 'dcaron', 'dcedilla', 'dcircumflexbelow', 'dcomb', 'ddotaccent', 'ddotbelow', 'dialytikaoxia', 
        'dialytikaperispomeni', 'dialytikatonoscomb', 'dialytikavaria', 'dieresiscomb', 'dieresistonos', 'dlinebelow', 'dmiddletilde', 'dotaboverightcomb', 
        'dotaccentcomb', 'doublebrevecomb', 'doublemacroncomb', 'dpalatalhook', 'dum', 'dz', 'dzcaron', 'dze-cy', 'dzeabkhasian-cy', 'e', 'eacute', 'ebreve', 
        'ecaron', 'ecedilla', 'ecedillabreve', 'ecircumflex', 'ecircumflexacute', 'ecircumflexbelow', 'ecircumflexdotbelow', 'ecircumflexgrave', 'ecircumflexhookabove', 
        'ecircumflextilde', 'ecomb', 'edblgrave', 'edieresis', 'edieresis-cy', 'edotaccent', 'edotbelow', 'egrave', 'ehookabove', 'einvertedbreve', 'emacron', 'emacronacute', 
        'emacrongrave', 'eogonek', 'eopen', 'eopenretroflexhook', 'eopenreversedretroflexhook', 'epsilon', 'epsilondasia', 'epsilondasiaoxia', 'epsilondasiavaria', 
        'epsilonoxia', 'epsilonpsili', 'epsilonpsilioxia', 'epsilonpsilivaria', 'epsilontonos', 'epsilonvaria', 'er-cy', 'eretroflexhook', 'ereversed-cy', 'ertick-cy', 
        'es-cy', 'estroke', 'eta', 'etadasia', 'etadasiaoxia', 'etadasiaoxiaypogegrammeni', 'etadasiaperispomeni', 'etadasiaperispomeniypogegrammeni', 'etadasiavaria', 
        'etadasiavariaypogegrammeni', 'etadasiaypogegrammeni', 'etaoxia', 'etaoxiaypogegrammeni', 'etaperispomeni', 'etaperispomeniypogegrammeni', 'etapsili', 'etapsilioxia', 
        'etapsilioxiaypogegrammeni', 'etapsiliperispomeni', 'etapsiliperispomeniypogegrammeni', 'etapsilivaria', 'etapsilivariaypogegrammeni', 'etapsiliypogegrammeni', 
        'etatonos', 'etavaria', 'etavariaypogegrammeni', 'etaypogegrammeni', 'etilde', 'etildebelow', 'eturned', 'ezh', 'ezhcaron', 'f', 'fStroke', 'fdotaccent', 'fermatacomb', 
        'firsttonechinese', 'flenis', 'fmiddletilde', 'fourthtonechinese', 'fpalatalhook', 'g', 'gacute', 'gbreve', 'gbridgeabovecomb', 'gcaron', 'gcircumflex', 'gcommaaccent', 
        'gdotaccent', 'ge-cy', 'gje-cy', 'gmacron', 'gobliquestroke', 'gpalatalhook', 'graphemejoinercomb', 'graveacutegravecomb', 'gravecomb', 'gravecomb.component', 
        'gravecomb.component1', 'gravecomb.component3', 'gravedottedcomb', 'gravemacroncomb', 'gravetonecomb', 'gsingle', 'h', 'hPalatalhook', 'ha-cy', 
        'hbrevebelow', 'hcaron', 'hcedilla', 'hcircumflex', 'hcomb', 'hdieresis', 'hdotaccent', 'hdotbelow', 'hlinebelow', 'homotheticabovecomb', 'hookabovecomb', 
        'hookabovecomb.component', 'horncomb', 'hungarumlautcomb', 'i', 'i-cy', 'iacute', 'ibreve', 'icaron', 'icircumflex', 'icomb', 'idblgrave', 'idieresis', 
        'idieresis-cy', 'idieresis.component', 'idieresisacute', 'idotbelow', 'idotless', 'ie-cy', 'iebreve-cy', 'iegrave-cy', 'igrave', 'ihookabove', 'ii-cy', 
        'iigrave-cy', 'iinvertedbreve', 'iishort-cy', 'iishorttail-cy', 'ij', 'imacron', 'imacron-cy', 'io-cy', 'iogonek', 'iota', 'iotadasia', 'iotadasiaoxia', 
        'iotadasiaperispomeni', 'iotadasiavaria', 'iotadialytikaoxia', 'iotadialytikaperispomeni', 'iotadialytikavaria', 'iotadieresis', 'iotadieresistonos', 'iotamacron', 
        'iotaoxia', 'iotaperispomeni', 'iotapsili', 'iotapsilioxia', 'iotapsiliperispomeni', 'iotapsilivaria', 'iotastroke', 'iotatonos', 'iotavaria', 'iotavrachy', 
        'iretroflexhook', 'itilde', 'itildebelow', 'izhitsa-cy', 'izhitsadblgrave-cy', 'jcaron', 'jcircumflex', 'jdotless', 'k', 'ka-cy', 'kacute', 'kcaron', 'kcommaaccent', 
        'kdiagonalstroke', 'kdotbelow', 'kgreenlandic', 'kje-cy', 'klinebelow', 'kobliquestroke', 'koronis', 'koroniscomb', 'kpalatalhook', 'kstroke', 'kstrokediagonalstroke', 
        'l', 'lacute', 'lcaron', 'lcircumflexbelow', 'lcommaaccent', 'ldot', 'ldotbelow', 'ldotbelowmacron', 'ldoublemiddletilde', 'leftangleabovecomb', 'lefthalfringabovecomb', 
        'lj', 'llinebelow', 'longs', 'longsdotaccent', 'lowcircumflexmod', 'lowtildemod', 'lpalatalhook', 'm', 'macronacutecomb', 'macroncomb', 
        'macroncomb.component', 'macroncomb.component1', 'macrongravecomb', 'macute', 'mcomb', 'mdotaccent', 'mdotbelow', 'mill', 'mmiddletilde', 
        'mpalatalhook', 'mum', 'n', 'nacute', 'napostrophe', 'ncaron', 'ncircumflexbelow', 'ncommaaccent', 'ndescender', 'ndotaccent', 'ndotbelow', 'ngrave', 'nj', 'nlinebelow', 
        'nmiddletilde', 'nobliquestroke', 'nottildeabovecomb', 'npalatalhook', 'ntilde', 'num', 'o', 'o-cy', 'oacute', 'obarred', 'obarred-cy', 
        'obarreddieresis-cy', 'obreve', 'ocaron', 'ocircumflex', 'ocircumflexacute', 'ocircumflexdotbelow', 'ocircumflexgrave', 'ocircumflexhookabove', 'ocircumflextilde', 
        'ocomb', 'odblgrave', 'odieresis', 'odieresis-cy', 'odieresismacron', 'odotaccent', 'odotaccentmacron', 'odotbelow', 'oe','ograve', 'ohookabove', 
        'ohorn', 'ohornacute', 'ohorndotbelow', 'ohorngrave', 'ohornhookabove', 'ohorntilde', 'ohungarumlaut', 'oinvertedbreve', 'omacron', 'omacronacute', 'omacrongrave', 
        'omega', 'omega-cy', 'omega-latin', 'omegadasia', 'omegadasiaoxia', 'omegadasiaoxiaypogegrammeni', 'omegadasiaperispomeni', 'omegadasiaperispomeniypogegrammeni', 
        'omegadasiavaria', 'omegadasiavariaypogegrammeni', 'omegadasiaypogegrammeni', 'omegaoxia', 'omegaoxiaypogegrammeni', 'omegaperispomeni', 'omegaperispomeniypogegrammeni', 
        'omegapsili', 'omegapsilioxia', 'omegapsilioxiaypogegrammeni', 'omegapsiliperispomeni', 'omegapsiliperispomeniypogegrammeni', 'omegapsilivaria', 
        'omegapsilivariaypogegrammeni', 'omegapsiliypogegrammeni', 'omegatonos', 'omegavaria', 'omegavariaypogegrammeni', 'omegaypogegrammeni', 'omicron', 'omicrondasia', 
        'omicrondasiaoxia', 'omicrondasiavaria', 'omicronoxia', 'omicronpsili', 'omicronpsilioxia', 'omicronpsilivaria', 'omicrontonos', 'omicronvaria', 'oogonek', 
        'oogonekmacron', 'oopenretroflexhook', 'oslash', 'oslashacute', 'otilde', 'otilde.component', 'otilde.component1', 'otildeacute', 'otildedieresis', 'otildemacron', 
        'overlinecomb', 'oxia', 'p', 'pacute', 'palatalizationcomb-cy', 'palochka-cy', 'pamphyliandigamma', 'pdotaccent', 'perispomeni', 'perispomenicomb', 'pmiddletilde', 
        'pokrytiecomb-cy', 'ppalatalhook', 'psili', 'psilioxia', 'psiliperispomeni', 'psilipneumatacomb-cy', 'psilivaria', 'pstroke', 'pstrokethroughdescender', 'q', 
        'qdiagonalstroke', 'qstrokethroughdescender', 'r', 'r.salt', 'racute', 'rcaron', 'rcomb', 'rcommaaccent', 'rdblgrave', 'rdotaccent', 'rdotbelow', 'rdotbelowmacron', 'rho', 
        'rhoStrokeSymbol', 'rhodasia', 'rhopsili', 'righthalfringabovecomb', 'ringcomb', 'ringacutecomb', 'ringhalfright', 'rinvertedbreve', 'rlinebelow', 
        'rmiddletilde', 'robliquestroke', 'rpalatalhook', 'rstroke', 'rum', 's', 'sacute', 'sacute.component', 'sacutedotaccent', 'scaron', 'scaron.component', 
        'scarondotaccent', 'scedilla', 'schwa', 'schwa-cy', 'schwadieresis-cy', 'schwaretroflexhook', 'scircumflex', 'scommaaccent', 'sdotaccent', 'sdotbelow', 
        'sdotbelowdotaccent', 'secondtonechinese', 'shha-cy', 'sigmaLunateDottedSymbol', 'sigmaLunateSymbol', 'smiddletilde', 'sobliquestroke', 'spalatalhook', 
         'suspensioncomb', 't', 'tcaron', 'tcedilla', 'tcircumflexbelow', 'tcomb', 'tcommaaccent', 'tdiagonalstroke', 
        'tdieresis', 'tdotaccent', 'tdotbelow', 'thstrikethrough', 'tildecomb', 'tildecomb.component', 'tildedoublecomb', 'tildeverticalcomb', 
        'titlocomb-cy', 'tlinebelow', 'tmiddletilde', 'u', 'u-cy', 'uacute', 'ubar', 'ubreve', 'ucaron', 'ucircumflex', 'ucircumflexbelow', 'ucomb', 'udblgrave', 
        'udieresis', 'udieresis-cy', 'udieresis.component', 'udieresisacute', 'udieresisbelow', 'udieresiscaron', 'udieresisgrave', 'udieresismacron', 'udotbelow', 'ugrave', 
        'uhookabove', 'uhorn', 'uhornacute', 'uhorndotbelow', 'uhorngrave', 'uhornhookabove', 'uhorntilde', 'uhungarumlaut', 'uhungarumlaut-cy', 'uinvertedbreve', 'umacron', 
        'umacron-cy', 'umacron.component', 'umacrondieresis', 'uni047E', 'uni047E.component', 'uni047F', 'uogonek', 'upsilon', 'upsilondasia', 'upsilondasiaoxia', 
        'upsilondasiaperispomeni', 'upsilondasiavaria', 'upsilondialytikaoxia', 'upsilondialytikaperispomeni', 'upsilondialytikavaria', 'upsilondieresis', 
        'upsilondieresistonos', 'upsilonmacron', 'upsilonoxia', 'upsilonperispomeni', 'upsilonpsili', 'upsilonpsilioxia', 'upsilonpsiliperispomeni', 'upsilonpsilivaria', 
        'upsilontonos', 'upsilonvaria', 'upsilonvrachy', 'uretroflexhook', 'uring', 'ushort-cy', 'utilde', 'utildeacute', 'utildebelow', 'v', 'varia', 'vcomb', 'vdiagonalstroke', 
        'vdotbelow', 'verticallineabovecomb', 'vpalatalhook', 'vrighthook', 'vtilde', 'w', 'wacute', 'wcircumflex', 'wdieresis', 'wdotaccent', 'wdotbelow', 
        'wgrave', 'wring', 'x', 'xabovecomb', 'xcomb', 'xdieresis', 'xdotaccent', 'xpalatalhook', 'y', 'yacute', 'ycircumflex', 'ydieresis', 'ydotaccent', 'ydotbelow', 
        'yeru-cy', 'yerudieresis-cy', 'ygrave', 'yhookabove', 'yi-cy', 'ymacron', 'yring', 'ystroke', 'ytilde', 'z', 'zacute', 'zcaron', 'zcircumflex', 'zdotaccent', 
        'zdotbelow', 'ze-cy', 'zedieresis-cy', 'zhe-cy', 'zhebreve-cy', 'zhedieresis-cy', 'zigzagabovecomb', 'zlinebelow', 'zmiddletilde', 'zpalatalhook',
        'dottedCircle', 'ringhalfleft',
    }

    MIDDLE_ANCHORS = {'A', 'Aring', 'Aringacute', 'A-cy', 'AE', 'AEacute', 'AEmacron', 'Aacute', 'Abreve', 'Abreve-cy', 'Abreveacute', 'Abrevedotbelow', 
        'Abrevegrave', 'Abrevehookabove', 'Abrevetilde', 'Acaron', 'Acircumflex', 'Acircumflexacute', 'Acircumflexdotbelow', 
        'Acircumflexgrave', 'Acircumflexhookabove', 'Acircumflextilde', 'Adblgrave', 'Adieresis', 'Adieresis-cy', 'Adieresismacron', 
        'Adotaccent', 'Adotbelow', 'Adotmacron', 'Agrave', 'Ahookabove', 'Aie-cy', 'Ainvertedbreve', 'Alpha', 'Alphadasia', 
        'Alphadasiaoxia', 'Alphadasiaoxiaprosgegrammeni', 'Alphadasiaperispomeni', 'Alphadasiaperispomeniprosgegrammeni', 
        'Alphadasiaprosgegrammeni', 'Alphadasiavaria', 'Alphadasiavariaprosgegrammeni', 'Alphamacron', 'Alphaoxia', 
        'Alphaprosgegrammeni', 'Alphapsili', 'Alphapsilioxia', 'Alphapsilioxiaprosgegrammeni', 'Alphapsiliperispomeni', 
        'Alphapsiliperispomeniprosgegrammeni', 'Alphapsiliprosgegrammeni', 'Alphapsilivaria', 'Alphapsilivariaprosgegrammeni', 
        'Alphatonos', 'Alphavaria', 'Alphavrachy', 'Amacron', 'Aogonek', 'Aringbelow', 'Astroke', 'Atilde', 'B', 'Bdotaccent', 
        'Bdotbelow', 'Beta', 'Blinebelow', 'Bstroke', 'C', 'Cacute', 'Cbar', 'Ccaron', 'Ccedilla', 'Ccedillaacute', 'Ccircumflex', 
        'Cdotaccent', 'Chi', 'Chi-latin', 'Csmall', 'Cstroke', 'D', 'DZ', 'DZcaron', 'Dcaron', 'Dcedilla', 'Dcircumflexbelow', 
        'Ddotaccent', 'Ddotbelow', 'Dlinebelow', 'Dz', 'Dzcaron', 'Dze-cy', 'E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecedilla', 
        'Ecedillabreve', 'Ecircumflex', 'Ecircumflexacute', 'Ecircumflexbelow', 'Ecircumflexdotbelow', 'Ecircumflexgrave', 
        'Ecircumflexhookabove', 'Ecircumflextilde', 'Edblgrave', 'Edieresis', 'Edotaccent', 'Edotbelow', 'Egrave', 'Ehookabove', 
        'Einvertedbreve', 'Em-cy', 'Emacron', 'Emacronacute', 'Emacrongrave', 'Emtail-cy', 'En-cy', 'Entail-cy', 'Eogonek', 
        'Epsilon', 'Epsilondasia', 'Epsilondasiaoxia', 'Epsilondasiavaria', 'Epsilonoxia', 'Epsilonpsili', 'Epsilonpsilioxia', 
        'Epsilonpsilivaria', 'Epsilontonos', 'Epsilonvaria', 'Er-cy', 'Es-cy', 'Estroke', 'Eta', 'Etadasia', 'Etadasiaoxia', 
        'Etadasiaoxiaprosgegrammeni', 'Etadasiaperispomeni', 'Etadasiaperispomeniprosgegrammeni', 'Etadasiaprosgegrammeni', 
        'Etadasiavaria', 'Etadasiavariaprosgegrammeni', 'Etaoxia', 'Etaprosgegrammeni', 'Etapsili', 'Etapsilioxia', 
        'Etapsilioxiaprosgegrammeni', 'Etapsiliperispomeni', 'Etapsiliperispomeniprosgegrammeni', 'Etapsiliprosgegrammeni', 
        'Etapsilivaria', 'Etapsilivariaprosgegrammeni', 'Etatonos', 'Etavaria', 'Etilde', 'Etildebelow', 'F', 'Fdotaccent', 'G', 
        'Gacute', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent', 'Gmacron', 'Gobliquestroke', 'H', 'Ha-cy', 
        'Hbrevebelow', 'Hcaron', 'Hcedilla', 'Hcircumflex', 'Hdieresis', 'Hdotaccent', 'Hdotbelow', 'I', 'I-cy', 'IJ', 'Iacute', 
        'Ibreve', 'Icaron', 'Icircumflex', 'Idblgrave', 'Idieresis', 'Idieresisacute', 'Idotaccent', 'Idotbelow', 'Ie-cy', 
        'Iebreve-cy', 'Iegrave-cy', 'Igrave', 'Ihookabove', 'Iinvertedbreve', 'Imacron', 'Io-cy', 'Iogonek', 'Iota', 'Iotadasia', 
        'Iotadasiaoxia', 'Iotadasiaperispomeni', 'Iotadasiavaria', 'Iotadieresis', 'Iotamacron', 'Iotaoxia', 'Iotapsili', 
        'Iotapsilioxia', 'Iotapsiliperispomeni', 'Iotapsilivaria', 'Iotatonos', 'Iotavaria', 'Iotavrachy', 'Itilde', 'Itildebelow', 
        'J', 'Jcircumflex', 'Je-cy', 'Jstroke', 'K', 'Ka-cy', 'Kacute', 'Kappa', 'Kcaron', 'Kcommaaccent', 'Kdiagonalstroke', 
        'Kdotbelow', 'Kje-cy', 'Klinebelow', 'Kobliquestroke', 'Kstroke', 'Kstrokediagonalstroke', 'L', 'LJ', 'Lacute', 'Lbar', 
        'Lcaron', 'Lcircumflexbelow', 'Lcommaaccent', 'Ldot', 'Ldotbelow', 'Ldotbelowmacron', 'Ldoublebar', 'Lj', 'Llinebelow', 
        'Lmiddletilde', 'M', 'Macute', 'Mdotaccent', 'Mdotbelow', 'Mu', 'N', 'NJ', 'Nacute', 'Ncaron', 'Ncircumflexbelow', 
        'Ncommaaccent', 'Ndescender', 'Ndotaccent', 'Ndotbelow', 'Ngrave', 'Nj', 'Nlinebelow', 'Nobliquestroke', 'Ntilde', 
        'Nu', 'O', 'O-cy', 'OE', 'Oacute', 'Obreve', 'Ocaron', 'Ocircumflex', 'Ocircumflexacute', 'Ocircumflexdotbelow', 
        'Ocircumflexgrave', 'Ocircumflexhookabove', 'Ocircumflextilde', 'Odblgrave', 'Odieresis', 'Odieresis-cy', 'Odieresismacron', 
        'Odotaccent', 'Odotaccentmacron', 'Odotbelow', 'Ograve', 'Ohookabove', 'Ohungarumlaut', 'Oinvertedbreve', 'Olongstroke', 
        'Omacron', 'Omacronacute', 'Omacrongrave', 'Omicron', 'Omicrondasia', 'Omicrondasiaoxia', 'Omicrondasiavaria', 'Omicronoxia', 
        'Omicronpsili', 'Omicronpsilioxia', 'Omicronpsilivaria', 'Omicrontonos', 'Omicronvaria', 'Oogonek', 'Oogonekmacron', 
        'Oslash', 'Oslashacute', 'Osmall', 'Otilde', 'Otildeacute', 'Otildedieresis', 'Otildemacron', 'P', 'Pacute', 'Palochka-cy', 
        'Pdotaccent', 'Pstroke', 'Pstrokethroughdescender', 'Q', 'Qstrokethroughdescender', 'R', 'Racute', 'Rcaron', 'Rcommaaccent', 
        'Rdblgrave', 'Rdotaccent', 'Rdotbelow', 'Rdotbelowmacron', 'Rho', 'Rhodasia', 'Rinvertedbreve', 'Rlinebelow', 'Robliquestroke', 
        'Rstroke', 'S', 'Sacute', 'Sacutedotaccent', 'Scaron', 'Scarondotaccent', 'Scedilla', 'Scircumflex', 'Scommaaccent', 
        'Sdotaccent', 'Sdotbelow', 'Sdotbelowdotaccent', 'SigmaLunateDottedSymbol', 'Sobliquestroke', 'T', 'Tau', 'Tcaron', 
        'Tcedilla', 'Tcircumflexbelow', 'Tcommaaccent', 'Tdiagonalstroke', 'Tdotaccent', 'Tdotbelow', 'Te-cy', 'Tlinebelow', 'U', 
        'Uacute', 'Ubar', 'Ubreve', 'Ucaron', 'Ucircumflex', 'Ucircumflexbelow', 'Udblgrave', 'Udieresis', 'Udieresisacute', 
        'Udieresisbelow', 'Udieresiscaron', 'Udieresisgrave', 'Udieresismacron', 'Udotbelow', 'Ugrave', 'Uhookabove', 'Uhungarumlaut', 
        'Uinvertedbreve', 'Umacron', 'Umacrondieresis', 'Uogonek', 'Upsilon', 'Upsilondasia', 'Upsilondasiaoxia', 
        'Upsilondasiaperispomeni', 'Upsilondasiavaria', 'Upsilondieresis', 'Upsilonmacron', 'Upsilonoxia', 'Upsilontonos', 
        'Upsilonvaria', 'Upsilonvrachy', 'Uring', 'Ustrait-cy', 'Utilde', 'Utildeacute', 'Utildebelow', 'V', 'Vdiagonalstroke', 
        'Vdotbelow', 'Ve-cy', 'Vsmall', 'Vtilde', 'W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wdotaccent', 'Wdotbelow', 'Wgrave', 
        'Wsmall', 'X', 'Xdieresis', 'Xdotaccent', 'Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ydotaccent', 'Ydotbelow', 'Ygrave', 
        'Yhookabove', 'Yi-cy', 'Ymacron', 'Yot', 'Ystroke', 'Ytilde', 'Z', 'Zacute', 'Zcaron', 'Zcircumflex', 'Zdotaccent', 
        'Zdotbelow', 'Zeta', 'Zlinebelow', 'Zsmall', 'a', 'a-cy', 'aacute', 'abreve', 'abreve-cy', 'abreveacute', 'abrevedotbelow', 
        'abrevegrave', 'abrevehookabove', 'abrevetilde', 'acaron', 'acircumflex', 'acircumflexacute', 'acircumflexdotbelow', 
        'acircumflexgrave', 'acircumflexhookabove', 'acircumflextilde', 'adblgrave', 'adieresis', 'adieresis-cy', 'adieresismacron', 
        'adotaccent', 'adotbelow', 'adotmacron', 'ae', 'aeacute', 'aemacron', 'agrave', 'ahookabove', 'aie-cy', 'ainvertedbreve', 
        'amacron', 'aogonek', 'aretroflexhook', 'arighthalfring', 'aring', 'aringacute', 'aringbelow', 'astroke', 'atilde', 'b', 'bdotaccent', 
        'bdotbelow', 'blinebelow', 'bmiddletilde', 'bpalatalhook', 'c', 'cPalatalhook', 'cacute', 'cbar', 'ccaron', 'ccedilla', 'ccedillaacute', 
        'ccircumflex', 'cdotaccent', 'cstroke', 'd', 'dcaron', 'dcedilla', 'dcircumflexbelow', 'ddotaccent', 'ddotbelow', 'dlinebelow', 'dmiddletilde', 
        'dpalatalhook', 'dum', 'dz', 'dzcaron', 'dze-cy', 'e', 'eacute', 'ebreve', 'ecaron', 'ecedilla', 'ecedillabreve', 'ecircumflex', 'ecircumflexacute', 
        'ecircumflexbelow', 'ecircumflexdotbelow', 'ecircumflexgrave', 'ecircumflexhookabove', 'ecircumflextilde', 'edblgrave', 'edieresis', 'edotaccent', 
        'edotbelow', 'egrave', 'ehookabove', 'einvertedbreve', 'emacron', 'emacronacute', 'emacrongrave', 'eogonek', 'er-cy', 'eretroflexhook', 'ertick-cy', 
        'es-cy', 'estroke', 'etilde', 'etildebelow', 'f', 'fStroke', 'fdotaccent', 'flenis', 'fmiddletilde', 'fpalatalhook', 'g', 'gacute', 'gbreve', 
        'gcaron', 'gcircumflex', 'gcommaaccent', 'gdotaccent', 'gmacron', 'gobliquestroke', 'gpalatalhook', 'gsingle', 'h', 'hPalatalhook', 'ha-cy', 
        'hbrevebelow', 'hcaron', 'hcedilla', 'hcircumflex', 'hdieresis', 'hdotaccent', 'hdotbelow', 'hlinebelow', 'i', 'i-cy', 'idotbelow', 'ie-cy', 
        'iebreve-cy', 'iegrave-cy', 'ij', 'io-cy', 'iogonek', 'iretroflexhook', 'itildebelow', 'j', 'jcaron', 'jcircumflex', 'jdotless', 'je-cy', 'jstroke', 
        'k', 'kacute', 'kcaron', 'kcommaaccent', 'kdiagonalstroke', 'kdotbelow', 'klinebelow', 'kobliquestroke', 'kpalatalhook', 'kstroke', 'kstrokediagonalstroke', 
        'l', 'lacute', 'lcaron', 'lcircumflexbelow', 'lcommaaccent', 'ldot', 'ldotbelow', 'ldotbelowmacron', 'ldoublemiddletilde', 'lj', 'llinebelow', 'lpalatalhook', 
        'm', 'macute', 'mdotaccent', 'mdotbelow', 'mill', 'mmiddletilde', 'mpalatalhook', 'mum', 'n', 'nacute', 'napostrophe', 'ncaron', 'ncircumflexbelow', 
        'ncommaaccent', 'ndescender', 'ndotaccent', 'ndotbelow', 'ngrave', 'nj', 'nlinebelow', 'nmiddletilde', 'nobliquestroke', 'npalatalhook', 'ntilde', 'num', 
        'o', 'o-cy', 'oacute', 'obreve', 'ocaron', 'ocircumflex', 'ocircumflexacute', 'ocircumflexdotbelow', 'ocircumflexgrave', 'ocircumflexhookabove', 
        'ocircumflextilde', 'odblgrave', 'odieresis', 'odieresis-cy', 'odieresismacron', 'odotaccent', 'odotaccentmacron', 'odotbelow', 'oe', 'ograve', 
        'ohookabove', 'ohungarumlaut', 'oinvertedbreve', 'omacron', 'omacronacute', 'omacrongrave', 'omicron', 'omicrondasia', 'omicrondasiaoxia', 
        'omicrondasiavaria', 'omicronoxia', 'omicronpsili', 'omicronpsilioxia', 'omicronpsilivaria', 'omicrontonos', 'omicronvaria', 'oogonek', 'oslash', 
        'oslashacute', 'otilde', 'otildeacute', 'otildedieresis', 'otildemacron', 'p', 'pacute', 'palochka-cy', 'pdotaccent', 'pmiddletilde', 'ppalatalhook', 
        'pstroke', 'pstrokethroughdescender', 'q', 'qdiagonalstroke', 'qstrokethroughdescender', 'r', 'r.salt', 'racute', 'rcaron', 'rcommaaccent', 'rdblgrave', 
        'rdotaccent', 'rdotbelow', 'rdotbelowmacron', 'rinvertedbreve', 'rlinebelow', 'rmiddletilde', 'robliquestroke', 'rpalatalhook', 'rstroke', 'rum', 
        's', 'sacute', 'sacutedotaccent', 'scaron', 'scarondotaccent', 'scedilla', 'scircumflex', 'scommaaccent', 'sdotaccent', 'sdotbelow', 'sdotbelowdotaccent', 
        'shha-cy', 'sigmaLunateDottedSymbol', 'sigmaLunateSymbol', 'smiddletilde', 'sobliquestroke', 'spalatalhook', 't', 'tcaron', 'tcedilla', 'tcircumflexbelow', 
        'tcommaaccent', 'tdiagonalstroke', 'tdieresis', 'tdotaccent', 'tdotbelow', 'thstrikethrough', 'tlinebelow', 'tmiddletilde', 'u', 'u-cy', 'uacute', 'ubar',  
        'uhorn', 'uhornacute', 'uhorndotbelow', 'uhorngrave', 'uhornhookabove', 'uhorntilde', 'uinvertedbreve', 'umacron', 
        'umacron-cy', 'umacron.component', 'umacrondieresis',
        'ubreve', 'ucaron', 'ucircumflex', 'ucircumflexbelow', 'udblgrave', 'udieresis', 'udieresis-cy', 'udieresisacute', 'udieresisbelow', 'udieresiscaron', 
        'udieresisgrave', 'udieresismacron', 'udotbelow', 'ugrave', 'uhookabove', 'uhungarumlaut', 'uhungarumlaut-cy', 'uinvertedbreve', 'umacron', 'umacron-cy', 
        'umacrondieresis', 'uogonek', 'uretroflexhook', 'uring', 'ushort-cy', 'utilde', 'utildeacute', 'utildebelow', 'v', 'vdiagonalstroke', 'vdotbelow', 'vpalatalhook', 
        'vtilde', 'w', 'wacute', 'wcircumflex', 'wdieresis', 'wdotaccent', 'wdotbelow', 'wgrave', 'wring', 'x', 'xdieresis', 'xdotaccent', 'xpalatalhook', 'y', 'yacute', 
        'ycircumflex', 'ydieresis', 'ydotaccent', 'ydotbelow', 'ygrave', 'yhookabove', 'ymacron', 'yot', 'yring', 'ystroke', 'ytilde', 'z', 'zacute', 'zcaron', 
        'zcircumflex', 'zdotaccent', 'zdotbelow', 'zlinebelow', 'zmiddletilde', 'zpalatalhook', 
        'tildeoverlaycomb', 'strokeshortcomb', 'strokelongcomb', 'slashshortcomb', 'slashlongcomb',  'idieresisacute', 'ihookabove', 'igrave',
        'iacute','icircumflex', 'idieresis', 'Ohornacute', 'Ohorndotbelow', 'Ohorngrave', 'Ohornhookabove', 'Ohorntilde',
        }

    BOTTOM_ANCHORS = {'A', 'Aring', 'Aringacute', 'A-cy', 'AE', 'AEacute', 'AEmacron', 'Aacute', 'Abreve', 'Abreve-cy', 'Abreveacute', 'Abrevedotbelow', 
        'Abrevegrave', 'Abrevehookabove', 'Abrevetilde', 'Acaron', 'Acircumflex', 'Acircumflexacute', 'Acircumflexdotbelow', 
        'Acircumflexgrave', 'Acircumflexhookabove', 'Acircumflextilde', 'Adblgrave', 'Adieresis', 'Adieresis-cy', 'Adieresismacron', 
        'Adotaccent', 'Adotbelow', 'Adotmacron', 'Agrave', 'Ahookabove', 'Aie-cy', 'Ainvertedbreve', 'Alpha', 'Alphadasia', 
        'Alphadasiaoxia', 'Alphadasiaoxiaprosgegrammeni', 'Alphadasiaperispomeni', 'Alphadasiaperispomeniprosgegrammeni', 
        'Alphadasiaprosgegrammeni', 'Alphadasiavaria', 'Alphadasiavariaprosgegrammeni', 'Alphamacron', 'Alphaoxia', 
        'Alphaprosgegrammeni', 'Alphapsili', 'Alphapsilioxia', 'Alphapsilioxiaprosgegrammeni', 'Alphapsiliperispomeni', 
        'Alphapsiliperispomeniprosgegrammeni', 'Alphapsiliprosgegrammeni', 'Alphapsilivaria', 'Alphapsilivariaprosgegrammeni', 
        'Alphatonos', 'Alphavaria', 'Alphavrachy', 'Amacron', 'Aogonek', 'Aringbelow', 'Astroke', 'Atilde', 'B', 'Bdotaccent', 
        'Bdotbelow', 'Beta', 'Blinebelow', 'Bstroke', 'C', 'Cacute', 'Cbar', 'Ccaron', 'Ccedilla', 'Ccedillaacute', 'Ccircumflex', 
        'Cdotaccent', 'Chi', 'Chi-latin', 'Csmall', 'Cstroke', 'D', 'DZ', 'DZcaron', 'Dcaron', 'Dcedilla', 'Dcircumflexbelow', 
        'Ddotaccent', 'Ddotbelow', 'Dlinebelow', 'Dz', 'Dzcaron', 'Dze-cy', 'E', 'Eacute', 'Ebreve', 'Ecaron', 'Ecedilla', 
        'Ecedillabreve', 'Ecircumflex', 'Ecircumflexacute', 'Ecircumflexbelow', 'Ecircumflexdotbelow', 'Ecircumflexgrave', 
        'Ecircumflexhookabove', 'Ecircumflextilde', 'Edblgrave', 'Edieresis', 'Edotaccent', 'Edotbelow', 'Egrave', 'Ehookabove', 'Einvertedbreve', 'Em-cy', 
        'Emacron', 'Emacronacute', 'Emacrongrave', 'Emtail-cy', 'En-cy', 'Entail-cy', 'Eogonek', 'Epsilon', 'Epsilondasia', 'Epsilondasiaoxia', 'Epsilondasiavaria', 
        'Epsilonoxia', 'Epsilonpsili', 'Epsilonpsilioxia', 'Epsilonpsilivaria', 'Epsilontonos', 'Epsilonvaria', 'Er-cy', 'Es-cy', 'Estroke', 'Eta', 'Etadasia', 
        'Etadasiaoxia', 'Etadasiaoxiaprosgegrammeni', 'Etadasiaperispomeni', 'Etadasiaperispomeniprosgegrammeni', 'Etadasiaprosgegrammeni', 'Etadasiavaria', 
        'Etadasiavariaprosgegrammeni', 'Etaoxia', 'Etaprosgegrammeni', 'Etapsili', 'Etapsilioxia', 'Etapsilioxiaprosgegrammeni', 'Etapsiliperispomeni', 
        'Etapsiliperispomeniprosgegrammeni', 'Etapsiliprosgegrammeni', 'Etapsilivaria', 'Etapsilivariaprosgegrammeni', 'Etatonos', 'Etavaria', 'Etilde', 'Etildebelow', 
        'F', 'Fdotaccent', 'G', 'Gacute', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent', 'Gdotaccent', 'Gmacron', 'Gobliquestroke', 'H', 'Ha-cy', 'Hbrevebelow', 
        'Hcaron', 'Hcedilla', 'Hcircumflex', 'Hdieresis', 'Hdotaccent', 'Hdotbelow', 'I', 'I-cy', 'IJ', 'Iacute', 'Ibreve', 'Icaron', 'Icircumflex', 'Idblgrave', 
        'Idieresis', 'Idieresisacute', 'Idotaccent', 'Idotbelow', 'Ie-cy', 'Iebreve-cy', 'Iegrave-cy', 'Igrave', 'Ihookabove', 'Iinvertedbreve', 'Imacron', 'Io-cy', 
        'Iogonek', 'Iota', 'Iotadasia', 'Iotadasiaoxia', 'Iotadasiaperispomeni', 'Iotadasiavaria', 'Iotadieresis', 'Iotamacron', 'Iotaoxia', 'Iotapsili', 'Iotapsilioxia', 
        'Iotapsiliperispomeni', 'Iotapsilivaria', 'Iotatonos', 'Iotavaria', 'Iotavrachy', 'Itilde', 'Itildebelow', 'J', 'Jcircumflex', 'Je-cy', 'Jstroke', 'K', 'Ka-cy', 'Kacute', 
        'Kappa', 'Kcaron', 'Kcommaaccent', 'Kdiagonalstroke', 'Kdotbelow', 'Kje-cy', 'Klinebelow', 'Kobliquestroke', 'Kstroke', 'Kstrokediagonalstroke', 'L', 'LJ', 'Lacute', 
        'Lbar', 'Lcaron', 'Lcircumflexbelow', 'Lcommaaccent', 'Ldot', 'Ldotbelow', 'Ldotbelowmacron', 'Ldoublebar', 'Lj', 'Llinebelow', 'Lmiddletilde', 'M', 'Macute', 'Mdotaccent', 
        'Mdotbelow', 'Mu', 'N', 'NJ', 'Nacute', 'Ncaron', 'Ncircumflexbelow', 'Ncommaaccent', 'Ndescender', 'Ndotaccent', 'Ndotbelow', 'Ngrave', 'Nj', 'Nlinebelow', 
        'Nobliquestroke', 'Ntilde', 'Nu', 'O', 'O-cy', 'OE', 'Oacute', 'Obreve', 'Ocaron', 'Ocircumflex', 'Ocircumflexacute', 'Ocircumflexdotbelow', 'Ocircumflexgrave', 
        'Ocircumflexhookabove', 'Ocircumflextilde', 'Odblgrave', 'Odieresis', 'Odieresis-cy', 'Odieresismacron', 'Odotaccent', 'Odotaccentmacron', 'Odotbelow', 'Ograve', 
        'Ohm', 'Ohookabove', 'Ohorn', 'Ohornacute', 'Ohorndotbelow', 'Ohorngrave', 'Ohornhookabove', 'Ohorntilde', 'Ohungarumlaut', 'Oinvertedbreve', 'Olongstroke', 
        'Omacron', 'Omacronacute', 'Omacrongrave', 'Omega', 'Omegadasia', 'Omegadasiaoxia', 'Omegadasiaoxiaprosgegrammeni', 'Omegadasiaperispomeni', 
        'Omegadasiaperispomeniprosgegrammeni', 'Omegadasiaprosgegrammeni', 'Omegadasiavaria', 'Omegadasiavariaprosgegrammeni', 'Omegaoxia', 'Omegaprosgegrammeni', 
        'Omegapsili', 'Omegapsilioxia', 'Omegapsilioxiaprosgegrammeni', 'Omegapsiliperispomeni', 'Omegapsiliperispomeniprosgegrammeni', 'Omegapsiliprosgegrammeni', 
        'Omegapsilivaria', 'Omegapsilivariaprosgegrammeni', 'Omegatonos', 'Omegavaria', 'Omicron', 'Omicrondasia', 'Omicrondasiaoxia', 'Omicrondasiavaria', 'Omicronoxia', 
        'Omicronpsili', 'Omicronpsilioxia', 'Omicronpsilivaria', 'Omicrontonos', 'Omicronvaria', 'Oogonek', 'Oogonekmacron', 'Oslash', 'Oslashacute', 'Osmall', 'Otilde', 
        'Otildeacute', 'Otildedieresis', 'Otildemacron', 'P', 'Pacute', 'Palochka-cy', 'Pdotaccent', 'Pstroke', 'Pstrokethroughdescender', 'Q', 'Qstrokethroughdescender', 
        'R', 'Racute', 'Rcaron', 'Rcommaaccent', 'Rdblgrave', 'Rdotaccent', 'Rdotbelow', 'Rdotbelowmacron', 'Rho', 'Rhodasia', 'Rinvertedbreve', 'Rlinebelow', 
        'Robliquestroke', 'Rstroke', 'S', 'Sacute', 'Sacutedotaccent', 'Scaron', 'Scarondotaccent', 'Scedilla', 'Scircumflex', 'Scommaaccent', 'Sdotaccent', 'Sdotbelow', 
        'Sdotbelowdotaccent', 'SigmaLunateDottedSymbol', 'Sobliquestroke', 'T', 'Tau', 'Tcaron', 'Tcedilla', 'Tcircumflexbelow', 'Tcommaaccent', 'Tdiagonalstroke', 
        'Tdotaccent', 'Tdotbelow', 'Te-cy', 'Tlinebelow', 'U', 'Uacute', 'Ubar', 'Ubreve', 'Ucaron', 'Ucircumflex', 'Ucircumflexbelow', 'Udblgrave', 'Udieresis', 
        'Udieresisacute', 'Udieresisbelow', 'Udieresiscaron', 'Udieresisgrave', 'Udieresismacron', 'Udotbelow', 'Ugrave', 'Uhookabove', 'Uhorn', 'Uhornacute', 'Uhorndotbelow', 
        'Uhorngrave', 'Uhornhookabove', 'Uhorntilde', 'Uhungarumlaut', 'Uinvertedbreve', 'Umacron', 'Umacrondieresis', 'Uogonek', 'Upsilon', 'Upsilondasia', 'Upsilondasiaoxia', 
        'Upsilondasiaperispomeni', 'Upsilondasiavaria', 'Upsilondieresis', 'Upsilonmacron', 'Upsilonoxia', 'Upsilontonos', 'Upsilonvaria', 'Upsilonvrachy', 'Uring', 'Ustrait-cy', 
        'Utilde', 'Utildeacute', 'Utildebelow', 'V', 'Vdiagonalstroke', 'Vdotbelow', 'Ve-cy', 'Vsmall', 'Vtilde', 'W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wdotaccent', 
        'Wdotbelow', 'Wgrave', 'Wsmall', 'X', 'Xdieresis', 'Xdotaccent', 'Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ydotaccent', 'Ydotbelow', 'Ygrave', 'Yhookabove', 'Yi-cy', 
        'Ymacron', 'Yot', 'Ystroke', 'Ytilde', 'Z', 'Zacute', 'Zcaron', 'Zcircumflex', 'Zdotaccent', 'Zdotbelow', 'Zeta', 'Zlinebelow', 'Zsmall', 'a', 'a-cy', 'aacute', 
        'abreve', 'abreve-cy', 'abreveacute', 'abrevedotbelow', 'abrevegrave', 'abrevehookabove', 'abrevetilde', 'acaron', 'acircumflex', 'acircumflexacute', 
        'acircumflexdotbelow', 'acircumflexgrave', 'acircumflexhookabove', 'acircumflextilde', 'acutebelowcomb', 'adblgrave', 'adieresis', 'adieresis-cy', 
        'adieresismacron', 'adotaccent', 'adotbelow', 'adotmacron', 'ae', 'aeacute', 'aemacron', 'agrave', 'ahookabove', 'aie-cy', 'ainvertedbreve', 'alpha', 
        'alphadasia', 'alphadasiaoxia', 'alphadasiaoxiaypogegrammeni', 'alphadasiaperispomeni', 'alphadasiaperispomeniypogegrammeni', 'alphadasiavaria', 
        'alphadasiavariaypogegrammeni', 'alphadasiaypogegrammeni', 'alphamacron', 'alphaoxia', 'alphaoxiaypogegrammeni', 'alphaperispomeni', 'alphaperispomeniypogegrammeni', 
        'alphapsili', 'alphapsilioxia', 'alphapsilioxiaypogegrammeni', 'alphapsiliperispomeni', 'alphapsiliperispomeniypogegrammeni', 'alphapsilivaria', 
        'alphapsilivariaypogegrammeni', 'alphapsiliypogegrammeni', 'alphatonos', 'alphavaria', 'alphavariaypogegrammeni', 'alphavrachy', 'alphaypogegrammeni', 
        'amacron', 'aogonek', 'aretroflexhook', 'arighthalfring', 'aring', 'aringacute', 'aringbelow', 'arrowdoublerightbelowcomb', 'arrowheadleftbelowcomb', 
        'arrowheadrightbelowcomb', 'arrowheadrightheadupbelowcomb', 'arrowleftrightbelowcomb', 'arrowupbelowcomb', 'asteriskbelowcomb', 'astroke', 'atilde', 'b', 
        'bdotaccent', 'bdotbelow', 'blinebelow', 'bmiddletilde', 'bpalatalhook', 'brevebelow', 'breveinvertedbelowcomb', 'bridgebelowcomb', 'bridgeinvertedbelowcomb', 'c', 
        'cPalatalhook', 'cacute', 'caronbelowcomb', 'cbar', 'ccaron', 'ccedilla', 'ccedillaacute', 'ccircumflex', 'cdotaccent', 'cedillacomb', 'cedillacomb.component', 
        'circumflexbelow', 'circumflexbelowcomb', 'commaaccentcomb', 'cstroke', 'd', 'dblarchinvertedbelowcomb', 'dbllowlinecomb', 'dblmacronbelowcomb', 
        'dcaron', 'dcedilla', 'dcircumflexbelow', 'ddotaccent', 'ddotbelow', 'dieresisbelow', 'dlinebelow', 'dmiddletilde', 'dotbelowcomb', 'doublebrevebelowcomb', 
        'doubleringbelowcomb', 'doubleverticallinebelowcomb', 'downtackbelowcomb', 'dpalatalhook', 'dum', 'dz', 'dzcaron', 'dze-cy', 'e', 
        'eacute', 'ebreve', 'ecaron', 'ecedilla', 'ecedillabreve', 'ecircumflex', 'ecircumflexacute', 'ecircumflexbelow', 'ecircumflexdotbelow', 'ecircumflexgrave', 
        'ecircumflexhookabove', 'ecircumflextilde', 'edblgrave', 'edieresis', 'edotaccent', 'edotbelow', 'egrave', 'ehookabove', 'einvertedbreve', 'emacron', 'emacronacute', 
        'emacrongrave', 'eogonek', 'equalbelowcomb', 'er-cy', 'eretroflexhook', 'ertick-cy', 'es-cy', 'eshpalatalhook', 'estroke', 'eta', 'etadasia', 'etadasiaoxia', 
        'etadasiaoxiaypogegrammeni', 'etadasiaperispomeni', 'etadasiaperispomeniypogegrammeni', 'etadasiavaria', 'etadasiavariaypogegrammeni', 'etadasiaypogegrammeni', 
        'etaoxia', 'etaoxiaypogegrammeni', 'etaperispomeni', 'etaperispomeniypogegrammeni', 'etapsili', 'etapsilioxia', 'etapsilioxiaypogegrammeni', 
        'etapsiliperispomeni', 'etapsiliperispomeniypogegrammeni', 'etapsilivaria', 'etapsilivariaypogegrammeni', 'etapsiliypogegrammeni', 'etatonos', 
        'etavaria', 'etavariaypogegrammeni', 'etaypogegrammeni', 'etilde', 'etildebelow', 'f', 'fStroke', 'fdotaccent', 'flenis', 'fmiddletilde', 
        'fpalatalhook', 'g', 'gacute', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent', 'gdotaccent', 'gmacron', 'gobliquestroke', 'gpalatalhook', 
        'gravebelowcomb', 'gsingle', 'h', 'hPalatalhook', 'ha-cy', 'hbrevebelow', 'hcaron', 'hcedilla', 'hcircumflex', 'hdieresis', 'hdotaccent', 
        'hdotbelow', 'hlinebelow', 'i', 'i-cy', 'idotbelow', 'idotless', 'ie-cy', 'iebreve-cy', 'iegrave-cy', 'ij', 'io-cy', 'iogonek', 
        'iretroflexhook', 'itildebelow', 'j', 'jcaron', 'jcircumflex', 'jdotless', 'je-cy', 'jstroke', 'k', 'kacute', 'kcaron', 'kcommaaccent', 
        'kdiagonalstroke', 'kdotbelow', 'klinebelow', 'kobliquestroke', 'kpalatalhook', 'kstroke', 'kstrokediagonalstroke', 'l', 'lacute', 'lcaron', 
        'lcircumflexbelow', 'lcommaaccent', 'ldot', 'ldotbelow', 'ldotbelowmacron', 'ldoublemiddletilde', 'leftanglebelowcomb', 'lefttackbelowcomb', 
        'lj', 'llinebelow', 'lowlinecomb', 'lpalatalhook', 'm', 'macronbelow', 'macronbelowcomb', 'macute', 'mdotaccent', 'mdotbelow', 'mill', 
        'minusbelowcomb', 'mmiddletilde', 'mpalatalhook', 'mum', 'n', 'nacute', 'napostrophe', 'ncaron', 'ncircumflexbelow', 'ncommaaccent', 
        'ndescender', 'ndotaccent', 'ndotbelow', 'ngrave', 'nj', 'nlinebelow', 'nmiddletilde', 'nobliquestroke', 'npalatalhook', 'ntilde', 
        'num', 'o', 'o-cy', 'oacute', 'obreve', 'ocaron', 'ocircumflex', 'ocircumflexacute', 'ocircumflexdotbelow', 'ocircumflexgrave',
         'ocircumflexhookabove', 'ocircumflextilde', 'odblgrave', 'odieresis', 'odieresis-cy', 'odieresismacron', 'odotaccent', 'odotaccentmacron', 
         'odotbelow', 'oe', 'ogonekcomb', 'ograve', 'ohookabove', 'ohorn', 'ohornacute', 'ohorndotbelow', 'ohorngrave', 'ohornhookabove', 'ohorntilde', 
         'ohungarumlaut', 'oinvertedbreve', 'omacron', 'omacronacute', 'omacrongrave', 'omega', 'omega-latin', 'omegadasia', 'omegadasiaoxia', 
         'omegadasiaoxiaypogegrammeni', 'omegadasiaperispomeni', 'omegadasiaperispomeniypogegrammeni', 'omegadasiavaria', 'omegadasiavariaypogegrammeni', 
         'omegadasiaypogegrammeni', 'omegaoxia', 'omegaoxiaypogegrammeni', 'omegaperispomeni', 'omegaperispomeniypogegrammeni', 'omegapsili', 'omegapsilioxia', 
         'omegapsilioxiaypogegrammeni', 'omegapsiliperispomeni', 'omegapsiliperispomeniypogegrammeni', 'omegapsilivaria', 'omegapsilivariaypogegrammeni', 
         'omegapsiliypogegrammeni', 'omegatonos', 'omegavaria', 'omegavariaypogegrammeni', 'omegaypogegrammeni', 'omicron', 'omicrondasia', 'omicrondasiaoxia', 
         'omicrondasiavaria', 'omicronoxia', 'omicronpsili', 'omicronpsilioxia', 'omicronpsilivaria', 'omicrontonos', 'omicronvaria', 'oogonek', 'oslash', 
         'oslashacute', 'otilde', 'otildeacute', 'otildedieresis', 'otildemacron', 'p', 'pacute', 'palatalhookcomb', 'palochka-cy', 'pdotaccent', 
         'plusbelowcomb', 'pmiddletilde', 'ppalatalhook', 'prosgegrammeni', 'pstroke', 'pstrokethroughdescender', 'q', 'qdiagonalstroke', 
         'qstrokethroughdescender', 'r', 'r.salt', 'racute', 'rbelowcomb', 'rcaron', 'rcommaaccent', 'rdblgrave', 'rdotaccent', 'rdotbelow', 'rdotbelowmacron', 
         'righttackbelowcomb', 'ringbelowcomb', 'ringhalfleftbelowcomb', 'ringhalfrightbelowcomb', 'rinvertedbreve', 'rlinebelow', 'rmiddletilde', 
         'robliquestroke', 'rpalatalhook', 'rstroke', 'rum', 's', 'sacute', 'sacutedotaccent', 'scaron', 'scarondotaccent', 'scedilla', 'scircumflex', 
         'scommaaccent', 'sdotaccent', 'sdotbelow', 'sdotbelowdotaccent', 'seagullbelowcomb', 'shha-cy', 'sigmaLunateDottedSymbol', 'sigmaLunateSymbol', 
         'smiddletilde', 'snakebelowcomb', 'sobliquestroke', 'spalatalhook', 'squarebelowcomb', 't', 'tcaron', 'tcedilla', 'tcircumflexbelow', 'tcommaaccent', 
         'tdiagonalstroke', 'tdieresis', 'tdotaccent', 'tdotbelow', 'thstrikethrough', 'tildebelow', 'tlinebelow', 'tmiddletilde', 'u', 'u-cy', 'uacute', 'ubar', 
         'ubreve', 'ucaron', 'ucircumflex', 'ucircumflexbelow', 'udblgrave', 'udieresis', 'udieresis-cy', 'udieresisacute', 'udieresisbelow', 'udieresiscaron', 
         'udieresisgrave', 'udieresismacron', 'udotbelow', 'ugrave', 'uhookabove', 'uhorn', 'uhornacute', 'uhorndotbelow', 'uhorngrave', 'uhornhookabove', 
         'uhorntilde', 'uhungarumlaut', 'uhungarumlaut-cy', 'uinvertedbreve', 'umacron', 'umacron-cy', 'umacrondieresis', 'uni2195', 'uni21a8', 'uogonek', 
         'uptackbelowcomb', 'uretroflexhook', 'uring', 'ushort-cy', 'utilde', 'utildeacute', 'utildebelow', 'v', 'vdiagonalstroke', 'vdotbelow', 
         'verticallinebelowcomb', 'vpalatalhook', 'vtilde', 'w', 'wacute', 'wcircumflex', 'wdieresis', 'wdotaccent', 'wdotbelow', 'wgrave', 'wring', 
         'x', 'xbelowcomb', 'xdieresis', 'xdotaccent', 'xpalatalhook', 'y', 'yacute', 'ycircumflex', 'ydieresis', 'ydotaccent', 
         'ydotbelow', 'ygrave', 'yhookabove', 'ymacron', 'yot', 'ypogegrammeni', 'ypogegrammenicomb', 'yring', 'ystroke', 'ytilde', 'z', 'zacute', 
         'zcaron', 'zcircumflex', 'zdotaccent', 'zdotbelow', 'zlinebelow', 'zmiddletilde', 'zpalatalhook','dottedCircle', 'idieresisacute', 'ihookabove',
         'arrowheadrightheaddownbelow', 'igrave', 'iacute', 'icircumflex', 'idieresis',  
    }

    OGONEK_ANCHORS = {'A', 'Aring', 'Aringacute', 'E', 'I', 'O', 'U', 'a', 'e', 'i', 'o', 'u',
        'A-cy', 'Aacute', 'Abreve', 'Abreve-cy', 'Abreveacute', 'Abrevedotbelow', 'Abrevegrave', 'Abrevehookabove', 'Abrevetilde', 'Acaron', 'Acircumflex', 
        'Acircumflexacute', 'Acircumflexdotbelow', 'Acircumflexgrave', 'Acircumflexhookabove', 'Acircumflextilde', 'Adblgrave', 'Adieresis', 'Adieresis-cy', 
        'Adieresismacron', 'Adotaccent', 'Adotbelow', 'Adotmacron', 'Agrave', 'Ahookabove', 'Ainvertedbreve', 'Alpha', 'Alphadasia', 'Alphadasiaoxia', 
        'Alphadasiaoxiaprosgegrammeni', 'Alphadasiaperispomeni', 'Alphadasiaperispomeniprosgegrammeni', 'Alphadasiaprosgegrammeni', 'Alphadasiavaria', 
        'Alphadasiavariaprosgegrammeni', 'Alphamacron', 'Alphaoxia', 'Alphaprosgegrammeni', 'Alphapsili', 'Alphapsilioxia', 'Alphapsilioxiaprosgegrammeni', 
        'Alphapsiliperispomeni', 'Alphapsiliperispomeniprosgegrammeni', 'Alphapsiliprosgegrammeni', 'Alphapsilivaria', 'Alphapsilivariaprosgegrammeni', 
        'Alphatonos', 'Alphavaria', 'Alphavrachy', 'Amacron', 'Aogonek', 'Aringacute', 'Aringbelow', 'Astroke', 'Atilde', 'Eacute', 'Ebreve', 'Ecaron', 
        'Ecedilla', 'Ecedillabreve', 'Ecircumflex', 'Ecircumflexacute', 'Ecircumflexbelow', 'Ecircumflexdotbelow', 'Ecircumflexgrave', 'Ecircumflexhookabove', 
        'Ecircumflextilde', 'Edblgrave', 'Edieresis', 'Edotaccent', 'Edotbelow', 'Egrave', 'Ehookabove', 'Einvertedbreve', 'Emacron', 'Emacronacute', 
        'Emacrongrave', 'Eogonek', 'Epsilon', 'Epsilondasia', 'Epsilondasiaoxia', 'Epsilondasiavaria', 'Epsilonoxia', 'Epsilonpsili', 'Epsilonpsilioxia', 
        'Epsilonpsilivaria', 'Epsilontonos', 'Epsilonvaria', 'Estroke', 'Etilde', 'Etildebelow', 'I-cy', 'IJ', 'Iacute', 'Ibreve', 'Icaron', 'Icircumflex', 
        'Idblgrave', 'Idieresis', 'Idieresisacute', 'Idotaccent', 'Idotbelow', 'Ie-cy', 'Iebreve-cy', 'Iegrave-cy', 'Igrave', 'Ihookabove', 'Iinvertedbreve', 
        'Imacron', 'Io-cy', 'Iogonek', 'Iota', 'Iotadasia', 'Iotadasiaoxia', 'Iotadasiaperispomeni', 'Iotadasiavaria', 'Iotadieresis', 'Iotamacron', 'Iotaoxia', 
        'Iotapsili', 'Iotapsilioxia', 'Iotapsiliperispomeni', 'Iotapsilivaria', 'Iotatonos', 'Iotavaria', 'Iotavrachy', 'Itilde', 'Itildebelow', 'O-cy', 'Oacute', 
        'Obreve', 'Ocaron', 'Ocircumflex', 'Ocircumflexacute', 'Ocircumflexdotbelow', 'Ocircumflexgrave', 'Ocircumflexhookabove', 'Ocircumflextilde', 'Odblgrave', 
        'Odieresis', 'Odieresis-cy', 'Odieresismacron', 'Odotaccent', 'Odotaccentmacron', 'Odotbelow', 'Ograve', 'Ohookabove', 'Ohungarumlaut', 'Oinvertedbreve', 
        'Olongstroke', 'Omacron', 'Omacronacute', 'Omacrongrave', 'Omicron', 'Omicrondasia', 'Omicrondasiaoxia', 'Omicrondasiavaria', 'Omicronoxia', 'Omicronpsili', 
        'Omicronpsilioxia', 'Omicronpsilivaria', 'Omicrontonos', 'Omicronvaria', 'Oogonek', 'Oogonekmacron', 'Oslash', 'Osmall', 'Otilde', 'Otildeacute', 
        'Otildedieresis', 'Otildemacron', 'Palochka-cy', 'Uacute', 'Ubar', 'Ubreve', 'Ucaron', 'Ucircumflex', 'Ucircumflexbelow', 'Udblgrave', 'Udieresis', 
        'Udieresisacute', 'Udieresisbelow', 'Udieresiscaron', 'Udieresisgrave', 'Udieresismacron', 'Udotbelow', 'Ugrave', 'Uhookabove', 'Uhungarumlaut', 
        'Uinvertedbreve', 'Umacron', 'Umacrondieresis', 'Uogonek', 'Uring', 'Utilde', 'Utildeacute', 'Utildebelow', 'Yi-cy', 'a-cy', 'aacute', 'abreve', 
        'abreve-cy', 'abreveacute', 'abrevedotbelow', 'abrevegrave', 'abrevehookabove', 'abrevetilde', 'acaron', 'acircumflex', 'acircumflexacute', 
        'acircumflexdotbelow', 'acircumflexgrave', 'acircumflexhookabove', 'acircumflextilde', 'adblgrave', 'adieresis', 'adieresis-cy', 'adieresismacron', 
        'adotaccent', 'adotbelow', 'adotmacron', 'agrave', 'ahookabove', 'ainvertedbreve', 'amacron', 'aogonek', 'aretroflexhook', 'arighthalfring', 'aring', 
        'aringacute', 'aringbelow', 'astroke', 'atilde', 'eacute', 'ebreve', 'ecaron', 'ecedilla', 'ecedillabreve', 'ecircumflex', 'ecircumflexacute', 
        'ecircumflexbelow', 'ecircumflexdotbelow', 'ecircumflexgrave', 'ecircumflexhookabove', 'ecircumflextilde', 'edblgrave', 'edieresis', 'edotaccent', 
        'edotbelow', 'egrave', 'ehookabove', 'einvertedbreve', 'emacron', 'emacronacute', 'emacrongrave', 'eogonek', 'eretroflexhook', 'estroke', 'etilde', 
        'etildebelow', 'i-cy', 'idotbelow', 'ie-cy', 'iebreve-cy', 'iegrave-cy', 'ii-cy', 'ij', 'io-cy', 'iogonek', 'iretroflexhook', 'itildebelow', 'o-cy', 
        'oacute', 'obreve', 'ocaron', 'ocircumflex', 'ocircumflexacute', 'ocircumflexdotbelow', 'ocircumflexgrave', 'ocircumflexhookabove', 'ocircumflextilde', 
        'odblgrave', 'odieresis', 'odieresis-cy', 'odieresismacron', 'odotaccent', 'odotaccentmacron', 'odotbelow', 'ograve', 'ohookabove', 'ohungarumlaut', 
        'oinvertedbreve', 'omacron', 'omacronacute', 'omacrongrave', 'omicron', 'omicrondasia', 'omicrondasiaoxia', 'omicrondasiavaria', 'omicronoxia', 
        'omicronpsili', 'omicronpsilioxia', 'omicronpsilivaria', 'omicrontonos', 'omicronvaria', 'oogonek', 'oslash', 'otilde', 'otildeacute', 'otildedieresis', 
        'otildemacron', 'uacute', 'ubar', 'ubreve', 'ucaron', 'ucircumflex', 'ucircumflexbelow', 'udblgrave', 'udieresis', 'udieresisacute', 'udieresisbelow', 
        'udieresiscaron', 'udieresisgrave', 'udieresismacron', 'udotbelow', 'ugrave', 'uhookabove', 'uhungarumlaut', 'uinvertedbreve', 'umacron', 'umacrondieresis', 
        'uogonek', 'uretroflexhook', 'uring', 'utilde', 'utildeacute', 'utildebelow'
    }

    DOT_ANCHORS = {'C', 'L', 'SigmaLunateReversedSymbol', 'c', 'h', 'l', 'oopen'}

    TONOS_ANCHORS = {'A', 'E', 'H', 'I', 'O', 'Ohm', 'P', 'UpsilonhookSymbol', 'Y'}

    VERT_ANCHORS = {'L', 'd', 'l', 't'}

    # Tilde anchors changed into top anchor.
    #TILDE_ANCHORS = ['Utilde', 'ytilde', 'lowtildemod', 'atilde', 'ohorntilde', 'utilde', 'Uhorntilde', 'Ntilde', 'Ytilde', 'Otilde', 
    #    'uhorntilde', 'Etilde', 'Ohorntilde', 'otilde', 'ntilde', 'vtilde', 'Atilde', 'tildeoverlaycomb', 'perispomenicomb', 
    #    'Vtilde', 'Itilde', 'etilde', 'itilde']

    _TOP_ANCHORS = {'Abreve.component', 'Abreve.component1', 'Abreve.component2', 'Abreve.component3', 'Idieresis.component', 'Otilde.component', 
        'Otilde.component1', 'Sacute.component', 'Scaron.component', 'Udieresis.component', 'Umacron.component', 'abreve.component', 
        'abreve.component1', 'abreve.component2', 'abreve.component3', 'acomb', 'acutecomb', 'acutecomb.component', 'acutecomb.component1', 
        'acutecomb.component3', 'acutecomb.component5', 'acutedottedcomb', 'acutegraveacutecomb', 'acutemacroncomb', 'acutetonecomb', 'almostequaltoabovecomb', 
        'arrowheadleftabovecomb', 'arrowheadrightabovecomb', 'asteriskabovecomb', 'brevecomb', 
        'brevecomb.component', 'breveinvertedcomb', 'breveinverteddoublecomb', 'candrabinducomb', 'caroncomb', 'ccomb', 'circumflexcomb', 
        'commaabovecomb', 'commaaboverightcomb', 'commareversedabovecomb', 'commaturnedabovecomb', 'dasiapneumatacomb-cy', 
        'dblgravecomb', 'dbloverlinecomb', 'dblverticallineabovecomb', 'dcomb', 'dialytikatonoscomb', 
        'dieresiscomb', 'dotaboverightcomb', 'dotaccentcomb', 'doublebrevecomb', 'doublemacroncomb', 'ecomb', 'fermatacomb', 
        'gbridgeabovecomb', 'graphemejoinercomb', 'graveacutegravecomb', 'gravecomb', 'gravecomb.component', 'gravecomb.component1', 
        'gravecomb.component3', 'gravedottedcomb', 'gravemacroncomb', 'gravetonecomb', 'hardsigncomb-cy', 'hcomb', 'homotheticabovecomb', 'hookabovecomb', 
        'hookabovecomb.component', 'horncomb', 'hungarumlautcomb', 'icomb', 'idieresis.component', 'koroniscomb', 'leftangleabovecomb', 
        'lefthalfringabovecomb', 'macronacutecomb', 'macroncomb', 'macroncomb.component', 'macroncomb.component1', 'macrongravecomb', 'mcomb', 
        'nottildeabovecomb', 'ocomb', 'otilde.component', 'otilde.component1', 'overlinecomb', 'palatalizationcomb-cy', 
        'perispomenicomb', 'pokrytiecomb-cy', 'psilipneumatacomb-cy', 'rcomb', 'righthalfringabovecomb', 
        'ringcomb', 'ringacutecomb', 'ringhalfright', 'sacute.component', 'scaron.component', 'softsigncomb-cy', 'suspensioncomb', 'tcomb', 
        'tildecomb', 'tildecomb.component', 'tildedoublecomb', 'tildeverticalcomb', 'titlocomb-cy', 'ucomb', 'udieresis.component', 
        'umacron.component', 'uni047E.component', 'vcomb', 'verticallineabovecomb', 'xabovecomb', 'xcomb', 'zigzagabovecomb',
        'ringhalfleft', 'varia', 
        
        #'six.pnum_enclosingkeycapcomb',
        #'three.pnum_enclosingkeycapcomb',
        #'five.pnum_enclosingkeycapcomb',
        #'millionssigncomb-cy',
        #'seven.pnum_enclosingkeycapcomb',
        #'eight.pnum_enclosingkeycapcomb',
        #'hundredthousandssigncomb-cy',
        #'four.pnum_enclosingkeycapcomb',
        #'nine.pnum_enclosingkeycapcomb',
        #'zero.pnum_enclosingkeycapcomb',
        #'one.pnum_enclosingkeycapcomb',
        #'two.pnum_enclosingkeycapcomb]',
    }

    _MIDDLE_ANCHORS = ['slashlongcomb', 'strokelongcomb', 'strokeshortcomb', 'slashshortcomb', 'tildeoverlaycomb',
        'middlegraveaccentmod', 'dagesh-hb',]

    _BOTTOM_ANCHORS = {'acutebelowcomb', 'arrowdoublerightbelowcomb', 'arrowheadleftbelowcomb', 'arrowheadrightbelowcomb', 'arrowheadrightheadupbelowcomb', 
    'arrowleftrightbelowcomb', 'arrowupbelowcomb', 'asteriskbelowcomb', 'brevebelow', 'breveinvertedbelowcomb', 'bridgebelowcomb', 'bridgeinvertedbelowcomb', 
    'caronbelowcomb', 'cedillacomb', 'cedillacomb.component', 'circumflexbelow', 'circumflexbelowcomb', 'commaaccentcomb', 
    'dblarchinvertedbelowcomb', 'dbllowlinecomb', 'dieresisbelow', 'dotbelowcomb', 'doublebrevebelowcomb', 'doubleringbelowcomb', 'doubleverticallinebelowcomb', 
    'downtackbelowcomb', 'equalbelowcomb', 'gravebelowcomb', 'leftanglebelowcomb', 'lefttackbelowcomb', 'lowlinecomb', 'macronbelow', 
    'macronbelowcomb', 'minusbelowcomb', 'ogonekcomb', 'palatalhookcomb', 'plusbelowcomb', 'prosgegrammeni', 'rbelowcomb', 'retroflexhookcomb', 'righttackbelowcomb', 
    'ringbelowcomb', 'ringhalfleftbelowcomb', 'ringhalfrightbelowcomb', 'seagullbelowcomb', 'snakebelowcomb', 'squarebelowcomb', 'tildebelow', 
    'uptackbelowcomb', 'verticallinebelowcomb', 'xbelowcomb', 'ypogegrammenicomb', 'dblmacronbelowcomb', 'voicingmod', 'lowringmod', 'gravebelowcomb', 'acutebelowcomb',
    'arrowheadrightheaddownbelow',
        #'six.pnum_enclosingkeycapcomb',
        #'three.pnum_enclosingkeycapcomb',
        #'five.pnum_enclosingkeycapcomb',
        #'millionssigncomb-cy',
        #'seven.pnum_enclosingkeycapcomb',
        #'eight.pnum_enclosingkeycapcomb',
        #'hundredthousandssigncomb-cy',
        #'four.pnum_enclosingkeycapcomb',
        #'nine.pnum_enclosingkeycapcomb',
        #'zero.pnum_enclosingkeycapcomb',
        #'one.pnum_enclosingkeycapcomb',
        #'two.pnum_enclosingkeycapcomb]',
    }

    _OGONEK_ANCHORS = {'ogonekcomb'}

    _DOT_ANCHORS = {'dotmiddle.component'}

    _TONOS_ANCHORS = {'dasia-uc', 'dasiaoxia-uc', 'dasiaperispomeni-uc', 'dasiavaria-uc', 'oxia-uc', 'psili-uc', 'psilioxia-uc', 
    'psiliperispomeni-uc', 'psilivaria-uc', 'tonoscomb', 'tonoscmb', 'tonos-uc', 'varia-uc'}

    _VERT_ANCHORS = {'caronvert.component'}

    ANCHORS = {
        TOP_: TOP_ANCHORS,
        MIDDLE_: MIDDLE_ANCHORS,
        BOTTOM_: BOTTOM_ANCHORS,
        OGONEK_: OGONEK_ANCHORS, 
        DOT_: DOT_ANCHORS, 
        TONOS_: TONOS_ANCHORS,
        VERT_: VERT_ANCHORS,
        _TOP: _TOP_ANCHORS, 
        _MIDDLE: _MIDDLE_ANCHORS, 
        _BOTTOM: _BOTTOM_ANCHORS,
        _OGONEK: _OGONEK_ANCHORS, 
        _DOT: _DOT_ANCHORS, 
        _TONOS: _TONOS_ANCHORS,
        _VERT: _VERT_ANCHORS,
    }
    GLYPH_ANCHORS = { # Anchor names --> glyphs that contain these anchors.
        TOP_: TOP_ANCHORS,
        MIDDLE_: MIDDLE_ANCHORS,
        BOTTOM_: BOTTOM_ANCHORS,
        OGONEK_: OGONEK_ANCHORS,
        DOT_: DOT_ANCHORS,
        TONOS_: TONOS_ANCHORS,
        VERT_: VERT_ANCHORS,
    }
AD = AnchorData
