# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Copyright (c) 2023+ TYPETR
#     Usage by MIT License
# ..............................................................................
#
#   groupBaseGlyphs.py
#

# Glyphs that are used as base for groups. Scripts only kern within the script (and "all") to the other side.
# The "all" also kern to each other, on the other side. There is no kerning allowed between the scripts.

FORCE_GROUP1 = {}
FORCE_GROUP2 = {}

PUBLIC_KERN1 = 'public.kern1.'
PUBLIC_KERN2 = 'public.kern2.'

SC = 'sc'
UC1 = 'uc1'
UC2 = 'uc2'

LT1 = 'lt1'
LT2 = 'lt2'
LT1_SC = SC + LT1
LT2_SC = SC + LT2

CY1 = 'cy1'
CY2 = 'cy2'
CY1_SC = SC + CY1
CY2_SC = SC + CY2

GR1 = 'gr1'
GR2 = 'gr2'
GR1_SC = SC + GR1
GR2_SC = SC + GR2

ASC1 = 'asc1'
ASC2 = 'asc2'

FIG1 = 'fig1'
FIG2 = 'fig2'
FIG1_SC = SC + FIG1
FIG2_SC = SC + FIG2

SUPS1 = 'superior1'
SUPS2 = 'superior2'
SINF1 = 'inferior1'
SINF2 = 'inferior2'
DNOM1 = 'dnom1'
DNOM2 = 'dnom2'
NUMR1 = 'numr1'
NUMR2 = 'numr2'
DNOM1 = 'dnom1'
DNOM2 = 'dnom2'
ONUM1 = 'onum1'
ONUM2 = 'onum2'

GROUP_NAME_PARTS = {
    LT1:    (PUBLIC_KERN1, '_lt'), 
    LT2:    (PUBLIC_KERN2, '_lt'),
    LT1_SC: (PUBLIC_KERN1, '_sc_lt'),
    LT2_SC: (PUBLIC_KERN2, '_sc_lt'),

    CY1: (PUBLIC_KERN1, '_cy'), 
    CY2: (PUBLIC_KERN2, '_cy'),
    CY1_SC: (PUBLIC_KERN1, '_sc_cy'),
    CY2_SC: (PUBLIC_KERN2, '_sc_cy'),

    GR1: (PUBLIC_KERN1, '_gr'), 
    GR2: (PUBLIC_KERN2, '_gr'),
    GR1_SC: (PUBLIC_KERN1, '_sc_gr'),
    GR2_SC: (PUBLIC_KERN2, '_sc_gr'),

    ASC1: (PUBLIC_KERN1, '_asc'), 
    ASC2: (PUBLIC_KERN2, '_asc'),

    FIG1: (PUBLIC_KERN1, '_fig'), 
    FIG2: (PUBLIC_KERN2, '_fig'),

    UC1: (PUBLIC_KERN1, '_uc'), 
    UC2: (PUBLIC_KERN2, '_uc'),

    SUPS1: (PUBLIC_KERN1, '_superior'), 
    SUPS2: (PUBLIC_KERN2, '_superior'),
    SINF1: (PUBLIC_KERN1, '_inferior'), 
    SINF2: (PUBLIC_KERN2, '_inferior'),
    NUMR1: (PUBLIC_KERN1, '_numr'), 
    NUMR2: (PUBLIC_KERN2, '_numr'),
    DNOM1: (PUBLIC_KERN1, '_dnom'), 
    DNOM2: (PUBLIC_KERN2, '_dnom'),
    ONUM1: (PUBLIC_KERN1, '_onum'), 
    ONUM2: (PUBLIC_KERN2, '_onum'),
}
BASE_SCRIPTS1 = (
    LT1, LT1_SC, 
    CY1, CY1_SC, 
    GR1, GR1_SC, 
    ASC1, 
    FIG1, FIG1_SC, 
    SUPS1, SINF1, NUMR1, DNOM1, ONUM1)
BASE_SCRIPTS2 = (
    LT2, LT2_SC, 
    CY2, CY2_SC, 
    GR2, GR2_SC, 
    ASC2, 
    FIG2, 
    SUPS2, SINF2, NUMR2, DNOM2, ONUM2)

# Defining all script <--> script combinations in the kerning table.
# Also this table is used to generate at least one placeholder kerning pair,
# to ensure that the [kern] lookup gets generated. Otherwise building the VF
# complains for incompatible amounts of [kern] lookups.
# In general this gets solved automatically if all kerning exists, but during 
# development not all kerning may have been filled in.

KERN_GROUPS = (
    # Latin
    (LT1, LT2),
    (LT1_SC, LT2_SC),
    (LT1, LT1_SC),
    (LT1, UC2),
    (UC1, LT2),

    (ASC1, ASC2),
    (ASC1, LT2),
    (ASC1, LT2_SC),
    (LT1, ASC2),
    (LT1_SC, ASC2),

    (FIG1, FIG2),
    (FIG1, LT2),
    (LT1, FIG2),
    
    (SUPS1, SUPS2),
    (SINF1, SINF2),
    (LT1, SUPS2),
    (LT1, SINF2),
    (SUPS1, LT2),
    (SINF1, LT2),
    
    (NUMR1, NUMR2),
    (LT1, NUMR2),
    (LT1, DNOM2),
    (NUMR1, LT2),
    (DNOM1, LT2),
    
    (ONUM1, ONUM2),
    (ONUM1, LT2),
    (LT1, ONUM2),

    # Cyrillic
    (CY1, CY2),
    (CY1_SC, CY2_SC),
    (CY1, CY1_SC),

    #(ASC1, ASC2),
    (ASC1, CY2),
    (ASC1, CY2_SC),
    (CY1, ASC2),
    (CY1_SC, ASC2),

    #(FIG1, FIG2),
    (FIG1, CY2),
    (CY1, FIG2),
    
    #(SUPS1, SUPS2),
    #(SINF1, SINF2),
    (CY1, SUPS2),
    (CY1, SINF2),
    (SUPS1, CY2),
    (SINF1, CY2),
    
    #(NUMR1, NUMR2),
    (CY1, NUMR2),
    (CY1, DNOM2),
    (NUMR1, CY2),
    (DNOM1, CY2),
    
    #(ONUM1, ONUM2),
    (ONUM1, CY2),
    (CY1, ONUM2),

    # Greek
    (GR1, GR2),
    (GR1_SC, GR2_SC),
    (GR1, GR1_SC),

    #(ASC1, ASC2),
    (ASC1, GR2),
    (ASC1, GR2_SC),
    (GR1, ASC2),
    (GR1_SC, ASC2),

    #(FIG1, FIG2),
    (FIG1, GR2),
    (GR1, FIG2),
    
    #(SUPS1, SUPS2),
    #(SINF1, SINF2),
    (GR1, SUPS2),
    (GR1, SINF2),
    (SUPS1, GR2),
    (SINF1, GR2),
    
    #(NUMR1, NUMR2),
    (GR1, NUMR2),
    (GR1, DNOM2),
    (NUMR1, GR2),
    (DNOM1, GR2),
    
    #(ONUM1, ONUM2),
    (ONUM1, GR2),
    (GR1, ONUM2),

)


GROUP_IGNORE = ('tnum', 'cmb', 'comb', 'mod', 'component',) # Always ignore glyphs that include these patterns

# This table is generated by the buildGroups.py script for now.
GROUP_BASE_GLYPHS = {
#==== Proforma_Pro-Regular_MA76.ufo
#Groups: 982 Kerning: 1786, Proforma_Pro-Regular_MA76.ufo
'superior1': {'threesuperior', 'centsuperior', 'usuperior', 'jsuperior', 'onesuperior', 'ksuperior', 'qsuperior', 'ssuperior', 'tsuperior', 'zsuperior', 'sixsuperior', 'foursuperior', 'bsuperior', 'eurosuperior', 'zerosuperior', 'dollarsuperior', 'sevensuperior', 'ysuperior', 'eightsuperior', 'fsuperior', 'parenrightsuperior', 'colonsuperior', 'fivesuperior', 'twosuperior', 'egravesuperior', 'hsuperior', 'quotedblleftsuperior', 'rsuperior', 'gsuperior', 'equalsuperior', 'wsuperior', 'parenleftsuperior', 'isuperior', 'sterlingsuperior', 'ninesuperior', 'asuperior', 'csuperior', 'vsuperior'}, 'superior2': {'threesuperior', 'centsuperior', 'usuperior', 'jsuperior', 'onesuperior', 'ssuperior', 'tsuperior', 'zsuperior', 'sixsuperior', 'bsuperior', 'foursuperior', 'eurosuperior', 'zerosuperior', 'dollarsuperior', 'sevensuperior', 'ysuperior', 'eightsuperior', 'parenrightsuperior', 'fsuperior', 'xsuperior', 'colonsuperior', 'fivesuperior', 'twosuperior', 'quotedblleftsuperior', 'equalsuperior', 'parenleftsuperior', 'isuperior', 'sterlingsuperior', 'ninesuperior', 'msuperior', 'asuperior', 'csuperior', 'vsuperior'}, 'cy1': {'Chedescender_cy', 'Ef_cy.sc', 'Hahook_cy.sc', 'Yi_cy.sc', 'Kahook_cy', 'Shha_cy.sc', 'en_cy.loclBGR', 'Che_cy.sc', 'Pemiddlehook_cy.sc', 'Cheabkhasian_cy', 'Ka_cy', 'chedescender_cy', 'Edieresis_cy.sc', 'Ha_cy', 've_cy.loclBGR', 'Haabkhasian_cy', 'ge_cy.loclBGR', 'Te_cy', 'Be_cy.sc', 'Dje_cy.sc', 'Dze_cy', 'de_cy.loclBGR', 'ustrait_cy', 'Kahook_cy.sc', 'haabkhasian_cy', 'el_cy.loclBGR', 'ka_cy', 'Shha_cy', 've_cy', 'dze_cy', 'Ustrait_cy', 'che_cy.loclBGR', 'Pemiddlehook_cy', 'Ve_cy.sc', 'Edieresis_cy', 'Ka_cy.sc', 'enhook_cy', 'Haabkhasian_cy.sc', 'ze_cy', 'E_cy', 'U_cy.sc', 'e_cy', 'Dze_cy.sc', 'A_cy', 'A_cy.sc', 'enghe_cy', 'Hahook_cy', 'Ustrait_cy.sc', 'be_cy', 'Be_cy', 'Chedescender_cy.sc', 'dzeabkh_cy', 'hahook_cy', 'shha_cy', 'Che_cy', 'ha_cy', 'kahook_cy', 'Enhook_cy', 'hardsign_cy', 'Hardsign_cy.sc', 'Er_cy.sc', 'Enghe_cy.sc', 'iigrave_cy.loclBGR', 'U_cy', 'Cheabkhasian_cy.sc', 'Dzeabkh_cy.sc', 'Ve_cy', 'Enhook_cy.sc', 'palochka_cy', 'pe_cy.loclBGR', 'Aie_cy', 'De_cy.loclBGR.sc', 'ghemiddlehook_cy', 'hardsign_cy.loclBGR', 'E_cy.sc', 'Te_cy.sc', 'u_cy', 'Aie_cy.sc', 'Ha_cy.sc', 'Ef_cy', 'Dje_cy', 'softsign_cy.loclBGR', 'yi_cy', 'aie_cy', 'Hardsign_cy', 'be_cy.loclSRB', 'dje_cy', 'Er_cy', 'Dzeabkh_cy', 'er_cy', 'che_cy', 'a_cy', 'De_cy.loclBGR', 'Enghe_cy'}, 'lt1': {'usuperior', 'henghook', 'P', 'Usuperior', 'jsuperior', 'Eng', 'eshreversedloop', 'dinferior', 'Lcaron', 'qsuperior', 'tsuperior', 'Y.sc', 'Ysuperior', 'Hsuperior', 'Germandbls', 'sinferior', 'Linferior', 'Nlongrightleg', 'yturned', 'Finferior', 'eopen', 'ghook', 'idotless', 'egraveinferior', 'mturned', 'eth', 'Einferior', 'Yinferior', 'Dinferior', 'y', 'Whook', 'dtail', 'kinferior', 'Rinferior', 'jcaron', 'tinferior', 'Eng.sc', 'Chook', 'J.base', 'iota_latin', 'dcaron', 'DZ.sc', 'Vsuperior', 'Binferior', 'A', 'G.sc', 'Whook.sc', 'Rsuperior', 'esh', 'Gscript', 'Ohorn.sc', 'V.sc', 'ezhreversed', 'chook', 'F', 'hinferior', 'eng', 'f.alt_connect', 'Zinferior', 'Fsuperior', 'D.sc', 'Aturned', 'r', 'Ghook', 'Germandbls.sc', 'U', 'L', 'Bsuperior', 'dsuperior', 'ldot', 'uinferior', 'C', 'Creversed', 'Eopen', 'Y', 'S', 'winferior', 'qinferior', 'F.sc', 'AE.sc', 'Chi_latin', 't', 'Ezhreversed', 'Ohorn', 'rsuperior', 'Thorn', 'gsuperior', 'idotlesshorn', 'Pinferior', 'R.sc', 'hturned', 'ezh', 'Ldot.sc', 'cinferior', 'Ssuperior', 'Dz', 'C.sc', 'rinferior', 'N.sc', 'Hinferior', 'Ezh', 'Khook.sc', 'zsuperior', 'tcaron', 'Jsuperior', 'Ezhreversed.sc', 'ginferior', 'Tsuperior', 'bsuperior', 'vturned', 'a', 'P.sc', 'Tinferior', 'Ereversed', 'Eopen.sc', 'Asuperior', 'Alpha_latin', 'Ereversed.sc', 'g', 'ysuperior', 'Jinferior', 'Ksuperior', 'Vinferior', 'd', 'Zsuperior', 'dhook', 'schwa', 'DZ', 'egravesuperior', 'hsuperior', 'alpha_latin', 'vinferior', 'Ainferior', 'U.sc', 'wsuperior', 'Uhorn', 'gamma_latin', 'ustroke', 'Dsuperior', 'germandbls.sc', 'J.base.sc', 'B.sc', 'binferior', 'asuperior', 'vsuperior', 'aturned', 'Chi_latin.sc', 'Ginferior', 'N', 'T.sc', 'Ldot', 'zinferior', 'L.sc', 'ksuperior', 'Sinferior', 'Uhorn.sc', 'f.alt_noconnect', 'ssuperior', 'Psuperior', 'Lcaron.sc', 'G', 'ainferior', 'W.sc', 'Nsuperior', 'Ezh.sc', 'finferior', 'jcrossedtail', 'Kinferior', 'Cinferior', 'B', 'hryvnia', 'Gsuperior', 'R', 'fsuperior', 'whook', 'jinferior', 'Lj', 'Ninferior', 'Qhooktail', 'Khook', 'ae', 'T', 'A.sc', 'f', 'c', 'W', 'fi', 'lbar', 'Thorn.sc', 'Esuperior', 'isuperior', 'ohorn', 'Csuperior', 'yinferior', 'Lsuperior', 'iinferior', 'Uinferior', 'AE', 'csuperior', 'chi_latin'}, 'sc_cy1': {'Te_cy.sc', 'Ef_cy.sc', 'Hahook_cy.sc', 'Aie_cy.sc', 'Yi_cy.sc', 'Shha_cy.sc', 'Ha_cy.sc', 'Ve_cy.sc', 'Che_cy.sc', 'Ka_cy.sc', 'Haabkhasian_cy.sc', 'Pemiddlehook_cy.sc', 'Hardsign_cy.sc', 'Er_cy.sc', 'Enghe_cy.sc', 'U_cy.sc', 'Dze_cy.sc', 'A_cy.sc', 'Cheabkhasian_cy.sc', 'Edieresis_cy.sc', 'Dzeabkh_cy.sc', 'Ustrait_cy.sc', 'Enhook_cy.sc', 'Chedescender_cy.sc', 'Be_cy.sc', 'De_cy.loclBGR.sc', 'Dje_cy.sc', 'Kahook_cy.sc', 'E_cy.sc'}, 'sc1': {'Ef_cy.sc', 'Hahook_cy.sc', 'Phi.sc', 'braceleft.sc', 'Yi_cy.sc', 'Shha_cy.sc', 'Y.sc', 'bracketleft.sc', 'Che_cy.sc', 'exclamdown.sc', 'Nu.sc', 'backslash.sc', 'Pemiddlehook_cy.sc', 'Xi.sc', 'Epsilon.sc', 'degree.sc', 'two.sc', 'Edieresis_cy.sc', 'Omicron.sc', 'Eng.sc', 'nine.sc', 'Be_cy.sc', 'DZ.sc', 'Dje_cy.sc', 'G.sc', 'Kahook_cy.sc', 'Whook.sc', 'bracketright.sc', 'Ohorn.sc', 'V.sc', 'parenleft.sc', 'question.sc', 'D.sc', 'Ve_cy.sc', 'Germandbls.sc', 'Ka_cy.sc', 'Haabkhasian_cy.sc', 'U_cy.sc', 'Rho.sc', 'Dze_cy.sc', 'F.sc', 'AE.sc', 'A_cy.sc', 'questiondown.sc', 'one.sc', 'Ustrait_cy.sc', 'KaiSymbol.sc', 'R.sc', 'Chedescender_cy.sc', 'Omega.sc', 'exclam.sc', 'five.sc', 'Ldot.sc', 'C.sc', 'section.sc', 'eight.sc', 'Psi.sc', 'N.sc', 'ampersand.sc', 'Khook.sc', 'Ezhreversed.sc', 'Hardsign_cy.sc', 'Er_cy.sc', 'P.sc', 'Enghe_cy.sc', 'Sigma.sc', 'Gamma.sc', 'Eopen.sc', 'four.sc', 'Ereversed.sc', 'parenright.sc', 'Cheabkhasian_cy.sc', 'three.sc', 'Dzeabkh_cy.sc', 'Enhook_cy.sc', 'U.sc', 'Beta.sc', 'germandbls.sc', 'De_cy.loclBGR.sc', 'J.base.sc', 'B.sc', 'E_cy.sc', 'Te_cy.sc', 'Chi_latin.sc', 'T.sc', 'Alpha.sc', 'Aie_cy.sc', 'L.sc', 'Uhorn.sc', 'Ha_cy.sc', 'Lcaron.sc', 'six.sc', 'Zeta.sc', 'W.sc', 'seven.sc', 'Ezh.sc', 'slash.sc', 'numbersign.sc', 'glottalstopsmall', 'A.sc', 'braceright.sc', 'Upsilon.sc', 'Chi.sc', 'zero.sc', 'Thorn.sc', 'Sigmafinal.sc'}, 'sc_lt1': {'Chi_latin.sc', 'T.sc', 'L.sc', 'Khook.sc', 'Uhorn.sc', 'D.sc', 'Y.sc', 'Ezhreversed.sc', 'Lcaron.sc', 'Germandbls.sc', 'W.sc', 'P.sc', 'Ezh.sc', 'Eopen.sc', 'Ereversed.sc', 'F.sc', 'AE.sc', 'A.sc', 'U.sc', 'Eng.sc', 'R.sc', 'Thorn.sc', 'Ldot.sc', 'DZ.sc', 'germandbls.sc', 'J.base.sc', 'G.sc', 'B.sc', 'Whook.sc', 'C.sc', 'Ohorn.sc', 'V.sc', 'N.sc'}, 'gr1': {'Phi.sc', 'Alpha.sc', 'Rho', 'Epsilon', 'delta', 'lowernumeral_greek', 'sigma', 'theta', 'lambda', 'Omega', 'Zeta.sc', 'pi', 'Nu.sc', 'chi', 'Xi.sc', 'upsilon', 'numeral_greek', 'KaiSymbol', 'Zeta', 'nu', 'Epsilon.sc', 'Gamma.sc', 'Chi', 'Nu', 'Sigma.sc', 'Omicron', 'zeta', 'tau', 'Rho.sc', 'Beta', 'gamma', 'beta', 'sigmafinal', 'Upsilon', 'Omicron.sc', 'KaiSymbol.sc', 'Upsilon.sc', 'xi', 'epsilon', 'Chi.sc', 'Omega.sc', 'iota', 'alpha', 'Beta.sc', 'Psi', 'iotadieresis', 'omega', 'Alpha', 'omicron', 'Xi', 'Sigmafinal.sc', 'Sigma', 'Gamma', 'eta', 'kaiSymbol', 'Phi', 'Psi.sc'}, 'inferior1': {'zeroinferior', 'hinferior', 'zinferior', 'dinferior', 'fourinferior', 'ginferior', 'ainferior', 'sinferior', 'uinferior', 'parenrightinferior', 'finferior', 'commainferior', 'parenleftinferior', 'egraveinferior', 'winferior', 'qinferior', 'equalinferior', 'oneinferior', 'jinferior', 'seveninferior', 'kinferior', 'sixinferior', 'twoinferior', 'vinferior', 'tinferior', 'threeinferior', 'eightinferior', 'cinferior', 'yinferior', 'nineinferior', 'binferior', 'iinferior', 'rinferior', 'fiveinferior'}, 'asc1': {'asciicircum', 'parenleft.sc', 'dotaccent', 'question.sc', 'braceleft.sc', 'ampersand.sc', 'florin', 'bar', 'bracketleft', 'quotedblleft', 'section', 'currency', 'periodcentered', 'bracketleft.sc', 'quotedblright', 'ordfeminine', 'section.sc', 'clickretroflex', 'ampersand', 'apple', 'comma', 'exclamdown.sc', 'degree', 'partialdiff', 'backslash.sc', 'parenleft', 'copyright', 'Glottalstop', 'glottalstopreversed', 'newsheqel', 'guillemotright', 'Saltillo', 'cent', 'slash.sc', 'sterling', 'asciitilde', 'trademark', 'parenright.sc', 'at', 'exclamdown', 'degree.sc', 'Esh', 'braceright', 'bullet', 'bracketright', 'emdash', 'braceleft', 'questiondown.sc', 'horizontalbar', 'radical', 'underscore', 'glottalstopsmall', 'yen', 'braceright.sc', 'space', 'slash', 'asterisk', 'exclam.sc', 'parenright', 'tilde', 'dollar', 'colon', 'guillemotleft', 'questiondown', 'bracketright.sc', 'anoteleia', 'percent', 'quotedblrightreversed', 'backslash'}, 'uc1': {'questiondown.uc', 'guillemotright.uc', 'guillemotleft.uc', 'bullet.uc', 'emdash.uc', 'periodcentered.uc', 'exclamdown.uc'}, 'nok1': {'multiply', 'infinity', 'integral', 'ogonek', 'paragraph', 'lozenge', 'numbersign', 'OU', 'dagger', 'minus', 'numbersign.sc', 'manat', 'approxequal'}, 'dnom1': {'eight.dnom', 'nine.dnom', 'four.dnom', 'oneseventh', 'onehalf', 'onetenth', 'fivesixths', 'five.dnom', 'onethird', 'one.dnom'}, 'fig1': {'six', 'two', 'seven', 'nine', 'eight', 'one', 'zero', 'five', 'three', 'four', 'fraction'}, 'numr1': {'three.numr', 'one.numr', 'five.numr', 'six.numr', 'four.numr', 'eight.numr', 'two.numr', 'seven.numr', 'zero.numr', 'nine.numr'}, 'onum1': {'zero.onum', 'nine.onum', 'seven.onum', 'three.onum', 'six.onum', 'five.onum', 'four.onum', 'two.onum', 'one.onum', 'eight.onum'}, 'lt2': {'usuperior', 'henghook', 'jsuperior', 'Usuperior', 'eshreversedloop', 'tsuperior', 'liraTurkish', 'Y.sc', 'Ysuperior', 'sinferior', 'Oopen', 'S.sc', 'yturned', 'eopen', 'ghook', 'idotless', 'Yinferior', 'y', 'jcaron', 'tinferior', 'J.base', 'iota_latin', 'z', 'Fstroke', 'Binferior', 'A', 'Vsuperior', 'esh', 'msuperior', 'V.sc', 'lbelt', 'ezhreversed', 'Schwa.sc', 'hinferior', 'eng', 'i', 'Zinferior', 'Aturned', 'U', 'jdotless', 'Bsuperior', 'uinferior', 'Creversed', 'Eopen', 'Y', 'b', 'S', 'AE.sc', 'Chi_latin', 'Xsuperior', 't', 'Ezhreversed', 'Dafrican', 'Bhook.sc', 'hturned', 'ezh', 'minferior', 'h', 'cinferior', 'Ssuperior', 'C.sc', 'Ezh', 'zsuperior', 'Jsuperior', 'Ezhreversed.sc', 'Tsuperior', 'bsuperior', 'germandbls', 'vturned', 'Oopen.sc', 'p', 'Hturned', 'a', 'Tinferior', 'Ereversed', 'hhook', 's', 'Eopen.sc', 'Asuperior', 'Alpha_latin', 'Ereversed.sc', 'g', 'ysuperior', 'Jinferior', 'Vinferior', 'beta_latin', 'Zsuperior', 'schwa', 'hsuperior', 'alpha_latin', 'vinferior', 'Ainferior', 'U.sc', 'gamma_latin', 'Jcrossedtail.sc', 'ustroke', 'germandbls.sc', 'Schwa', 'J.base.sc', 'B.sc', 'binferior', 'Fstroke.sc', 'Z', 'asuperior', 'j', 'vsuperior', 'aturned', 'oopen', 'T.sc', 'Chi_latin.sc', 'zinferior', 'bhook', 'Sinferior', 'ssuperior', 'Z.sc', 'ainferior', 'W.sc', 'Bhook', 'Jcrossedtail', 'Ezh.sc', 'jcrossedtail', 'hryvnia', 'Cinferior', 'B', 'xsuperior', 'Xinferior', 'Yogh', 'jinferior', 'T', 'A.sc', 'f', 'lbar', 'W', 'xinferior', 'Hturned.sc', 'isuperior', 'Csuperior', 'yinferior', 'Dafrican.sc', 'iinferior', 'Uinferior', 'AE', 'csuperior', 'chi_latin'}, 'sc_lt2': {'Schwa.sc', 'T.sc', 'Chi_latin.sc', 'Y.sc', 'Ezhreversed.sc', 'Z.sc', 'W.sc', 'Oopen.sc', 'S.sc', 'Ezh.sc', 'Eopen.sc', 'Ereversed.sc', 'AE.sc', 'A.sc', 'U.sc', 'Bhook.sc', 'Jcrossedtail.sc', 'Hturned.sc', 'germandbls.sc', 'J.base.sc', 'Dafrican.sc', 'B.sc', 'Fstroke.sc', 'C.sc', 'V.sc'}, 'sc2': {'Ef_cy.sc', 'Phi.sc', 'braceleft.sc', 'Gehookstroke_cy.sc', 'Yi_cy.sc', 'Y.sc', 'bracketleft.sc', 'Schwa_cy.sc', 'Che_cy.sc', 'exclamdown.sc', 'backslash.sc', 'Xi.sc', 'De_cy.sc', 'S.sc', 'degree.sc', 'two.sc', 'Edieresis_cy.sc', 'Omicron.sc', 'nine.sc', 'Be_cy.sc', 'Dje_cy.sc', 'bracketright.sc', 'V.sc', 'parenleft.sc', 'Schwa.sc', 'question.sc', 'Tau.sc', 'U_cy.sc', 'Dze_cy.sc', 'AE.sc', 'A_cy.sc', 'questiondown.sc', 'one.sc', 'Ustrait_cy.sc', 'KaiSymbol.sc', 'Zhe_cy.sc', 'Bhook.sc', 'Omega.sc', 'exclam.sc', 'five.sc', 'C.sc', 'Alphatonos.sc', 'section.sc', 'eight.sc', 'Psi.sc', 'ampersand.sc', 'Ia_cy.sc', 'Ezhreversed.sc', 'Oopen.sc', 'Omicrontonos.sc', 'Sigma.sc', 'Eopen.sc', 'four.sc', 'Ereversed.sc', 'parenright.sc', 'El_cy.sc', 'Cheabkhasian_cy.sc', 'three.sc', 'Dzeabkh_cy.sc', 'U.sc', 'Beta.sc', 'Jcrossedtail.sc', 'germandbls.sc', 'De_cy.loclBGR.sc', 'J.base.sc', 'B.sc', 'Fstroke.sc', 'E_cy.sc', 'Omegatonos.sc', 'T.sc', 'Alpha.sc', 'Aie_cy.sc', 'Chi_latin.sc', 'Ha_cy.sc', 'six.sc', 'Z.sc', 'Zeta.sc', 'W.sc', 'seven.sc', 'Ezh.sc', 'Etatonos.sc', 'slash.sc', 'numbersign.sc', 'Upsilontonos.sc', 'glottalstopsmall', 'A.sc', 'braceright.sc', 'Upsilon.sc', 'Chi.sc', 'zero.sc', 'Hturned.sc', 'Dafrican.sc', 'Sigmafinal.sc'}, 'cy2': {'Ef_cy.sc', 'Che_cy', 'Aie_cy.sc', 'u_cy', 'Gehookstroke_cy.sc', 'Yi_cy.sc', 'dze_cy', 'Ia_cy.sc', 'Ustrait_cy', 'ha_cy', 'Ha_cy.sc', 'Ef_cy', 'Schwa_cy.sc', 'De_cy', 'Che_cy.sc', 'Edieresis_cy', 'Dje_cy', 'Gehookstroke_cy', 'yi_cy', 'hardsign_cy', 'De_cy.sc', 'E_cy', 'iigrave_cy.loclBGR', 'U_cy', 'dje_cy', 'Cheabkhasian_cy', 'be_cy.loclSRB', 'Dzeabkh_cy', 'U_cy.sc', 'Dze_cy.sc', 'gehookstroke_cy', 'El_cy', 'El_cy.sc', 'A_cy', 'A_cy.sc', 'er_cy', 'el_cy', 'schwa_cy', 'cheabkhasian_cy', 'che_cy', 'Cheabkhasian_cy.sc', 'Edieresis_cy.sc', 'Dzeabkh_cy.sc', 'Ustrait_cy.sc', 'Ia_cy', 'a_cy', 'be_cy', 'De_cy.loclBGR', 'Be_cy', 'Ha_cy', 'Zhe_cy.sc', 've_cy.loclBGR', 'ii_cy.loclBGR', 'ge_cy.loclBGR', 'pe_cy.loclBGR', 'Aie_cy', 'dzeabkh_cy', 'Be_cy.sc', 'zhe_cy', 'De_cy.loclBGR.sc', 'Dje_cy.sc', 'Dze_cy', 'dzhe_cy', 'edieresis_cy', 'ia_cy', 'ustrait_cy', 'de_cy', 'E_cy.sc', 'Zhe_cy', 'el_cy.loclBGR', 'Schwa_cy'}, 'sc_cy2': {'Ef_cy.sc', 'Aie_cy.sc', 'Gehookstroke_cy.sc', 'Yi_cy.sc', 'Ia_cy.sc', 'Ha_cy.sc', 'Schwa_cy.sc', 'Che_cy.sc', 'De_cy.sc', 'U_cy.sc', 'Dze_cy.sc', 'El_cy.sc', 'A_cy.sc', 'Cheabkhasian_cy.sc', 'Edieresis_cy.sc', 'Dzeabkh_cy.sc', 'Ustrait_cy.sc', 'Zhe_cy.sc', 'Be_cy.sc', 'De_cy.loclBGR.sc', 'Dje_cy.sc', 'E_cy.sc'}, 'gr2': {'Omegatonos.sc', 'Phi.sc', 'Alpha.sc', 'delta', 'lowernumeral_greek', 'theta', 'Alphatonos', 'lambda', 'Tau.sc', 'rho', 'Omega', 'Zeta.sc', 'pi', 'chi', 'Xi.sc', 'upsilon', 'numeral_greek', 'KaiSymbol', 'Omicrontonos.sc', 'Zeta', 'nu', 'Sigma.sc', 'Omicron', 'Chi', 'Etatonos.sc', 'Omicrontonos', 'zeta', 'kappa', 'psi', 'Omegatonos', 'Etatonos', 'tau', 'Beta', 'Upsilontonos.sc', 'gamma', 'beta', 'Upsilontonos', 'Upsilon', 'Omicron.sc', 'KaiSymbol.sc', 'Upsilon.sc', 'xi', 'epsilon', 'Chi.sc', 'Omega.sc', 'iota', 'alpha', 'phi', 'Beta.sc', 'Psi', 'omega', 'Alpha', 'omicron', 'Xi', 'Sigmafinal.sc', 'Sigma', 'Alphatonos.sc', 'eta', 'Tau', 'kaiSymbol', 'Phi', 'Psi.sc'}, 'asc2': {'asciicircum', 'question.sc', 'braceleft.sc', 'ampersand.sc', 'Euro', 'florin', 'bar', 'bracketleft', 'circumflex', 'quotedblleft', 'currency', 'periodcentered', 'bracketleft.sc', 'section', 'ordfeminine', 'section.sc', 'clickretroflex', 'ampersand', 'apple', 'Napostrophe.sc', 'comma', 'exclamdown.sc', 'degree', 'partialdiff', 'backslash.sc', 'parenleft', 'copyright', 'Glottalstop', 'glottalstopreversed', 'newsheqel', 'creversed', 'guillemotright', 'cent', 'Saltillo', 'sterling', 'asciitilde', 'trademark', 'numbersign.sc', 'at', 'exclamdown', 'degree.sc', 'numbersign', 'braceright', 'Esh', 'bullet', 'bracketright', 'emdash', 'braceleft', 'questiondown.sc', 'horizontalbar', 'radical', 'underscore', 'glottalstopsmall', 'yen', 'braceright.sc', 'space', 'slash', 'asterisk', 'exclam.sc', 'parenright', 'dollar', 'paragraph', 'colon', 'guillemotleft', 'questiondown', 'ruble', 'rupeeIndian', 'bracketright.sc', 'anoteleia', 'percent', 'quotedblrightreversed', 'backslash'}, 'inferior2': {'zeroinferior', 'zinferior', 'fourinferior', 'ainferior', 'sinferior', 'uinferior', 'parenrightinferior', 'finferior', 'commainferior', 'parenleftinferior', 'equalinferior', 'oneinferior', 'jinferior', 'seveninferior', 'sixinferior', 'twoinferior', 'vinferior', 'tinferior', 'xinferior', 'threeinferior', 'minferior', 'eightinferior', 'cinferior', 'yinferior', 'nineinferior', 'binferior', 'iinferior', 'fiveinferior'}, 'uc2': {'questiondown.uc', 'guillemotright.uc', 'guillemotleft.uc', 'bullet.uc', 'emdash.uc', 'periodcentered.uc', 'exclamdown.uc'}, 'nok2': {'dotaccent', 'infinity', 'integral', 'multiply', 'approxequal', 'ogonek', 'hungarumlaut', 'lozenge', 'OU', 'dagger', 'manat', 'hungarumlautcmb', 'macron'}, 'dnom2': {'eight.dnom', 'nine.dnom', 'four.dnom', 'seven.dnom', 'six.dnom', 'three.dnom', 'zero.dnom', 'five.dnom', 'two.dnom', 'one.dnom'}, 'fig2': {'six', 'two', 'seven', 'nine', 'eight', 'one', 'zero', 'five', 'three', 'four', 'fraction'}, 'numr2': {'three.numr', 'one.numr', 'five.numr', 'six.numr', 'four.numr', 'onethird', 'eight.numr', 'seven.numr', 'zero.numr', 'nine.numr'}, 'onum2': {'zero.onum', 'nine.onum', 'seven.onum', 'three.onum', 'six.onum', 'five.onum', 'four.onum', 'two.onum', 'one.onum', 'eight.onum'}}



