# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Copyright (c) 2023+ TYPETR
#     Usage by MIT License
# ..............................................................................
#
#   groupBaseGlyphs.py
#

# Glyphs that are used as base for groups. Scripts only kern within the script (and "all") to the other side.
# The "all" also kern to each other, on the other side. There is no kerning allowed between the scripts.

FORCE_GROUP1 = {}
FORCE_GROUP2 = {}

PUBLIC_KERN1 = 'public.kern1.'
PUBLIC_KERN2 = 'public.kern2.'

SC = 'sc'
UC = 'uc'

LT1 = 'lt1'
LT2 = 'lt2'
LT1_SC = LT1+SC
LT2_SC = LT2+SC

CY1 = 'cy1'
CY2 = 'cy2'
CY1_SC = CY1+SC
CY2_SC = CY2+SC

GR1 = 'gr1'
GR2 = 'gr2'
GR1_SC = GR1+SC
GR2_SC = GR2+SC

ASC1 = 'asc1'
ASC2 = 'asc2'

FIG1 = 'fig1'
FIG2 = 'fig2'
FIG1_SC = FIG1+SC
FIG2_SC = FIG2+SC

SUPS1 = 'sups1'
SUPS2 = 'sups2'
SINF1 = 'sinf1'
SINF2 = 'sinf2'
DNOM1 = 'dnom1'
DNOM2 = 'dnom2'
NUMR1 = 'numr1'
NUMR2 = 'numr2'
DNOM1 = 'dnom1'
DNOM2 = 'dnom2'
ONUM1 = 'onum1'
ONUM2 = 'onum2'

GROUP_NAME_PARTS = {
    LT1:    (PUBLIC_KERN1, '_lt'), 
    LT2:    (PUBLIC_KERN2, '_lt'),
    LT1_SC: (PUBLIC_KERN1, '_lt_sc'),
    LT2_SC: (PUBLIC_KERN2, '_lt_sc'),

    CY1: (PUBLIC_KERN1, '_cy'), 
    CY2: (PUBLIC_KERN2, '_cy'),
    CY1_SC: (PUBLIC_KERN1, '_cy_sc'),
    CY2_SC: (PUBLIC_KERN2, '_cy_sc'),

    GR1: (PUBLIC_KERN1, '_gr'), 
    GR2: (PUBLIC_KERN2, '_gr'),
    GR1_SC: (PUBLIC_KERN1, '_gr_sc'),
    GR2_SC: (PUBLIC_KERN2, '_gr_sc'),

    ASC1: (PUBLIC_KERN1, '_asc'), 
    ASC2: (PUBLIC_KERN2, '_asc'),

    FIG1: (PUBLIC_KERN1, '_fig'), 
    FIG2: (PUBLIC_KERN2, '_fig'),

    SUPS1: (PUBLIC_KERN1, '_sups'), 
    SUPS2: (PUBLIC_KERN2, '_sups'),
    SINF1: (PUBLIC_KERN1, '_sinf'), 
    SINF2: (PUBLIC_KERN2, '_sinf'),
    NUMR1: (PUBLIC_KERN1, '_numr'), 
    NUMR2: (PUBLIC_KERN2, '_numr'),
    DNOM1: (PUBLIC_KERN1, '_dnom'), 
    DNOM2: (PUBLIC_KERN2, '_dnom'),
    ONUM1: (PUBLIC_KERN1, '_onum'), 
    ONUM2: (PUBLIC_KERN2, '_onum'),
}
BASE_SCRIPTS1 = (
    LT1, LT1_SC, 
    CY1, CY1_SC, 
    GR1, GR1_SC, 
    ASC1, 
    FIG1, FIG1_SC, 
    SUPS1, SINF1, NUMR1, DNOM1, ONUM1)
BASE_SCRIPTS2 = (
    LT2, LT2_SC, 
    CY2, CY2_SC, 
    GR2, GR2_SC, 
    ASC2, 
    FIG2, 
    SUPS2, SINF2, NUMR2, DNOM2, ONUM2)

# For now, this is an italic table.
# Defining all script <--> script combinations in the kerning table.
# Also this table is used to generate at least one placeholder kerning pair,
# to ensure that the [kern] lookup gets generated. Otherwise building the VF
# complains for incompatible amounts of [kern] lookups.
# In general this gets solved automatically if all kerning exists, but during 
# development not all kerning may have been filled in.

KERN_GROUPS = (
    # Latin
    (LT1, LT2),
    (LT1_SC, LT2_SC),
    (LT1, LT1_SC),

    (ASC1, ASC2),
    (ASC1, LT2),
    (ASC1, LT2_SC),
    (LT1, ASC2),
    (LT1_SC, ASC2),

    (FIG1, FIG2),
    (FIG1, LT2),
    (LT1, FIG2),
    
    (SUPS1, SUPS2),
    (SINF1, SINF2),
    (LT1, SUPS2),
    (LT1, SINF2),
    (SUPS1, LT2),
    (SINF1, LT2),
    
    (NUMR1, NUMR2),
    (LT1, NUMR2),
    (LT1, DNOM2),
    (NUMR1, LT2),
    (DNOM1, LT2),
    
    (ONUM1, ONUM2),
    (ONUM1, LT2),
    (LT1, ONUM2),

    # Cyrillic
    (CY1, CY2),
    (CY1_SC, CY2_SC),
    (CY1, CY1_SC),

    #(ASC1, ASC2),
    (ASC1, CY2),
    (ASC1, CY2_SC),
    (CY1, ASC2),
    (CY1_SC, ASC2),

    #(FIG1, FIG2),
    (FIG1, CY2),
    (CY1, FIG2),
    
    #(SUPS1, SUPS2),
    #(SINF1, SINF2),
    (CY1, SUPS2),
    (CY1, SINF2),
    (SUPS1, CY2),
    (SINF1, CY2),
    
    #(NUMR1, NUMR2),
    (CY1, NUMR2),
    (CY1, DNOM2),
    (NUMR1, CY2),
    (DNOM1, CY2),
    
    #(ONUM1, ONUM2),
    (ONUM1, CY2),
    (CY1, ONUM2),

    # Greek
    (GR1, GR2),
    (GR1_SC, GR2_SC),
    (GR1, GR1_SC),

    #(ASC1, ASC2),
    (ASC1, GR2),
    (ASC1, GR2_SC),
    (GR1, ASC2),
    (GR1_SC, ASC2),

    #(FIG1, FIG2),
    (FIG1, GR2),
    (GR1, FIG2),
    
    #(SUPS1, SUPS2),
    #(SINF1, SINF2),
    (GR1, SUPS2),
    (GR1, SINF2),
    (SUPS1, GR2),
    (SINF1, GR2),
    
    #(NUMR1, NUMR2),
    (GR1, NUMR2),
    (GR1, DNOM2),
    (NUMR1, GR2),
    (DNOM1, GR2),
    
    #(ONUM1, ONUM2),
    (ONUM1, GR2),
    (GR1, ONUM2),

)

GROUP_IGNORE = ('tnum', 'cmb', 'comb', 'mod', 'superior', 'inferior', 'component',) # Always ignore glyphs that include these patterns

# This table is generated by the autoGroups.py script for now.
GROUP_BASE_GLYPHS = {
"""
    LT1: ['A', 'B', 'C', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'AE', 'Eth', 'Thorn', 'germandbls', 'ae', 'iacute', 'idieresis', 'oacute', 'dcaron', 'napostrophe', 'bstroke', 'Bhook', 'btopbar', 'khook', 'Ohorn', 'ohorn', 'thook', 'Uhorn', 'uhorn', 'Ezh', 'icaron', 'qhooktail', 'Ysmall', 'dezh', 'tesh'], 
    LT2: ['A', 'B', 'C', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'AE', 'Eth', 'Thorn', 'germandbls', 'ae', 'iacute', 'idieresis', 'oacute', 'dcaron', 'napostrophe', 'bstroke', 'Bhook', 'btopbar', 'khook', 'Ohorn', 'ohorn', 'thook', 'Uhorn', 'uhorn', 'Ezh', 'icaron', 'qhooktail', 'Ysmall', 'dezh', 'tesh'], 
    SC1: ['A.sc', 'B.sc', 'C.sc', 'E.sc', 'F.sc', 'G.sc', 'H.sc', 'J.sc', 'K.sc', 'L.sc', 'O.sc', 'P.sc', 'R.sc', 'S.sc', 'T.sc', 'U.sc', 'V.sc', 'W.sc', 'X.sc', 'Y.sc', 'Z.sc'], 
    SC2: ['A.sc', 'B.sc', 'C.sc', 'E.sc', 'F.sc', 'G.sc', 'H.sc', 'J.sc', 'K.sc', 'L.sc', 'O.sc', 'P.sc', 'R.sc', 'S.sc', 'T.sc', 'U.sc', 'V.sc', 'W.sc', 'X.sc', 'Y.sc', 'Z.sc'], 
    CY1: ['E-cy', 'Dze-cy', 'I-cy', 'Je-cy', 'Tshe-cy', 'A-cy', 'Be-cy', 'Ve-cy', 'Ge-cy', 'De-cy', 'Ie-cy', 'Zhe-cy', 'Ze-cy', 'El-cy', 'O-cy', 'Er-cy', 'Te-cy', 'U-cy', 'Ef-cy', 'Ha-cy', 'Che-cy', 'Hardsign-cy', 'Ia-cy', 'be-cy', 've-cy', 'ge-cy', 'de-cy', 'ie-cy', 'zhe-cy', 'ze-cy', 'el-cy', 'em-cy', 'o-cy', 'pe-cy', 'es-cy', 'te-cy', 'u-cy', 'ha-cy', 'tse-cy', 'che-cy', 'ereversed-cy', 'iu-cy', 'ia-cy', 'dje-cy', 'dze-cy', 'i-cy', 'je-cy', 'lje-cy', 'ushort-cy', 'omega-cy', 'Yat-cy', 'yuslittle-cy', 'Yusbig-cy', 'yusbig-cy', 'yusbigiotified-cy', 'Ksi-cy', 'Psi-cy', 'psi-cy', 'Izhitsa-cy', 'izhitsa-cy', 'izhitsadblgrave-cy', 'Uk-cy', 'uk-cy', 'uni047F', 'Koppa-cy', 'koppa-cy', 'Ghestroke-cy', 'ghestroke-cy', 'Kadescender-cy', 'Pemiddlehook-cy', 'pemiddlehook-cy', 'Haabkhasian-cy', 'haabkhasian-cy', 'Ustrait-cy', 'ustrait-cy', 'Ustraitstroke-cy', 'ustraitstroke-cy', 'tetse-cy', 'Shha-cy', 'Cheabkhasian-cy', 'cheabkhasian-cy', 'Kahook-cy', 'kahook-cy', 'Eltail-cy', 'eltail-cy', 'Aie-cy', 'Schwa-cy', 'schwa-cy', 'Dzeabkhasian-cy', 'dzeabkhasian-cy', 'Edieresis-cy', 'Hastroke-cy', 'hastroke-cy'], 
    CY2: ['E-cy', 'Dze-cy', 'I-cy', 'Je-cy', 'Tshe-cy', 'A-cy', 'Be-cy', 'Ve-cy', 'Ge-cy', 'De-cy', 'Ie-cy', 'Zhe-cy', 'Ze-cy', 'El-cy', 'O-cy', 'Er-cy', 'Te-cy', 'U-cy', 'Ef-cy', 'Ha-cy', 'Che-cy', 'Hardsign-cy', 'Ia-cy', 'be-cy', 've-cy', 'ge-cy', 'de-cy', 'ie-cy', 'zhe-cy', 'ze-cy', 'el-cy', 'em-cy', 'o-cy', 'pe-cy', 'es-cy', 'te-cy', 'u-cy', 'ha-cy', 'tse-cy', 'che-cy', 'ereversed-cy', 'iu-cy', 'ia-cy', 'dje-cy', 'dze-cy', 'i-cy', 'je-cy', 'lje-cy', 'ushort-cy', 'omega-cy', 'Yat-cy', 'yuslittle-cy', 'Yusbig-cy', 'yusbig-cy', 'yusbigiotified-cy', 'Ksi-cy', 'Psi-cy', 'psi-cy', 'Izhitsa-cy', 'izhitsa-cy', 'izhitsadblgrave-cy', 'Uk-cy', 'uk-cy', 'uni047F', 'Koppa-cy', 'koppa-cy', 'Ghestroke-cy', 'ghestroke-cy', 'Kadescender-cy', 'Pemiddlehook-cy', 'pemiddlehook-cy', 'Haabkhasian-cy', 'haabkhasian-cy', 'Ustrait-cy', 'ustrait-cy', 'Ustraitstroke-cy', 'ustraitstroke-cy', 'tetse-cy', 'Shha-cy', 'Cheabkhasian-cy', 'cheabkhasian-cy', 'Kahook-cy', 'kahook-cy', 'Eltail-cy', 'eltail-cy', 'Aie-cy', 'Schwa-cy', 'schwa-cy', 'Dzeabkhasian-cy', 'dzeabkhasian-cy', 'Edieresis-cy', 'Hastroke-cy', 'hastroke-cy'], 
    GR1: ['Alpha', 'question', 'Heta', 'heta', 'archaicsampi', 'numeral-greek', 'lowernumeral-greek', 'sigmaLunateReversedSymbol', 'Yot', 'Beta', 'Epsilon', 'Zeta', 'Theta', 'Kappa', 'Mu', 'Xi', 'Omicron', 'Rho', 'Tau', 'Upsilon', 'Phi', 'Chi', 'Psi', 'alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'lambda', 'mu', 'nu', 'xi', 'pi', 'rho', 'sigmafinal', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega', 'iotadieresis', 'upsilondieresis', 'betaSymbol', 'thetaSymbol', 'piSymbol', 'kaiSymbol', 'KoppaArchaic', 'Stigma', 'stigma', 'Digamma', 'digamma', 'Koppa', 'koppa', 'Sampi', 'sampi', 'shei-coptic', 'fei-coptic', 'Khei-coptic', 'khei-coptic', 'Hori-coptic', 'hori-coptic', 'Gangia-coptic', 'gangia-coptic', 'Shima-coptic', 'shima-coptic', 'Dei-coptic', 'dei-coptic', 'rhoSymbol', 'sigmaLunateSymbol', 'yot', 'epsilonLunateReversedSymbol', 'Sho', 'sho', 'SigmaLunateSymbol', 'san', 'SigmaLunateReversedSymbol', 'SigmaLunateDottedSymbol', 'uni047E', 'Etadasia', 'Ohm', 'Omega-latin'], 
    GR2: ['Alpha', 'question', 'Heta', 'heta', 'archaicsampi', 'numeral-greek', 'lowernumeral-greek', 'sigmaLunateReversedSymbol', 'Yot', 'Beta', 'Epsilon', 'Zeta', 'Theta', 'Kappa', 'Mu', 'Xi', 'Omicron', 'Rho', 'Tau', 'Upsilon', 'Phi', 'Chi', 'Psi', 'alpha', 'beta', 'gamma', 'delta', 'epsilon', 'zeta', 'eta', 'theta', 'iota', 'lambda', 'mu', 'nu', 'xi', 'pi', 'rho', 'sigmafinal', 'tau', 'upsilon', 'phi', 'chi', 'psi', 'omega', 'iotadieresis', 'upsilondieresis', 'betaSymbol', 'thetaSymbol', 'piSymbol', 'kaiSymbol', 'KoppaArchaic', 'Stigma', 'stigma', 'Digamma', 'digamma', 'Koppa', 'koppa', 'Sampi', 'sampi', 'shei-coptic', 'fei-coptic', 'Khei-coptic', 'khei-coptic', 'Hori-coptic', 'hori-coptic', 'Gangia-coptic', 'gangia-coptic', 'Shima-coptic', 'shima-coptic', 'Dei-coptic', 'dei-coptic', 'rhoSymbol', 'sigmaLunateSymbol', 'yot', 'epsilonLunateReversedSymbol', 'Sho', 'sho', 'SigmaLunateSymbol', 'san', 'SigmaLunateReversedSymbol', 'SigmaLunateDottedSymbol', 'uni047E', 'Etadasia', 'Ohm', 'Omega-latin'], 
    ASC1: ['dollar', 'exclam', 'quotedbl', 'percent', 'ampersand', 'parenleft', 'parenright', 'asterisk', 'hyphen', 'period', 'slash', 'colon', 'question', 'at', 'backslash', 'bar', 'exclamdown', 'guillemetleft', 'periodcentered', 'guillemetright', 'questiondown', 'dagger', 'bullet', 'trademark'], 
    ASC2: ['dollar', 'exclam', 'quotedbl', 'percent', 'ampersand', 'parenleft', 'parenright', 'asterisk', 'hyphen', 'period', 'slash', 'colon', 'question', 'at', 'backslash', 'bar', 'exclamdown', 'guillemetleft', 'periodcentered', 'guillemetright', 'questiondown', 'dagger', 'bullet', 'trademark'], 
    FIG1: ['zero', 'one', 'four', 'seven', 'nine'], 
    FIG2: ['zero', 'one', 'four', 'seven', 'nine'], 
    NUMR1: ['zero.numr', 'zero.numr'], 
    NUMR2: ['zero.numr', 'zero.numr'], 
    DNOM1: ['zero.dnom', 'zero.dnom'], 
    DNOM2: ['zero.dnom', 'zero.dnom'],
"""
}

