# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Copyright (c) 2023+ TYPETR
#     Usage by MIT License
# ..............................................................................
#
#   TYPETR_full_set.py
#

from copy import deepcopy

from assistantLib.assistantParts.glyphsets.glyphData import * #GD, TOP, TOP_, _BOTTOM, BOTTOM_ etc.
from assistantLib.assistantParts.glyphsets.TYPETR_full_set import TYPETR_GlyphSet

class TYPETR_UpgradeNeonGlyphSet(TYPETR_GlyphSet):
    """GlyphSet for the default TYPETR families

    >>> gs = TYPETR_UPgradeNeonGlyphSet()
    >>> gs
    <TYPETR_GlyphSet 2533 glyphs>
    >>> gs['A']
    <GlyphData A>
    >>> gs['B']
    <GlyphData B>
    """

    # The "c" attribtes are redundant, if the @uni or @hex atre defined, but they offer easy searching in the source by char.

    gds = GLYPH_DATA = deepcopy(TYPETR_GlyphSet.GLYPH_DATA)

    # Add missing glyphs in Neon that are not in the TYPETR_full_set
    gds['Euro.lc'] = GD(name='Euro.lc')
    gds['J.base_sc'] = GD(name='J.base_sc')
    gds['Ruble'] = GD(name='Ruble')
    gds['Sigma'] = GD(name='Sigma')
    gds['Won'] = GD(name='Won')
    gds['a.alt'] = GD(name='a.alt')
    gds['a.sinf'] = GD(name='a.sinf', base='a.sups')
    gds['a.sups'] = GD(name='a.sups')
    gds['aacute.alt'] = GD(name='aacute.alt', base='a.alt', accents=('acutecmb'))
    gds['abreve.alt'] = GD(name='abreve.alt', base='a.alt', accents=('brevecmb'))
    gds['acircumflex.alt'] = GD(name='acircumflex.alt', base='a.alt', accents=('circumflexcmb'))
    gds['adieresis.alt'] = GD(name='adieresis.alt', base='a.alt', accents=('dieresiscmb'))
    gds['ae.alt'] = GD(name='ae.alt')
    gds['agrave.alt'] = GD(name='agrave.alt', base='a.alt', accents=('gravecmb'))
    gds['amacron.alt'] = GD(name='amacron.alt', base='a.alt', accents=('macroncmb'))
    gds['aogonek.alt'] = GD(name='aogonek.alt', base='a.alt', accents=('ogonekcmb'))
    gds['apple'] = GD(name='apple')
    gds['approxequal.lc'] = GD(name='approxequal.lc', base='approxequal')
    gds['approxequal.tab'] = GD(name='approxequal.tab', base='approxequal')
    gds['aring.alt'] = GD(name='aring.alt', base='a.alt', accents=('ringcmb'))
    gds['aringacute.alt'] = GD(name='aringacute.alt', base='a.alt', accents=('ringcmb_acutecmb'))
    gds['atilde.alt'] = GD(name='atilde.alt', base='a.alt', accents=('tildecmb'))
    gds['b.sinf'] = GD(name='b.sinf', base='b.sups')
    gds['b.sups'] = GD(name='b.sups')
    gds['backslash.tab'] = GD(name='backslash.tab', base='backslash')
    gds['bitcoin.lc'] = GD(name='bitcoin.lc')
    gds['bitcoin.sc'] = GD(name='bitcoin.sc')
    gds['braceleft.sc'] = GD(name='braceleft.sc')
    gds['braceleft.tab'] = GD(name='braceleft.tab', base='braceleft')
    gds['braceleft.uc'] = GD(name='braceleft.uc')
    gds['braceright.sc'] = GD(name='braceright.sc')
    gds['braceright.tab'] = GD(name='braceright.tab', base='braceright')
    gds['braceright.uc'] = GD(name='braceright.uc')
    gds['bracketleft.sc'] = GD(name='bracketleft.sc')
    gds['bracketleft.tab'] = GD(name='bracketleft.tab', base='bracketleft')
    gds['bracketleft.uc'] = GD(name='bracketleft.uc')
    gds['bracketright.sc'] = GD(name='bracketright.sc')
    gds['bracketright.tab'] = GD(name='bracketright.tab', base='bracketright')
    gds['bracketright.uc'] = GD(name='bracketright.uc')
    gds['c.sinf'] = GD(name='c.sinf', base='c.sups')
    gds['c.sups'] = GD(name='c.sups')
    gds['cent.alt'] = GD(name='cent.alt')
    gds['cent.lc'] = GD(name='cent.lc')
    gds['cent.lc.alt'] = GD(name='cent.lc.alt', base='cent.lc')
    gds['cent.sc'] = GD(name='cent.sc')
    gds['cent.sc.alt'] = GD(name='cent.sc.alt')
    gds['cent.tab.alt'] = GD(name='cent.tab.alt', base='cent.alt', accents=('cent.lc'))
    gds['cent'] = GD(name='cent')    
    gds['colon.tab'] = GD(name='colon.tab', base='colon')
    gds['commaaccent'] = GD(name='commaaccent', base='commaaccentcmb')
    gds['commaaccentabove'] = GD(name='commaaccentabove', base='commaaccentabovecmb')
    gds['commaaccentabovecmb'] = GD(name='commaaccentabovecmb')
    gds['commaaccentcmb'] = GD(name='commaaccentcmb')
    gds['d.sinf'] = GD(name='d.sinf', base='d.sups')
    gds['d.sups'] = GD(name='d.sups')
    gds['dagger.uc'] = GD(name='dagger.uc')
    gds['daggerdbl.uc'] = GD(name='daggerdbl.uc')
    gds['dcroat'] = GD(name='dcroat')
    gds['degree.lc'] = GD(name='degree.lc', base='degree')
    gds['degree.sc'] = GD(name='degree.sc', base='degree')
    gds['degree.tab'] = GD(name='degree.tab', base='degree')
    gds['divide.lc'] = GD(name='divide.lc', base='divide')
    gds['divide.tab'] = GD(name='divide.tab', base='divide')
    gds['dollar.alt'] = GD(name='dollar.alt')
    gds['dollar.lc'] = GD(name='dollar.lc')
    gds['dollar.lc.alt'] = GD(name='dollar.lc.alt', base='dollar.sc.alt')
    gds['dollar.sc'] = GD(name='dollar.sc')
    gds['dollar.sc.alt'] = GD(name='dollar.sc.alt')
    gds['dollar.tab.alt'] = GD(name='dollar.tab.alt', base='dollar.alt')
    gds['dollar'] = GD(name='dollar')
    gds['e.alt'] = GD(name='e.alt')
    gds['e.sinf'] = GD(name='e.sinf', base='e.sups')
    gds['e.sups'] = GD(name='e.sups')
    gds['eacute.alt'] = GD(name='eacute.alt', base='e.alt', accents=('acutecmb'))
    gds['ebreve.alt'] = GD(name='ebreve.alt', base='e.alt', accents=('brevecmb'))
    gds['ecaron.alt'] = GD(name='ecaron.alt', base='e.alt', accents=('caroncmb'))
    gds['ecircumflex.alt'] = GD(name='ecircumflex.alt', base='e.alt', accents=('circumflexcmb'))
    gds['edieresis.alt'] = GD(name='edieresis.alt', base='e.alt', accents=('dieresiscmb'))
    gds['edotaccent.alt'] = GD(name='edotaccent.alt', base='e.alt', accents=('dotaccentcmb'))
    gds['egrave.alt'] = GD(name='egrave.alt', base='e.alt', accents=('gravecmb'))
    gds['egrave.sinf'] = GD(name='egrave.sinf', base='egrave.sups')
    gds['egrave.sups'] = GD(name='egrave.sups', base='e.sups')
    gds['eight.lc'] = GD(name='eight.lc')
    gds['eight.tab_lc'] = GD(name='eight.tab_lc', base='eight.lc')
    gds['eight.tab_sc'] = GD(name='eight.tab_sc', base='eight.sc')
    gds['emacron.alt'] = GD(name='emacron.alt', base='e.alt', accents=('macroncmb'))
    gds['endash.tab'] = GD(name='endash.tab', base='endash')
    gds['Eng.sc'] = GD(name='Eng.sc', base='N.sc')
    gds['Eng'] = GD(name='Eng', base='N')
    gds['eogonek.alt'] = GD(name='eogonek.alt', base='e.alt', accents=('ogonekcmb'))
    gds['equal.lc'] = GD(name='equal.lc', base='equal')
    gds['equal.tab'] = GD(name='equal.tab', base='equal')
    gds['Eth.sc'] = GD(name='Eth.sc')
    gds['Eth'] = GD(name='Eth')
    gds['Euro'] = GD(name='Euro')
    gds['exclam.sc'] = GD(name='exclam.sc')
    gds['exclamdown.sc'] = GD(name='exclamdown.sc')
    gds['f.salt_noconnect'] = GD(name='f.salt_noconnect')
    gds['f.sinf'] = GD(name='f.sinf', base='f.sups')
    gds['f.sups'] = GD(name='f.sups')
    gds['fi'] = GD(name='fi', base='f', accents=('idotless',))
    gds['five.lc'] = GD(name='five.lc')
    gds['five.tab_lc'] = GD(name='five.tab_lc', base='five.lc')
    gds['five.tab_sc'] = GD(name='five.tab_sc', base='five.sc')
    gds['fl'] = GD(name='fl')
    gds['florin.lc'] = GD(name='florin.lc')
    gds['florin.sc'] = GD(name='florin.sc')
    gds['florin.tab'] = GD(name='florin.tab', base='florin')
    gds['four.lc'] = GD(name='four.lc')
    gds['four.tab_lc'] = GD(name='four.tab_lc', base='four.lc')
    gds['four.tab_sc'] = GD(name='four.tab_sc', base='four.sc')
    gds['g.salt'] = GD(name='g.salt')
    gds['g.sinf'] = GD(name='g.sinf', base='g.sups')
    gds['g.sups'] = GD(name='g.sups')
    gds['gbreve.salt'] = GD(name='gbreve.salt', base='g.salt', accents=('brevecmb',))
    gds['gcaron.salt'] = GD(name='gcaron.salt', base='g.salt', accents=('caroncmb',))
    gds['gcircumflex.salt'] = GD(name='gcircumflex.salt', base='g.salt', accents=('circumflexcmb'))
    gds['gcommaaccent.salt'] = GD(name='gcommaaccent.salt', base='g.salt', accents=('brevecmb'))
    gds['gdotaccent.salt'] = GD(name='gdotaccent.salt', base='g.salt', accents=('brevecmb'))
    gds['germandbls.sc'] = GD(name='germandbls.sc', base='S.sc', accents=('S.sc',))
    gds['greater.lc'] = GD(name='greater.lc', base='greater')
    gds['greater.tab'] = GD(name='greater.tab', base='greater')
    gds['greaterequal.lc'] = GD(name='greaterequal.lc', base='greaterequal')
    gds['greaterequal.tab'] = GD(name='greaterequal.tab', base='greaterequal')
    gds['h.sinf'] = GD(name='h.sinf', base='h.sups')
    gds['h.sups'] = GD(name='h.sups')
    gds['Hbar.sc'] = GD(name='Hbar.sc')
    gds['Hbar'] = GD(name='Hbar')
    gds['hbar'] = GD(name='hbar')
    gds['horizontalbar'] = GD(name='horizontalbar')
    gds['i.sinf'] = GD(name='i.sinf', base='i.sups')
    gds['i.sups'] = GD(name='i.sups')
    gds['idotaccent'] = GD(name='idotaccent', base='idotless', accents=('dotaccentcmb',))
    gds['j.sinf'] = GD(name='j.sinf', base='j.sups')
    gds['j.sups'] = GD(name='j.sups')
    gds['Jcircumflex.base'] = GD(name='Jcircumflex.base', base='J.base', accents=('circumflexcmb',))
    gds['Jcircumflex.base_sc'] = GD(name='Jcircumflex.base_sc', base='J.base_sc', accents=('circumflexcmb',))
    gds['k.sinf'] = GD(name='k.sinf', base='k.sups')
    gds['k.sups'] = GD(name='k.sups')
    gds['l.sinf'] = GD(name='l.sinf', base='l.sups')
    gds['l.sups'] = GD(name='l.sups')
    gds['less.lc'] = GD(name='less.lc', base='less')
    gds['less.tab'] = GD(name='less.tab', base='less')
    gds['lessequal.lc'] = GD(name='lessequal.lc', base='lessequal')
    gds['lessequal.tab'] = GD(name='lessequal.tab', base='lessequal')
    gds['logicalnot.lc'] = GD(name='logicalnot.lc', base='logicalnot')
    gds['Lslash.sc'] = GD(name='Lslash.sc')
    gds['Lslash'] = GD(name='Lslash')
    gds['lslash'] = GD(name='lslash')
    gds['m.sinf'] = GD(name='m.sinf', base='m.sups')
    gds['m.sups'] = GD(name='m.sups')
    gds['minus.lc'] = GD(name='minus.lc', base='minus')
    gds['minus.tab'] = GD(name='minus.tab', base='minus')
    gds['minute.lc'] = GD(name='minute.lc')
    gds['minute.tab'] = GD(name='minute.tab', base='minute')
    gds['multiply.lc'] = GD(name='multiply.lc', base='multiply')
    gds['multiply.tab'] = GD(name='multiply.tab', base='multiply')
    gds['n.sinf'] = GD(name='n.sinf', base='n.sups')
    gds['n.sups'] = GD(name='n.sups')
    gds['nbspace'] = GD(name='nbspace')
    gds['nine.lc'] = GD(name='nine.lc')
    gds['nine.salt'] = GD(name='nine.salt')
    gds['nine.tab_lc'] = GD(name='nine.tab_lc', base='nine.lc')
    gds['nine.tab_sc'] = GD(name='nine.tab_sc', base='nine.sc')
    gds['notequal.lc'] = GD(name='notequal.lc', base='notequal')
    gds['notequal.tab'] = GD(name='notequal.tab')
    gds['notequal'] = GD(name='notequal')
    gds['numbersign.lc'] = GD(name='numbersign.lc', base='numbersign')
    gds['numbersign.sc'] = GD(name='numbersign.sc')
    gds['numbersign.tab'] = GD(name='numbersign.tab', base='numbersign')
    gds['o.sinf'] = GD(name='o.sinf', base='o.sups')
    gds['o.sups'] = GD(name='o.sups')
    gds['oe.alt'] = GD(name='oe.alt')
    gds['oe'] = GD(name='oe')
    gds['one.lc'] = GD(name='one.lc')
    gds['one.tab_lc'] = GD(name='one.tab_lc', base='one.lc')
    gds['one.tab_sc'] = GD(name='one.tab_sc', base='one.sc')
    gds['ordfeminine.lc'] = GD(name='ordfeminine.lc', base='ordfeminine')
    gds['ordmasculine.lc'] = GD(name='ordmasculine.lc', base='ordmasculine')
    gds['p.sinf'] = GD(name='p.sinf', base='p.sups')
    gds['p.sups'] = GD(name='p.sups')
    gds['paragraph.lc'] = GD(name='paragraph.lc', base='paragraph')
    gds['parenleft.sc'] = GD(name='parenleft.sc')
    gds['parenleft.tab'] = GD(name='parenleft.tab', base='parenleft')
    gds['parenleft.uc'] = GD(name='parenleft.uc')
    gds['parenright.sc'] = GD(name='parenright.sc')
    gds['parenright.tab'] = GD(name='parenright.tab', base='parenright')
    gds['parenright.uc'] = GD(name='parenright.uc')
    gds['percent.lc'] = GD(name='percent.lc')
    gds['percent.tab'] = GD(name='percent.tab')
    gds['periodcmb'] = GD(name='periodcmb')
    gds['perthousand.lc'] = GD(name='perthousand.lc')
    gds['perthousand.tab'] = GD(name='perthousand.tab')
    gds['plus.lc'] = GD(name='plus.lc', base='plus')
    gds['plus.tab'] = GD(name='plus.tab', base='plus')
    gds['plusminus.lc'] = GD(name='plusminus.lc', base='plusminus')
    gds['plusminus.tab'] = GD(name='plusminus.tab', base='plusminus')
    gds['Q.sc'] = GD(name='Q.sc')
    gds['Q'] = GD(name='Q')
    gds['q.sinf'] = GD(name='q.sinf', base='q.sups')
    gds['q.sups'] = GD(name='q.sups')
    gds['question.sc'] = GD(name='question.sc')
    gds['questiondown.sc'] = GD(name='questiondown.sc')
    gds['quoteright'] = GD(name='quoteright')
    gds['r.sinf'] = GD(name='r.sinf', base='r.sups')
    gds['r.sups'] = GD(name='r.sups')
    gds['ringcmb_acutecmb'] = GD(name='ringcmb_acutecmb')
    gds['s.sinf'] = GD(name='s.sinf', base='s.sups')
    gds['s.sups'] = GD(name='s.sups')
    gds['schwa.alt'] = GD(name='schwa.alt')
    gds['second.lc'] = GD(name='second.lc')
    gds['second.tab'] = GD(name='second.tab', base='second')
    gds['second'] = GD(name='second', base='quotesingle', accents=('quotesingle',))
    gds['section.lc'] = GD(name='section.lc', base='section')
    gds['semicolon.tab'] = GD(name='semicolon.tab', base='semicolon')
    gds['seven.lc'] = GD(name='seven.lc')
    gds['seven.tab_lc'] = GD(name='seven.tab_lc', base='seven')
    gds['seven.tab_sc'] = GD(name='seven.tab_sc', base='seven.sc')
    gds['sfthyphen'] = GD(name='sfthyphen')
    gds['six.lc'] = GD(name='six.lc')
    gds['six.salt'] = GD(name='six.salt')
    gds['six.tab_lc'] = GD(name='six.tab_lc', base='six')
    gds['six.tab_sc'] = GD(name='six.tab_sc', base='six.sc')
    gds['slash.tab'] = GD(name='slash.tab', base='slash')
    gds['space.em'] = GD(name='space.em')
    gds['space.en'] = GD(name='space.en')
    gds['space.frac'] = GD(name='space.frac')
    gds['space.tab'] = GD(name='space.tab')
    gds['space.tab_em'] = GD(name='space.tab_em')
    gds['space.tab_en'] = GD(name='space.tab_en')
    gds['space.tab_thin'] = GD(name='space.tab_thin')
    gds['space.thin'] = GD(name='space.thin')
    gds['sterling.lc'] = GD(name='sterling.lc')
    gds['t.sinf'] = GD(name='t.sinf', base='t.sups')
    gds['t.sups'] = GD(name='t.sups')
    gds['Tbar.sc'] = GD(name='Tbar.sc')
    gds['Tbar'] = GD(name='Tbar')
    gds['three.lc'] = GD(name='three.lc')
    gds['three.tab_lc'] = GD(name='three.tab_lc', base='three.lc')
    gds['three.tab_sc'] = GD(name='three.tab_sc', base='three.sc')
    gds['two.lc'] = GD(name='two.lc')
    gds['two.tab_lc'] = GD(name='two.tab_lc', base='two.lc')
    gds['two.tab_sc'] = GD(name='two.tab_sc', base='two.sc')
    gds['u.sinf'] = GD(name='u.sinf', base='u.sups')
    gds['u.sups'] = GD(name='u.sups')
    gds['uni2117'] = GD(name='uni2117', base='copyrightsound')
    gds['v.sinf'] = GD(name='v.sinf', base='v.sups')
    gds['v.sups'] = GD(name='v.sups')
    gds['w.sinf'] = GD(name='w.sinf', base='w.sups')
    gds['w.sups'] = GD(name='w.sups')
    gds['x.sinf'] = GD(name='x.sinf', base='x.sups')
    gds['x.sups'] = GD(name='x.sups')
    gds['y.sinf'] = GD(name='y.sinf', base='y.sups')
    gds['y.sups'] = GD(name='y.sups')
    gds['yen.lc'] = GD(name='yen.lc')
    gds['yen'] = GD(name='yen')
    gds['z.sinf'] = GD(name='z.sinf', base='z.sups')
    gds['z.sups'] = GD(name='z.sups')
    gds['zero.lc'] = GD(name='zero.lc')
    gds['zero.lc_salt_slash'] = GD(name='zero.lc_salt_slash', base='zero.lc')
    gds['zero.salt_slash'] = GD(name='zero.salt_slash', base='zero')
    gds['zero.sc_salt_slash'] = GD(name='zero.sc_salt_slash')
    gds['zero.tab_lc'] = GD(name='zero.tab_lc', base='zero.lc')
    gds['zero.tab_lc_salt_slash'] = GD(name='zero.tab_lc_salt_slash', base='zero.sc')
    gds['zero.tab_salt_slash'] = GD(name='zero.tab_salt_slash')
    gds['zero.tab_sc'] = GD(name='zero.tab_sc', base='zero.sc')
