# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#     Copyright (c) 2014+ Type Network
#
#     T N  B I T S
#     No distribution without permission.
#
# -----------------------------------------------------------------------------
#
####### FB Latin Extended
glyphlist = ('exclam', 'quotedbl', 'numbersign', 'dollar', 'percent', 'ampersand', 'quotesingle', 'parenleft', 
             'parenright', 'asterisk', 'plus', 'comma', 'period', 'slash', 'zero', 'one', 'two', 'three', 'four', 
             'five', 'six', 'seven', 'eight', 'nine', 'colon', 'semicolon', 'less', 'equal', 'greater', 'question', 
             'at', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 
             'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'bracketleft', 'backslash', 'bracketright', 'asciicircum', 
             'underscore', 'grave', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 
             'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'braceleft', 'bar', 'braceright', 'asciitilde', 
             'space', 'exclamdown', 'cent', 'sterling', 'currency', 'yen', 'brokenbar', 'section', 'dieresis', 
             'copyright', 'ordfeminine', 'guillemotleft', 'logicalnot', 'hyphen', 'registered', 'degree', 'plusminus', 
             'two.sups', 'three.sups', 'acute', 'mu1', 'paragraph', 'cedilla', 'one.sups', 'ordmasculine', 
             'guillemotright', 'onequarter', 'onehalf', 'threequarters', 'questiondown', 'Agrave', 'Aacute', 
             'Acircumflex', 'Atilde', 'Adieresis', 'Aring', 'AE', 'Ccedilla', 'Egrave', 'Eacute', 'Ecircumflex', 
             'Edieresis', 'Igrave', 'Iacute', 'Icircumflex', 'Idieresis', 'Eth', 'Ntilde', 'Ograve', 'Oacute', 
             'Ocircumflex', 'Otilde', 'Odieresis', 'multiply', 'Oslash', 'Ugrave', 'Uacute', 'Ucircumflex', 
             'Udieresis', 'Yacute', 'Thorn', 'germandbls', 'agrave', 'aacute', 'acircumflex', 'atilde', 'adieresis', 
             'aring', 'ae', 'ccedilla', 'egrave', 'eacute', 'ecircumflex', 'edieresis', 'igrave', 'iacute', 'icircumflex', 
             'idieresis', 'eth', 'ntilde', 'ograve', 'oacute', 'ocircumflex', 'otilde', 'odieresis', 'divide', 'oslash', 
             'ugrave', 'uacute', 'ucircumflex', 'udieresis', 'yacute', 'thorn', 'ydieresis', 'Amacron', 'amacron', 
             'Abreve', 'abreve', 'Aogonek', 'aogonek', 'Cacute', 'cacute', 'Ccircumflex', 'ccircumflex', 'Cdotaccent', 
             'cdotaccent', 'Ccaron', 'ccaron', 'Dcaron', 'dcaron', 'Dcroat', 'dcroat', 'Emacron', 'emacron', 'Ebreve', 
             'ebreve', 'Edotaccent', 'edotaccent', 'Eogonek', 'eogonek', 'Ecaron', 'ecaron', 'Gcircumflex', 'gcircumflex', 
             'Gbreve', 'gbreve', 'Gdotaccent', 'gdotaccent', 'Gcommaaccent', 'gcommaaccent', 'Hcircumflex', 'hcircumflex', 
             'Hbar', 'hbar', 'Itilde', 'itilde', 'Imacron', 'imacron', 'Ibreve', 'ibreve', 'Iogonek', 'iogonek', 'Idotaccent', 
             'dotlessi', 'IJ', 'ij', 'Jcircumflex', 'jcircumflex', 'Kcommaaccent', 'kcommaaccent', 'kgreenlandic', 'Lacute', 
             'lacute', 'Lcommaaccent', 'lcommaaccent', 'Lcaron', 'lcaron', 'Ldot', 'ldot', 'Lslash', 'lslash', 'Nacute', 
             'nacute', 'Ncommaaccent', 'ncommaaccent', 'Ncaron', 'ncaron', 'Eng', 'eng', 'Omacron', 'omacron', 'Obreve', 
             'obreve', 'Ohungarumlaut', 'ohungarumlaut', 'OE', 'oe', 'Racute', 'racute', 'Rcommaaccent', 'rcommaaccent', 
             'Rcaron', 'rcaron', 'Sacute', 'sacute', 'Scircumflex', 'scircumflex', 'Scedilla', 'scedilla', 'Scaron', 'scaron', 
             'Tcedilla', 'tcedilla', 'Tcaron', 'tcaron', 'Tbar', 'tbar', 'Utilde', 'utilde', 'Umacron', 'umacron', 'Ubreve', 
             'ubreve', 'Uring', 'uring', 'Uhungarumlaut', 'uhungarumlaut', 'Uogonek', 'uogonek', 'Wcircumflex', 'wcircumflex', 
             'Ycircumflex', 'ycircumflex', 'Ydieresis', 'Zacute', 'zacute', 'Zdotaccent', 'zdotaccent', 'Zcaron', 'zcaron', 
             'florin', 'Scommaaccent', 'scommaaccent', 'Tcommaaccent', 'tcommaaccent', 'circumflex', 'caron', 'breve', 
             'dotaccent', 'ring', 'ogonek', 'tilde', 'hungarumlaut', 'macroncmb', 'commaaccentcmb', 'Delta', 'Omega', 'mu', 
             'pi', 'Wgrave', 'wgrave', 'Wacute', 'wacute', 'Wdieresis', 'wdieresis', 'Ygrave', 'ygrave', 'uni2002', 'uni2003', 
             'uni2009', 'endash', 'emdash', 'horizontalbar', 'quoteright', 'quotesinglbase', 'quotedblleft', 'quotedblright', 
             'quotedblbase', 'dagger', 'daggerdbl', 'bullet', 'ellipsis', 'perthousand', 'minute', 'second', 'guilsinglleft', 
             'guilsinglright', 'zero.sups', 'four.sups', 'five.sups', 'six.sups', 'seven.sups', 'eight.sups', 'nine.sups', 
             'zero.sinf', 'one.sinf', 'two.sinf', 'three.sinf', 'four.sinf', 'five.sinf', 'six.sinf', 'seven.sinf', 
             'eight.sinf', 'nine.sinf', 'Euro', 'trademark', 'Ohm', 'partialdiff', 'Delta#1', 'summation', 'minus', 
             'fraction', 'periodcentered', 'radical', 'infinity', 'integral', 'approxequal', 'notequal', 'lessequal', 
             'greaterequal', 'lozenge', 'checkmark', 'apple', 'fi', 'fl', 'l.salt_serifs', 'icircumflex.salt_topserif', 
             'i.salt_serifs', 'dotlessi.salt_topserif', 'g.salt_ss', 'adieresis.salt_ss', 'gcommaaccent.salt_ss', 
             'ibreve.salt_topserif', 'igrave.salt_serifs', 'lcommaaccent.salt_serifs', 'lacute.salt_topserif', 'a.salt_ss', 
             'lacute.salt_serifs', 'amacron.salt_ss', 'lslash.salt_serifs_round', 'dotlessi.salt_serif', 'l.salt_serif', 
             'zero.salt_slash', 'lcaron.salt_serif', 'iogonek.salt_serif', 'abreve.salt_ss', 'icircumflex.salt_serifs', 
             'icircumflex.salt_serif', 'idieresis.salt_serif', 'itilde.salt_serifs', 'ij.salt_serif', 'ij.salt_serifs', 
             'ldot.salt_serif', 'space.frac', 'iogonek.salt_serifs_round', 'l.salt_topserif', 'itilde.salt_serifs_round', 
             'acircumflex.salt_ss', 'ldot.salt_serifs_round', 'gcircumflex.salt_ss', 'lcommaaccent.salt_serifs_round', 
             'ldot.salt_serifs', 'aring.salt_ss', 'igrave.salt_serif', 'ij.salt_serifs_round', 'lcommaaccent.salt_serif', 
             'dotlessi.salt_serifs', 'ibreve.salt_serif', 'ibreve.salt_serifs', 'lslash.salt_serifs', 'lcommaaccent.salt_topserif', 
             'igrave.salt_serifs_round', 'lslash.salt_topserif', 'iacute.salt_topserif', 'lslash.salt_serif', 'igrave.salt_topserif', 
             'iogonek.salt_topserif', 'itilde.salt_topserif', 'i.salt_serifs_round', 'iogonek.salt_serifs', 'gbreve.salt_ss', 
             'aogonek.salt_ss', 'aacute.salt_ss', 'l.salt_serifs_round', 'imacron.salt_serif', 'ij.salt_topserif', 
             'imacron.salt_serifs', 'lcaron.salt_serifs_round', 'iacute.salt_serifs_round', 'iacute.salt_serif', 
             'asterisk.salt_height', 'ibreve.salt_serifs_round', 'iacute.salt_serifs', 'lacute.salt_serif', 'i.salt_serif', 
             'agrave.salt_ss', 'ldot.salt_topserif', 'lacute.salt_serifs_round', 'idieresis.salt_serifs_round', 
             'itilde.salt_serif', 'lcaron.salt_topserif', 'lcaron.salt_serifs', 'imacron.salt_serifs_round', 'atilde.salt_ss', 
             'imacron.salt_topserif', 'icircumflex.salt_serifs_round', 'dotlessi.salt_serifs_round', 'i.salt_topserif', 
             'idieresis.salt_serifs', 'idieresis.salt_topserif', 'gdotaccent.salt_ss')


