
def process(self):
    self.edit("RIGHT-SIDE ARC CLOCKWISE ARROW", "rightsidearcclockwisearrow")
    self.edit("LEFT-SIDE ARC ANTICLOCKWISE ARROW", "leftsidearcanticlockarrow")
    self.edit("TOP ARC ANTICLOCKWISE ARROW", "toparcanticlockarrow")
    self.edit("BOTTOM ARC ANTICLOCKWISE ARROW", "bottomarcanticlockarrow")
    self.edit("TOP ARC CLOCKWISE ARROW WITH MINUS", "toparcclockarrowminus")
    self.condense("GAPPED CIRCLE ARROW")
    self.edit("CLOCKWISE ARROW", "clockarrow")
    self.edit("ANTICLOCKWISE ARROW", "anticlockarrow")
    self.edit("WITH MINUS", "minus")
    self.edit("WITH PLUS", "plus")
    self.condense("SEMICIRCULAR")

    self.edit("RISING DIAGONAL CROSSING FALLING DIAGONAL", "risingdiagonalXfallingdiagonal")
    self.edit("FALLING DIAGONAL CROSSING RISING DIAGONAL", "fallingdiagonalXrisingdiagonal")

    self.edit("ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS", 'arrowrightthencurveup')
    self.edit("ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS", 'arrowrightthendown')
    self.edit("ARROW POINTING DOWNWARDS THEN CURVING LEFTWARDS", 'arrowdownthenleft')
    self.edit("ARROW POINTING DOWNWARDS THEN CURVING RIGHTWARDS", 'arrowdownthenright')

    self.edit("LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON", "leftharpoonoverrightharpoon")
    self.edit("RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON", "rightharpoonoverleftharpoon")

    self.edit("UPWARDS HARPOON", "harpoonup")
    self.edit("DOWNWARDS HARPOON", "harpoondown")
    self.edit("LEFTWARDS HARPOON", "harpoonleft")
    self.edit("RIGHTWARDS HARPOON", "harpoonright")

    self.edit("WITH BARB", "barb")
    self.edit("THREE RIGHTWARDS ARROWS", "threerightarrows")
    self.edit("RISING DIAGONAL CROSSING SOUTH EAST ARROW", "risingdiagonalXSEarrow")
    self.edit("WAVE ARROW POINTING DIRECTLY RIGHT", "wavearrowright")
    self.edit("NORTH EAST ARROW CROSSING NORTH WEST ARROW", "NEarrowXNWarrow")
    self.edit("SOUTH EAST ARROW CROSSING NORTH EAST ARROW", "SEarrowXNEarrow")
    self.edit("NORTH EAST ARROW CROSSING SOUTH EAST ARROW", "NEarrowXSEarrow")
    self.edit("NORTH WEST ARROW CROSSING NORTH EAST ARROW", "NEarrowXNEarrow")

    self.edit("RIGHTWARDS ARROW OVER LEFTWARDS ARROW", "rightarrowoverleftarrow")
    self.edit("UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW", "uparrowleftofdownarrow")
    self.edit("DOWNWARDS ARROW LEFTWARDS OF UPWARDS ARROW", "downwarrowleftofuparrow")
    self.edit("LEFTWARDS ARROW OVER RIGHTWARDS ARROW", "leftarrowoverrightarrow")
    self.edit("PAIRED ARROWS", "arrowspaired")

    self.edit("WITH DOUBLE STROKE", "dblstroke")
    self.edit("WITH DOUBLE VERTICAL STROKE", "verticalsdbltroke")
    self.edit("WITH VERTICAL STROKE", "verticalstroke")

    self.edit("WITH HORIZONTAL BAR", "horizontalbar")
    self.edit("WITH VERTICAL BAR", "verticalbar")
    self.edit("FALLING DIAGONAL CROSSING", "fallingdiagonalx")
    self.edit("ARROW-TAIL", "arrowtail")
    self.edit("FISH TAIL", 'fishtail')
    self.edit("OPEN-HEADED", "openhead")
    self.edit("TRIPLE ARROW", "triplearrow")
    self.edit("DOUBLE DASH ARROW", "dbldasharrow")
    self.edit("WHITE DOUBLE ARROW", "whitedblarrow")
    self.edit("DOUBLE", "dbl")
    self.edit("QUADRUPLE ARROW", "quadarrow")
    self.edit("WHITE ARROW", "whitearrow")
    self.edit("ON PEDESTAL", "onpedestal")
    self.edit("FROM WALL", "fromwall")
    self.edit("TO CORNER", "tocorner")
    self.edit("ARROW", "arrow")

    self.edit("LONG", "long")
    self.edit("LEFTWARDS", "left")
    self.edit("OVER RIGHTWARDS", "overright")
    self.edit("RIGHTWARDS", "right")
    self.edit("UPWARDS", "up")
    self.edit("DOWNWARDS", "down")
    self.edit("LEFT RIGHT", "leftright")
    self.edit("UP DOWN", "updown")
    self.edit("SQUIGGLE", "squiggle")
    self.edit("TRIPLE DASH", "tripledash")
    self.edit("DASHED", "dashed")
    self.edit("NORTH WEST", "NW")
    self.edit("NORTH EAST", "NE")
    self.edit("SOUTH WEST", "SW")
    self.edit("SOUTH EAST", "SE")
    self.edit("NORTH", "N")
    self.edit("WEST", "W")
    self.edit("SOUTH", "S")
    self.edit("EAST", "E")
    self.edit("WITH STROKE", 'stroke')
    self.edit("TWO HEADED", "twoheaded")
    self.edit("TWO-HEADED", "twoheaded")
    self.edit("WITH DIAGONAL STROKE", "diagonalstroke")
    self.edit("WITH HORIZONTAL STROKE", "horizontalstroke")
    self.edit("WITH CIRCLED PLUS", "circledplus")
    self.edit("WITH TAIL", "tail")
    self.edit("WAVE", 'wave')
    self.edit("TO BAR", "tobar")
    self.edit("FROM BAR", "frombar")
    self.edit("WITH BASE", "withbase")
    self.edit("WITH HOOK", "hook")
    self.edit("WITH LOOP", "loop")
    self.edit("ZIGZAG", "zigzag")
    self.edit("WITH TIP", "tip")
    self.edit("WITH CORNER", "corner")
    self.edit("WITH DOTTED STEM", "dottedstem")
    self.edit("TO BLACK DIAMOND", "blackdiamond")
    self.edit("RIGHT", "right")
    self.edit("LEFT", "left")
    self.edit("UP", "up")
    self.edit("DOWN", "down")
    self.edit("AND", "")

    self.edit("THROUGH X", "thruX")
    self.edit("WITH SMALL CIRCLE", "smallcircle")
    self.edit("THROUGH SMALL CIRCLE", "thrusmallcircle")
    self.edit("ANTICLOCKWISE CLOSED CIRCLE", "anticlockwiseclosedcircle")
    self.edit("CLOCKWISE CLOSED CIRCLE", "clockwiseclosedcircle")
    self.edit("ANTICLOCKWISE TOP SEMICIRCLE", "anticlockwisesemicircle")
    self.edit("CLOCKWISE TOP SEMICIRCLE", "clockwisesemicircle")
    self.edit("ANTICLOCKWISE OPEN CIRCLE", "anticlockwiseopencircle")
    self.edit("CLOCKWISE OPEN CIRCLE", "clockwiseopencircle")
    self.edit("ABOVE ALMOST EQUAL TO", "abovealmostequal")
    self.edit("ABOVE TILDE OPERATOR", 'tildeabove')
    self.edit("TILDE OPERATOR ABOVE", 'tildeabove')

if __name__ == "__main__":
    from assistantLib.glyphNameFormatter.exporters import printRange
    printRange("Arrows")
