# https://github.com/LettError/glyphNameFormatter/issues/43
# This data was obtained from the Sinhala PDF code chart
# It got minor changes to the sign names (not the vowel sign)

sinhalaNameEquivalentsDict = {
    'SINHALA SIGN ANUSVARAYA': 'SINHALA SIGN ANUSVARA',
    'SINHALA SIGN VISARGAYA': 'SINHALA SIGN VISARGA',
    'SINHALA LETTER AYANNA': 'SINHALA LETTER A',
    'SINHALA LETTER AAYANNA': 'SINHALA LETTER AA',
    'SINHALA LETTER AEYANNA': 'SINHALA LETTER AE',
    'SINHALA LETTER AEEYANNA': 'SINHALA LETTER AAE',
    'SINHALA LETTER IYANNA': 'SINHALA LETTER I',
    'SINHALA LETTER IIYANNA': 'SINHALA LETTER II',
    'SINHALA LETTER UYANNA': 'SINHALA LETTER U',
    'SINHALA LETTER UUYANNA': 'SINHALA LETTER UU',
    'SINHALA LETTER IRUYANNA': 'SINHALA LETTER VOCALIC R',
    'SINHALA LETTER IRUUYANNA': 'SINHALA LETTER VOCALIC RR',
    'SINHALA LETTER ILUYANNA': 'SINHALA LETTER VOCALIC L',
    'SINHALA LETTER ILUUYANNA': 'SINHALA LETTER VOCALIC LL',
    'SINHALA LETTER EYANNA': 'SINHALA LETTER E',
    'SINHALA LETTER EEYANNA': 'SINHALA LETTER EE',
    'SINHALA LETTER AIYANNA': 'SINHALA LETTER AI',
    'SINHALA LETTER OYANNA': 'SINHALA LETTER O',
    'SINHALA LETTER OOYANNA': 'SINHALA LETTER OO',
    'SINHALA LETTER AUYANNA': 'SINHALA LETTER AU',
    'SINHALA LETTER ALPAPRAANA KAYANNA': 'SINHALA LETTER KA',
    'SINHALA LETTER MAHAAPRAANA KAYANNA': 'SINHALA LETTER KHA',
    'SINHALA LETTER ALPAPRAANA GAYANNA': 'SINHALA LETTER GA',
    'SINHALA LETTER MAHAAPRAANA GAYANNA': 'SINHALA LETTER GHA',
    'SINHALA LETTER KANTAJA NAASIKYAYA': 'SINHALA LETTER NGA',
    'SINHALA LETTER SANYAKA GAYANNA': 'SINHALA LETTER NNGA',
    'SINHALA LETTER ALPAPRAANA CAYANNA': 'SINHALA LETTER CA',
    'SINHALA LETTER MAHAAPRAANA CAYANNA': 'SINHALA LETTER CHA',
    'SINHALA LETTER ALPAPRAANA JAYANNA': 'SINHALA LETTER JA',
    'SINHALA LETTER MAHAAPRAANA JAYANNA': 'SINHALA LETTER JHA',
    'SINHALA LETTER TAALUJA NAASIKYAYA': 'SINHALA LETTER NYA',
    'SINHALA LETTER TAALUJA SANYOOGA NAAKSIKYAYA': 'SINHALA LETTER JNYA',
    'SINHALA LETTER SANYAKA JAYANNA': 'SINHALA LETTER NYJA',
    'SINHALA LETTER ALPAPRAANA TTAYANNA': 'SINHALA LETTER TTA',
    'SINHALA LETTER MAHAAPRAANA TTAYANNA': 'SINHALA LETTER TTHA',
    'SINHALA LETTER ALPAPRAANA DDAYANNA': 'SINHALA LETTER DDA',
    'SINHALA LETTER MAHAAPRAANA DDAYANNA': 'SINHALA LETTER DDHA',
    'SINHALA LETTER MUURDHAJA NAYANNA': 'SINHALA LETTER NNA',
    'SINHALA LETTER SANYAKA DDAYANNA': 'SINHALA LETTER NNDDA',
    'SINHALA LETTER ALPAPRAANA TAYANNA': 'SINHALA LETTER TA',
    'SINHALA LETTER MAHAAPRAANA TAYANNA': 'SINHALA LETTER THA',
    'SINHALA LETTER ALPAPRAANA DAYANNA': 'SINHALA LETTER DA',
    'SINHALA LETTER MAHAAPRAANA DAYANNA': 'SINHALA LETTER DHA',
    'SINHALA LETTER DANTAJA NAYANNA': 'SINHALA LETTER NA',
    'SINHALA LETTER SANYAKA DAYANNA': 'SINHALA LETTER NDA',
    'SINHALA LETTER ALPAPRAANA PAYANNA': 'SINHALA LETTER PA',
    'SINHALA LETTER MAHAAPRAANA PAYANNA': 'SINHALA LETTER PHA',
    'SINHALA LETTER ALPAPRAANA BAYANNA': 'SINHALA LETTER BA',
    'SINHALA LETTER MAHAAPRAANA BAYANNA': 'SINHALA LETTER BHA',
    'SINHALA LETTER MAYANNA': 'SINHALA LETTER MA',
    'SINHALA LETTER AMBA BAYANNA': 'SINHALA LETTER MBA',
    'SINHALA LETTER YAYANNA': 'SINHALA LETTER YA',
    'SINHALA LETTER RAYANNA': 'SINHALA LETTER RA',
    'SINHALA LETTER DANTAJA LAYANNA': 'SINHALA LETTER LA',
    'SINHALA LETTER VAYANNA': 'SINHALA LETTER VA',
    'SINHALA LETTER TAALUJA SAYANNA': 'SINHALA LETTER SHA',
    'SINHALA LETTER MUURDHAJA SAYANNA': 'SINHALA LETTER SSA',
    'SINHALA LETTER DANTAJA SAYANNA': 'SINHALA LETTER SA',
    'SINHALA LETTER HAYANNA': 'SINHALA LETTER HA',
    'SINHALA LETTER MUURDHAJA LAYANNA': 'SINHALA LETTER LLA',
    'SINHALA LETTER FAYANNA': 'SINHALA LETTER FA',
    'SINHALA SIGN AL-LAKUNA': 'SINHALA SIGN VIRAMA',
    'SINHALA VOWEL SIGN AELA-PILLA': 'SINHALA VOWEL SIGN AA',
    'SINHALA VOWEL SIGN KETTI AEDA-PILLA': 'SINHALA VOWEL SIGN AE',
    'SINHALA VOWEL SIGN DIGA AEDA-PILLA': 'SINHALA VOWEL SIGN AAE',
    'SINHALA VOWEL SIGN KETTI IS-PILLA': 'SINHALA VOWEL SIGN I',
    'SINHALA VOWEL SIGN DIGA IS-PILLA': 'SINHALA VOWEL SIGN II',
    'SINHALA VOWEL SIGN KETTI PAA-PILLA': 'SINHALA VOWEL SIGN U',
    'SINHALA VOWEL SIGN DIGA PAA-PILLA': 'SINHALA VOWEL SIGN UU',
    'SINHALA VOWEL SIGN GAETTA-PILLA': 'SINHALA VOWEL SIGN VOCALIC R',
    'SINHALA VOWEL SIGN KOMBUVA': 'SINHALA VOWEL SIGN E',
    'SINHALA VOWEL SIGN DIGA KOMBUVA': 'SINHALA VOWEL SIGN EE',
    'SINHALA VOWEL SIGN KOMBU DEKA': 'SINHALA VOWEL SIGN AI',
    'SINHALA VOWEL SIGN KOMBUVA HAA AELA-PILLA': 'SINHALA VOWEL SIGN O',
    'SINHALA VOWEL SIGN KOMBUVA HAA DIGA AELA-PILLA': 'SINHALA VOWEL SIGN OO',
    'SINHALA VOWEL SIGN KOMBUVA HAA GAYANUKITTA': 'SINHALA VOWEL SIGN AU',
    'SINHALA VOWEL SIGN GAYANUKITTA': 'SINHALA VOWEL SIGN VOCALIC L',
    'SINHALA VOWEL SIGN DIGA GAETTA-PILLA': 'SINHALA VOWEL SIGN VOCALIC RR',
    'SINHALA VOWEL SIGN DIGA GAYANUKITTA': 'SINHALA VOWEL SIGN VOCALIC LL',
}


def process(self):
    if self.uniName in sinhalaNameEquivalentsDict:
        self.replace(self.uniName, sinhalaNameEquivalentsDict[self.uniName])

    self.edit("SINHALA")
    self.edit("LETTER")
    self.edit("LITH", "lith")
    self.edit("DIGIT")
    self.edit("VOWEL SIGN", "sign")
    self.edit("PUNCTUATION")
    self.processAs("Helper Indic")
    self.processAs("Helper Numbers")
    self.replace("-")
    self.lower()
    self.compress()
    self.scriptPrefix()


if __name__ == "__main__":
    from assistantLib.glyphNameFormatter.exporters import printRange
    printRange("Sinhala")
