# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#     Copyright (c) 2014+ Type Network
#
#     T N  B I T S
#     No distribution without permission.
#
# -----------------------------------------------------------------------------
#
#    groups.py
#

LEFT = 'left'
RIGHT = 'right'

# Same key compatible with accentBuilder tool.
EXTKEY = "com.typenetwork.accentbuilder"
EXTKEY_LOCK = "%s.locked" % EXTKEY

# TODO: move to tnbits.base.
from tnbits.tools.toolparts.accentbuilder.instructions import INSTRUCTIONS, BASES_COMPOSITES

# Make new versions including small caps as keys.
# Including smallcap variants.
BASES = {}

# Including smallcap variants.
BASES_SC_COMPOSITES = {}
INSTRUCTIONS_SC = {}

for glyphName, instruction in INSTRUCTIONS.items():
    items = instruction.split("+")

    # Copy plain instruction.
    INSTRUCTIONS_SC[glyphName] = instruction

    # Keep glyphName --> base glyph.
    BASES[glyphName] = base = items[0]

    if base[0].upper() == base[0] and glyphName[0].upper() == glyphName[0]:
        base_sc = base + '.sc'
        glyphName_sc = glyphName+'.sc'
        INSTRUCTIONS_SC[glyphName_sc] = base_sc + '+' + '+'.join(items[1:])
        BASES[glyphName_sc] = base_sc

for base, composites in BASES_COMPOSITES.items():
   BASES_SC_COMPOSITES[base] = composites

   if base[0].upper() == base[0]:
       base_sc = base + '.sc'
       BASES_SC_COMPOSITES[base_sc] = composites_sc = set()

       for composite in composites:
           composites_sc.add(composite + '.sc')

DEFAULTGROUPS_ROMAN = {
    'public.kern1.A': ['A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis',
        'Agrave', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde'],
    'public.kern1.A_sc': ['A.sc', 'Aacute.sc', 'Abreve.sc', 'Acircumflex.sc',
        'Adieresis.sc', 'Agrave.sc', 'Amacron.sc', 'Aogonek.sc', 'Aring.sc',
        'Aringacute.sc', 'Atilde.sc'],
    'public.kern1.B': ['B'],
    'public.kern1.B_sc': ['B.sc'],
    'public.kern1.C': ['C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex',
        'Cdotaccent'],
    'public.kern1.C_sc': ['C.sc', 'Cacute.sc', 'Ccaron.sc', 'Ccedilla.sc',
        'Ccircumflex.sc', 'Cdotaccent.sc'],
    'public.kern1.Delta': ['Delta'],
    'public.kern1.E': ['AE', 'AEacute', 'E', 'Eacute', 'Ebreve', 'Ecaron',
        'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron',
        'Eogonek', 'OE'],
    'public.kern1.E_sc': ['AE.sc', 'AEacute.sc', 'E.sc', 'Eacute.sc',
        'Ebreve.sc', 'Ecaron.sc', 'Ecircumflex.sc', 'Edieresis.sc',
        'Edotaccent.sc', 'Egrave.sc', 'Emacron.sc', 'Eogonek.sc', 'OE.sc'],
    'public.kern1.Euro_lc': ['Euro.lc'],
    'public.kern1.Euro_sc': ['Euro.sc'],
    'public.kern1.Eurog': ['Euro'],
    'public.kern1.F': ['F'],
    'public.kern1.F_sc': ['F.sc'],
    'public.kern1.G': ['G', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent',
        'Gdotaccent'],
    'public.kern1.G_sc': ['G.sc', 'Gbreve.sc', 'Gcaron.sc', 'Gcircumflex.sc',
        'Gcommaaccent.sc', 'Gdotaccent.sc'],
    'public.kern1.H': ['Eng', 'H', 'Hcircumflex', 'M', 'N', 'Nacute', 'Ncaron',
        'Ncommaaccent', 'Ntilde'],
    'public.kern1.H_sc': ['Eng.sc', 'H.sc', 'Hcircumflex.sc', 'M.sc', 'N.sc',
        'Nacute.sc', 'Ncaron.sc', 'Ncommaaccent.sc', 'Ntilde.sc'],
    'public.kern1.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
        'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'public.kern1.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
        'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
        'Iogonek.sc', 'Itilde.sc'],
    'public.kern1.J': ['J'],
    'public.kern1.J_sc': ['J.sc'],
    'public.kern1.Jcircumflex': ['Jcircumflex'],
    'public.kern1.Jcircumflex_sc': ['Jcircumflex.sc'],
    'public.kern1.K': ['K', 'Kcommaaccent', 'X'],
    'public.kern1.K_sc': ['K.sc', 'Kcommaaccent.sc', 'X.sc'],
    'public.kern1.L': ['L'],
    'public.kern1.L_sc': ['L.sc'],
    'public.kern1.Lacute': ['Lacute'],
    'public.kern1.Lacute_sc': ['Lacute.sc'],
    'public.kern1.Lcaron': ['Lcaron'],
    'public.kern1.Lcaron_sc': ['Lcaron.sc'],
    'public.kern1.Ldot': ['Ldot'],
    'public.kern1.Ldot_sc': ['Ldot.sc'],
    'public.kern1.Lslash': ['Lslash'],
    'public.kern1.Lslash_sc': ['Lslash.sc'],
    'public.kern1.O': ['D', 'Dcaron', 'Dcroat', 'Eth', 'O', 'Oacute', 'Obreve',
            'Ocircumflex', 'Odieresis', 'Ograve', 'Ohungarumlaut', 'Omacron',
            'Oslash', 'Oslashacute', 'Otilde', 'Q'],
    'public.kern1.O_sc': ['D.sc', 'Dcaron.sc', 'Dcroat.sc', 'Eth.sc', 'O.sc',
            'Oacute.sc', 'Obreve.sc', 'Ocircumflex.sc', 'Odieresis.sc',
            'Ograve.sc', 'Ohungarumlaut.sc', 'Omacron.sc', 'Oslash.sc',
            'Oslashacute.sc', 'Otilde.sc', 'Q.sc'],
    'public.kern1.Omega': ['Omega'],
    'public.kern1.P': ['P'],
    'public.kern1.P_sc': ['P.sc'],
    'public.kern1.R': ['R', 'Racute', 'Rcaron', 'Rcommaaccent'],
    'public.kern1.R_sc': ['R.sc', 'Racute.sc', 'Rcaron.sc', 'Rcommaaccent.sc'],
    'public.kern1.S': ['S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex',
            'Scommaaccent'],
    'public.kern1.S_sc': ['S.sc', 'Sacute.sc', 'Scaron.sc', 'Scedilla.sc',
            'Scircumflex.sc', 'Scommaaccent.sc'],
    'public.kern1.T': ['T', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'],
    'public.kern1.T_sc': ['T.sc', 'Tbar.sc', 'Tcaron.sc', 'Tcedilla.sc',
            'Tcommaaccent.sc'],
    'public.kern1.Thorn': ['Thorn'],
    'public.kern1.Thorn_sc': ['Thorn.sc'],
    'public.kern1.U': ['U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis',
            'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring',
            'Utilde'],
    'public.kern1.U_sc': ['U.sc', 'Uacute.sc', 'Ubreve.sc', 'Ucircumflex.sc',
            'Udieresis.sc', 'Ugrave.sc', 'Uhungarumlaut.sc', 'Umacron.sc',
            'Uogonek.sc', 'Uring.sc', 'Utilde.sc'],
    'public.kern1.V': ['V'],
    'public.kern1.V_sc': ['V.sc'],
    'public.kern1.W': ['W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'],
    'public.kern1.W_sc': ['W.sc', 'Wacute.sc', 'Wcircumflex.sc',
            'Wdieresis.sc', 'Wgrave.sc'],
    'public.kern1.Y': ['Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'],
    'public.kern1.Y_sc': ['Y.sc', 'Yacute.sc', 'Ycircumflex.sc',
            'Ydieresis.sc', 'Ygrave.sc'],
    'public.kern1.Z': ['Z', 'Zacute', 'Zcaron', 'Zdotaccent'],
    'public.kern1.Z_sc': ['Z.sc', 'Zacute.sc', 'Zcaron.sc', 'Zdotaccent.sc'],
    'public.kern1.a': ['a', 'aacute', 'abreve', 'acircumflex', 'adieresis',
            'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde'],
    'public.kern1.a_sinf': ['a.sinf'],
    'public.kern1.a_sups': ['a.sups'],
    'public.kern1.ampersand': ['ampersand'],
    'public.kern1.ampersand_sc': ['ampersand.sc'],
    'public.kern1.apple': ['apple'],
    'public.kern1.approxequal': ['approxequal'],
    'public.kern1.approxequal_lc': ['approxequal.lc'],
    'public.kern1.ascii': ['asciitilde'],
    'public.kern1.asciicircum': ['asciicircum'],
    'public.kern1.asterisk': ['asterisk'],
    'public.kern1.at': ['at'],
    'public.kern1.back': ['backslash'],
    'public.kern1.back_sc': ['backslash.sc'],
    'public.kern1.bar': ['bar', 'brokenbar'],
    'public.kern1.braceleft': ['braceleft'],
    'public.kern1.braceleft_sc': ['braceleft.sc'],
    'public.kern1.braceleft_uc': ['braceleft.uc'],
    'public.kern1.braceright': ['braceright'],
    'public.kern1.braceright_sc': ['braceright.sc'],
    'public.kern1.braceright_uc': ['braceright.uc'],
    'public.kern1.bracketleft': ['bracketleft'],
    'public.kern1.bracketleft_sc': ['bracketleft.sc'],
    'public.kern1.bracketleft_uc': ['bracketleft.uc'],
    'public.kern1.bracketright': ['bracketright'],
    'public.kern1.bracketright_sc': ['bracketright.sc'],
    'public.kern1.bracketright_uc': ['bracketright.uc'],
    'public.kern1.bullet': ['bullet'],
    'public.kern1.bullet_uc': ['bullet.uc'],
    'public.kern1.c': ['c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex',
            'cdotaccent'],
    'public.kern1.c_sinf': ['c.sups'],
    'public.kern1.cent': ['cent'],
    'public.kern1.cent_AT_weight800': ['cent_AT_weight800'],
    'public.kern1.cent_lc_AT_weight800': ['cent.lc_AT_weight800'],
    'public.kern1.cent_sc': ['cent.lc'],
    'public.kern1.cent_sc_AT_weight800': ['cent.sc_AT_weight800'],
    'public.kern1.checkmark': ['checkmark'],
    'public.kern1.colon': ['colon'],
    'public.kern1.comma': ['comma', 'quotedblbase', 'quotesinglbase'],
    'public.kern1.currency': ['currency'],
    'public.kern1.dagger': ['dagger'],
    'public.kern1.daggerdbl': ['daggerdbl'],
    'public.kern1.dcroat': ['dcroat'],
    'public.kern1.degree': ['degree'],
    'public.kern1.degree_lc': ['degree.lc'],
    'public.kern1.degree_sc': ['degree.sc'],
    'public.kern1.divide': ['divide'],
    'public.kern1.dollar': ['dollar', 'dollar_AT_weight800'],
    'public.kern1.dollar_lc': ['dollar.lc', 'dollar.lc_AT_weight800'],
    'public.kern1.dollar_sc': ['dollar.sc', 'dollar.sc_AT_weight800'],
    'public.kern1.dotaccent': ['dotaccent'],
    'public.kern1.dotlessi': ['dotlessi'],
    'public.kern1.dotlessj': ['dotlessj'],
    'public.kern1.e': ['ae', 'aeacute', 'e', 'eacute', 'ebreve', 'ecaron',
            'ecircumflex', 'edieresis', 'edotaccent', 'egrave', 'emacron',
            'eogonek', 'oe'],
    'public.kern1.e_sinf': ['e.sinf', 'egrave.sinf'],
    'public.kern1.e_sups': ['e.sups', 'egrave.sups'],
    'public.kern1.eight': ['eight'],
    'public.kern1.eight_dnom': ['eight.dnom'],
    'public.kern1.eight_lc': ['eight.lc'],
    'public.kern1.eight_numr': ['eight.numr'],
    'public.kern1.eight_sc': ['eight.sc'],
    'public.kern1.eight_sinf': ['eight.sinf'],
    'public.kern1.eight_sups': ['eight.sups'],
    'public.kern1.equal': ['equal'],
    'public.kern1.equal_lc': ['equal.lc'],
    'public.kern1.eth': ['eth'],
    'public.kern1.exclam': ['exclam'],
    'public.kern1.exclam_sc': ['exclam.sc'],
    'public.kern1.exclamdown': ['exclamdown'],
    'public.kern1.exclamdown_uc': ['exclamdown.uc'],
    'public.kern1.f': ['f'],
    'public.kern1.f_salt_nokern': ['f.salt_noconnect'],
    'public.kern1.f_sinf': ['f.sinf'],
    'public.kern1.f_sups': ['f.sups'],
    'public.kern1.five': ['five'],
    'public.kern1.five_dnom': ['five.dnom'],
    'public.kern1.five_lc': ['five.lc'],
    'public.kern1.five_numr': ['five.numr'],
    'public.kern1.five_sc': ['five.sc'],
    'public.kern1.five_sinf': ['five.sinf'],
    'public.kern1.five_sups': ['five.sups'],
    'public.kern1.florin': ['florin'],
    'public.kern1.florin_lc': ['florin.lc'],
    'public.kern1.florin_sc': ['florin.sc'],
    'public.kern1.four': ['four'],
    'public.kern1.four_dnom': ['four.dnom'],
    'public.kern1.four_lc': ['four.lc'],
    'public.kern1.four_numr': ['four.numr'],
    'public.kern1.four_sc': ['four.sc'],
    'public.kern1.four_sinf': ['four.sinf'],
    'public.kern1.four_sups': ['four.sups'],
    'public.kern1.fraction': ['fraction'],
    'public.kern1.g': ['g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent',
            'gdotaccent'],
    'public.kern1.g_salt': ['g.salt', 'gbreve.salt', 'gcaron.salt',
            'gcircumflex.salt', 'gcommaaccent.salt', 'gdotaccent.salt'],
    'public.kern1.g_sinf': ['g.sinf'],
    'public.kern1.g_sups': ['g.sups'],
    'public.kern1.germandbls': ['germandbls'],
    'public.kern1.greater': ['greater', 'greater.lc', 'greaterequal',
            'greaterequal.lc'],
    'public.kern1.guillemotleft': ['guillemotleft', 'guilsinglleft'],
    'public.kern1.guillemotleft_uc': ['guillemotleft.uc', 'guilsinglleft.uc'],
    'public.kern1.guillemotright': ['guillemotright', 'guilsinglright'],
    'public.kern1.guillemotright_uc': ['guillemotright.uc',
            'guilsinglright.uc'],
    'public.kern1.h': ['h', 'hbar', 'hcircumflex'],
    'public.kern1.horizontal': ['horizontalbar'],
    'public.kern1.hyphen': ['emdash', 'endash', 'hyphen', 'sfthyphen'],
    'public.kern1.hyphen_uc': ['emdash.uc', 'endash.uc', 'hyphen.uc'],
    'public.kern1.i': ['i', 'idotaccent'],
    'public.kern1.i_sinf': ['i.sinf'],
    'public.kern1.i_sups': ['i.sups'],
    'public.kern1.iacute': ['iacute'],
    'public.kern1.ibreve': ['ibreve'],
    'public.kern1.icircumflex': ['icircumflex'],
    'public.kern1.idieresis': ['idieresis'],
    'public.kern1.igrave': ['igrave'],
    'public.kern1.imacron': ['imacron'],
    'public.kern1.infinity': ['infinity'],
    'public.kern1.integral': ['integral'],
    'public.kern1.iogonek': ['iogonek'],
    'public.kern1.itilde': ['itilde'],
    'public.kern1.j': ['j'],
    'public.kern1.j_sinf': ['j.sinf'],
    'public.kern1.j_sups': ['j.sups'],
    'public.kern1.jcircumflex': ['jcircumflex'],
    'public.kern1.k': ['k', 'kcommaaccent', 'x'],
    'public.kern1.k_sinf': ['k.sinf', 'x.sinf'],
    'public.kern1.k_sups': ['k.sups', 'x.sups'],
    'public.kern1.l': ['d', 'l'],
    'public.kern1.l_sinf': ['l.sinf'],
    'public.kern1.l_sups': ['d.sups'],
    'public.kern1.lacute': ['lacute'],
    'public.kern1.lcaron': ['dcaron', 'lcaron'],
    'public.kern1.ldot': ['ldot'],
    'public.kern1.less': ['less', 'less.lc', 'lessequal', 'lessequal.lc'],
    'public.kern1.logicalnot': ['logicalnot'],
    'public.kern1.lozenge': ['lozenge'],
    'public.kern1.lslash': ['lslash'],
    'public.kern1.minus': ['minus'],
    'public.kern1.minus_lc': ['minus.lc'],
    'public.kern1.multiply': ['multiply'],
    'public.kern1.multiply_lc': ['multiply.lc'],
    'public.kern1.n': ['eng', 'm', 'n', 'nacute', 'ncaron', 'ncommaaccent',
            'ntilde'],
    'public.kern1.n_sinf': ['h.sinf', 'm.sinf', 'n.sinf'],
    'public.kern1.n_sups': ['h.sups', 'm.sups', 'n.sups'],
    'public.kern1.nine': ['nine'],
    'public.kern1.nine_dnom': ['nine.dnom'],
    'public.kern1.nine_lc': ['nine.lc'],
    'public.kern1.nine_numr': ['nine.numr'],
    'public.kern1.nine_salt': ['nine.salt'],
    'public.kern1.nine_sc': ['nine.sc'],
    'public.kern1.nine_sinf': ['nine.sinf'],
    'public.kern1.nine_sups': ['nine.sups'],
    'public.kern1.notequal': ['notequal'],
    'public.kern1.notequal_lc': ['notequal.lc'],
    'public.kern1.numbersign': ['numbersign'],
    'public.kern1.numbersign_sc': ['numbersign.sc'],
    'public.kern1.o': ['b', 'o', 'oacute', 'obreve', 'ocircumflex',
            'odieresis', 'ograve', 'ohungarumlaut', 'omacron', 'oslash',
            'oslashacute', 'otilde', 'p', 'thorn'],
    'public.kern1.o_sinf': ['b.sinf', 'o.sinf', 'p.sinf'],
    'public.kern1.o_sups': ['b.sups', 'o.sups', 'p.sups'],
    'public.kern1.one': ['one'],
    'public.kern1.one_dnom': ['one.dnom'],
    'public.kern1.one_lc': ['one.lc'],
    'public.kern1.one_numr': ['one.numr'],
    'public.kern1.one_sc': ['one.sc'],
    'public.kern1.one_sinf': ['one.sinf'],
    'public.kern1.one_sups': ['one.sups'],
    'public.kern1.onehalf': ['onehalf'],
    'public.kern1.onequarter': ['onequarter'],
    'public.kern1.onesuperior': ['onesuperior'],
    'public.kern1.ord': ['ordfeminine', 'ordmasculine'],
    'public.kern1.paragraph': ['paragraph'],
    'public.kern1.paragraph_lc': ['paragraph.lc'],
    'public.kern1.parenleft': ['parenleft'],
    'public.kern1.parenleft_sc': ['parenleft.sc'],
    'public.kern1.parenleft_uc': ['parenleft.uc'],
    'public.kern1.parenright': ['parenright'],
    'public.kern1.parenright_sc': ['parenright.sc'],
    'public.kern1.parenright_uc': ['parenright.uc'],
    'public.kern1.partialdiff': ['partialdiff'],
    'public.kern1.percent': ['percent', 'perthousand'],
    'public.kern1.percent_lc': ['percent.lc', 'perthousand.lc'],
    'public.kern1.period': ['ellipsis', 'period'],
    'public.kern1.periodcentered': ['periodcentered'],
    'public.kern1.periodcentered_uc': ['periodcentered.uc'],
    'public.kern1.pi': ['pi'],
    'public.kern1.plus': ['plus'],
    'public.kern1.plus_lc': ['plus.lc'],
    'public.kern1.plusminus': ['plusminus'],
    'public.kern1.plusminus_lc': ['plusminus.lc'],
    'public.kern1.product': ['product'],
    'public.kern1.q': ['q'],
    'public.kern1.q_sinf': ['q.sinf'],
    'public.kern1.q_sups': ['q.sups'],
    'public.kern1.question': ['question'],
    'public.kern1.question_sc': ['question.sc'],
    'public.kern1.questiondown': ['questiondown'],
    'public.kern1.questiondown_uc': ['questiondown.uc'],
    'public.kern1.quote': ['minute', 'quotedbl', 'quotesingle', 'second'],
    'public.kern1.quoteleft': ['quotedblleft', 'quoteleft'],
    'public.kern1.quoteright': ['quotedblright', 'quoteright'],
    'public.kern1.r': ['r', 'racute', 'rcaron', 'rcommaaccent'],
    'public.kern1.r_sinf': ['r.sinf'],
    'public.kern1.r_sups': ['r.sups'],
    'public.kern1.radical': ['radical'],
    'public.kern1.registered': ['copyright', 'copyrightsound', 'registered',
            'uni2117'],
    'public.kern1.s': ['s', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'public.kern1.s_sinf': ['s.sinf'],
    'public.kern1.s_sups': ['s.sups'],
    'public.kern1.schwa': ['schwa'],
    'public.kern1.section': ['section'],
    'public.kern1.section_lc': ['section.lc'],
    'public.kern1.section_sc': ['section.sc'],
    'public.kern1.semicolon': ['semicolon'],
    'public.kern1.seven': ['seven'],
    'public.kern1.seven_dnom': ['seven.dnom'],
    'public.kern1.seven_lc': ['seven.lc'],
    'public.kern1.seven_numr': ['seven.numr'],
    'public.kern1.seven_sc': ['seven.sc'],
    'public.kern1.seven_sinf': ['seven.sinf'],
    'public.kern1.seven_sups': ['seven.sups'],
    'public.kern1.six': ['six'],
    'public.kern1.six_dnom': ['six.dnom'],
    'public.kern1.six_lc': ['six.lc'],
    'public.kern1.six_numr': ['six.numr'],
    'public.kern1.six_salt': ['six.salt'],
    'public.kern1.six_sc': ['six.sc'],
    'public.kern1.six_sinf': ['six.sinf'],
    'public.kern1.six_sups': ['six.sups'],
    'public.kern1.slash': ['slash'],
    'public.kern1.slash_sc': ['slash.sc'],
    'public.kern1.space': ['space'],
    'public.kern1.space_em': ['space.em'],
    'public.kern1.space_en': ['space.en'],
    'public.kern1.sterling': ['sterling'],
    'public.kern1.sterling_lc': ['sterling.lc'],
    'public.kern1.sterling_sc': ['sterling.sc'],
    'public.kern1.summation': ['summation'],
    'public.kern1.t': ['t', 'tbar', 'tcedilla', 'tcommaaccent'],
    'public.kern1.t_sinf': ['t.sinf'],
    'public.kern1.t_sups': ['t.sups'],
    'public.kern1.tcaron': ['tcaron'],
    'public.kern1.three': ['three'],
    'public.kern1.three_dnom': ['three.dnom'],
    'public.kern1.three_lc': ['three.lc'],
    'public.kern1.three_numr': ['three.numr'],
    'public.kern1.three_sc': ['three.sc'],
    'public.kern1.three_sinf': ['three.sinf'],
    'public.kern1.three_sups': ['three.sups'],
    'public.kern1.threequarters': ['threequarters'],
    'public.kern1.threesuperior': ['threesuperior'],
    'public.kern1.tilde': ['tilde'],
    'public.kern1.trademark': ['trademark'],
    'public.kern1.two': ['two'],
    'public.kern1.two_dnom': ['two.dnom'],
    'public.kern1.two_lc': ['two.lc'],
    'public.kern1.two_numr': ['two.numr'],
    'public.kern1.two_sc': ['two.sc'],
    'public.kern1.two_sinf': ['two.sinf'],
    'public.kern1.two_sups': ['two.sups'],
    'public.kern1.twosuperior': ['twosuperior'],
    'public.kern1.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex',
            'udieresis', 'ugrave', 'umacron', 'uogonek', 'uring', 'utilde'],
    'public.kern1.u_sinf': ['u.sinf'],
    'public.kern1.u_sups': ['u.sups'],
    'public.kern1.uhungarumlaut': ['uhungarumlaut'],
    'public.kern1.underscore': ['underscore'],
    'public.kern1.v': ['v', 'w', 'wacute', 'wcircumflex', 'wdieresis',
            'wgrave'],
    'public.kern1.v_sinf': ['v.sinf'],
    'public.kern1.v_sups': ['v.sups'],
    'public.kern1.w_sinf': ['w.sinf'],
    'public.kern1.w_sups': ['w.sups'],
    'public.kern1.y': ['y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'],
    'public.kern1.y_sinf': ['y.sinf'],
    'public.kern1.y_sups': ['y.sups'],
    'public.kern1.yen': ['yen'],
    'public.kern1.z': ['z', 'zacute', 'zcaron', 'zdotaccent'],
    'public.kern1.z_sinf': ['z.sinf'],
    'public.kern1.z_sups': ['z.sups'],
    'public.kern1.zero': ['zero'],
    'public.kern1.zero_dnom': ['zero.dnom'],
    'public.kern1.zero_lc': ['zero.lc'],
    'public.kern1.zero_lc_salt_slash': ['zero.lc_salt_slash'],
    'public.kern1.zero_numr': ['zero.numr'],
    'public.kern1.zero_salt_slash': ['zero.salt_slash'],
    'public.kern1.zero_sc': ['zero.sc'],
    'public.kern1.zero_sc_salt_slash': ['zero.sc_salt_slash'],
    'public.kern1.zero_sinf': ['zero.sinf'],
    'public.kern1.zero_sups': ['zero.sups'],
    #------------------------------
    #    R I G H T = Left margin
    #------------------------------
    'public.kern2.A': ['A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis',
            'Agrave', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde'],
    'public.kern2.AE': ['AE', 'AEacute'],
    'public.kern2.AE_sc': ['AE.sc', 'AEacute.sc'],
    'public.kern2.A_sc': ['A.sc', 'Aacute.sc', 'Abreve.sc', 'Acircumflex.sc',
            'Adieresis.sc', 'Agrave.sc', 'Amacron.sc', 'Aogonek.sc',
            'Aring.sc', 'Aringacute.sc', 'Atilde.sc'],
    'public.kern2.Dcroat': ['Dcroat', 'Eth'],
    'public.kern2.Dcroat_sc': ['Dcroat.sc', 'Eth.sc'],
    'public.kern2.Delta': ['Delta'],
    'public.kern2.Euro': ['Euro'],
    'public.kern2.Euro_lc': ['Euro.lc'],
    'public.kern2.Euro_sc': ['Euro.sc'],
    'public.kern2.H': ['B', 'D', 'Dcaron', 'E', 'Eacute', 'Ebreve', 'Ecaron',
            'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron',
            'Eng', 'Eogonek', 'F', 'H', 'Hcircumflex', 'K', 'Kcommaaccent',
            'L', 'Lcommaaccent', 'Ldot', 'M', 'N', 'Nacute', 'Ncaron',
            'Ncommaaccent', 'Ntilde', 'P', 'R', 'Racute', 'Rcaron',
            'Rcommaaccent', 'Thorn'],
    'public.kern2.H_sc': ['B.sc', 'D.sc', 'Dcaron.sc', 'E.sc', 'Eacute.sc',
            'Ebreve.sc', 'Ecaron.sc', 'Ecircumflex.sc', 'Edieresis.sc',
            'Edotaccent.sc', 'Egrave.sc', 'Emacron.sc', 'Eng.sc', 'Eogonek.sc',
            'F.sc', 'H.sc', 'Hcircumflex.sc', 'K.sc', 'Kcommaaccent.sc',
            'L.sc', 'Lcommaaccent.sc', 'Ldot.sc', 'M.sc', 'N.sc', 'Nacute.sc',
            'Ncaron.sc', 'Ncommaaccent.sc', 'Ntilde.sc', 'P.sc', 'R.sc',
            'Racute.sc', 'Rcaron.sc', 'Rcommaaccent.sc', 'Thorn.sc'],
    'public.kern2.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'public.kern2.I_sc': ['I.sc', 'Iacute.sc'],
    'public.kern2.Ibreve_sc': ['Ibreve.sc'],
    'public.kern2.Icircumflex_sc': ['Icircumflex.sc'],
    'public.kern2.Idieresis_sc': ['Idieresis.sc'],
    'public.kern2.Idotaccent_sc': ['Idotaccent.sc'],
    'public.kern2.Igrave_sc': ['Igrave.sc'],
    'public.kern2.Imacron_sc': ['Imacron.sc'],
    'public.kern2.Iogonek_sc': ['Iogonek.sc'],
    'public.kern2.Itilde_sc': ['Itilde.sc'],
    'public.kern2.J': ['J'],
    'public.kern2.J_sc': ['J.sc'],
    'public.kern2.Jcircumflex': ['Jcircumflex'],
    'public.kern2.Jcircumflex_sc': ['Jcircumflex.sc'],
    'public.kern2.O': ['C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex',
            'Cdotaccent', 'G', 'Gbreve', 'Gcaron', 'Gcircumflex',
            'Gcommaaccent', 'Gdotaccent', 'O', 'OE', 'Oacute', 'Obreve',
            'Ocircumflex', 'Odieresis', 'Ograve', 'Ohungarumlaut', 'Omacron',
            'Oslash', 'Oslashacute', 'Otilde', 'Q'],
    'public.kern2.O_sc': ['C.sc', 'Cacute.sc', 'Ccaron.sc', 'Ccedilla.sc',
            'Ccircumflex.sc', 'Cdotaccent.sc', 'G.sc', 'Gbreve.sc',
            'Gcaron.sc', 'Gcircumflex.sc', 'Gcommaaccent.sc', 'Gdotaccent.sc',
            'O.sc', 'OE.sc', 'Oacute.sc', 'Obreve.sc', 'Ocircumflex.sc',
            'Odieresis.sc', 'Ograve.sc', 'Ohungarumlaut.sc', 'Omacron.sc',
            'Oslash.sc', 'Oslashacute.sc', 'Otilde.sc', 'Q.sc'],
    'public.kern2.Omega': ['Omega'],
    'public.kern2.S': ['S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex',
            'Scommaaccent'],
    'public.kern2.S_sc': ['S.sc', 'Sacute.sc', 'Scaron.sc', 'Scedilla.sc',
            'Scircumflex.sc', 'Scommaaccent.sc'],
    'public.kern2.T': ['T', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'],
    'public.kern2.T_sc': ['T.sc', 'Tbar.sc', 'Tcaron.sc', 'Tcedilla.sc',
            'Tcommaaccent.sc'],
    'public.kern2.U': ['U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis',
            'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring',
            'Utilde'],
    'public.kern2.U_sc': ['U.sc', 'Uacute.sc', 'Ubreve.sc', 'Ucircumflex.sc',
            'Udieresis.sc', 'Ugrave.sc', 'Uhungarumlaut.sc', 'Umacron.sc',
            'Uogonek.sc', 'Uring.sc', 'Utilde.sc'],
    'public.kern2.V': ['V'],
    'public.kern2.V_sc': ['V.sc'],
    'public.kern2.W': ['W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'],
    'public.kern2.W_sc': ['W.sc', 'Wacute.sc', 'Wcircumflex.sc',
            'Wdieresis.sc', 'Wgrave.sc'],
    'public.kern2.X': ['X'],
    'public.kern2.X_sc': ['X.sc'],
    'public.kern2.Y': ['Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'],
    'public.kern2.Y_sc': ['Y.sc', 'Yacute.sc', 'Ycircumflex.sc',
            'Ydieresis.sc', 'Ygrave.sc'],
    'public.kern2.Z': ['Z', 'Zacute', 'Zcaron', 'Zdotaccent'],
    'public.kern2.Z_sc': ['Z.sc', 'Zacute.sc', 'Zcaron.sc', 'Zdotaccent.sc'],
    'public.kern2.a': ['a', 'aacute', 'abreve', 'acircumflex', 'adieresis',
            'ae', 'aeacute', 'agrave', 'amacron', 'aogonek', 'aring',
            'aringacute', 'atilde'],
    'public.kern2.a_sinf': ['a.sinf'],
    'public.kern2.a_sups': ['a.sups'],
    'public.kern2.ampersand': ['ampersand'],
    'public.kern2.ampersand_sc': ['ampersand.sc'],
    'public.kern2.apple': ['apple'],
    'public.kern2.approxequal': ['approxequal'],
    'public.kern2.approxequal_lc': ['approxequal.lc'],
    'public.kern2.ascii': ['asciitilde'],
    'public.kern2.asciicircum': ['asciicircum'],
    'public.kern2.asterisk': ['asterisk'],
    'public.kern2.at': ['at'],
    'public.kern2.back': ['backslash'],
    'public.kern2.back_sc': ['backslash.sc'],
    'public.kern2.bar': ['bar', 'brokenbar'],
    'public.kern2.braceleft': ['braceleft'],
    'public.kern2.braceleft_sc': ['braceleft.sc'],
    'public.kern2.braceleft_uc': ['braceleft.uc'],
    'public.kern2.braceright': ['braceright'],
    'public.kern2.braceright_sc': ['braceright.sc'],
    'public.kern2.braceright_uc': ['braceright.uc'],
    'public.kern2.bracketleft': ['bracketleft'],
    'public.kern2.bracketleft_sc': ['bracketleft.sc'],
    'public.kern2.bracketleft_uc': ['bracketleft.uc'],
    'public.kern2.bracketright': ['bracketright'],
    'public.kern2.bracketright_sc': ['bracketright.sc'],
    'public.kern2.bracketright_uc': ['bracketright.uc'],
    'public.kern2.bullet': ['bullet'],
    'public.kern2.bullet_uc': ['bullet.uc'],
    'public.kern2.cent': ['cent'],
    'public.kern2.cent_AT_weight800': ['cent_AT_weight800'],
    'public.kern2.cent_lc': ['cent.lc'],
    'public.kern2.cent_lc_AT_weight800': ['cent.lc_AT_weight800'],
    'public.kern2.cent_sc': ['cent.sc'],
    'public.kern2.cent_sc_AT_weight800': ['cent.sc_AT_weight800'],
    'public.kern2.checkmark': ['checkmark'],
    'public.kern2.circumflex': ['circumflex'],
    'public.kern2.comma': ['comma', 'quotedblbase', 'quotesinglbase'],
    'public.kern2.currency': ['currency'],
    'public.kern2.dagger': ['dagger'],
    'public.kern2.daggerdbl': ['daggerdbl'],
    'public.kern2.degree': ['degree'],
    'public.kern2.degree_lc': ['degree.lc'],
    'public.kern2.degree_sc': ['degree.sc'],
    'public.kern2.divide': ['divide'],
    'public.kern2.dollar': ['dollar', 'dollar_AT_weight800'],
    'public.kern2.dollar_lc': ['dollar.lc', 'dollar.lc_AT_weight800'],
    'public.kern2.dollar_sc': ['dollar.sc', 'dollar.sc_AT_weight800'],
    'public.kern2.dotaccent': ['dotaccent'],
    'public.kern2.dotlessi': ['dotlessi'],
    'public.kern2.dotlessj': ['dotlessj'],
    'public.kern2.eight_dnom': ['eight.dnom'],
    'public.kern2.eight_lc': ['eight.lc'],
    'public.kern2.eight_numr': ['eight.numr'],
    'public.kern2.eight_sc': ['eight.sc'],
    'public.kern2.eight_sinf': ['eight.sinf'],
    'public.kern2.eight_sups': ['eight.sups'],
    'public.kern2.equal': ['equal'],
    'public.kern2.equal_lc': ['equal.lc'],
    'public.kern2.exclam': ['exclam'],
    'public.kern2.exclam_sc': ['exclam.sc'],
    'public.kern2.exclamdown': ['exclamdown'],
    'public.kern2.exclamdown_uc': ['exclamdown.uc'],
    'public.kern2.f': ['f', 'f.salt_connect', 'f.salt_noconnect'],
    'public.kern2.f_sinf': ['f.sinf'],
    'public.kern2.f_sups': ['f.sups'],
    'public.kern2.five': ['five'],
    'public.kern2.five_dnom': ['five.dnom'],
    'public.kern2.five_lc': ['five.lc'],
    'public.kern2.five_numr': ['five.numr'],
    'public.kern2.five_sc': ['five.sc'],
    'public.kern2.five_sinf': ['five.sinf'],
    'public.kern2.five_sups': ['five.sups'],
    'public.kern2.florin': ['florin'],
    'public.kern2.florin_lc': ['florin.lc'],
    'public.kern2.florin_sc': ['florin.sc'],
    'public.kern2.four': ['four'],
    'public.kern2.four_dnom': ['four.dnom'],
    'public.kern2.four_lc': ['four.lc'],
    'public.kern2.four_numr': ['four.numr'],
    'public.kern2.four_sc': ['four.sc'],
    'public.kern2.four_sinf': ['four.sinf'],
    'public.kern2.four_sups': ['four.sups'],
    'public.kern2.fraction': ['fraction'],
    'public.kern2.g': ['g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent',
            'gdotaccent'],
    'public.kern2.g_salt': ['g.salt', 'gbreve.salt', 'gcaron.salt',
            'gcircumflex.salt', 'gcommaaccent.salt', 'gdotaccent.salt'],
    'public.kern2.germandbls': ['germandbls'],
    'public.kern2.greater': ['greater'],
    'public.kern2.greater_lc': ['greater.lc'],
    'public.kern2.greaterequal': ['greaterequal'],
    'public.kern2.greaterequal_lc': ['greaterequal.lc'],
    'public.kern2.guillemotleft': ['guillemotleft', 'guilsinglleft'],
    'public.kern2.guillemotleft_uc': ['guillemotleft.uc', 'guilsinglleft.uc'],
    'public.kern2.guillemotright': ['guillemotright', 'guilsinglright'],
    'public.kern2.guillemotright_uc': ['guillemotright.uc',
            'guilsinglright.uc'],
    'public.kern2.h': ['b', 'h', 'hcircumflex', 'k', 'kcommaaccent', 'l',
            'lcaron', 'ldot', 'thorn'],
    'public.kern2.h_sinf': ['b.sinf', 'h.sinf', 'k.sinf', 'l.sinf'],
    'public.kern2.h_sups': ['b.sups', 'h.sups', 'k.sups', 'l.sups'],
    'public.kern2.hbar': ['hbar'],
    'public.kern2.horizontal': ['horizontalbar'],
    'public.kern2.hungarumlaut': ['hungarumlaut'],
    'public.kern2.hungarumlautcmb': ['hungarumlautcmb'],
    'public.kern2.hyphen': ['emdash', 'endash', 'hyphen', 'sfthyphen'],
    'public.kern2.hyphen_uc': ['emdash.uc', 'endash.uc', 'hyphen.uc'],
    'public.kern2.i': ['i', 'idotaccent'],
    'public.kern2.i_sinf': ['i.sinf'],
    'public.kern2.i_sups': ['i.sups'],
    'public.kern2.iacute': ['iacute'],
    'public.kern2.ibreve': ['ibreve'],
    'public.kern2.icircumflex': ['icircumflex'],
    'public.kern2.idieresis': ['idieresis'],
    'public.kern2.igrave': ['igrave'],
    'public.kern2.imacron': ['imacron'],
    'public.kern2.infinity': ['infinity'],
    'public.kern2.integral': ['integral'],
    'public.kern2.iogonek': ['iogonek'],
    'public.kern2.itilde': ['itilde'],
    'public.kern2.j': ['j'],
    'public.kern2.j_sinf': ['j.sinf'],
    'public.kern2.j_sups': ['j.sups'],
    'public.kern2.jcircumflex': ['jcircumflex'],
    'public.kern2.lacute': ['lacute'],
    'public.kern2.lcommaaccent': ['lcommaaccent'],
    'public.kern2.less': ['less', 'less.lc', 'lessequal', 'lessequal.lc'],
    'public.kern2.logicalnot': ['logicalnot'],
    'public.kern2.lozenge': ['lozenge'],
    'public.kern2.lslash': ['lslash'],
    'public.kern2.m_sinf': ['m.sinf', 'n.sinf', 'p.sinf', 'r.sinf'],
    'public.kern2.m_sups': ['m.sups', 'n.sups', 'p.sups', 'r.sups'],
    'public.kern2.macron': ['macron'],
    'public.kern2.minus': ['minus.lc'],
    'public.kern2.multiply': ['multiply', 'multiply.lc'],
    'public.kern2.n': ['eng', 'm', 'n', 'nacute', 'ncaron', 'ncommaaccent',
            'ntilde', 'p', 'r', 'racute', 'rcaron', 'rcommaaccent'],
    'public.kern2.nine': ['nine'],
    'public.kern2.nine_dnom': ['nine.dnom'],
    'public.kern2.nine_lc': ['nine.lc'],
    'public.kern2.nine_numr': ['nine.numr'],
    'public.kern2.nine_salt': ['nine.salt'],
    'public.kern2.nine_sc': ['nine.sc'],
    'public.kern2.nine_sinf': ['nine.sinf'],
    'public.kern2.nine_sups': ['nine.sups'],
    'public.kern2.notequal': ['notequal'],
    'public.kern2.notequal_lc': ['notequal.lc'],
    'public.kern2.numbersign': ['numbersign'],
    'public.kern2.numbersign_sc': ['numbersign.sc'],
    'public.kern2.o': ['c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex',
            'cdotaccent', 'd', 'dcaron', 'dcroat', 'e', 'eacute', 'ebreve',
            'ecaron', 'ecircumflex', 'edieresis', 'edotaccent', 'egrave',
            'emacron', 'eogonek', 'eth', 'o', 'oacute', 'obreve',
            'ocircumflex', 'odieresis', 'oe', 'ograve', 'ohungarumlaut',
            'omacron', 'oslash', 'oslashacute', 'otilde', 'q'],
    'public.kern2.o_sinf': ['c.sinf', 'd.sinf', 'e.sinf', 'egrave.sinf',
            'g.sinf', 'o.sinf', 'q.sinf'],
    'public.kern2.o_sups': ['c.sups', 'd.sups', 'e.sups', 'egrave.sups',
            'g.sups', 'o.sups', 'q.sups'],
    'public.kern2.ogonek': ['ogonek'],
    'public.kern2.one': ['one'],
    'public.kern2.one_dnom': ['one.dnom'],
    'public.kern2.one_lc': ['one.lc'],
    'public.kern2.one_numr': ['one.numr'],
    'public.kern2.one_sc': ['one.sc'],
    'public.kern2.one_sinf': ['one.sinf'],
    'public.kern2.one_sups': ['one.sups'],
    'public.kern2.onehalf': ['onehalf'],
    'public.kern2.onequarter': ['onequarter'],
    'public.kern2.onesuperior': ['onesuperior'],
    'public.kern2.ordfeminine': ['ordfeminine'],
    'public.kern2.ordmasculine': ['ordmasculine'],
    'public.kern2.paragraph': ['paragraph'],
    'public.kern2.paragraph_lc': ['paragraph.lc'],
    'public.kern2.parenleft': ['parenleft'],
    'public.kern2.parenleft_sc': ['parenleft.sc'],
    'public.kern2.parenleft_uc': ['parenleft.uc'],
    'public.kern2.parenright': ['parenright'],
    'public.kern2.parenright_sc': ['parenright.sc'],
    'public.kern2.parenright_uc': ['parenright.uc'],
    'public.kern2.partialdiff': ['partialdiff'],
    'public.kern2.percent': ['percent', 'perthousand'],
    'public.kern2.percent_lc': ['percent.lc', 'perthousand.lc'],
    'public.kern2.period': ['ellipsis', 'period'],
    'public.kern2.periodcentered': ['periodcentered'],
    'public.kern2.periodcentered_uc': ['periodcentered.uc'],
    'public.kern2.pi': ['pi'],
    'public.kern2.plus': ['plus'],
    'public.kern2.plus_lc': ['plus.lc'],
    'public.kern2.plusminus': ['plusminus'],
    'public.kern2.plusminus_lc': ['plusminus.lc'],
    'public.kern2.product': ['product'],
    'public.kern2.question': ['question'],
    'public.kern2.question_sc': ['question.sc'],
    'public.kern2.questiondown': ['questiondown'],
    'public.kern2.questiondown_uc': ['questiondown.uc'],
    'public.kern2.quote': ['minute', 'quotedbl', 'quotesingle', 'second'],
    'public.kern2.quoteleft': ['quotedblleft', 'quoteleft'],
    'public.kern2.quoteright': ['quotedblright', 'quoteright'],
    'public.kern2.radical': ['radical'],
    'public.kern2.registered': ['copyright', 'copyrightsound', 'registered',
            'uni2117'],
    'public.kern2.s': ['s', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'public.kern2.s_sinf': ['s.sinf'],
    'public.kern2.s_sups': ['s.sups'],
    'public.kern2.schwa': ['schwa'],
    'public.kern2.section': ['section'],
    'public.kern2.section_lc': ['section.lc'],
    'public.kern2.section_sc': ['section.sc'],
    'public.kern2.semicolon': ['semicolon'],
    'public.kern2.seven': ['seven'],
    'public.kern2.seven_dnom': ['seven.dnom'],
    'public.kern2.seven_lc': ['seven.lc'],
    'public.kern2.seven_numr': ['seven.numr'],
    'public.kern2.seven_sc': ['seven.sc'],
    'public.kern2.seven_sinf': ['seven.sinf'],
    'public.kern2.seven_sups': ['seven.sups'],
    'public.kern2.six': ['six'],
    'public.kern2.six_dnom': ['six.dnom'],
    'public.kern2.six_lc': ['six.lc'],
    'public.kern2.six_numr': ['six.numr'],
    'public.kern2.six_salt': ['six.salt'],
    'public.kern2.six_sc': ['six.sc'],
    'public.kern2.six_sinf': ['six.sinf'],
    'public.kern2.six_sups': ['six.sups'],
    'public.kern2.slash': ['slash'],
    'public.kern2.slash_sc': ['slash.sc'],
    'public.kern2.space': ['space'],
    'public.kern2.space_em': ['space.em'],
    'public.kern2.space_en': ['space.en'],
    'public.kern2.space_frac': ['space.frac'],
    'public.kern2.space_thin': ['space.thin'],
    'public.kern2.sterling': ['sterling'],
    'public.kern2.sterling_lc': ['sterling.lc'],
    'public.kern2.sterling_sc': ['sterling.sc'],
    'public.kern2.summation': ['summation'],
    'public.kern2.t': ['t', 'tbar', 'tcaron', 'tcedilla', 'tcommaaccent'],
    'public.kern2.t_sinf': ['t.sinf'],
    'public.kern2.t_sups': ['t.sups'],
    'public.kern2.three': ['three'],
    'public.kern2.three_dnom': ['three.dnom'],
    'public.kern2.three_lc': ['three.lc'],
    'public.kern2.three_numr': ['three.numr'],
    'public.kern2.three_sc': ['three.sc'],
    'public.kern2.three_sinf': ['three.sinf'],
    'public.kern2.three_sups': ['three.sups'],
    'public.kern2.threequarters': ['threequarters'],
    'public.kern2.threesuperior': ['threesuperior'],
    'public.kern2.trademark': ['trademark'],
    'public.kern2.two': ['two'],
    'public.kern2.two_dnom': ['two.dnom'],
    'public.kern2.two_lc': ['two.lc'],
    'public.kern2.two_numr': ['two.numr'],
    'public.kern2.two_sc': ['two.sc'],
    'public.kern2.two_sinf': ['two.sinf'],
    'public.kern2.two_sups': ['two.sups'],
    'public.kern2.twosuperior': ['twosuperior'],
    'public.kern2.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex',
            'udieresis', 'ugrave', 'uhungarumlaut', 'umacron', 'uogonek',
            'uring', 'utilde'],
    'public.kern2.u_sinf': ['u.sinf'],
    'public.kern2.u_sups': ['u.sups'],
    'public.kern2.underscore': ['underscore'],
    'public.kern2.v': ['v', 'w', 'wacute', 'wcircumflex', 'wdieresis',
            'wgrave'],
    'public.kern2.v_sinf': ['v.sinf', 'w.sinf'],
    'public.kern2.v_sups': ['v.sups', 'w.sups'],
    'public.kern2.x': ['x'],
    'public.kern2.x_sinf': ['x.sinf'],
    'public.kern2.x_sups': ['x.sups'],
    'public.kern2.y': ['y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'],
    'public.kern2.y_sinf': ['y.sinf'],
    'public.kern2.y_sups': ['y.sups'],
    'public.kern2.yen': ['yen'],
    'public.kern2.z': ['z', 'zacute', 'zcaron', 'zdotaccent'],
    'public.kern2.z_sinf': ['z.sinf'],
    'public.kern2.z_sups': ['z.sups'],
    'public.kern2.zero': ['zero'],
    'public.kern2.zero_dnom': ['zero.dnom'],
    'public.kern2.zero_lc': ['zero.lc'],
    'public.kern2.zero_lc_salt_slash': ['zero.lc_salt_slash'],
    'public.kern2.zero_numr': ['zero.numr'],
    'public.kern2.zero_salt_slash': ['zero.salt_slash'],
    'public.kern2.zero_sc': ['zero.sc'],
    'public.kern2.zero_sc_salt_slash': ['zero.sc_salt_slash'],
    'public.kern2.zero_sinf': ['zero.sinf'],
    'public.kern2.zero_sups': ['zero.sups'],
    'TC1.Euro': ['Euro', 'Euro.lc', 'Euro.sc'],
    'TC1.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'TC1.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
            'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
            'Iogonek.sc', 'Itilde.sc'],
    'TC1.J': ['J', 'Jcircumflex'],
    'TC1.J_sc': ['J.sc', 'Jcircumflex.sc'],
    'TC1.a_sinf': ['a.sinf', 'a.sups'],
    'TC1.back': ['backslash', 'backslash.sc'],
    'TC1.braceleft': ['braceleft', 'braceleft.sc', 'braceleft.uc'],
    'TC1.braceright': ['braceright', 'braceright.sc', 'braceright.uc'],
    'TC1.bracketleft': ['bracketleft', 'bracketleft.sc', 'bracketleft.uc'],
    'TC1.bracketright': ['bracketright', 'bracketright.sc', 'bracketright.uc'],
    'TC1.bullet': ['bullet', 'bullet.uc'],
    'TC1.c_sinf': ['c.sinf', 'c.sups'],
    'TC1.cent': ['cent', 'cent.lc', 'cent.lc_AT_weight800', 'cent.sc',
            'cent.sc_AT_weight800', 'cent_AT_weight800'],
    'TC1.comma': ['comma', 'quotedblbase', 'quotedblright', 'quoteright',
            'quotesinglbase', 'semicolon'],
    'TC1.degree': ['degree', 'degree.lc', 'degree.sc'],
    'TC1.e_sinf': ['e.sinf', 'e.sups', 'egrave.sinf', 'egrave.sups'],
    'TC1.eight_dnom': ['eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups'],
    'TC1.equal': ['approxequal', 'approxequal.lc', 'equal', 'equal.lc'],
    'TC1.exclam': ['exclam', 'exclam.sc'],
    'TC1.exclamdown': ['exclamdown', 'exclamdown.uc'],
    'TC1.f_sinf': ['f.sinf', 'f.sups'],
    'TC1.five_dnom': ['five.dnom', 'five.numr', 'five.sinf', 'five.sups'],
    'TC1.florin': ['florin', 'florin.lc', 'florin.sc'],
    'TC1.four_dnom': ['four.dnom', 'four.numr', 'four.sinf', 'four.sups',
            'onequarter', 'threequarters'],
    'TC1.g_sinf': ['g.sinf', 'g.sups'],
    'TC1.hyphen': ['emdash', 'emdash.uc', 'endash', 'endash.uc', 'hyphen',
            'hyphen.uc', 'sfthyphen'],
    'TC1.i': ['dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis',
            'idotaccent', 'igrave', 'imacron', 'iogonek', 'itilde'],
    'TC1.i_sinf': ['i.sinf', 'i.sups'],
    'TC1.j': ['dotlessj', 'j', 'jcircumflex'],
    'TC1.j_sinf': ['j.sinf', 'j.sups'],
    'TC1.k_sinf': ['k.sinf', 'k.sups', 'x.sinf', 'x.sups'],
    'TC1.l_sinf': ['d.sups', 'l.sinf'],
    'TC1.minus': ['minus', 'minus.lc'],
    'TC1.multiply': ['multiply', 'multiply.lc'],
    'TC1.n_sinf': ['h.sinf', 'h.sups', 'm.sinf', 'm.sups', 'n.sinf', 'n.sups'],
    'TC1.nine': ['nine', 'nine.salt'],
    'TC1.nine_dnom': ['nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'],
    'TC1.notequal': ['notequal', 'notequal.lc'],
    'TC1.numbersign': ['numbersign', 'numbersign.sc'],
    'TC1.o_sinf': ['b.sinf', 'b.sups', 'o.sinf', 'o.sups', 'p.sinf', 'p.sups'],
    'TC1.one_dnom': ['one.dnom', 'one.numr', 'one.sinf', 'one.sups',
            'onesuperior'],
    'TC1.parenleft': ['parenleft', 'parenleft.sc', 'parenleft.uc'],
    'TC1.parenright': ['parenright', 'parenright.sc', 'parenright.uc'],
    'TC1.period': ['colon', 'ellipsis', 'period', 'periodcentered',
            'periodcentered.uc'],
    'TC1.plus': ['plus', 'plus.lc', 'plusminus', 'plusminus.lc'],
    'TC1.q_sinf': ['q.sinf', 'q.sups'],
    'TC1.question': ['question', 'question.sc'],
    'TC1.questiondown': ['questiondown', 'questiondown.uc'],
    'TC1.r_sinf': ['r.sinf', 'r.sups'],
    'TC1.s': ['germandbls', 's', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'TC1.s_sinf': ['s.sinf', 's.sups'],
    'TC1.section': ['section', 'section.lc', 'section.sc'],
    'TC1.seven_dnom': ['seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups'],
    'TC1.six': ['six', 'six.salt'],
    'TC1.six_dnom': ['six.dnom', 'six.numr', 'six.sinf', 'six.sups'],
    'TC1.slash': ['slash', 'slash.sc'],
    'TC1.sterling': ['sterling', 'sterling.lc', 'sterling.sc'],
    'TC1.t_sinf': ['t.sinf', 't.sups'],
    'TC1.three_dnom': ['three.dnom', 'three.numr', 'three.sinf', 'three.sups',
            'threesuperior'],
    'TC1.two_dnom': ['onehalf', 'two.dnom', 'two.numr', 'two.sinf', 'two.sups',
            'twosuperior'],
    'TC1.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex', 'udieresis',
            'ugrave', 'uhungarumlaut', 'umacron', 'uogonek', 'uring',
            'utilde'],
    'TC1.u_sinf': ['u.sinf', 'u.sups'],
    'TC1.v_sinf': ['v.sinf', 'v.sups', 'w.sinf', 'w.sups', 'y.sinf', 'y.sups'],
    'TC1.z_sinf': ['z.sinf', 'z.sups'],
    'TC1.zero': ['zero', 'zero.salt_slash'],
    'TC1.zero_dnom': ['percent', 'percent.lc', 'perthousand', 'perthousand.lc',
            'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups'],
    'TC1.zero_lc': ['zero.lc', 'zero.lc_salt_slash'],
    'TC1.zero_sc': ['zero.sc', 'zero.sc_salt_slash'],
    'TC2.Euro': ['Euro', 'Euro.lc', 'Euro.sc'],
    'TC2.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'TC2.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
            'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
            'Iogonek.sc', 'Itilde.sc'],
    'TC2.J': ['J', 'Jcircumflex'],
    'TC2.J_sc': ['J.sc', 'Jcircumflex.sc'],
    'TC2.a_sinf': ['a.sinf', 'a.sups'],
    'TC2.back': ['backslash', 'backslash.sc'],
    'TC2.braceleft': ['braceleft', 'braceleft.sc', 'braceleft.uc'],
    'TC2.braceright': ['braceright', 'braceright.sc', 'braceright.uc'],
    'TC2.bracketleft': ['bracketleft', 'bracketleft.sc', 'bracketleft.uc'],
    'TC2.bracketright': ['bracketright', 'bracketright.sc', 'bracketright.uc'],
    'TC2.bullet': ['bullet', 'bullet.uc'],
    'TC2.cent': ['cent', 'cent.lc', 'cent.lc_AT_weight800', 'cent.sc',
            'cent.sc_AT_weight800', 'cent_AT_weight800'],
    'TC2.comma': ['comma', 'quotedblbase', 'quotedblright', 'quoteright',
            'quotesinglbase', 'semicolon'],
    'TC2.degree': ['degree', 'degree.lc', 'degree.sc'],
    'TC2.eight_sinf': ['eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups'],
    'TC2.equal': ['approxequal', 'approxequal.lc', 'equal', 'equal.lc'],
    'TC2.exclam': ['exclam', 'exclam.sc'],
    'TC2.exclamdown': ['exclamdown', 'exclamdown.uc'],
    'TC2.f_sinf': ['f.sinf', 'f.sups'],
    'TC2.five_sinf': ['five.dnom', 'five.numr', 'five.sinf', 'five.sups'],
    'TC2.florin': ['florin', 'florin.lc', 'florin.sc'],
    'TC2.four_sinf': ['four.dnom', 'four.numr', 'four.sinf', 'four.sups'],
    'TC2.greater': ['greater', 'greater.lc', 'greaterequal',
            'greaterequal.lc'],
    'TC2.guillemotleft': ['guillemotleft', 'guillemotleft.uc', 'guilsinglleft',
            'guilsinglleft.uc'],
    'TC2.guillemotright': ['guillemotright', 'guillemotright.uc',
            'guilsinglright', 'guilsinglright.uc'],
    'TC2.h_sinf': ['b.sinf', 'b.sups', 'h.sinf', 'h.sups', 'k.sinf', 'k.sups',
            'l.sinf', 'l.sups'],
    'TC2.hyphen': ['emdash', 'emdash.uc', 'endash', 'endash.uc', 'hyphen',
            'hyphen.uc', 'sfthyphen'],
    'TC2.i': ['dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis',
            'idotaccent', 'igrave', 'imacron', 'iogonek', 'itilde'],
    'TC2.i_sinf': ['i.sinf', 'i.sups'],
    'TC2.j': ['dotlessj', 'j', 'jcircumflex'],
    'TC2.j_sinf': ['j.sinf', 'j.sups'],
    'TC2.l': ['b', 'h', 'hbar', 'hcircumflex', 'k', 'kcommaaccent', 'l',
            'lcommaaccent', 'thorn'],
    'TC2.m_sinf': ['m.sinf', 'm.sups', 'n.sinf', 'n.sups', 'p.sinf', 'p.sups',
            'r.sinf', 'r.sups'],
    'TC2.minus': ['minus', 'minus.lc'],
    'TC2.nine': ['nine', 'nine.salt'],
    'TC2.nine_sinf': ['nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'],
    'TC2.notequal': ['notequal', 'notequal.lc'],
    'TC2.numbersign': ['numbersign', 'numbersign.sc'],
    'TC2.o_sinf': ['c.sinf', 'c.sups', 'd.sinf', 'd.sups', 'e.sinf', 'e.sups',
            'egrave.sinf', 'egrave.sups', 'g.sinf', 'g.sups', 'o.sinf',
            'o.sups', 'q.sinf', 'q.sups'],
    'TC2.one_sinf': ['one.dnom', 'one.numr', 'one.sinf', 'one.sups', 'onehalf',
            'onequarter', 'onesuperior'],
    'TC2.parenleft': ['parenleft', 'parenleft.sc', 'parenleft.uc'],
    'TC2.parenright': ['parenright', 'parenright.sc', 'parenright.uc'],
    'TC2.period': ['colon', 'ellipsis', 'period', 'periodcentered',
            'periodcentered.uc'],
    'TC2.plus': ['plus', 'plus.lc', 'plusminus', 'plusminus.lc'],
    'TC2.question': ['question', 'question.sc'],
    'TC2.questiondown': ['questiondown', 'questiondown.uc'],
    'TC2.s_sinf': ['s.sinf', 's.sups'],
    'TC2.section': ['section', 'section.lc', 'section.sc'],
    'TC2.seven_sinf': ['seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups'],
    'TC2.six': ['six', 'six.salt'],
    'TC2.six_sinf': ['six.dnom', 'six.numr', 'six.sinf', 'six.sups'],
    'TC2.slash': ['slash', 'slash.sc'],
    'TC2.sterling': ['sterling', 'sterling.lc', 'sterling.sc'],
    'TC2.t_sinf': ['t.sinf', 't.sups'],
    'TC2.three_sinf': ['three.dnom', 'three.numr', 'three.sinf', 'three.sups',
            'threequarters', 'threesuperior'],
    'TC2.two_sinf': ['two.dnom', 'two.numr', 'two.sinf', 'two.sups',
            'twosuperior'],
    'TC2.u_sinf': ['u.sinf', 'u.sups'],
    'TC2.v_sinf': ['v.sinf', 'v.sups', 'w.sinf', 'w.sups'],
    'TC2.x_sinf': ['x.sinf', 'x.sups'],
    'TC2.z_sinf': ['z.sinf', 'z.sups'],
    'TC2.zero': ['zero', 'zero.salt_slash'],
    'TC2.zero_lc': ['zero.lc', 'zero.lc_salt_slash'],
    'TC2.zero_sc': ['zero.sc', 'zero.sc_salt_slash'],
    'TC2.zero_sinf': ['percent', 'percent.lc', 'perthousand', 'perthousand.lc',
            'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups']
    }

DEFAULTGROUPS_ITALIC = {
    'public.kern1.A': ['A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis',
        'Agrave', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde'],
    'public.kern1.A_sc': ['A.sc', 'Aacute.sc', 'Abreve.sc', 'Acircumflex.sc',
        'Adieresis.sc', 'Agrave.sc', 'Amacron.sc', 'Aogonek.sc', 'Aring.sc',
        'Aringacute.sc', 'Atilde.sc'],
    'public.kern1.B': ['B'],
    'public.kern1.B_sc': ['B.sc'],
    'public.kern1.C': ['C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex',
        'Cdotaccent'],
    'public.kern1.C_sc': ['C.sc', 'Cacute.sc', 'Ccaron.sc', 'Ccedilla.sc',
        'Ccircumflex.sc', 'Cdotaccent.sc'],
    'public.kern1.Delta': ['Delta'],
    'public.kern1.E': ['AE', 'AEacute', 'E', 'Eacute', 'Ebreve', 'Ecaron',
        'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron',
        'Eogonek', 'OE'],
    'public.kern1.E_sc': ['AE.sc', 'AEacute.sc', 'E.sc', 'Eacute.sc',
        'Ebreve.sc', 'Ecaron.sc', 'Ecircumflex.sc', 'Edieresis.sc',
        'Edotaccent.sc', 'Egrave.sc', 'Emacron.sc', 'Eogonek.sc', 'OE.sc'],
    'public.kern1.Euro_lc': ['Euro.lc'],
    'public.kern1.Euro_sc': ['Euro.sc'],
    'public.kern1.Eurog': ['Euro'],
    'public.kern1.F': ['F'],
    'public.kern1.F_sc': ['F.sc'],
    'public.kern1.G': ['G', 'Gbreve', 'Gcaron', 'Gcircumflex', 'Gcommaaccent',
        'Gdotaccent'],
    'public.kern1.G_sc': ['G.sc', 'Gbreve.sc', 'Gcaron.sc', 'Gcircumflex.sc',
        'Gcommaaccent.sc', 'Gdotaccent.sc'],
    'public.kern1.H': ['Eng', 'H', 'Hcircumflex', 'M', 'N', 'Nacute', 'Ncaron',
        'Ncommaaccent', 'Ntilde'],
    'public.kern1.H_sc': ['Eng.sc', 'H.sc', 'Hcircumflex.sc', 'M.sc', 'N.sc',
        'Nacute.sc', 'Ncaron.sc', 'Ncommaaccent.sc', 'Ntilde.sc'],
    'public.kern1.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
        'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'public.kern1.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
        'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
        'Iogonek.sc', 'Itilde.sc'],
    'public.kern1.J': ['J'],
    'public.kern1.J_sc': ['J.sc'],
    'public.kern1.Jcircumflex': ['Jcircumflex'],
    'public.kern1.Jcircumflex_sc': ['Jcircumflex.sc'],
    'public.kern1.K': ['K', 'Kcommaaccent', 'X'],
    'public.kern1.K_sc': ['K.sc', 'Kcommaaccent.sc', 'X.sc'],
    'public.kern1.L': ['L'],
    'public.kern1.L_sc': ['L.sc'],
    'public.kern1.Lacute': ['Lacute'],
    'public.kern1.Lacute_sc': ['Lacute.sc'],
    'public.kern1.Lcaron': ['Lcaron'],
    'public.kern1.Lcaron_sc': ['Lcaron.sc'],
    'public.kern1.Ldot': ['Ldot'],
    'public.kern1.Ldot_sc': ['Ldot.sc'],
    'public.kern1.Lslash': ['Lslash'],
    'public.kern1.Lslash_sc': ['Lslash.sc'],
    'public.kern1.O': ['D', 'Dcaron', 'Dcroat', 'Eth', 'O', 'Oacute', 'Obreve',
            'Ocircumflex', 'Odieresis', 'Ograve', 'Ohungarumlaut', 'Omacron',
            'Oslash', 'Oslashacute', 'Otilde', 'Q'],
    'public.kern1.O_sc': ['D.sc', 'Dcaron.sc', 'Dcroat.sc', 'Eth.sc', 'O.sc',
            'Oacute.sc', 'Obreve.sc', 'Ocircumflex.sc', 'Odieresis.sc',
            'Ograve.sc', 'Ohungarumlaut.sc', 'Omacron.sc', 'Oslash.sc',
            'Oslashacute.sc', 'Otilde.sc', 'Q.sc'],
    'public.kern1.Omega': ['Omega'],
    'public.kern1.P': ['P'],
    'public.kern1.P_sc': ['P.sc'],
    'public.kern1.R': ['R', 'Racute', 'Rcaron', 'Rcommaaccent'],
    'public.kern1.R_sc': ['R.sc', 'Racute.sc', 'Rcaron.sc', 'Rcommaaccent.sc'],
    'public.kern1.S': ['S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex',
            'Scommaaccent'],
    'public.kern1.S_sc': ['S.sc', 'Sacute.sc', 'Scaron.sc', 'Scedilla.sc',
            'Scircumflex.sc', 'Scommaaccent.sc'],
    'public.kern1.T': ['T', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'],
    'public.kern1.T_sc': ['T.sc', 'Tbar.sc', 'Tcaron.sc', 'Tcedilla.sc',
            'Tcommaaccent.sc'],
    'public.kern1.Thorn': ['Thorn'],
    'public.kern1.Thorn_sc': ['Thorn.sc'],
    'public.kern1.U': ['U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis',
            'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring',
            'Utilde'],
    'public.kern1.U_sc': ['U.sc', 'Uacute.sc', 'Ubreve.sc', 'Ucircumflex.sc',
            'Udieresis.sc', 'Ugrave.sc', 'Uhungarumlaut.sc', 'Umacron.sc',
            'Uogonek.sc', 'Uring.sc', 'Utilde.sc'],
    'public.kern1.V': ['V'],
    'public.kern1.V_sc': ['V.sc'],
    'public.kern1.W': ['W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'],
    'public.kern1.W_sc': ['W.sc', 'Wacute.sc', 'Wcircumflex.sc',
            'Wdieresis.sc', 'Wgrave.sc'],
    'public.kern1.Y': ['Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'],
    'public.kern1.Y_sc': ['Y.sc', 'Yacute.sc', 'Ycircumflex.sc',
            'Ydieresis.sc', 'Ygrave.sc'],
    'public.kern1.Z': ['Z', 'Zacute', 'Zcaron', 'Zdotaccent'],
    'public.kern1.Z_sc': ['Z.sc', 'Zacute.sc', 'Zcaron.sc', 'Zdotaccent.sc'],
    'public.kern1.a': ['a', 'aacute', 'abreve', 'acircumflex', 'adieresis',
            'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde'],
    'public.kern1.a_sinf': ['a.sinf'],
    'public.kern1.a_sups': ['a.sups'],
    'public.kern1.ampersand': ['ampersand'],
    'public.kern1.ampersand_sc': ['ampersand.sc'],
    'public.kern1.apple': ['apple'],
    'public.kern1.approxequal': ['approxequal'],
    'public.kern1.approxequal_lc': ['approxequal.lc'],
    'public.kern1.ascii': ['asciitilde'],
    'public.kern1.asciicircum': ['asciicircum'],
    'public.kern1.asterisk': ['asterisk'],
    'public.kern1.at': ['at'],
    'public.kern1.back': ['backslash'],
    'public.kern1.back_sc': ['backslash.sc'],
    'public.kern1.bar': ['bar', 'brokenbar'],
    'public.kern1.braceleft': ['braceleft'],
    'public.kern1.braceleft_sc': ['braceleft.sc'],
    'public.kern1.braceleft_uc': ['braceleft.uc'],
    'public.kern1.braceright': ['braceright'],
    'public.kern1.braceright_sc': ['braceright.sc'],
    'public.kern1.braceright_uc': ['braceright.uc'],
    'public.kern1.bracketleft': ['bracketleft'],
    'public.kern1.bracketleft_sc': ['bracketleft.sc'],
    'public.kern1.bracketleft_uc': ['bracketleft.uc'],
    'public.kern1.bracketright': ['bracketright'],
    'public.kern1.bracketright_sc': ['bracketright.sc'],
    'public.kern1.bracketright_uc': ['bracketright.uc'],
    'public.kern1.bullet': ['bullet'],
    'public.kern1.bullet_uc': ['bullet.uc'],
    'public.kern1.c': ['c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex',
            'cdotaccent'],
    'public.kern1.c_sinf': ['c.sups'],
    'public.kern1.cent': ['cent'],
    'public.kern1.cent_AT_weight800': ['cent_AT_weight800'],
    'public.kern1.cent_lc_AT_weight800': ['cent.lc_AT_weight800'],
    'public.kern1.cent_sc': ['cent.lc'],
    'public.kern1.cent_sc_AT_weight800': ['cent.sc_AT_weight800'],
    'public.kern1.checkmark': ['checkmark'],
    'public.kern1.colon': ['colon'],
    'public.kern1.comma': ['comma', 'quotedblbase', 'quotesinglbase'],
    'public.kern1.currency': ['currency'],
    'public.kern1.dagger': ['dagger'],
    'public.kern1.daggerdbl': ['daggerdbl'],
    'public.kern1.dcroat': ['dcroat'],
    'public.kern1.degree': ['degree'],
    'public.kern1.degree_lc': ['degree.lc'],
    'public.kern1.degree_sc': ['degree.sc'],
    'public.kern1.divide': ['divide'],
    'public.kern1.dollar': ['dollar', 'dollar_AT_weight800'],
    'public.kern1.dollar_lc': ['dollar.lc', 'dollar.lc_AT_weight800'],
    'public.kern1.dollar_sc': ['dollar.sc', 'dollar.sc_AT_weight800'],
    'public.kern1.dotaccent': ['dotaccent'],
    'public.kern1.dotlessi': ['dotlessi'],
    'public.kern1.dotlessj': ['dotlessj'],
    'public.kern1.e': ['ae', 'aeacute', 'e', 'eacute', 'ebreve', 'ecaron',
            'ecircumflex', 'edieresis', 'edotaccent', 'egrave', 'emacron',
            'eogonek', 'oe'],
    'public.kern1.e_sinf': ['e.sinf', 'egrave.sinf'],
    'public.kern1.e_sups': ['e.sups', 'egrave.sups'],
    'public.kern1.eight': ['eight'],
    'public.kern1.eight_dnom': ['eight.dnom'],
    'public.kern1.eight_lc': ['eight.lc'],
    'public.kern1.eight_numr': ['eight.numr'],
    'public.kern1.eight_sc': ['eight.sc'],
    'public.kern1.eight_sinf': ['eight.sinf'],
    'public.kern1.eight_sups': ['eight.sups'],
    'public.kern1.equal': ['equal'],
    'public.kern1.equal_lc': ['equal.lc'],
    'public.kern1.eth': ['eth'],
    'public.kern1.exclam': ['exclam'],
    'public.kern1.exclam_sc': ['exclam.sc'],
    'public.kern1.exclamdown': ['exclamdown'],
    'public.kern1.exclamdown_uc': ['exclamdown.uc'],
    'public.kern1.f': ['f'],
    'public.kern1.f_salt_nokern': ['f.salt_noconnect'],
    'public.kern1.f_sinf': ['f.sinf'],
    'public.kern1.f_sups': ['f.sups'],
    'public.kern1.five': ['five'],
    'public.kern1.five_dnom': ['five.dnom'],
    'public.kern1.five_lc': ['five.lc'],
    'public.kern1.five_numr': ['five.numr'],
    'public.kern1.five_sc': ['five.sc'],
    'public.kern1.five_sinf': ['five.sinf'],
    'public.kern1.five_sups': ['five.sups'],
    'public.kern1.florin': ['florin'],
    'public.kern1.florin_lc': ['florin.lc'],
    'public.kern1.florin_sc': ['florin.sc'],
    'public.kern1.four': ['four'],
    'public.kern1.four_dnom': ['four.dnom'],
    'public.kern1.four_lc': ['four.lc'],
    'public.kern1.four_numr': ['four.numr'],
    'public.kern1.four_sc': ['four.sc'],
    'public.kern1.four_sinf': ['four.sinf'],
    'public.kern1.four_sups': ['four.sups'],
    'public.kern1.fraction': ['fraction'],
    'public.kern1.g': ['g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent',
            'gdotaccent'],
    'public.kern1.g_salt': ['g.salt', 'gbreve.salt', 'gcaron.salt',
            'gcircumflex.salt', 'gcommaaccent.salt', 'gdotaccent.salt'],
    'public.kern1.g_sinf': ['g.sinf'],
    'public.kern1.g_sups': ['g.sups'],
    'public.kern1.germandbls': ['germandbls'],
    'public.kern1.greater': ['greater', 'greater.lc', 'greaterequal',
            'greaterequal.lc'],
    'public.kern1.guillemotleft': ['guillemotleft', 'guilsinglleft'],
    'public.kern1.guillemotleft_uc': ['guillemotleft.uc', 'guilsinglleft.uc'],
    'public.kern1.guillemotright': ['guillemotright', 'guilsinglright'],
    'public.kern1.guillemotright_uc': ['guillemotright.uc',
            'guilsinglright.uc'],
    'public.kern1.h': ['h', 'hbar', 'hcircumflex'],
    'public.kern1.horizontal': ['horizontalbar'],
    'public.kern1.hyphen': ['emdash', 'endash', 'hyphen', 'sfthyphen'],
    'public.kern1.hyphen_uc': ['emdash.uc', 'endash.uc', 'hyphen.uc'],
    'public.kern1.i': ['i', 'idotaccent'],
    'public.kern1.i_sinf': ['i.sinf'],
    'public.kern1.i_sups': ['i.sups'],
    'public.kern1.iacute': ['iacute'],
    'public.kern1.ibreve': ['ibreve'],
    'public.kern1.icircumflex': ['icircumflex'],
    'public.kern1.idieresis': ['idieresis'],
    'public.kern1.igrave': ['igrave'],
    'public.kern1.imacron': ['imacron'],
    'public.kern1.infinity': ['infinity'],
    'public.kern1.integral': ['integral'],
    'public.kern1.iogonek': ['iogonek'],
    'public.kern1.itilde': ['itilde'],
    'public.kern1.j': ['j'],
    'public.kern1.j_sinf': ['j.sinf'],
    'public.kern1.j_sups': ['j.sups'],
    'public.kern1.jcircumflex': ['jcircumflex'],
    'public.kern1.k': ['k', 'kcommaaccent', 'x'],
    'public.kern1.k_sinf': ['k.sinf', 'x.sinf'],
    'public.kern1.k_sups': ['k.sups', 'x.sups'],
    'public.kern1.l': ['d', 'l'],
    'public.kern1.l_sinf': ['l.sinf'],
    'public.kern1.l_sups': ['d.sups'],
    'public.kern1.lacute': ['lacute'],
    'public.kern1.lcaron': ['dcaron', 'lcaron'],
    'public.kern1.ldot': ['ldot'],
    'public.kern1.less': ['less', 'less.lc', 'lessequal', 'lessequal.lc'],
    'public.kern1.logicalnot': ['logicalnot'],
    'public.kern1.lozenge': ['lozenge'],
    'public.kern1.lslash': ['lslash'],
    'public.kern1.minus': ['minus'],
    'public.kern1.minus_lc': ['minus.lc'],
    'public.kern1.multiply': ['multiply'],
    'public.kern1.multiply_lc': ['multiply.lc'],
    'public.kern1.n': ['eng', 'm', 'n', 'nacute', 'ncaron', 'ncommaaccent',
            'ntilde'],
    'public.kern1.n_sinf': ['h.sinf', 'm.sinf', 'n.sinf'],
    'public.kern1.n_sups': ['h.sups', 'm.sups', 'n.sups'],
    'public.kern1.nine': ['nine'],
    'public.kern1.nine_dnom': ['nine.dnom'],
    'public.kern1.nine_lc': ['nine.lc'],
    'public.kern1.nine_numr': ['nine.numr'],
    'public.kern1.nine_salt': ['nine.salt'],
    'public.kern1.nine_sc': ['nine.sc'],
    'public.kern1.nine_sinf': ['nine.sinf'],
    'public.kern1.nine_sups': ['nine.sups'],
    'public.kern1.notequal': ['notequal'],
    'public.kern1.notequal_lc': ['notequal.lc'],
    'public.kern1.numbersign': ['numbersign'],
    'public.kern1.numbersign_sc': ['numbersign.sc'],
    'public.kern1.o': ['b', 'o', 'oacute', 'obreve', 'ocircumflex',
            'odieresis', 'ograve', 'ohungarumlaut', 'omacron', 'oslash',
            'oslashacute', 'otilde', 'p', 'thorn'],
    'public.kern1.o_sinf': ['b.sinf', 'o.sinf', 'p.sinf'],
    'public.kern1.o_sups': ['b.sups', 'o.sups', 'p.sups'],
    'public.kern1.one': ['one'],
    'public.kern1.one_dnom': ['one.dnom'],
    'public.kern1.one_lc': ['one.lc'],
    'public.kern1.one_numr': ['one.numr'],
    'public.kern1.one_sc': ['one.sc'],
    'public.kern1.one_sinf': ['one.sinf'],
    'public.kern1.one_sups': ['one.sups'],
    'public.kern1.onehalf': ['onehalf'],
    'public.kern1.onequarter': ['onequarter'],
    'public.kern1.onesuperior': ['onesuperior'],
    'public.kern1.ord': ['ordfeminine', 'ordmasculine'],
    'public.kern1.paragraph': ['paragraph'],
    'public.kern1.paragraph_lc': ['paragraph.lc'],
    'public.kern1.parenleft': ['parenleft'],
    'public.kern1.parenleft_sc': ['parenleft.sc'],
    'public.kern1.parenleft_uc': ['parenleft.uc'],
    'public.kern1.parenright': ['parenright'],
    'public.kern1.parenright_sc': ['parenright.sc'],
    'public.kern1.parenright_uc': ['parenright.uc'],
    'public.kern1.partialdiff': ['partialdiff'],
    'public.kern1.percent': ['percent', 'perthousand'],
    'public.kern1.percent_lc': ['percent.lc', 'perthousand.lc'],
    'public.kern1.period': ['ellipsis', 'period'],
    'public.kern1.periodcentered': ['periodcentered'],
    'public.kern1.periodcentered_uc': ['periodcentered.uc'],
    'public.kern1.pi': ['pi'],
    'public.kern1.plus': ['plus'],
    'public.kern1.plus_lc': ['plus.lc'],
    'public.kern1.plusminus': ['plusminus'],
    'public.kern1.plusminus_lc': ['plusminus.lc'],
    'public.kern1.product': ['product'],
    'public.kern1.q': ['q'],
    'public.kern1.q_sinf': ['q.sinf'],
    'public.kern1.q_sups': ['q.sups'],
    'public.kern1.question': ['question'],
    'public.kern1.question_sc': ['question.sc'],
    'public.kern1.questiondown': ['questiondown'],
    'public.kern1.questiondown_uc': ['questiondown.uc'],
    'public.kern1.quote': ['minute', 'quotedbl', 'quotesingle', 'second'],
    'public.kern1.quoteleft': ['quotedblleft', 'quoteleft'],
    'public.kern1.quoteright': ['quotedblright', 'quoteright'],
    'public.kern1.r': ['r', 'racute', 'rcaron', 'rcommaaccent'],
    'public.kern1.r_sinf': ['r.sinf'],
    'public.kern1.r_sups': ['r.sups'],
    'public.kern1.radical': ['radical'],
    'public.kern1.registered': ['copyright', 'copyrightsound', 'registered',
            'uni2117'],
    'public.kern1.s': ['s', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'public.kern1.s_sinf': ['s.sinf'],
    'public.kern1.s_sups': ['s.sups'],
    'public.kern1.schwa': ['schwa'],
    'public.kern1.section': ['section'],
    'public.kern1.section_lc': ['section.lc'],
    'public.kern1.section_sc': ['section.sc'],
    'public.kern1.semicolon': ['semicolon'],
    'public.kern1.seven': ['seven'],
    'public.kern1.seven_dnom': ['seven.dnom'],
    'public.kern1.seven_lc': ['seven.lc'],
    'public.kern1.seven_numr': ['seven.numr'],
    'public.kern1.seven_sc': ['seven.sc'],
    'public.kern1.seven_sinf': ['seven.sinf'],
    'public.kern1.seven_sups': ['seven.sups'],
    'public.kern1.six': ['six'],
    'public.kern1.six_dnom': ['six.dnom'],
    'public.kern1.six_lc': ['six.lc'],
    'public.kern1.six_numr': ['six.numr'],
    'public.kern1.six_salt': ['six.salt'],
    'public.kern1.six_sc': ['six.sc'],
    'public.kern1.six_sinf': ['six.sinf'],
    'public.kern1.six_sups': ['six.sups'],
    'public.kern1.slash': ['slash'],
    'public.kern1.slash_sc': ['slash.sc'],
    'public.kern1.space': ['space'],
    'public.kern1.space_em': ['space.em'],
    'public.kern1.space_en': ['space.en'],
    'public.kern1.sterling': ['sterling'],
    'public.kern1.sterling_lc': ['sterling.lc'],
    'public.kern1.sterling_sc': ['sterling.sc'],
    'public.kern1.summation': ['summation'],
    'public.kern1.t': ['t', 'tbar', 'tcedilla', 'tcommaaccent'],
    'public.kern1.t_sinf': ['t.sinf'],
    'public.kern1.t_sups': ['t.sups'],
    'public.kern1.tcaron': ['tcaron'],
    'public.kern1.three': ['three'],
    'public.kern1.three_dnom': ['three.dnom'],
    'public.kern1.three_lc': ['three.lc'],
    'public.kern1.three_numr': ['three.numr'],
    'public.kern1.three_sc': ['three.sc'],
    'public.kern1.three_sinf': ['three.sinf'],
    'public.kern1.three_sups': ['three.sups'],
    'public.kern1.threequarters': ['threequarters'],
    'public.kern1.threesuperior': ['threesuperior'],
    'public.kern1.tilde': ['tilde'],
    'public.kern1.trademark': ['trademark'],
    'public.kern1.two': ['two'],
    'public.kern1.two_dnom': ['two.dnom'],
    'public.kern1.two_lc': ['two.lc'],
    'public.kern1.two_numr': ['two.numr'],
    'public.kern1.two_sc': ['two.sc'],
    'public.kern1.two_sinf': ['two.sinf'],
    'public.kern1.two_sups': ['two.sups'],
    'public.kern1.twosuperior': ['twosuperior'],
    'public.kern1.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex',
            'udieresis', 'ugrave', 'umacron', 'uogonek', 'uring', 'utilde'],
    'public.kern1.u_sinf': ['u.sinf'],
    'public.kern1.u_sups': ['u.sups'],
    'public.kern1.uhungarumlaut': ['uhungarumlaut'],
    'public.kern1.underscore': ['underscore'],
    'public.kern1.v': ['v', 'w', 'wacute', 'wcircumflex', 'wdieresis',
            'wgrave'],
    'public.kern1.v_sinf': ['v.sinf'],
    'public.kern1.v_sups': ['v.sups'],
    'public.kern1.w_sinf': ['w.sinf'],
    'public.kern1.w_sups': ['w.sups'],
    'public.kern1.y': ['y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'],
    'public.kern1.y_sinf': ['y.sinf'],
    'public.kern1.y_sups': ['y.sups'],
    'public.kern1.yen': ['yen'],
    'public.kern1.z': ['z', 'zacute', 'zcaron', 'zdotaccent'],
    'public.kern1.z_sinf': ['z.sinf'],
    'public.kern1.z_sups': ['z.sups'],
    'public.kern1.zero': ['zero'],
    'public.kern1.zero_dnom': ['zero.dnom'],
    'public.kern1.zero_lc': ['zero.lc'],
    'public.kern1.zero_lc_salt_slash': ['zero.lc_salt_slash'],
    'public.kern1.zero_numr': ['zero.numr'],
    'public.kern1.zero_salt_slash': ['zero.salt_slash'],
    'public.kern1.zero_sc': ['zero.sc'],
    'public.kern1.zero_sc_salt_slash': ['zero.sc_salt_slash'],
    'public.kern1.zero_sinf': ['zero.sinf'],
    'public.kern1.zero_sups': ['zero.sups'],
    #------------------------------
    #    R I G H T = Left margin
    #------------------------------
    'public.kern2.A': ['A', 'Aacute', 'Abreve', 'Acircumflex', 'Adieresis',
            'Agrave', 'Amacron', 'Aogonek', 'Aring', 'Aringacute', 'Atilde'],
    'public.kern2.AE': ['AE', 'AEacute'],
    'public.kern2.AE_sc': ['AE.sc', 'AEacute.sc'],
    'public.kern2.A_sc': ['A.sc', 'Aacute.sc', 'Abreve.sc', 'Acircumflex.sc',
            'Adieresis.sc', 'Agrave.sc', 'Amacron.sc', 'Aogonek.sc',
            'Aring.sc', 'Aringacute.sc', 'Atilde.sc'],
    'public.kern2.Dcroat': ['Dcroat', 'Eth'],
    'public.kern2.Dcroat_sc': ['Dcroat.sc', 'Eth.sc'],
    'public.kern2.Delta': ['Delta'],
    'public.kern2.Euro': ['Euro'],
    'public.kern2.Euro_lc': ['Euro.lc'],
    'public.kern2.Euro_sc': ['Euro.sc'],
    'public.kern2.H': ['B', 'D', 'Dcaron', 'E', 'Eacute', 'Ebreve', 'Ecaron',
            'Ecircumflex', 'Edieresis', 'Edotaccent', 'Egrave', 'Emacron',
            'Eng', 'Eogonek', 'F', 'H', 'Hcircumflex', 'K', 'Kcommaaccent',
            'L', 'Lcommaaccent', 'Ldot', 'M', 'N', 'Nacute', 'Ncaron',
            'Ncommaaccent', 'Ntilde', 'P', 'R', 'Racute', 'Rcaron',
            'Rcommaaccent', 'Thorn'],
    'public.kern2.H_sc': ['B.sc', 'D.sc', 'Dcaron.sc', 'E.sc', 'Eacute.sc',
            'Ebreve.sc', 'Ecaron.sc', 'Ecircumflex.sc', 'Edieresis.sc',
            'Edotaccent.sc', 'Egrave.sc', 'Emacron.sc', 'Eng.sc', 'Eogonek.sc',
            'F.sc', 'H.sc', 'Hcircumflex.sc', 'K.sc', 'Kcommaaccent.sc',
            'L.sc', 'Lcommaaccent.sc', 'Ldot.sc', 'M.sc', 'N.sc', 'Nacute.sc',
            'Ncaron.sc', 'Ncommaaccent.sc', 'Ntilde.sc', 'P.sc', 'R.sc',
            'Racute.sc', 'Rcaron.sc', 'Rcommaaccent.sc', 'Thorn.sc'],
    'public.kern2.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'public.kern2.I_sc': ['I.sc', 'Iacute.sc'],
    'public.kern2.Ibreve_sc': ['Ibreve.sc'],
    'public.kern2.Icircumflex_sc': ['Icircumflex.sc'],
    'public.kern2.Idieresis_sc': ['Idieresis.sc'],
    'public.kern2.Idotaccent_sc': ['Idotaccent.sc'],
    'public.kern2.Igrave_sc': ['Igrave.sc'],
    'public.kern2.Imacron_sc': ['Imacron.sc'],
    'public.kern2.Iogonek_sc': ['Iogonek.sc'],
    'public.kern2.Itilde_sc': ['Itilde.sc'],
    'public.kern2.J': ['J'],
    'public.kern2.J_sc': ['J.sc'],
    'public.kern2.Jcircumflex': ['Jcircumflex'],
    'public.kern2.Jcircumflex_sc': ['Jcircumflex.sc'],
    'public.kern2.O': ['C', 'Cacute', 'Ccaron', 'Ccedilla', 'Ccircumflex',
            'Cdotaccent', 'G', 'Gbreve', 'Gcaron', 'Gcircumflex',
            'Gcommaaccent', 'Gdotaccent', 'O', 'OE', 'Oacute', 'Obreve',
            'Ocircumflex', 'Odieresis', 'Ograve', 'Ohungarumlaut', 'Omacron',
            'Oslash', 'Oslashacute', 'Otilde', 'Q'],
    'public.kern2.O_sc': ['C.sc', 'Cacute.sc', 'Ccaron.sc', 'Ccedilla.sc',
            'Ccircumflex.sc', 'Cdotaccent.sc', 'G.sc', 'Gbreve.sc',
            'Gcaron.sc', 'Gcircumflex.sc', 'Gcommaaccent.sc', 'Gdotaccent.sc',
            'O.sc', 'OE.sc', 'Oacute.sc', 'Obreve.sc', 'Ocircumflex.sc',
            'Odieresis.sc', 'Ograve.sc', 'Ohungarumlaut.sc', 'Omacron.sc',
            'Oslash.sc', 'Oslashacute.sc', 'Otilde.sc', 'Q.sc'],
    'public.kern2.Omega': ['Omega'],
    'public.kern2.S': ['S', 'Sacute', 'Scaron', 'Scedilla', 'Scircumflex',
            'Scommaaccent'],
    'public.kern2.S_sc': ['S.sc', 'Sacute.sc', 'Scaron.sc', 'Scedilla.sc',
            'Scircumflex.sc', 'Scommaaccent.sc'],
    'public.kern2.T': ['T', 'Tbar', 'Tcaron', 'Tcedilla', 'Tcommaaccent'],
    'public.kern2.T_sc': ['T.sc', 'Tbar.sc', 'Tcaron.sc', 'Tcedilla.sc',
            'Tcommaaccent.sc'],
    'public.kern2.U': ['U', 'Uacute', 'Ubreve', 'Ucircumflex', 'Udieresis',
            'Ugrave', 'Uhungarumlaut', 'Umacron', 'Uogonek', 'Uring',
            'Utilde'],
    'public.kern2.U_sc': ['U.sc', 'Uacute.sc', 'Ubreve.sc', 'Ucircumflex.sc',
            'Udieresis.sc', 'Ugrave.sc', 'Uhungarumlaut.sc', 'Umacron.sc',
            'Uogonek.sc', 'Uring.sc', 'Utilde.sc'],
    'public.kern2.V': ['V'],
    'public.kern2.V_sc': ['V.sc'],
    'public.kern2.W': ['W', 'Wacute', 'Wcircumflex', 'Wdieresis', 'Wgrave'],
    'public.kern2.W_sc': ['W.sc', 'Wacute.sc', 'Wcircumflex.sc',
            'Wdieresis.sc', 'Wgrave.sc'],
    'public.kern2.X': ['X'],
    'public.kern2.X_sc': ['X.sc'],
    'public.kern2.Y': ['Y', 'Yacute', 'Ycircumflex', 'Ydieresis', 'Ygrave'],
    'public.kern2.Y_sc': ['Y.sc', 'Yacute.sc', 'Ycircumflex.sc',
            'Ydieresis.sc', 'Ygrave.sc'],
    'public.kern2.Z': ['Z', 'Zacute', 'Zcaron', 'Zdotaccent'],
    'public.kern2.Z_sc': ['Z.sc', 'Zacute.sc', 'Zcaron.sc', 'Zdotaccent.sc'],
    'public.kern2.a': ['a', 'aacute', 'abreve', 'acircumflex', 'adieresis',
            'ae', 'aeacute', 'agrave', 'amacron', 'aogonek', 'aring',
            'aringacute', 'atilde'],
    'public.kern2.a_sinf': ['a.sinf'],
    'public.kern2.a_sups': ['a.sups'],
    'public.kern2.ampersand': ['ampersand'],
    'public.kern2.ampersand_sc': ['ampersand.sc'],
    'public.kern2.apple': ['apple'],
    'public.kern2.approxequal': ['approxequal'],
    'public.kern2.approxequal_lc': ['approxequal.lc'],
    'public.kern2.ascii': ['asciitilde'],
    'public.kern2.asciicircum': ['asciicircum'],
    'public.kern2.asterisk': ['asterisk'],
    'public.kern2.at': ['at'],
    'public.kern2.back': ['backslash'],
    'public.kern2.back_sc': ['backslash.sc'],
    'public.kern2.bar': ['bar', 'brokenbar'],
    'public.kern2.braceleft': ['braceleft'],
    'public.kern2.braceleft_sc': ['braceleft.sc'],
    'public.kern2.braceleft_uc': ['braceleft.uc'],
    'public.kern2.braceright': ['braceright'],
    'public.kern2.braceright_sc': ['braceright.sc'],
    'public.kern2.braceright_uc': ['braceright.uc'],
    'public.kern2.bracketleft': ['bracketleft'],
    'public.kern2.bracketleft_sc': ['bracketleft.sc'],
    'public.kern2.bracketleft_uc': ['bracketleft.uc'],
    'public.kern2.bracketright': ['bracketright'],
    'public.kern2.bracketright_sc': ['bracketright.sc'],
    'public.kern2.bracketright_uc': ['bracketright.uc'],
    'public.kern2.bullet': ['bullet'],
    'public.kern2.bullet_uc': ['bullet.uc'],
    'public.kern2.cent': ['cent'],
    'public.kern2.cent_AT_weight800': ['cent_AT_weight800'],
    'public.kern2.cent_lc': ['cent.lc'],
    'public.kern2.cent_lc_AT_weight800': ['cent.lc_AT_weight800'],
    'public.kern2.cent_sc': ['cent.sc'],
    'public.kern2.cent_sc_AT_weight800': ['cent.sc_AT_weight800'],
    'public.kern2.checkmark': ['checkmark'],
    'public.kern2.circumflex': ['circumflex'],
    'public.kern2.comma': ['comma', 'quotedblbase', 'quotesinglbase'],
    'public.kern2.currency': ['currency'],
    'public.kern2.dagger': ['dagger'],
    'public.kern2.daggerdbl': ['daggerdbl'],
    'public.kern2.degree': ['degree'],
    'public.kern2.degree_lc': ['degree.lc'],
    'public.kern2.degree_sc': ['degree.sc'],
    'public.kern2.divide': ['divide'],
    'public.kern2.dollar': ['dollar', 'dollar_AT_weight800'],
    'public.kern2.dollar_lc': ['dollar.lc', 'dollar.lc_AT_weight800'],
    'public.kern2.dollar_sc': ['dollar.sc', 'dollar.sc_AT_weight800'],
    'public.kern2.dotaccent': ['dotaccent'],
    'public.kern2.dotlessi': ['dotlessi'],
    'public.kern2.dotlessj': ['dotlessj'],
    'public.kern2.eight_dnom': ['eight.dnom'],
    'public.kern2.eight_lc': ['eight.lc'],
    'public.kern2.eight_numr': ['eight.numr'],
    'public.kern2.eight_sc': ['eight.sc'],
    'public.kern2.eight_sinf': ['eight.sinf'],
    'public.kern2.eight_sups': ['eight.sups'],
    'public.kern2.equal': ['equal'],
    'public.kern2.equal_lc': ['equal.lc'],
    'public.kern2.exclam': ['exclam'],
    'public.kern2.exclam_sc': ['exclam.sc'],
    'public.kern2.exclamdown': ['exclamdown'],
    'public.kern2.exclamdown_uc': ['exclamdown.uc'],
    'public.kern2.f': ['f', 'f.salt_connect', 'f.salt_noconnect'],
    'public.kern2.f_sinf': ['f.sinf'],
    'public.kern2.f_sups': ['f.sups'],
    'public.kern2.five': ['five'],
    'public.kern2.five_dnom': ['five.dnom'],
    'public.kern2.five_lc': ['five.lc'],
    'public.kern2.five_numr': ['five.numr'],
    'public.kern2.five_sc': ['five.sc'],
    'public.kern2.five_sinf': ['five.sinf'],
    'public.kern2.five_sups': ['five.sups'],
    'public.kern2.florin': ['florin'],
    'public.kern2.florin_lc': ['florin.lc'],
    'public.kern2.florin_sc': ['florin.sc'],
    'public.kern2.four': ['four'],
    'public.kern2.four_dnom': ['four.dnom'],
    'public.kern2.four_lc': ['four.lc'],
    'public.kern2.four_numr': ['four.numr'],
    'public.kern2.four_sc': ['four.sc'],
    'public.kern2.four_sinf': ['four.sinf'],
    'public.kern2.four_sups': ['four.sups'],
    'public.kern2.fraction': ['fraction'],
    'public.kern2.g': ['g', 'gbreve', 'gcaron', 'gcircumflex', 'gcommaaccent',
            'gdotaccent'],
    'public.kern2.g_salt': ['g.salt', 'gbreve.salt', 'gcaron.salt',
            'gcircumflex.salt', 'gcommaaccent.salt', 'gdotaccent.salt'],
    'public.kern2.germandbls': ['germandbls'],
    'public.kern2.greater': ['greater'],
    'public.kern2.greater_lc': ['greater.lc'],
    'public.kern2.greaterequal': ['greaterequal'],
    'public.kern2.greaterequal_lc': ['greaterequal.lc'],
    'public.kern2.guillemotleft': ['guillemotleft', 'guilsinglleft'],
    'public.kern2.guillemotleft_uc': ['guillemotleft.uc', 'guilsinglleft.uc'],
    'public.kern2.guillemotright': ['guillemotright', 'guilsinglright'],
    'public.kern2.guillemotright_uc': ['guillemotright.uc',
            'guilsinglright.uc'],
    'public.kern2.h': ['b', 'h', 'hcircumflex', 'k', 'kcommaaccent', 'l',
            'lcaron', 'ldot', 'thorn'],
    'public.kern2.h_sinf': ['b.sinf', 'h.sinf', 'k.sinf', 'l.sinf'],
    'public.kern2.h_sups': ['b.sups', 'h.sups', 'k.sups', 'l.sups'],
    'public.kern2.hbar': ['hbar'],
    'public.kern2.horizontal': ['horizontalbar'],
    'public.kern2.hungarumlaut': ['hungarumlaut'],
    'public.kern2.hungarumlautcmb': ['hungarumlautcmb'],
    'public.kern2.hyphen': ['emdash', 'endash', 'hyphen', 'sfthyphen'],
    'public.kern2.hyphen_uc': ['emdash.uc', 'endash.uc', 'hyphen.uc'],
    'public.kern2.i': ['i', 'idotaccent'],
    'public.kern2.i_sinf': ['i.sinf'],
    'public.kern2.i_sups': ['i.sups'],
    'public.kern2.iacute': ['iacute'],
    'public.kern2.ibreve': ['ibreve'],
    'public.kern2.icircumflex': ['icircumflex'],
    'public.kern2.idieresis': ['idieresis'],
    'public.kern2.igrave': ['igrave'],
    'public.kern2.imacron': ['imacron'],
    'public.kern2.infinity': ['infinity'],
    'public.kern2.integral': ['integral'],
    'public.kern2.iogonek': ['iogonek'],
    'public.kern2.itilde': ['itilde'],
    'public.kern2.j': ['j'],
    'public.kern2.j_sinf': ['j.sinf'],
    'public.kern2.j_sups': ['j.sups'],
    'public.kern2.jcircumflex': ['jcircumflex'],
    'public.kern2.lacute': ['lacute'],
    'public.kern2.lcommaaccent': ['lcommaaccent'],
    'public.kern2.less': ['less', 'less.lc', 'lessequal', 'lessequal.lc'],
    'public.kern2.logicalnot': ['logicalnot'],
    'public.kern2.lozenge': ['lozenge'],
    'public.kern2.lslash': ['lslash'],
    'public.kern2.m_sinf': ['m.sinf', 'n.sinf', 'p.sinf', 'r.sinf'],
    'public.kern2.m_sups': ['m.sups', 'n.sups', 'p.sups', 'r.sups'],
    'public.kern2.macron': ['macron'],
    'public.kern2.minus': ['minus.lc'],
    'public.kern2.multiply': ['multiply', 'multiply.lc'],
    'public.kern2.n': ['eng', 'm', 'n', 'nacute', 'ncaron', 'ncommaaccent',
            'ntilde', 'p', 'r', 'racute', 'rcaron', 'rcommaaccent'],
    'public.kern2.nine': ['nine'],
    'public.kern2.nine_dnom': ['nine.dnom'],
    'public.kern2.nine_lc': ['nine.lc'],
    'public.kern2.nine_numr': ['nine.numr'],
    'public.kern2.nine_salt': ['nine.salt'],
    'public.kern2.nine_sc': ['nine.sc'],
    'public.kern2.nine_sinf': ['nine.sinf'],
    'public.kern2.nine_sups': ['nine.sups'],
    'public.kern2.notequal': ['notequal'],
    'public.kern2.notequal_lc': ['notequal.lc'],
    'public.kern2.numbersign': ['numbersign'],
    'public.kern2.numbersign_sc': ['numbersign.sc'],
    'public.kern2.o': ['c', 'cacute', 'ccaron', 'ccedilla', 'ccircumflex',
            'cdotaccent', 'd', 'dcaron', 'dcroat', 'e', 'eacute', 'ebreve',
            'ecaron', 'ecircumflex', 'edieresis', 'edotaccent', 'egrave',
            'emacron', 'eogonek', 'eth', 'o', 'oacute', 'obreve',
            'ocircumflex', 'odieresis', 'oe', 'ograve', 'ohungarumlaut',
            'omacron', 'oslash', 'oslashacute', 'otilde', 'q'],
    'public.kern2.o_sinf': ['c.sinf', 'd.sinf', 'e.sinf', 'egrave.sinf',
            'g.sinf', 'o.sinf', 'q.sinf'],
    'public.kern2.o_sups': ['c.sups', 'd.sups', 'e.sups', 'egrave.sups',
            'g.sups', 'o.sups', 'q.sups'],
    'public.kern2.ogonek': ['ogonek'],
    'public.kern2.one': ['one'],
    'public.kern2.one_dnom': ['one.dnom'],
    'public.kern2.one_lc': ['one.lc'],
    'public.kern2.one_numr': ['one.numr'],
    'public.kern2.one_sc': ['one.sc'],
    'public.kern2.one_sinf': ['one.sinf'],
    'public.kern2.one_sups': ['one.sups'],
    'public.kern2.onehalf': ['onehalf'],
    'public.kern2.onequarter': ['onequarter'],
    'public.kern2.onesuperior': ['onesuperior'],
    'public.kern2.ordfeminine': ['ordfeminine'],
    'public.kern2.ordmasculine': ['ordmasculine'],
    'public.kern2.paragraph': ['paragraph'],
    'public.kern2.paragraph_lc': ['paragraph.lc'],
    'public.kern2.parenleft': ['parenleft'],
    'public.kern2.parenleft_sc': ['parenleft.sc'],
    'public.kern2.parenleft_uc': ['parenleft.uc'],
    'public.kern2.parenright': ['parenright'],
    'public.kern2.parenright_sc': ['parenright.sc'],
    'public.kern2.parenright_uc': ['parenright.uc'],
    'public.kern2.partialdiff': ['partialdiff'],
    'public.kern2.percent': ['percent', 'perthousand'],
    'public.kern2.percent_lc': ['percent.lc', 'perthousand.lc'],
    'public.kern2.period': ['ellipsis', 'period'],
    'public.kern2.periodcentered': ['periodcentered'],
    'public.kern2.periodcentered_uc': ['periodcentered.uc'],
    'public.kern2.pi': ['pi'],
    'public.kern2.plus': ['plus'],
    'public.kern2.plus_lc': ['plus.lc'],
    'public.kern2.plusminus': ['plusminus'],
    'public.kern2.plusminus_lc': ['plusminus.lc'],
    'public.kern2.product': ['product'],
    'public.kern2.question': ['question'],
    'public.kern2.question_sc': ['question.sc'],
    'public.kern2.questiondown': ['questiondown'],
    'public.kern2.questiondown_uc': ['questiondown.uc'],
    'public.kern2.quote': ['minute', 'quotedbl', 'quotesingle', 'second'],
    'public.kern2.quoteleft': ['quotedblleft', 'quoteleft'],
    'public.kern2.quoteright': ['quotedblright', 'quoteright'],
    'public.kern2.radical': ['radical'],
    'public.kern2.registered': ['copyright', 'copyrightsound', 'registered',
            'uni2117'],
    'public.kern2.s': ['s', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'public.kern2.s_sinf': ['s.sinf'],
    'public.kern2.s_sups': ['s.sups'],
    'public.kern2.schwa': ['schwa'],
    'public.kern2.section': ['section'],
    'public.kern2.section_lc': ['section.lc'],
    'public.kern2.section_sc': ['section.sc'],
    'public.kern2.semicolon': ['semicolon'],
    'public.kern2.seven': ['seven'],
    'public.kern2.seven_dnom': ['seven.dnom'],
    'public.kern2.seven_lc': ['seven.lc'],
    'public.kern2.seven_numr': ['seven.numr'],
    'public.kern2.seven_sc': ['seven.sc'],
    'public.kern2.seven_sinf': ['seven.sinf'],
    'public.kern2.seven_sups': ['seven.sups'],
    'public.kern2.six': ['six'],
    'public.kern2.six_dnom': ['six.dnom'],
    'public.kern2.six_lc': ['six.lc'],
    'public.kern2.six_numr': ['six.numr'],
    'public.kern2.six_salt': ['six.salt'],
    'public.kern2.six_sc': ['six.sc'],
    'public.kern2.six_sinf': ['six.sinf'],
    'public.kern2.six_sups': ['six.sups'],
    'public.kern2.slash': ['slash'],
    'public.kern2.slash_sc': ['slash.sc'],
    'public.kern2.space': ['space'],
    'public.kern2.space_em': ['space.em'],
    'public.kern2.space_en': ['space.en'],
    'public.kern2.space_frac': ['space.frac'],
    'public.kern2.space_thin': ['space.thin'],
    'public.kern2.sterling': ['sterling'],
    'public.kern2.sterling_lc': ['sterling.lc'],
    'public.kern2.sterling_sc': ['sterling.sc'],
    'public.kern2.summation': ['summation'],
    'public.kern2.t': ['t', 'tbar', 'tcaron', 'tcedilla', 'tcommaaccent'],
    'public.kern2.t_sinf': ['t.sinf'],
    'public.kern2.t_sups': ['t.sups'],
    'public.kern2.three': ['three'],
    'public.kern2.three_dnom': ['three.dnom'],
    'public.kern2.three_lc': ['three.lc'],
    'public.kern2.three_numr': ['three.numr'],
    'public.kern2.three_sc': ['three.sc'],
    'public.kern2.three_sinf': ['three.sinf'],
    'public.kern2.three_sups': ['three.sups'],
    'public.kern2.threequarters': ['threequarters'],
    'public.kern2.threesuperior': ['threesuperior'],
    'public.kern2.trademark': ['trademark'],
    'public.kern2.two': ['two'],
    'public.kern2.two_dnom': ['two.dnom'],
    'public.kern2.two_lc': ['two.lc'],
    'public.kern2.two_numr': ['two.numr'],
    'public.kern2.two_sc': ['two.sc'],
    'public.kern2.two_sinf': ['two.sinf'],
    'public.kern2.two_sups': ['two.sups'],
    'public.kern2.twosuperior': ['twosuperior'],
    'public.kern2.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex',
            'udieresis', 'ugrave', 'uhungarumlaut', 'umacron', 'uogonek',
            'uring', 'utilde'],
    'public.kern2.u_sinf': ['u.sinf'],
    'public.kern2.u_sups': ['u.sups'],
    'public.kern2.underscore': ['underscore'],
    'public.kern2.v': ['v', 'w', 'wacute', 'wcircumflex', 'wdieresis',
            'wgrave'],
    'public.kern2.v_sinf': ['v.sinf', 'w.sinf'],
    'public.kern2.v_sups': ['v.sups', 'w.sups'],
    'public.kern2.x': ['x'],
    'public.kern2.x_sinf': ['x.sinf'],
    'public.kern2.x_sups': ['x.sups'],
    'public.kern2.y': ['y', 'yacute', 'ycircumflex', 'ydieresis', 'ygrave'],
    'public.kern2.y_sinf': ['y.sinf'],
    'public.kern2.y_sups': ['y.sups'],
    'public.kern2.yen': ['yen'],
    'public.kern2.z': ['z', 'zacute', 'zcaron', 'zdotaccent'],
    'public.kern2.z_sinf': ['z.sinf'],
    'public.kern2.z_sups': ['z.sups'],
    'public.kern2.zero': ['zero'],
    'public.kern2.zero_dnom': ['zero.dnom'],
    'public.kern2.zero_lc': ['zero.lc'],
    'public.kern2.zero_lc_salt_slash': ['zero.lc_salt_slash'],
    'public.kern2.zero_numr': ['zero.numr'],
    'public.kern2.zero_salt_slash': ['zero.salt_slash'],
    'public.kern2.zero_sc': ['zero.sc'],
    'public.kern2.zero_sc_salt_slash': ['zero.sc_salt_slash'],
    'public.kern2.zero_sinf': ['zero.sinf'],
    'public.kern2.zero_sups': ['zero.sups'],
    'TC1.Euro': ['Euro', 'Euro.lc', 'Euro.sc'],
    'TC1.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'TC1.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
            'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
            'Iogonek.sc', 'Itilde.sc'],
    'TC1.J': ['J', 'Jcircumflex'],
    'TC1.J_sc': ['J.sc', 'Jcircumflex.sc'],
    'TC1.a_sinf': ['a.sinf', 'a.sups'],
    'TC1.back': ['backslash', 'backslash.sc'],
    'TC1.braceleft': ['braceleft', 'braceleft.sc', 'braceleft.uc'],
    'TC1.braceright': ['braceright', 'braceright.sc', 'braceright.uc'],
    'TC1.bracketleft': ['bracketleft', 'bracketleft.sc', 'bracketleft.uc'],
    'TC1.bracketright': ['bracketright', 'bracketright.sc', 'bracketright.uc'],
    'TC1.bullet': ['bullet', 'bullet.uc'],
    'TC1.c_sinf': ['c.sinf', 'c.sups'],
    'TC1.cent': ['cent', 'cent.lc', 'cent.lc_AT_weight800', 'cent.sc',
            'cent.sc_AT_weight800', 'cent_AT_weight800'],
    'TC1.comma': ['comma', 'quotedblbase', 'quotedblright', 'quoteright',
            'quotesinglbase', 'semicolon'],
    'TC1.degree': ['degree', 'degree.lc', 'degree.sc'],
    'TC1.e_sinf': ['e.sinf', 'e.sups', 'egrave.sinf', 'egrave.sups'],
    'TC1.eight_dnom': ['eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups'],
    'TC1.equal': ['approxequal', 'approxequal.lc', 'equal', 'equal.lc'],
    'TC1.exclam': ['exclam', 'exclam.sc'],
    'TC1.exclamdown': ['exclamdown', 'exclamdown.uc'],
    'TC1.f_sinf': ['f.sinf', 'f.sups'],
    'TC1.five_dnom': ['five.dnom', 'five.numr', 'five.sinf', 'five.sups'],
    'TC1.florin': ['florin', 'florin.lc', 'florin.sc'],
    'TC1.four_dnom': ['four.dnom', 'four.numr', 'four.sinf', 'four.sups',
            'onequarter', 'threequarters'],
    'TC1.g_sinf': ['g.sinf', 'g.sups'],
    'TC1.hyphen': ['emdash', 'emdash.uc', 'endash', 'endash.uc', 'hyphen',
            'hyphen.uc', 'sfthyphen'],
    'TC1.i': ['dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis',
            'idotaccent', 'igrave', 'imacron', 'iogonek', 'itilde'],
    'TC1.i_sinf': ['i.sinf', 'i.sups'],
    'TC1.j': ['dotlessj', 'j', 'jcircumflex'],
    'TC1.j_sinf': ['j.sinf', 'j.sups'],
    'TC1.k_sinf': ['k.sinf', 'k.sups', 'x.sinf', 'x.sups'],
    'TC1.l_sinf': ['d.sups', 'l.sinf'],
    'TC1.minus': ['minus', 'minus.lc'],
    'TC1.multiply': ['multiply', 'multiply.lc'],
    'TC1.n_sinf': ['h.sinf', 'h.sups', 'm.sinf', 'm.sups', 'n.sinf', 'n.sups'],
    'TC1.nine': ['nine', 'nine.salt'],
    'TC1.nine_dnom': ['nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'],
    'TC1.notequal': ['notequal', 'notequal.lc'],
    'TC1.numbersign': ['numbersign', 'numbersign.sc'],
    'TC1.o_sinf': ['b.sinf', 'b.sups', 'o.sinf', 'o.sups', 'p.sinf', 'p.sups'],
    'TC1.one_dnom': ['one.dnom', 'one.numr', 'one.sinf', 'one.sups',
            'onesuperior'],
    'TC1.parenleft': ['parenleft', 'parenleft.sc', 'parenleft.uc'],
    'TC1.parenright': ['parenright', 'parenright.sc', 'parenright.uc'],
    'TC1.period': ['colon', 'ellipsis', 'period', 'periodcentered',
            'periodcentered.uc'],
    'TC1.plus': ['plus', 'plus.lc', 'plusminus', 'plusminus.lc'],
    'TC1.q_sinf': ['q.sinf', 'q.sups'],
    'TC1.question': ['question', 'question.sc'],
    'TC1.questiondown': ['questiondown', 'questiondown.uc'],
    'TC1.r_sinf': ['r.sinf', 'r.sups'],
    'TC1.s': ['germandbls', 's', 'sacute', 'scaron', 'scedilla', 'scircumflex',
            'scommaaccent'],
    'TC1.s_sinf': ['s.sinf', 's.sups'],
    'TC1.section': ['section', 'section.lc', 'section.sc'],
    'TC1.seven_dnom': ['seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups'],
    'TC1.six': ['six', 'six.salt'],
    'TC1.six_dnom': ['six.dnom', 'six.numr', 'six.sinf', 'six.sups'],
    'TC1.slash': ['slash', 'slash.sc'],
    'TC1.sterling': ['sterling', 'sterling.lc', 'sterling.sc'],
    'TC1.t_sinf': ['t.sinf', 't.sups'],
    'TC1.three_dnom': ['three.dnom', 'three.numr', 'three.sinf', 'three.sups',
            'threesuperior'],
    'TC1.two_dnom': ['onehalf', 'two.dnom', 'two.numr', 'two.sinf', 'two.sups',
            'twosuperior'],
    'TC1.u': ['mu', 'u', 'uacute', 'ubreve', 'ucircumflex', 'udieresis',
            'ugrave', 'uhungarumlaut', 'umacron', 'uogonek', 'uring',
            'utilde'],
    'TC1.u_sinf': ['u.sinf', 'u.sups'],
    'TC1.v_sinf': ['v.sinf', 'v.sups', 'w.sinf', 'w.sups', 'y.sinf', 'y.sups'],
    'TC1.z_sinf': ['z.sinf', 'z.sups'],
    'TC1.zero': ['zero', 'zero.salt_slash'],
    'TC1.zero_dnom': ['percent', 'percent.lc', 'perthousand', 'perthousand.lc',
            'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups'],
    'TC1.zero_lc': ['zero.lc', 'zero.lc_salt_slash'],
    'TC1.zero_sc': ['zero.sc', 'zero.sc_salt_slash'],
    'TC2.Euro': ['Euro', 'Euro.lc', 'Euro.sc'],
    'TC2.I': ['I', 'Iacute', 'Ibreve', 'Icircumflex', 'Idieresis',
            'Idotaccent', 'Igrave', 'Imacron', 'Iogonek', 'Itilde'],
    'TC2.I_sc': ['I.sc', 'Iacute.sc', 'Ibreve.sc', 'Icircumflex.sc',
            'Idieresis.sc', 'Idotaccent.sc', 'Igrave.sc', 'Imacron.sc',
            'Iogonek.sc', 'Itilde.sc'],
    'TC2.J': ['J', 'Jcircumflex'],
    'TC2.J_sc': ['J.sc', 'Jcircumflex.sc'],
    'TC2.a_sinf': ['a.sinf', 'a.sups'],
    'TC2.back': ['backslash', 'backslash.sc'],
    'TC2.braceleft': ['braceleft', 'braceleft.sc', 'braceleft.uc'],
    'TC2.braceright': ['braceright', 'braceright.sc', 'braceright.uc'],
    'TC2.bracketleft': ['bracketleft', 'bracketleft.sc', 'bracketleft.uc'],
    'TC2.bracketright': ['bracketright', 'bracketright.sc', 'bracketright.uc'],
    'TC2.bullet': ['bullet', 'bullet.uc'],
    'TC2.cent': ['cent', 'cent.lc', 'cent.lc_AT_weight800', 'cent.sc',
            'cent.sc_AT_weight800', 'cent_AT_weight800'],
    'TC2.comma': ['comma', 'quotedblbase', 'quotedblright', 'quoteright',
            'quotesinglbase', 'semicolon'],
    'TC2.degree': ['degree', 'degree.lc', 'degree.sc'],
    'TC2.eight_sinf': ['eight.dnom', 'eight.numr', 'eight.sinf', 'eight.sups'],
    'TC2.equal': ['approxequal', 'approxequal.lc', 'equal', 'equal.lc'],
    'TC2.exclam': ['exclam', 'exclam.sc'],
    'TC2.exclamdown': ['exclamdown', 'exclamdown.uc'],
    'TC2.f_sinf': ['f.sinf', 'f.sups'],
    'TC2.five_sinf': ['five.dnom', 'five.numr', 'five.sinf', 'five.sups'],
    'TC2.florin': ['florin', 'florin.lc', 'florin.sc'],
    'TC2.four_sinf': ['four.dnom', 'four.numr', 'four.sinf', 'four.sups'],
    'TC2.greater': ['greater', 'greater.lc', 'greaterequal',
            'greaterequal.lc'],
    'TC2.guillemotleft': ['guillemotleft', 'guillemotleft.uc', 'guilsinglleft',
            'guilsinglleft.uc'],
    'TC2.guillemotright': ['guillemotright', 'guillemotright.uc',
            'guilsinglright', 'guilsinglright.uc'],
    'TC2.h_sinf': ['b.sinf', 'b.sups', 'h.sinf', 'h.sups', 'k.sinf', 'k.sups',
            'l.sinf', 'l.sups'],
    'TC2.hyphen': ['emdash', 'emdash.uc', 'endash', 'endash.uc', 'hyphen',
            'hyphen.uc', 'sfthyphen'],
    'TC2.i': ['dotlessi', 'i', 'iacute', 'ibreve', 'icircumflex', 'idieresis',
            'idotaccent', 'igrave', 'imacron', 'iogonek', 'itilde'],
    'TC2.i_sinf': ['i.sinf', 'i.sups'],
    'TC2.j': ['dotlessj', 'j', 'jcircumflex'],
    'TC2.j_sinf': ['j.sinf', 'j.sups'],
    'TC2.l': ['b', 'h', 'hbar', 'hcircumflex', 'k', 'kcommaaccent', 'l',
            'lcommaaccent', 'thorn'],
    'TC2.m_sinf': ['m.sinf', 'm.sups', 'n.sinf', 'n.sups', 'p.sinf', 'p.sups',
            'r.sinf', 'r.sups'],
    'TC2.minus': ['minus', 'minus.lc'],
    'TC2.nine': ['nine', 'nine.salt'],
    'TC2.nine_sinf': ['nine.dnom', 'nine.numr', 'nine.sinf', 'nine.sups'],
    'TC2.notequal': ['notequal', 'notequal.lc'],
    'TC2.numbersign': ['numbersign', 'numbersign.sc'],
    'TC2.o_sinf': ['c.sinf', 'c.sups', 'd.sinf', 'd.sups', 'e.sinf', 'e.sups',
            'egrave.sinf', 'egrave.sups', 'g.sinf', 'g.sups', 'o.sinf',
            'o.sups', 'q.sinf', 'q.sups'],
    'TC2.one_sinf': ['one.dnom', 'one.numr', 'one.sinf', 'one.sups', 'onehalf',
            'onequarter', 'onesuperior'],
    'TC2.parenleft': ['parenleft', 'parenleft.sc', 'parenleft.uc'],
    'TC2.parenright': ['parenright', 'parenright.sc', 'parenright.uc'],
    'TC2.period': ['colon', 'ellipsis', 'period', 'periodcentered',
            'periodcentered.uc'],
    'TC2.plus': ['plus', 'plus.lc', 'plusminus', 'plusminus.lc'],
    'TC2.question': ['question', 'question.sc'],
    'TC2.questiondown': ['questiondown', 'questiondown.uc'],
    'TC2.s_sinf': ['s.sinf', 's.sups'],
    'TC2.section': ['section', 'section.lc', 'section.sc'],
    'TC2.seven_sinf': ['seven.dnom', 'seven.numr', 'seven.sinf', 'seven.sups'],
    'TC2.six': ['six', 'six.salt'],
    'TC2.six_sinf': ['six.dnom', 'six.numr', 'six.sinf', 'six.sups'],
    'TC2.slash': ['slash', 'slash.sc'],
    'TC2.sterling': ['sterling', 'sterling.lc', 'sterling.sc'],
    'TC2.t_sinf': ['t.sinf', 't.sups'],
    'TC2.three_sinf': ['three.dnom', 'three.numr', 'three.sinf', 'three.sups',
            'threequarters', 'threesuperior'],
    'TC2.two_sinf': ['two.dnom', 'two.numr', 'two.sinf', 'two.sups',
            'twosuperior'],
    'TC2.u_sinf': ['u.sinf', 'u.sups'],
    'TC2.v_sinf': ['v.sinf', 'v.sups', 'w.sinf', 'w.sups'],
    'TC2.x_sinf': ['x.sinf', 'x.sups'],
    'TC2.z_sinf': ['z.sinf', 'z.sups'],
    'TC2.zero': ['zero', 'zero.salt_slash'],
    'TC2.zero_lc': ['zero.lc', 'zero.lc_salt_slash'],
    'TC2.zero_sc': ['zero.sc', 'zero.sc_salt_slash'],
    'TC2.zero_sinf': ['percent', 'percent.lc', 'perthousand', 'perthousand.lc',
            'zero.dnom', 'zero.numr', 'zero.sinf', 'zero.sups'],

}
