# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#     Copyright (c) 2014+ Type Network
#
#     T N  B I T S
#     No distribution without permission.
#
# -----------------------------------------------------------------------------
#
#    landingpattern.py
#

# For Flight paths see CodePages.

DEFAULT_FLIGHTPATH = 'Latin 1' # Default flight path if not defined in the font
LIBKEY_FLIGHTPATH = 'FlightPath' # Font.lib tool key for storing the flight path

# Identifiers (lowercase, no spaces).

LANDINGPATTERN_DEFAULT = 'default'
LANDINGPATTERN_DESKTOP = 'desktop'
LANDINGPATTERN_DESKTOPTTF = 'desktop_ttf'
LANDINGPATTERN_WEB = 'web' # TTF+OTF+WOFF
LANDINGPATTERN_WEBOTF = 'web_otf'
LANDINGPATTERN_WEBSNAPSHOT = 'web_snapshot'
LANDINGPATTERN_APP = 'app'
LANDINGPATTERN_CIDKEYEDOTF = 'cid_keyed_otf'

# Pretty names.

LANDINGPATTERNNAME_DEFAULT = 'Default'
LANDINGPATTERNNAME_DESKTOP = 'Desktop'
LANDINGPATTERNNAME_DESKTOPTTF = 'Desktop TrueType'
LANDINGPATTERNNAME_WEB = 'Web' # TTF+OTF+WOFF
LANDINGPATTERNNAME_WEBOTF = 'Web OpenType'
LANDINGPATTERNNAME_WEBSNAPSHOT = 'Web Snapshot'
LANDINGPATTERNNAME_APP = 'App'
LANDINGPATTERNNAME_CIDKEYEDOTF = 'CID Keyed OpenType'

# Active set.

LANDINGPATTERNS = (
    LANDINGPATTERN_DESKTOP, LANDINGPATTERN_DESKTOPTTF,
    LANDINGPATTERN_WEB, LANDINGPATTERN_WEBOTF,
    LANDINGPATTERN_WEBSNAPSHOT,
    LANDINGPATTERN_CIDKEYEDOTF,
    LANDINGPATTERN_APP
)

# Mapping.

LANDINGPATTERN_NAMES = {
    LANDINGPATTERN_DEFAULT: LANDINGPATTERNNAME_DEFAULT,
    LANDINGPATTERN_DESKTOP: LANDINGPATTERNNAME_DESKTOP,
    LANDINGPATTERN_DESKTOPTTF: LANDINGPATTERNNAME_DESKTOPTTF,
    LANDINGPATTERN_WEB: LANDINGPATTERNNAME_WEB,
    LANDINGPATTERN_WEBOTF: LANDINGPATTERNNAME_WEBOTF,
    LANDINGPATTERN_WEBSNAPSHOT: LANDINGPATTERNNAME_WEBSNAPSHOT,
    LANDINGPATTERN_CIDKEYEDOTF: LANDINGPATTERNNAME_CIDKEYEDOTF,
    LANDINGPATTERN_APP: LANDINGPATTERNNAME_APP,
}

PATHDIRECTION_CLOCK = 'CW' #
PATHDIRECTION_COUNTERCLOCK = 'CCW'

HINTING_FDKAUTOHINT = 'FDK Autohint'

FONTINFO_TYPE_DESKTOP = 'Desktop'
FONTINFO_TYPE_WEB = 'Web'
FONTINFO_TYPE_APP = 'App'
FONTINFO_TYPE_DEFAULT = 'Default'
FONTINFO_TYPE_ROBOFONTDEFAULTS = 'RoboFont Defaults'

