# TODO tcommaaccent might not be the same bottom anchor as cedilla...
# TODO GREEK should dieresistonos be dieresis_tonos ? Seems like a special case with a unicode U+0385 and a combining one U+0344
# TODO CYRILLIC dotlessi ? dotlessiukrcyr ?
# TODO slash
#'Lslash': '',
#'lslash': '',
#'Oslash': '',
#'oslash': '',
# TODO special dot
#'Ldot': '',
#'ldot': '',
# TODO ?
#'napostrophe': '',

INSTRUCTIONS = {
'Aacute': 'A+acutecmb@top',
'aacute': 'a+acutecmb@top',
'Abreve': 'A+brevecmb@top',
'abreve': 'a+brevecmb@top',
'Abreveacute': 'A+brevecmb_acutecmb@top',
'abreveacute': 'a+brevecmb_acutecmb@top',
'Abrevedotbelow': 'A+brevecmb@top+dotbelowcmb@bottom',
'abrevedotbelow': 'a+brevecmb@top+dotbelowcmb@bottom',
'Abrevegrave': 'A+brevecmb_gravecmb@top',
'abrevegrave': 'a+brevecmb_gravecmb@top',
'Abrevehoi': 'A+brevecmb_hoicmb@top',
'abrevehoi': 'a+brevecmb_hoicmb@top',
'Abrevetilde': 'A+brevecmb_tildecmb@top',
'abrevetilde': 'a+brevecmb_tildecmb@top',
'Acircumflex': 'A+circumflexcmb@top',
'acircumflex': 'a+circumflexcmb@top',
'Acircumflexacute': 'A+circumflexcmb_acutecmb@top',
'acircumflexacute': 'a+circumflexcmb_acutecmb@top',
'Acircumflexdotbelow': 'A+circumflexcmb@top+dotbelowcmb@bottom',
'acircumflexdotbelow': 'a+circumflexcmb@top+dotbelowcmb@bottom',
'Acircumflexgrave': 'A+circumflexcmb_gravecmb@top',
'acircumflexgrave': 'a+circumflexcmb_gravecmb@top',
'Acircumflexhoi': 'A+circumflexcmb_hoicmb@top',
'acircumflexhoi': 'a+circumflexcmb_hoicmb@top',
'Acircumflextilde': 'A+circumflexcmb_tildecmb@top',
'acircumflextilde': 'a+circumflexcmb_tildecmb@top',
'Adieresis': 'A+dieresiscmb@top',
'adieresis': 'a+dieresiscmb@top',
'Adotbelow': 'A+dotbelowcmb@bottom',
'adotbelow': 'a+dotbelowcmb@bottom',
'AEacute': 'AE+acutecmb@top',
'aeacute': 'ae+acutecmb@top',
'Agrave': 'A+gravecmb@top',
'agrave': 'a+gravecmb@top',
'Ahoi': 'A+hoicmb@top',
'ahoi': 'a+hoicmb@top',
'Alphatonos': 'Alpha+tonos.cap@tonos.cap',
'alphatonos': 'alpha+tonos@top',
'Amacron': 'A+macroncmb@top',
'amacron': 'a+macroncmb@top',
'Aogonek': 'A+ogonekcmb@ogonek',
'aogonek': 'a+ogonekcmb@ogonek',
'Aring': 'A+ringcmb@top',
'aring': 'a+ringcmb@top',
'Aringacute': 'A+ringcmb_acutecmb@top',
'aringacute': 'a+ringcmb_acutecmb@top',
'Atilde': 'A+tildecmb@top',
'atilde': 'a+tildecmb@top',
'Cacute': 'C+acutecmb@top',
'cacute': 'c+acutecmb@top',
'Ccaron': 'C+caroncmb@top',
'ccaron': 'c+caroncmb@top',
'Ccedilla': 'C+cedillacmb@bottom',
'ccedilla': 'c+cedillacmb@bottom',
'Ccircumflex': 'C+circumflexcmb@top',
'ccircumflex': 'c+circumflexcmb@top',
'Cdotaccent': 'C+dotaccentcmb@top',
'cdotaccent': 'c+dotaccentcmb@top',
'Dcaron': 'D+caroncmb@top',
'dcaron': 'd+caroncmb.vert@caron.vert',
'Eacute': 'E+acutecmb@top',
'eacute': 'e+acutecmb@top',
'Ebreve': 'E+brevecmb@top',
'ebreve': 'e+brevecmb@top',
'Ecaron': 'E+caroncmb@top',
'ecaron': 'e+caroncmb@top',
'Ecircumflex': 'E+circumflexcmb@top',
'ecircumflex': 'e+circumflexcmb@top',
'Ecircumflexacute': 'E+circumflexcmb_acutecmb@top',
'ecircumflexacute': 'e+circumflexcmb_acutecmb@top',
'Ecircumflexdotbelow': 'E+circumflexcmb@top+dotbelowcmb@bottom',
'ecircumflexdotbelow': 'e+circumflexcmb@top+dotbelowcmb@bottom',
'Ecircumflexgrave': 'E+circumflexcmb_gravecmb@top',
'ecircumflexgrave': 'e+circumflexcmb_gravecmb@top',
'Ecircumflexhoi': 'E+circumflexcmb_hoicmb@top',
'ecircumflexhoi': 'e+circumflexcmb_hoicmb@top',
'Ecircumflextilde': 'E+circumflexcmb_tildecmb@top',
'ecircumflextilde': 'e+circumflexcmb_tildecmb@top',
'Edieresis': 'E+dieresiscmb@top',
'edieresis': 'e+dieresiscmb@top',
'Edotaccent': 'E+dotaccentcmb@top',
'edotaccent': 'e+dotaccentcmb@top',
'Edotbelow': 'E+dotbelowcmb@bottom',
'edotbelow': 'e+dotbelowcmb@bottom',
'Egrave': 'E+gravecmb@top',
'egrave': 'e+gravecmb@top',
'Ehoi': 'E+hoicmb@top',
'ehoi': 'e+hoicmb@top',
'Emacron': 'E+macroncmb@top',
'emacron': 'e+macroncmb@top',
'Eogonek': 'E+ogonekcmb@ogonek',
'eogonek': 'e+ogonekcmb@ogonek',
'Epsilontonos': 'Epsilon+tonos.cap@tonos.cap',
'epsilontonos': 'epsilon+tonos@top',
'Etatonos': 'Eta+tonos.cap@tonos.cap',
'etatonos': 'eta+tonos@top',
'Etilde': 'E+tildecmb@top',
'etilde': 'e+tildecmb@top',
'Gbreve': 'G+brevecmb@top',
'gbreve': 'g+brevecmb@top',
'Gcircumflex': 'G+circumflexcmb@top',
'gcircumflex': 'g+circumflexcmb@top',
'Gcommaaccent': 'G+commabelowcmb@bottom',
'gcommaaccent': 'g+commaturnedabovecmb@top',
'Gdotaccent': 'G+dotaccentcmb@top',
'gdotaccent': 'g+dotaccentcmb@top',
'Gje': 'Ghe+acutecmb@top',
'gje': 'ghe+acutecmb@top',
'Hcircumflex': 'H+circumflexcmb@top',
'hcircumflex': 'h+circumflexcmb@top',
'iacute': 'dotlessi+acutecmb@top',
'Iacute': 'I+acutecmb@top',
'ibreve': 'dotlessi+brevecmb@top',
'Ibreve': 'I+brevecmb@top',
'icircumflex': 'dotlessi+circumflexcmb@top',
'Icircumflex': 'I+circumflexcmb@top',
'idieresis': 'dotlessi+dieresiscmb@top',
'Idieresis': 'I+dieresiscmb@top',
'Idotaccent': 'I+dotaccentcmb@top',
'Idotbelow': 'I+dotbelowcmb@bottom',
'idotbelow': 'i+dotbelowcmb@bottom',
'igrave': 'dotlessi+gravecmb@top',
'Igrave': 'I+gravecmb@top',
'ihoi': 'dotlessi+hoicmb@top',
'Ihoi': 'I+hoicmb@top',
'imacron': 'dotlessi+macroncmb@top',
'Imacron': 'I+macroncmb@top',
'Io': 'Ie+dieresiscmb@top',
'io': 'ie+dieresiscmb@top',
'Iogonek': 'I+ogonekcmb@ogonek',
'iogonek': 'i+ogonekcmb@ogonek',
'Iotadieresis': 'Iota+dieresiscmb@top',
'iotadieresis': 'iota+dieresiscmb@top',
'iotadieresistonos': 'iota+dieresistonos@top',
'Iotatonos': 'Iota+tonos.cap@tonos.cap',
'iotatonos': 'iota+tonos@top',
'Ishort': 'Icyr+brevecmb.cyrl@top',
'ishort': 'icyr+brevecmb.cyrl@top',
'itilde': 'dotlessi+tildecmb@top',
'Itilde': 'I+tildecmb@top',
'jcircumflex': 'dotlessj+circumflexcmb@top',
'Jcircumflex': 'J+circumflexcmb@top',
'Kcommaaccent': 'K+commabelowcmb@bottom',
'kcommaaccent': 'k+commabelowcmb@bottom',
'Kje': 'Ka+acutecmb@top',
'kje': 'ka+acutecmb@top',
'Lacute': 'L+acutecmb@top',
'lacute': 'l+acutecmb@top',
'Lcaron': 'L+caroncmb.vert@caron.vert',
'lcaron': 'l+caroncmb.vert@caron.vert',
'Lcommaaccent': 'L+commabelowcmb@bottom',
'lcommaaccent': 'l+commabelowcmb@bottom',
'Nacute': 'N+acutecmb@top',
'nacute': 'n+acutecmb@top',
'Ncaron': 'N+caroncmb@top',
'ncaron': 'n+caroncmb@top',
'Ncommaaccent': 'N+commabelowcmb@bottom',
'ncommaaccent': 'n+commabelowcmb@bottom',
'Ntilde': 'N+tildecmb@top',
'ntilde': 'n+tildecmb@top',
'Oacute': 'O+acutecmb@top',
'oacute': 'o+acutecmb@top',
'Obreve': 'O+brevecmb@top',
'obreve': 'o+brevecmb@top',
'Ocircumflex': 'O+circumflexcmb@top',
'ocircumflex': 'o+circumflexcmb@top',
'Ocircumflexacute': 'O+circumflexcmb_acutecmb@top',
'ocircumflexacute': 'o+circumflexcmb_acutecmb@top',
'Ocircumflexdotbelow': 'O+circumflexcmb@top+dotbelowcmb@bottom',
'ocircumflexdotbelow': 'o+circumflexcmb@top+dotbelowcmb@bottom',
'Ocircumflexgrave': 'O+circumflexcmb_gravecmb@top',
'ocircumflexgrave': 'o+circumflexcmb_gravecmb@top',
'Ocircumflexhoi': 'O+circumflexcmb_hoicmb@top',
'ocircumflexhoi': 'o+circumflexcmb_hoicmb@top',
'Ocircumflextilde': 'O+circumflexcmb_tildecmb@top',
'ocircumflextilde': 'o+circumflexcmb_tildecmb@top',
'Odieresis': 'O+dieresiscmb@top',
'odieresis': 'o+dieresiscmb@top',
'Odotbelow': 'O+dotbelowcmb@bottom',
'odotbelow': 'o+dotbelowcmb@bottom',
'Ograve': 'O+gravecmb@top',
'ograve': 'o+gravecmb@top',
'Ohoi': 'O+hoicmb@top',
'ohoi': 'o+hoicmb@top',
'Ohorn': 'O+horncmb@horn',
'ohorn': 'o+horncmb@horn',
'Ohornacute': 'O+horncmb@horn+acutecmb@top',
'ohornacute': 'o+horncmb@horn+acutecmb@top',
'Ohorndotbelow': 'O+horncmb@horn+dotbelowcmb@bottom',
'ohorndotbelow': 'o+horncmb@horn+dotbelowcmb@bottom',
'Ohorngrave': 'O+horncmb@horn+gravecmb@top',
'ohorngrave': 'o+horncmb@horn+gravecmb@top',
'Ohornhoi': 'O+horncmb@horn+hoicmb@top',
'ohornhoi': 'o+horncmb@horn+hoicmb@top',
'Ohorntilde': 'O+horncmb@horn+tildecmb@top',
'ohorntilde': 'o+horncmb@horn+tildecmb@top',
'Ohungarumlaut': 'O+hungarumlautcmb@top',
'ohungarumlaut': 'o+hungarumlautcmb@top',
'Omacron': 'O+macroncmb@top',
'omacron': 'o+macroncmb@top',
'Omegatonos': 'Omega+tonos.cap@tonos.cap',
'omegatonos': 'omega+tonos@top',
'Omicrontonos': 'Omicron+tonos.cap@tonos.cap',
'omicrontonos': 'omicron+tonos@top',
'Oslashacute': 'Oslash+acutecmb@top',
'oslashacute': 'oslash+acutecmb@top',
'Otilde': 'O+tildecmb@top',
'otilde': 'o+tildecmb@top',
'Racute': 'R+acutecmb@top',
'racute': 'r+acutecmb@top',
'Rcaron': 'R+caroncmb@top',
'rcaron': 'r+caroncmb@top',
'Rcommaaccent': 'R+commabelowcmb@bottom',
'rcommaaccent': 'r+commabelowcmb@bottom',
'Sacute': 'S+acutecmb@top',
'sacute': 's+acutecmb@top',
'Scaron': 'S+caroncmb@top',
'scaron': 's+caroncmb@top',
'Scedilla': 'S+cedillacmb@bottom',
'scedilla': 's+cedillacmb@bottom',
'Scircumflex': 'S+circumflexcmb@top',
'scircumflex': 's+circumflexcmb@top',
'Scommaaccent': 'S+commabelowcmb@bottom',
'scommaaccent': 's+commabelowcmb@bottom',
'Tcaron': 'T+caroncmb@top',
'tcaron': 't+caroncmb.vert@caron.vert',
'Tcedilla': 'T+cedillacmb@bottom',
'tcedilla': 't+cedillacmb@bottom',
'Tcommaaccent': 'T+commabelowcmb@bottom',
'tcommaaccent': 't+commabelowcmb@bottom',
'Uacute': 'U+acutecmb@top',
'uacute': 'u+acutecmb@top',
'Ubreve': 'U+brevecmb@top',
'ubreve': 'u+brevecmb@top',
'Ucircumflex': 'U+circumflexcmb@top',
'ucircumflex': 'u+circumflexcmb@top',
'Udieresis': 'U+dieresiscmb@top',
'udieresis': 'u+dieresiscmb@top',
'Udotbelow': 'U+dotbelowcmb@bottom',
'udotbelow': 'u+dotbelowcmb@bottom',
'Ugrave': 'U+gravecmb@top',
'ugrave': 'u+gravecmb@top',
'Uhoi': 'U+hoicmb@top',
'uhoi': 'u+hoicmb@top',
'Uhorn': 'U+horncmb@horn',
'uhorn': 'u+horncmb@horn',
'Uhornacute': 'Uhorn+acutecmb@top',
'uhornacute': 'uhorn+acutecmb@top',
'Uhorndotbelow': 'Uhorn+dotbelowcmb@bottom',
'uhorndotbelow': 'uhorn+dotbelowcmb@bottom',
'Uhorngrave': 'Uhorn+gravecmb@top',
'uhorngrave': 'uhorn+gravecmb@top',
'Uhornhoi': 'Uhorn+hoicmb@top',
'uhornhoi': 'uhorn+hoicmb@top',
'Uhorntilde': 'Uhorn+tildecmb@top',
'uhorntilde': 'uhorn+tildecmb@top',
'Uhungarumlaut': 'U+hungarumlautcmb@top',
'uhungarumlaut': 'u+hungarumlautcmb@top',
'Umacron': 'U+macroncmb@top',
'umacron': 'u+macroncmb@top',
'Uogonek': 'U+ogonekcmb@ogonek',
'uogonek': 'u+ogonekcmb@ogonek',
'Upsilondieresis': 'Upsilon+dieresiscmb@top',
'upsilondieresis': 'upsilon+dieresiscmb@top',
'upsilondieresistonos': 'upsilon+dieresistonos@top',
'Upsilontonos': 'Upsilon+tonos.cap@tonos.cap',
'upsilontonos': 'upsilon+tonos@top',
'Uring': 'U+ringcmb@top',
'uring': 'u+ringcmb@top',
'Ushort': 'Ucyr+brevecmb.cyrl@top',
'ushort': 'ucyr+brevecmb.cyrl@top',
'Utilde': 'U+tildecmb@top',
'utilde': 'u+tildecmb@top',
'Wacute': 'W+acutecmb@top',
'wacute': 'w+acutecmb@top',
'Wcircumflex': 'W+circumflexcmb@top',
'wcircumflex': 'w+circumflexcmb@top',
'Wdieresis': 'W+dieresiscmb@top',
'wdieresis': 'w+dieresiscmb@top',
'Wgrave': 'W+gravecmb@top',
'wgrave': 'w+gravecmb@top',
'Yacute': 'Y+acutecmb@top',
'yacute': 'y+acutecmb@top',
'Ycircumflex': 'Y+circumflexcmb@top',
'ycircumflex': 'y+circumflexcmb@top',
'Ydieresis': 'Y+dieresiscmb@top',
'ydieresis': 'y+dieresiscmb@top',
'Ydotbelow': 'Y+dotbelowcmb@bottom',
'ydotbelow': 'y+dotbelowcmb@bottom',
'Ygrave': 'Y+gravecmb@top',
'ygrave': 'y+gravecmb@top',
'Yhoi': 'Y+hoicmb@top',
'yhoi': 'y+hoicmb@top',
'Yi': 'Iukran+dieresiscmb@top',
'yi': 'iukran+dieresiscmb@top',
'ytilde': 'y+tildecmb@top',
'Ytilde': 'Y+tildecmb@top',
'Zacute': 'Z+acutecmb@top',
'zacute': 'z+acutecmb@top',
'Zcaron': 'Z+caroncmb@top',
'zcaron': 'z+caroncmb@top',
'Zdotaccent': 'Z+dotaccentcmb@top',
'zdotaccent': 'z+dotaccentcmb@top',
# added april 26, 2017
'Acaron': 'A+caroncmb@top',
'Ahookabove': 'A+hookabovecmb@top',
'Acircumflexhookabove': 'A+circumflexcmb_hookabovecmb@top',
'Abrevehookabove': 'A+brevecmb_hookabovecmb@top',
'Ddotbelow': 'D+dotbelowcmb@bottom',
'Dlinebelow': 'D+linebelowcmb@bottom',
'Ehookabove': 'E+hookabovecmb@top',
'Ecircumflexhookabove': 'E+circumflexcmb_hookabovecmb@top',
'Gcaron': 'G+caroncmb@top',
'Gmacron': 'G+macroncmb@top',
'Hdotbelow': 'H+dotbelowcmb@bottom',
'Hbrevebelow': 'H+brevebelowcmb@bottom',
'Icaron': 'I+caroncmb@top',
'Ihookabove': 'I+hookabovecmb@top',
'Ldotbelow': 'L+dotbelowcmb@bottom',
'Ldotbelowmacron': 'Ldotbelow+macroncmb@top',
'Llinebelow': 'L+linebelowcmb@bottom',
'Mdotbelow': 'M+dotbelowcmb@bottom',
'Ndotaccent': 'N+dotaccentcmb@top',
'Ndotbelow': 'N+dotbelowcmb@bottom',
'Nlinebelow': 'N+linebelowcmb@bottom',
'Ocaron': 'O+caroncmb@top',
'Ohookabove': 'O+hookabovecmb@top',
'Ocircumflexhookabove': 'O+circumflexcmb_hookabovecmb@top',
'Ohornhookabove': 'Ohorn+hookabovecmb@top',
'Rdotbelow': 'R+dotbelowcmb@bottom',
'Rdotbelowmacron': 'Rdotbelow+macroncmb@top',
'Rlinebelow': 'R+linebelowcmb@bottom',
'Sdotaccent': 'S+dotaccentcmb@top',
'Sdotbelow': 'S+dotbelowcmb@bottom',
'Tdotbelow': 'T+dotbelowcmb@bottom',
'Tlinebelow': 'T+linebelowcmb@bottom',
'Ucaron': 'U+caroncmb@top',
'Udieresismacron': 'U+dieresiscmb_macroncmb@top',
'Udieresisacute': 'U+dieresiscmb_acutecmb@top',
'Udieresiscaron': 'U+dieresiscmb_caroncmb@top',
'Udieresisgrave': 'U+dieresiscmb_gravecmb@top',
'Uhookabove': 'U+hookabovecmb@top',
'Uhornhookabove': 'Uhorn+hookabovecmb@top',
'Ydotaccent': 'Y+dotaccentcmb@top',
'Yhookabove': 'Y+hookabovecmb@top',
'Zdotbelow': 'Z+dotbelowcmb@bottom',
'acaron': 'a+caroncmb@top',
'ahookabove': 'a+hookabovecmb@top',
'acircumflexhookabove': 'a+circumflexcmb_hookabovecmb@top',
'abrevehookabove': 'a+brevecmb_hookabovecmb@top',
'ddotbelow': 'd+dotbelowcmb@bottom',
'dlinebelow': 'd+linebelowcmb@bottom',
'ehookabove': 'e+hookabovecmb@top',
'ecircumflexhookabove': 'e+circumflexcmb_hookabovecmb@top',
'gcaron': 'g+caroncmb@top',
'gmacron': 'g+macroncmb@top',
'hdotbelow': 'h+dotbelowcmb@bottom',
'hbrevebelow': 'h+brevebelowcmb@bottom',
'icaron': 'dotlessi+caroncmb@top',
'ihookabove': 'dotlessi+hookabovecmb@top',
'ldotbelow': 'l+dotbelowcmb@bottom',
'ldotbelowmacron': 'ldotbelow+macroncmb@top',
'llinebelow': 'l+linebelowcmb@bottom',
'mdotbelow': 'm+dotbelowcmb@bottom',
'ndotaccent': 'n+dotaccentcmb@top',
'ndotbelow': 'n+dotbelowcmb@bottom',
'nlinebelow': 'n+linebelowcmb@bottom',
'ocaron': 'o+caroncmb@top',
'ohookabove': 'o+hookabovecmb@top',
'ocircumflexhookabove': 'o+circumflexcmb_hookabovecmb@top',
'ohornhookabove': 'ohorn+hookabovecmb@top',
'rdotbelow': 'r+dotbelowcmb@bottom',
'rdotbelowmacron': 'rdotbelow+macroncmb@top',
'rlinebelow': 'r+linebelowcmb@bottom',
'sdotaccent': 's+dotaccentcmb@top',
'sdotbelow': 's+dotbelowcmb@bottom',
'tdotbelow': 't+dotbelowcmb@bottom',
'tlinebelow': 't+linebelowcmb@bottom',
'ucaron': 'u+caroncmb@top',
'udieresismacron': 'u+dieresiscmb_macroncmb@top',
'udieresisacute': 'u+dieresiscmb_acutecmb@top',
'udieresiscaron': 'u+dieresiscmb_caroncmb@top',
'udieresisgrave': 'u+dieresiscmb_gravecmb@top',
'uhookabove': 'u+hookabovecmb@top',
'uhornhookabove': 'uhorn+hookabovecmb@top',
'ydotaccent': 'y+dotaccentcmb@top',
'yhookabove': 'y+hookabovecmb@top',
'zdotbelow': 'z+dotbelowcmb@bottom',
}

ANCHOR_POS = {
'top': ('center', 'top'),
'bottom': ('center', 'bottom'),
'ogonek': ('right', 'bottom'),
'horn': ('right', 'top'),
'caron.vert': ('right', 'top'),
'tonos.cap': ('left', 'top'),
}

BASES_COMPOSITES = {}

for glyphName, instruction in INSTRUCTIONS.items():
    items = instruction.split("+")
    base = items[0]
    if base not in BASES_COMPOSITES:
        BASES_COMPOSITES[base] = set()
    BASES_COMPOSITES[base].add(glyphName)

"""
COMPOSITE_SET = INSTRUCTIONS.keys()
BASE_SET = set()
ACCENT_SET = set()
for string in INSTRUCTIONS.values():
    items = string.split("+")
    base = items[0]
    BASE_SET.add(base)
    for i in items[1:]:
        accent, _ = i.split("@")
        ACCENT_SET.add(accent)
"""

# accentname 2 accentnamecmb and unicodevalue 2 unicodevaluecmb
# these are the 13 'legacy' accent
# other accents only exist as cmb

AN2CMB = {
'grave': 'gravecmb',
'dieresis': 'dieresiscmb',
'macron': 'macroncmb',
'acute': 'acutecmb',
'cedilla': 'cedillacmb',
'circumflex': 'circumflexcmb',
'caron': 'caroncmb',
'breve': 'brevecmb',
'dotaccent': 'dotaccentcmb',
'ring': 'ringcmb',
'ogonek': 'ogonekcmb',
'tilde': 'tildecmb',
'hungarumlaut': 'hungarumlautcmb',
}

UV2CMB = {
0x0060: 0x0300, # grave
0x00A8: 0x0308, # dieresis
0x00AF: 0x0304, # macron
0x00B4: 0x0301, # acute
0x00B8: 0x0327, # cedilla
0x02C6: 0x0302, # circumflex
0x02C7: 0x030C, # caron
0x02D8: 0x0306, # breve
0x02D9: 0x0307, # dotaccent
0x02DA: 0x030A, # ring
0x02DB: 0x0328, # ogonek
0x02DC: 0x0303, # tilde
0x02DD: 0x030B, # hungarumlaut
}

CMB2AN = {}
for k, v in AN2CMB.items():
    CMB2AN[v] = k

CMB2UV = {}
for k, v in UV2CMB.items():
    CMB2UV[v] = k
