SS = [
    'efcyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:116:2)
	'vecyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:151:2)
	'Decyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:212)
	'Decyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:227)
	'Decyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:242)
	'Djecyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:257)
	'Djecyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:273)
	'Djecyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:289)
	'Dzhecyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:353)
	'Dzhecyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:370)
	'Dzhecyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:387)
	'Efcyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:446)
	'Efcyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:461)
	'Efcyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:476)
	'Ucyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2111)
	'Ucyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2125)
	'Ucyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2139)
	'Ushortcyrillic.cm0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2153)
	'Ushortcyrillic.cm1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2172)
	'Ushortcyrillic.cm2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:304:2191)
	'Decyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:212)
	'Decyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:227)
	'Decyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:242)
	'Djecyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:257)
	'Djecyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:273)
	'Djecyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:289)
	'Dzhecyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:353)
	'Dzhecyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:370)
	'Dzhecyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:387)
	'Efcyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:446)
	'Efcyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:461)
	'Efcyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:476)
	'Ucyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2111)
	'Ucyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2125)
	'Ucyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2139)
	'Ushortcyrillic.ct0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2153)
	'Ushortcyrillic.ct1', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2172)
	'Ushortcyrillic.ct2', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:308:2191)
	'Decyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:312:72)
	'Djecyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:312:87)
	'Dzhecyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:312:119)
	'Efcyrillic.cl0', # /Users/petr/Desktop/TYPETR-git/TYPETR-Responder/ufo/features/Auto_Responder_Alts.fea:312:150)
]
for f in AllFonts():
    if 'Regular.ufo' in f.path:
        reg = f
print(reg)
f = CurrentFont()
for name in SS:
    if not name in f:
        f.newGlyph(name)
        print(name, f.path)
    else:
        f[name] = reg[name]
        print('Copy', name, f.path)
print('Done') 