f = CurrentFont()
if 1:
    for groupName, group in f.groups.items():
        if 'jecyrillic.cm0' in group:
            print(groupName, group) #, group)
#del f.groups['public.kern1.t_cm']

SAVE = False

f.groups['public.kern1.gecyrillic_cy'] = ('gecyrillic', 'gecyrillic.alt1', 'gecyrillic.alt2', 'gjecyrillic', 'gjecyrillic.alt1', 'gjecyrillic.alt2')

f.groups['public.kern2.a_lt'] = ('a', 'a.alt1', 'a.alt2', 'a.cm0', 'a.cm1', 'a.cm2', 'a.ct0', 'a.ct1', 'a.ct2', 'aacute', 'abreve', 'acircumflex', 'adieresis', 'ae', 'aeacute', 'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde', 'd', 'd.alt1', 'd.alt2', 'd.cm0', 'd.cm1', 'd.cm2', 'd.ct0', 'd.ct1', 'd.ct2', 'd.sans', 'q', 'q.alt1', 'q.alt2', 'q.cm0', 'q.cm1', 'q.cm2', 'q.ct0', 'q.ct1', 'q.ct2')

f.groups['public.kern2.acyrillic_cy'] = ('acyrillic', 'acyrillic.alt1', 'acyrillic.alt2', 'acyrillic.cl0', 'acyrillic.cm0', 'acyrillic.cm1', 'acyrillic.cm2', 'acyrillic.ct0', 'acyrillic.ct1', 'acyrillic.ct2', 'becyrillic', 'becyrillic.alt1', 'becyrillic.alt2', 'becyrillic.cl0', 'becyrillic.cm0', 'becyrillic.cm1', 'becyrillic.ct0', 'becyrillic.ct1', 'becyrillic.ct2')

f.groups['public.kern2.acyrillic_cy'] = ('acyrillic', 'acyrillic.alt1', 'acyrillic.alt2', 'acyrillic.cl0', 'acyrillic.cm0', 'acyrillic.cm1', 'acyrillic.cm2', 'acyrillic.ct0', 'acyrillic.ct1', 'acyrillic.ct2', 'becyrillic', 'becyrillic.alt1', 'becyrillic.alt2', 'becyrillic.cl0', 'becyrillic.cm0', 'becyrillic.cm1', 'becyrillic.cm2', 'becyrillic.ct0', 'becyrillic.ct1', 'becyrillic.ct2')

f.groups['public.kern2.vecyrillic_cy'] = ('vecyrillic', 'vecyrillic.alt1', 'vecyrillic.alt2', 'vecyrillic.cm0', 'vecyrillic.cm1', 'vecyrillic.cm2', 'vecyrillic.ct0', 'vecyrillic.ct1', 'vecyrillic.ct2')

f.groups['public.kern2.decyrillic_cy'] = ('decyrillic', 'decyrillic.alt1', 'decyrillic.alt2', 'decyrillic.cl0', 'decyrillic.cm0', 'decyrillic.cm1', 'decyrillic.cm2', 'decyrillic.ct0', 'decyrillic.ct1', 'decyrillic.ct2')

f.groups['public.kern2.ocyrillic_cy'] = ('ecyrillic', 'ecyrillic.alt1', 'ecyrillic.alt2', 'ecyrillic.cl0', 'ecyrillic.cm0', 'ecyrillic.cm1', 'ecyrillic.cm2', 'ecyrillic.ct0', 'ecyrillic.ct1', 'ecyrillic.ct2', 'efcyrillic', 'efcyrillic.alt1', 'efcyrillic.alt2', 'efcyrillic.cm0', 'efcyrillic.cm1', 'efcyrillic.cm2', 'efcyrillic.ct0', 'efcyrillic.ct1', 'efcyrillic.ct2', 'escyrillic', 'escyrillic.alt1', 'escyrillic.alt2', 'escyrillic.cl0', 'escyrillic.cm0', 'escyrillic.cm1', 'escyrillic.ct0', 'escyrillic.ct1', 'escyrillic.ct2', 'iecyrillic', 'iecyrillic.alt1', 'iecyrillic.alt2', 'iecyrillic.cl0', 'iecyrillic.cm0', 'iecyrillic.cm1', 'iecyrillic.cm2', 'iecyrillic.ct0', 'iecyrillic.ct1', 'iecyrillic.ct2', 'iegravecyrillic', 'iegravecyrillic.alt1', 'iegravecyrillic.alt2', 'iegravecyrillic.cl0', 'iegravecyrillic.cm0', 'iegravecyrillic.cm2', 'iegravecyrillic.ct0', 'iegravecyrillic.ct1', 'iegravecyrillic.ct2', 'iocyrillic', 'iocyrillic.alt1', 'iocyrillic.alt2', 'iocyrillic.cl0', 'iocyrillic.cm0', 'iocyrillic.cm1', 'iocyrillic.cm2', 'iocyrillic.ct0', 'iocyrillic.ct1', 'iocyrillic.ct2', 'ocyrillic', 'ocyrillic.alt1', 'ocyrillic.alt2', 'ocyrillic.cl0', 'ocyrillic.cm0', 'ocyrillic.cm1', 'ocyrillic.ct0', 'ocyrillic.ct1', 'ocyrillic.ct2')

f.groups['public.kern2.khacyrillic_cy'] = ('hadescendercyrillic', 'hadescendercyrillic.alt1', 'hadescendercyrillic.alt2', 'hadescendercyrillic.cl0', 'hadescendercyrillic.cm0', 'hadescendercyrillic.cm1', 'hadescendercyrillic.cm2', 'hadescendercyrillic.ct0', 'hadescendercyrillic.ct1', 'hadescendercyrillic.ct2', 'khacyrillic', 'khacyrillic.alt1', 'khacyrillic.alt2', 'khacyrillic.cl0', 'khacyrillic.cm0', 'khacyrillic.cm1', 'khacyrillic.cm2', 'khacyrillic.ct0', 'khacyrillic.ct1', 'khacyrillic.ct2', 'zhecyrillic', 'zhecyrillic.alt1', 'zhecyrillic.alt2', 'zhecyrillic.cl0', 'zhecyrillic.cm0', 'zhecyrillic.cm1', 'zhecyrillic.cm2', 'zhecyrillic.ct0', 'zhecyrillic.ct1', 'zhecyrillic.ct2', 'zhedescendercyrillic', 'zhedescendercyrillic.alt1', 'zhedescendercyrillic.alt2', 'zhedescendercyrillic.cl0', 'zhedescendercyrillic.cm0', 'zhedescendercyrillic.cm1', 'zhedescendercyrillic.cm2', 'zhedescendercyrillic.ct0', 'zhedescendercyrillic.ct1', 'zhedescendercyrillic.ct2')

f.groups['public.kern2.hardsigncyrillic_cy'] = ('hardsigncyrillic', 'hardsigncyrillic.alt1', 'hardsigncyrillic.alt2', 'hardsigncyrillic.cl0', 'hardsigncyrillic.cm0', 'hardsigncyrillic.cm1', 'hardsigncyrillic.cm2', 'hardsigncyrillic.ct0', 'hardsigncyrillic.ct1', 'hardsigncyrillic.ct2')

f.groups['public.kern2.vecyrillic_cy'] = ('vecyrillic', 'vecyrillic.alt1', 'vecyrillic.alt2', 'vecyrillic.cl0', 'vecyrillic.cm0', 'vecyrillic.cm1', 'vecyrillic.cm2', 'vecyrillic.ct0', 'vecyrillic.ct1', 'vecyrillic.ct2')

f.groups['public.kern2.ocyrillic_cy'] = ('ecyrillic', 'ecyrillic.alt1', 'ecyrillic.alt2', 'ecyrillic.cl0', 'ecyrillic.cm0', 'ecyrillic.cm1', 'ecyrillic.cm2', 'ecyrillic.ct0', 'ecyrillic.ct1', 'ecyrillic.ct2', 'efcyrillic', 'efcyrillic.alt1', 'efcyrillic.alt2', 'efcyrillic.cm0', 'efcyrillic.cl0', 'efcyrillic.cm1', 'efcyrillic.cm2', 'efcyrillic.ct0', 'efcyrillic.ct1', 'efcyrillic.ct2', 'escyrillic', 'escyrillic.alt1', 'escyrillic.alt2', 'escyrillic.cl0', 'escyrillic.cm0', 'escyrillic.cm1', 'escyrillic.ct0', 'escyrillic.ct1', 'escyrillic.ct2', 'iecyrillic', 'iecyrillic.alt1', 'iecyrillic.alt2', 'iecyrillic.cl0', 'iecyrillic.cm0', 'iecyrillic.cm1', 'iecyrillic.cm2', 'iecyrillic.ct0', 'iecyrillic.ct1', 'iecyrillic.ct2', 'iegravecyrillic', 'iegravecyrillic.alt1', 'iegravecyrillic.alt2', 'iegravecyrillic.cl0', 'iegravecyrillic.cm0', 'iegravecyrillic.cm2', 'iegravecyrillic.ct0', 'iegravecyrillic.ct1', 'iegravecyrillic.ct2', 'iocyrillic', 'iocyrillic.alt1', 'iocyrillic.alt2', 'iocyrillic.cl0', 'iocyrillic.cm0', 'iocyrillic.cm1', 'iocyrillic.cm2', 'iocyrillic.ct0', 'iocyrillic.ct1', 'iocyrillic.ct2', 'ocyrillic', 'ocyrillic.alt1', 'ocyrillic.alt2', 'ocyrillic.cl0', 'ocyrillic.cm0', 'ocyrillic.cm1', 'ocyrillic.ct0', 'ocyrillic.ct1', 'ocyrillic.ct2')

f.groups['public.kern2.iacyrillic_cy'] = ('iacyrillic', 'iacyrillic.alt1', 'iacyrillic.alt2', 'iacyrillic.cl0', 'iacyrillic.cm0', 'iacyrillic.cm1', 'iacyrillic.cm2', 'iacyrillic.ct0', 'iacyrillic.ct1', 'iacyrillic.ct2')

f.groups['public.kern2.icyrillic_cy'] = ('icyrillic', 'icyrillic.alt1', 'icyrillic.alt2', 'icyrillic.cl0', 'icyrillic.cm0', 'icyrillic.cm1', 'icyrillic.cm2', 'icyrillic.ct0', 'icyrillic.ct1', 'icyrillic.ct2')

f.groups['public.kern2.yicyrillic_cy'] = ('yicyrillic', 'yicyrillic.alt1', 'yicyrillic.alt2', 'yicyrillic.cl0', 'yicyrillic.cm0', 'yicyrillic.cm1', 'yicyrillic.cm2', 'yicyrillic.ct0', 'yicyrillic.ct1', 'yicyrillic.ct2')

f.groups['public.kern2.jecyrillic_cy'] = ('jecyrillic', 'jecyrillic.alt1', 'jecyrillic.alt2', 'jecyrillic.cl0', 'jecyrillic.cm0', 'jecyrillic.cm1', 'jecyrillic.cm2', 'jecyrillic.ct0', 'jecyrillic.ct1', 'jecyrillic.ct2')

f.groups['public.kern2.a_lt'] = ('a', 'a.alt1', 'a.alt2', 'a.cm0', 'a.cm1', 'a.cm2', 'a.ct0', 'a.ct1', 'a.ct2', 'aacute', 'abreve', 'acircumflex', 'adieresis', 'ae', 'aeacute', 'agrave', 'amacron', 'aogonek', 'aring', 'aringacute', 'atilde', 'd', 'd.alt1', 'd.alt2', 'd.cm0', 'd.cm1', 'd.cm2', 'd.ct0', 'd.ct1', 'd.ct2', 'd.sans', 'd.sans.cm0', 'd.sans.cm1', 'd.sans.cm2', 'd.sans.ct0', 'd.sans.ct1', 'd.sans.ct2', 'q', 'q.alt1', 'q.alt2', 'q.cm0', 'q.cm1', 'q.cm2', 'q.ct0', 'q.ct1', 'q.ct2')
f.groups['public.kern2.elcyrillic_cy'] = ('elcyrillic', 'elcyrillic.alt1', 'elcyrillic.alt2', 'elcyrillic.cl0', 'elcyrillic.cm0', 'elcyrillic.cm1', 'elcyrillic.cm2', 'elcyrillic.ct0', 'elcyrillic.ct1', 'elcyrillic.ct2', 'emcyrillic', 'emcyrillic.alt1', 'emcyrillic.alt2', 'emcyrillic.cl0', 'emcyrillic.cm0', 'emcyrillic.cm1', 'emcyrillic.cm2', 'emcyrillic.ct0', 'emcyrillic.ct1', 'emcyrillic.ct2')
f.groups['public.kern2.encyrillic_cy'] = ('dzhecyrillic', 'dzhecyrillic.alt1', 'dzhecyrillic.alt2', 'dzhecyrillic.cl0', 'dzhecyrillic.cm0', 'dzhecyrillic.cm1', 'dzhecyrillic.cm2', 
    'dzhecyrillic.ct0', 'dzhecyrillic.ct1', 'dzhecyrillic.ct2', 
    'encyrillic', 'encyrillic.alt1', 'encyrillic.alt2', 'encyrillic.cl0', 'encyrillic.cm0', 'encyrillic.cm1', 'encyrillic.cm2', 'encyrillic.ct0', 'encyrillic.ct1', 'encyrillic.ct2', 
    'ercyrillic', 'ercyrillic.alt1', 'ercyrillic.alt2', 'ercyrillic.cl0', 'ercyrillic.cm0', 'ercyrillic.cm1', 'ercyrillic.cm2', 'ercyrillic.ct0', 'ercyrillic.ct1', 'ercyrillic.ct2', 
    'igravecyrillic', 'igravecyrillic.alt1', 'igravecyrillic.alt2', 'igravecyrillic.cl0', 'igravecyrillic.cm0', 'igravecyrillic.cm1', 'igravecyrillic.cm2', 
        'igravecyrillic.ct0', 'igravecyrillic.ct1', 'igravecyrillic.ct2', 
    'iicyrillic', 'iicyrillic.alt1', 'iicyrillic.alt2', 'iicyrillic.cl0', 'iicyrillic.cm0', 'iicyrillic.cm1', 'iicyrillic.cm2', 
        'iicyrillic.ct0', 'iicyrillic.ct1', 'iicyrillic.ct2', 
    'iishortcyrillic', 'iishortcyrillic.alt1', 'iishortcyrillic.alt2', 'iishortcyrillic.cl0', 'iishortcyrillic.cm0', 'iishortcyrillic.cm1', 'iishortcyrillic.cm2', 
        'iishortcyrillic.ct0', 'iishortcyrillic.ct1', 'iishortcyrillic.ct2', 
    'iucyrillic', 'iucyrillic.alt1', 'iucyrillic.alt2', 'iucyrillic.cl0', 'iucyrillic.cm0', 'iucyrillic.cm1', 'iucyrillic.cm2', 'iucyrillic.ct0', 'iucyrillic.ct1', 'iucyrillic.ct2', 
    'kacyrillic', 'kacyrillic.alt1', 'kacyrillic.alt2', 'kacyrillic.cl0', 'kacyrillic.cm0', 'kacyrillic.cm1', 'kacyrillic.cm2', 'kacyrillic.ct0', 'kacyrillic.ct1', 'kacyrillic.ct2', 
    'kadescendercyrillic', 'kadescendercyrillic.alt1', 'kadescendercyrillic.alt2', 'kadescendercyrillic.cl0', 
        'kadescendercyrillic.cm0', 'kadescendercyrillic.cm1', 'kadescendercyrillic.cm2', 
        'kadescendercyrillic.ct0', 'kadescendercyrillic.ct1', 'kadescendercyrillic.ct2', 
    'kjecyrillic', 'kjecyrillic.alt1', 'kjecyrillic.alt2', 'kjecyrillic.cl0', 'kjecyrillic.cm0', 'kjecyrillic.cm1', 'kjecyrillic.cm2', 
        'kjecyrillic.ct0', 'kjecyrillic.ct1', 'kjecyrillic.ct2', 
    'njecyrillic', 'njecyrillic.alt1', 'njecyrillic.alt2', 'njecyrillic.cl0', 'njecyrillic.cm0', 'njecyrillic.cm1', 'njecyrillic.cm2', 
        'njecyrillic.ct0', 'njecyrillic.ct1', 'njecyrillic.ct2', 
    'pecyrillic', 'pecyrillic.alt1', 'pecyrillic.alt2', 'pecyrillic.cl0', 'pecyrillic.cm0', 'pecyrillic.cm1', 'pecyrillic.cm2', 
        'pecyrillic.ct0', 'pecyrillic.ct1', 'pecyrillic.ct2', 
    'shacyrillic', 'shacyrillic.alt1', 'shacyrillic.alt2', 'shacyrillic.cl0', 'shacyrillic.cm0', 'shacyrillic.cm1', 'shacyrillic.cm2', 
        'shacyrillic.ct0', 'shacyrillic.ct1', 'shacyrillic.ct2', 
    'shchacyrillic', 'shchacyrillic.alt1', 'shchacyrillic.alt2', 'shchacyrillic.cl0', 'shchacyrillic.cm0', 'shchacyrillic.cm1', 'shchacyrillic.cm2', 
        'shchacyrillic.ct0', 'shchacyrillic.ct1', 'shchacyrillic.ct2', 
    'softsigncyrillic', 'softsigncyrillic.alt1', 'softsigncyrillic.alt2', 'softsigncyrillic.cl0', 'softsigncyrillic.cm0', 'softsigncyrillic.cm1', 'softsigncyrillic.cm2', 
        'softsigncyrillic.ct0', 'softsigncyrillic.ct1', 'softsigncyrillic.ct2', 
    'tecyrillic', 'tecyrillic.alt1', 'tecyrillic.alt2', 'tecyrillic.cl0', 'tecyrillic.cm0', 'tecyrillic.cm1', 'tecyrillic.cm2', 
        'tecyrillic.ct0', 'tecyrillic.ct1', 'tecyrillic.ct2', 
    'tsecyrillic', 'tsecyrillic.alt1', 'tsecyrillic.alt2', 'tsecyrillic.cl0', 'tsecyrillic.cm0', 'tsecyrillic.cm1', 'tsecyrillic.cm2', 
        'tsecyrillic.ct0', 'tsecyrillic.ct1', 'tsecyrillic.ct2', 
    'ucyrillic', 'ucyrillic.alt1', 'ucyrillic.alt2', 'ucyrillic.cl0', 'ucyrillic.cm0', 'ucyrillic.cm1', 'ucyrillic.cm2', 
        'ucyrillic.ct0', 'ucyrillic.ct1', 'ucyrillic.ct2', 
    'ushortcyrillic', 'ushortcyrillic.alt1', 'ushortcyrillic.alt2', 'ushortcyrillic.cl0', 'ushortcyrillic.cm0', 'ushortcyrillic.cm1', 'ushortcyrillic.cm2', 
        'ushortcyrillic.ct0', 'ushortcyrillic.ct1', 'ushortcyrillic.ct2', 
    'yericyrillic', 'yericyrillic.alt1', 'yericyrillic.alt2', 'yericyrillic.cl0', 'yericyrillic.cm0', 'yericyrillic.cm1', 'yericyrillic.cm2', 
        'yericyrillic.ct0', 'yericyrillic.ct1', 'yericyrillic.ct2')

f.groups['public.kern1.ct_lt'] = sorted(set([
'd.sans.ct0', 'h.sans.ct0',     
'A.ct0', 'A.ct1', 'A.ct2', 'B.ct0', 'B.ct1', 'B.ct2', 'C.ct0', 'C.ct1', 'C.ct2', 'D.ct0', 'D.ct1', 'D.ct2', 'E.ct0', 'E.ct1', 'E.ct2', 
'G.ct0', 'G.ct1', 'G.ct2', 'H.ct0', 'H.ct1', 'H.ct2', 'I.ct0', 'I.ct1', 'I.ct2', 'J.base.ct0', 'J.ct0', 'J.ct1', 'J.ct2', 'K.ct0', 'K.ct1', 'K.ct2', 'L.ct0', 'L.ct1', 
'L.ct2', 'M.ct0', 'M.ct1', 'M.ct2', 'O.ct0', 'O.ct1', 'O.ct2', 'P.ct0', 'P.ct1', 'P.ct2', 'R.ct0', 'R.ct1', 'R.ct2', 'S.ct0', 'S.ct1', 'S.ct2', 'X.ct0', 'X.ct1', 'X.ct2', 
'Z.ct0', 'Z.ct1', 'Z.ct2', 'a.ct0', 'a.ct1', 'a.ct2', 'b.ct0', 'b.ct1', 'b.ct2', 'b.sans.ct0', 'c.ct0', 'c.ct1', 'c.ct2', 'd.ct0', 'd.ct1', 'd.ct2', 'd.sans.ct0', 'e.ct0', 
'e.ct0b', 'e.ct1', 'e.ct1b', 'e.ct2', 'e.ct2b', 'g.ct0', 'g.ct1', 'g.ct2', 'h.ct0', 'h.ct1', 'h.ct2', 'h.sans.ct0', 'i.ct0', 'i.ct1', 'i.ct2', 'idotless.ct0', 'idotless.ct1', 
'idotless.ct2', 'j.ct0', 'j.ct1', 'j.ct2', 'jdotless.ct0', 'k.ct0', 'k.ct1', 'k.ct2', 'k.sans.ct0', 'l.ct0', 'l.ct1', 'l.ct2', 'l.sans.ct0', 'm.ct0', 'm.ct1', 'm.ct2', 'n.ct0', 
'n.ct1', 'n.ct2', 'p.ct0', 'p.ct1', 'p.ct2', 'q.ct0', 'q.ct1', 'q.ct2', 'r.ct0', 'r.ct1', 'r.ct2', 's.ct0', 's.ct1', 's.ct2', 'u.ct0', 'u.ct1', 'u.ct2', 'z.ct0', 'z.ct1', 'z.ct2',

'T.ct0', 'T.ct1', 'T.ct2',
'Y.ct0', 'Y.ct1', 'Y.ct2',

]))
f.groups['public.kern1.cm_lt'] = sorted(set([
'd.sans.cm0', 'h.sans.cm0',   
't.cm0', 't.cm1', 't.cm2', 'A.cm0', 'A.cm1', 'A.cm2', 'B.cm0', 'B.cm1', 'B.cm2', 'C.cm0', 'C.cm1', 'C.cm2', 'D.cm0', 'D.cm1', 'D.cm2', 'E.cm0', 'E.cm1', 'E.cm2', 
'G.cm0', 'G.cm1', 'G.cm2', 'H.cm0', 'H.cm1', 'H.cm2', 'I.cm0', 'I.cm1', 'I.cm2', 'J.base.cm0', 'J.cm0', 'J.cm1', 'J.cm2', 'K.cm0', 'K.cm1', 'K.cm2', 'L.cm0', 'L.cm1', 'L.cm2', 
'M.cm0', 'M.cm1', 'M.cm2', 'O.cm0', 'O.cm1', 'O.cm2', 'P.cm0', 'P.cm1', 'P.cm2', 'R.cm0', 'R.cm1', 'R.cm2', 'S.cm0', 'S.cm1', 'S.cm2', 'X.cm0', 'X.cm1', 'X.cm2', 'Z.cm0', 
'Z.cm1', 'Z.cm2', 'a.cm0', 'a.cm1', 'a.cm2', 'b.cm0', 'b.cm1', 'b.cm2', 'b.sans.cm0', 'c.cm0', 'c.cm1', 'c.cm2', 'd.cm0', 'd.cm1', 'd.cm2', 'd.sans.cm0', 'e.cm0', 'e.cm0b', 
'e.cm1', 'e.cm1b', 'e.cm2', 'e.cm2b', 'g.cm0', 'g.cm1', 'g.cm2', 'h.cm0', 'h.cm1', 'h.cm2', 'h.sans.cm0', 'i.cm0', 'i.cm1', 'i.cm2', 'idotless.cm0', 'idotless.cm1', 'idotless.cm2', 
'j.cm0', 'j.cm1', 'j.cm2', 'jdotless.cm0', 'k.cm0', 'k.cm1', 'k.cm2', 'k.sans.cm0', 'l.cm0', 'l.cm1', 'l.cm2', 'l.sans.cm0', 'm.cm0', 'm.cm1', 'm.cm2', 'n.cm0', 'n.cm1', 'n.cm2', 
'p.cm0', 'p.cm1', 'p.cm2', 'q.cm0', 'q.cm1', 'q.cm2', 'r.cm0', 'r.cm1', 'r.cm2', 's.cm0', 's.cm1', 's.cm2', 'u.cm0', 'u.cm1', 'u.cm2', 'x.cm0', 'x.cm1', 'x.cm2', 'z.cm0', 'z.cm1', 'z.cm2',

'T.cm0', 'T.cm1', 'T.cm2',
'Y.cm0', 'Y.cm1', 'Y.cm2',
]))

f.groups['public.kern1.cl_cy'] = sorted(set((
    'Djecyrillic.cl0', 'Tecyrillic.cl0', 'Efcyrillic.cl0',
    'vecyrillic.cl0',  'gecyrillic.cl0', 'gjecyrillic.cl0',
    'efcyrillic.cl0', 'vecyrillic.cl0', 
    'Acyrillic.cl0', 'Becyrillic.cl0', 'Checyrillic.cl0', 'Dzecyrillic.cl0', 'Ecyrillic.cl0', 'Elcyrillic.cl0', 'Emcyrillic.cl0', 'Encyrillic.cl0', 'Ereversedcyrillic.cl0', 'Escyrillic.cl0', 'Hardsigncyrillic.cl0', 'IAcyrillic.cl0', 'IEgravecyrillic.cl0', 'IUcyrillic.cl0', 'Icyrillic.cl0', 'Iecyrillic.cl0', 'Igravecyrillic.cl0', 'Iicyrillic.cl0', 'Iishortcyrillic.cl0', 'Iocyrillic.cl0', 'Jecyrillic.cl0', 'Kacyrillic.cl0', 'Khacyrillic.cl0', 'Kjecyrillic.cl0', 'Ljecyrillic.cl0', 'Njecyrillic.cl0', 'Ocyrillic.cl0', 'Pecyrillic.cl0', 'Softsigncyrillic.cl0', 'Tshecyrillic.cl0', 'Vecyrillic.cl0', 'Yericyrillic.cl0', 'Yicyrillic.cl0', 'Zecyrillic.cl0', 'Zhecyrillic.cl0', 'acyrillic.cl0', 'becyrillic.cl0', 'checyrillic.cl0', 'chedescendercyrillic.cl0', 'decyrillic.cl0', 'djecyrillic.cl0', 'dzecyrillic.cl0', 'dzhecyrillic.cl0', 'ecyrillic.cl0', 'elcyrillic.cl0', 'emcyrillic.cl0', 'encyrillic.cl0', 'ercyrillic.cl0', 'escyrillic.cl0', 'hadescendercyrillic.cl0', 'hardsigncyrillic.cl0', 'iacyrillic.cl0', 'icyrillic.cl0', 'iecyrillic.cl0', 'iegravecyrillic.cl0', 'igravecyrillic.cl0', 'iicyrillic.cl0', 'iishortcyrillic.cl0', 'iocyrillic.cl0', 'iucyrillic.cl0', 'jecyrillic.cl0', 'kacyrillic.cl0', 'kadescendercyrillic.cl0', 'khacyrillic.cl0', 'kjecyrillic.cl0', 'ljecyrillic.cl0', 'njecyrillic.cl0', 'ocyrillic.cl0', 'pecyrillic.cl0', 'shacyrillic.cl0', 'shchacyrillic.cl0', 'softsigncyrillic.cl0', 'tecyrillic.cl0', 'tsecyrillic.cl0', 'tshecyrillic.cl0', 'ucyrillic.cl0', 'ushortcyrillic.cl0', 'ustraightstrokecyrillic.cl0', 'yericyrillic.cl0', 'yicyrillic.cl0', 'zecyrillic.cl0', 'zhecyrillic.cl0', 'zhedescendercyrillic.cl0')))
f.groups['public.kern1.cm_cy'] = sorted(set((
    'Djecyrillic.cm0', 'Djecyrillic.cm1', 'Djecyrillic.cm2',
    'Dzecyrillic.cm0', 'Dzecyrillic.cm1', 'Dzecyrillic.cm2',
    'Icyrillic.cm0', 'Icyrillic.cm1', 'Icyrillic.cm2',
    'Yicyrillic.cm0', 'Yicyrillic.cm1', 'Yicyrillic.cm2',
    'Jecyrillic.cm0', 'Jecyrillic.cm1', 'Jecyrillic.cm2',
    'Ljecyrillic.cm0', 'Ljecyrillic.cm1', 'Ljecyrillic.cm2',
    'Njecyrillic.cm0', 'Njecyrillic.cm1', 'Njecyrillic.cm2',
    'Tshecyrillic.cm0', 'Tshecyrillic.cm1', 'Tshecyrillic.cm2',
    'Acyrillic.cm0', 'Acyrillic.cm1', 'Acyrillic.cm2',
    'Becyrillic.cm0', 'Becyrillic.cm1', 'Becyrillic.cm2',
    'Vecyrillic.cm0', 'Vecyrillic.cm1', 'Vecyrillic.cm2',
    'Iecyrillic.cm0', 'Iecyrillic.cm1', 'Iecyrillic.cm2',
    'IEgravecyrillic.cm0', 'IEgravecyrillic.cm1', 'IEgravecyrillic.cm2',
    'Iocyrillic.cm0', 'Iocyrillic.cm1', 'Iocyrillic.cm2',
    'Zhecyrillic.cm0', 'Zhecyrillic.cm1', 'Zhecyrillic.cm2',
    'Zecyrillic.cm0', 'Zecyrillic.cm1', 'Zecyrillic.cm2',
    'Iicyrillic.cm0', 'Iicyrillic.cm1', 'Iicyrillic.cm2',
    'Igravecyrillic.cm0', 'Igravecyrillic.cm1', 'Igravecyrillic.cm2',
    'Iishortcyrillic.cm0', 'Iishortcyrillic.cm1', 'Iishortcyrillic.cm2',
    'Kacyrillic.cm0', 'Kacyrillic.cm1', 'Kacyrillic.cm2',
    'Kjecyrillic.cm0', 'Kjecyrillic.cm1', 'Kjecyrillic.cm2',
    'Elcyrillic.cm0', 'Elcyrillic.cm1', 'Elcyrillic.cm2',
    'Emcyrillic.cm0', 'Emcyrillic.cm1', 'Emcyrillic.cm2',
    'Encyrillic.cm0', 'Encyrillic.cm1', 'Encyrillic.cm2',
    'Ocyrillic.cm0', 'Ocyrillic.cm1', 'Ocyrillic.cm2',
    'Pecyrillic.cm0', 'Pecyrillic.cm1', 'Pecyrillic.cm2',
    'Ercyrillic.cm0', 'Ercyrillic.cm1', 'Ercyrillic.cm2',
    'Escyrillic.cm0', 'Escyrillic.cm1', 'Escyrillic.cm2',
    'Tecyrillic.cm0', 'Tecyrillic.cm1', 'Tecyrillic.cm2',
    'Ucyrillic.cm0', 'Ucyrillic.cm1', 'Ucyrillic.cm2',
    'Ushortcyrillic.cm0', 'Ushortcyrillic.cm1', 'Ushortcyrillic.cm2',
    'Efcyrillic.cm0', 'Efcyrillic.cm1', 'Efcyrillic.cm2',
    'Khacyrillic.cm0', 'Khacyrillic.cm1', 'Khacyrillic.cm2',
    'Checyrillic.cm0', 'Checyrillic.cm1', 'Checyrillic.cm2',
    'Hardsigncyrillic.cm0', 'Hardsigncyrillic.cm1', 'Hardsigncyrillic.cm2',
    'Yericyrillic.cm0', 'Yericyrillic.cm1', 'Yericyrillic.cm2',
    'Softsigncyrillic.cm0', 'Softsigncyrillic.cm1', 'Softsigncyrillic.cm2',
    'Ereversedcyrillic.cm0', 'Ereversedcyrillic.cm1', 'Ereversedcyrillic.cm2',
    'IUcyrillic.cm0', 'IUcyrillic.cm1', 'IUcyrillic.cm2',
    'IAcyrillic.cm0', 'IAcyrillic.cm1', 'IAcyrillic.cm2',
    'acyrillic.cm0', 'acyrillic.cm1', 'acyrillic.cm2',
    'becyrillic.cm0', 'becyrillic.cm1', 'becyrillic.cm2',
    'vecyrillic.cm0', 'vecyrillic.cm1', 'vecyrillic.cm2',
    'gecyrillic.cm0', 'gecyrillic.cm1', 'gecyrillic.cm2',
    'gjecyrillic.cm0', 'gjecyrillic.cm1', 'gjecyrillic.cm2',
    'decyrillic.cm0', 'decyrillic.cm1', 'decyrillic.cm2',
    'iecyrillic.cm0', 'iecyrillic.cm1', 'iecyrillic.cm2',
    'iegravecyrillic.cm0', 'iegravecyrillic.cm1', 'iegravecyrillic.cm2',
    'iocyrillic.cm0', 'iocyrillic.cm1', 'iocyrillic.cm2',
    'zhecyrillic.cm0', 'zhecyrillic.cm1', 'zhecyrillic.cm2',
    'zecyrillic.cm0', 'zecyrillic.cm1', 'zecyrillic.cm2',
    'igravecyrillic.cm0', 'igravecyrillic.cm1', 'igravecyrillic.cm2',
    'iishortcyrillic.cm0', 'iishortcyrillic.cm1', 'iishortcyrillic.cm2',
    'kacyrillic.cm0', 'kacyrillic.cm1', 'kacyrillic.cm2',
    'kjecyrillic.cm0', 'kjecyrillic.cm1', 'kjecyrillic.cm2',
    'elcyrillic.cm0', 'elcyrillic.cm1', 'elcyrillic.cm2',
    'emcyrillic.cm0', 'emcyrillic.cm1', 'emcyrillic.cm2',
    'encyrillic.cm0', 'encyrillic.cm1', 'encyrillic.cm2',
    'ocyrillic.cm0', 'ocyrillic.cm1', 'ocyrillic.cm2',
    'pecyrillic.cm0', 'pecyrillic.cm1', 'pecyrillic.cm2',
    'ercyrillic.cm0', 'ercyrillic.cm1', 'ercyrillic.cm2',
    'tecyrillic.cm0', 'tecyrillic.cm1', 'tecyrillic.cm2',
    'ucyrillic.cm0', 'ucyrillic.cm1', 'ucyrillic.cm2',
    'ushortcyrillic.cm0', 'ushortcyrillic.cm1', 'ushortcyrillic.cm2',
    'efcyrillic.cm0', 'efcyrillic.cm1', 'efcyrillic.cm2',
    'khacyrillic.cm0', 'khacyrillic.cm1', 'khacyrillic.cm2',
    'tsecyrillic.cm0', 'tsecyrillic.cm1', 'tsecyrillic.cm2',
    'checyrillic.cm0', 'checyrillic.cm1', 'checyrillic.cm2',
    'shacyrillic.cm0', 'shacyrillic.cm1', 'shacyrillic.cm2',
    'shchacyrillic.cm0', 'shchacyrillic.cm1', 'shchacyrillic.cm2',
    'hardsigncyrillic.cm0', 'hardsigncyrillic.cm1', 'hardsigncyrillic.cm2',
    'yericyrillic.cm0', 'yericyrillic.cm1', 'yericyrillic.cm2',
    'softsigncyrillic.cm0', 'softsigncyrillic.cm1', 'softsigncyrillic.cm2',
    'ereversedcyrillic.cm0', 'ereversedcyrillic.cm1', 'ereversedcyrillic.cm2',
    'ereversedcyrillic.cm0', 'ereversedcyrillic.cm1', 'ereversedcyrillic.cm2',
    'iucyrillic.cm0', 'iucyrillic.cm1', 'iucyrillic.cm2',
    'iacyrillic.cm0', 'iacyrillic.cm1', 'iacyrillic.cm2',
    'djecyrillic.cm0', 'djecyrillic.cm1', 'djecyrillic.cm2',
    'ecyrillic.cm0', 'ecyrillic.cm1', 'ecyrillic.cm2',
    'dzecyrillic.cm0', 'dzecyrillic.cm1', 'dzecyrillic.cm2',
    'icyrillic.cm0', 'icyrillic.cm1', 'icyrillic.cm2',
    'yicyrillic.cm0', 'yicyrillic.cm1', 'yicyrillic.cm2',
    'jecyrillic.cm0', 'jecyrillic.cm1', 'jecyrillic.cm2',
    'ljecyrillic.cm0', 'ljecyrillic.cm1', 'ljecyrillic.cm2',
    'njecyrillic.cm0', 'njecyrillic.cm1', 'njecyrillic.cm2',
    'tshecyrillic.cm0', 'tshecyrillic.cm1', 'tshecyrillic.cm2',
    'dzhecyrillic.cm0', 'dzhecyrillic.cm1', 'dzhecyrillic.cm2',
    'chedescendercyrillic.cm0', 'chedescendercyrillic.cm1', 'chedescendercyrillic.cm2',
    'hadescendercyrillic.cm0', 'hadescendercyrillic.cm1', 'hadescendercyrillic.cm2',
    'ustraightstrokecyrillic.cm0', 'ustraightstrokecyrillic.cm1', 'ustraightstrokecyrillic.cm2',
    'kadescendercyrillic.cm0', 'kadescendercyrillic.cm1', 'kadescendercyrillic.cm2',
    'zhedescendercyrillic.cm0', 'zhedescendercyrillic.cm1', 'zhedescendercyrillic.cm2',
    'IUcyrillic.cm0', 'IUcyrillic.cm1', 'Ocyrillic.cm0', 'Ocyrillic.cm1', 'efcyrillic.cm0', 'efcyrillic.cm1', 'ocyrillic.cm0', 'ocyrillic.cm1', 'vecyrillic.cm0', 'vecyrillic.cm1',
    'Ecyrillic.cm0', 'Ecyrillic.cm1', 'Ecyrillic.cm2', 'Acyrillic.cm0', 'Acyrillic.cm1', 'Acyrillic.cm2', 'Becyrillic.cm0', 'Becyrillic.cm1', 'Becyrillic.cm2', 
    'Checyrillic.cm0', 'Checyrillic.cm1', 'Checyrillic.cm2', 
    'Dzecyrillic.cm0', 'Dzecyrillic.cm1', 'Dzecyrillic.cm2', 
    'Ecyrillic.cm0', 'Ecyrillic.cm1', 'Ecyrillic.cm2', 
    'Elcyrillic.cm0', 'Elcyrillic.cm1', 'Elcyrillic.cm2', 
    'Emcyrillic.cm0', 'Emcyrillic.cm1', 'Emcyrillic.cm2', 
    'Encyrillic.cm0', 'Encyrillic.cm1', 'Encyrillic.cm2', 
    'Ercyrillic.cm0', 'Ercyrillic.cm1', 'Ercyrillic.cm2', 
    'Ereversedcyrillic.cm0', 'Ereversedcyrillic.cm1', 'Escyrillic.cm0', 'Escyrillic.cm1', 'Hardsigncyrillic.cm0', 'Hardsigncyrillic.cm1', 'IAcyrillic.cm0', 'IAcyrillic.cm1', 'IAcyrillic.cm2', 
    'IEgravecyrillic.cm0', 'IEgravecyrillic.cm1', 'IEgravecyrillic.cm2', 
    'Icyrillic.cm0', 'Icyrillic.cm1', 'Icyrillic.cm2', 
    'Iecyrillic.cm0', 'Iecyrillic.cm1', 'Iecyrillic.cm2', 
    'Igravecyrillic.cm0', 'Igravecyrillic.cm1', 'Igravecyrillic.cm2', 
    'Iicyrillic.cm0', 'Iicyrillic.cm1', 'Iicyrillic.cm2', 
    'Iishortcyrillic.cm0', 'Iishortcyrillic.cm1', 'Iishortcyrillic.cm2', 
    'Iocyrillic.cm0', 'Iocyrillic.cm1', 'Iocyrillic.cm2', 
    'Jecyrillic.cm0', 'Jecyrillic.cm1', 'Jecyrillic.cm2', 
    'Kacyrillic.cm0', 'Kacyrillic.cm1', 'Kacyrillic.cm2', 
    'Khacyrillic.cm0', 'Khacyrillic.cm1', 'Khacyrillic.cm2', 
    'Kjecyrillic.cm0', 'Kjecyrillic.cm1', 'Kjecyrillic.cm2', 
    'Ljecyrillic.cm0', 'Ljecyrillic.cm1', 'Ljecyrillic.cm2', 
    'Njecyrillic.cm0', 'Njecyrillic.cm1', 'Njecyrillic.cm2', 
    'Pecyrillic.cm0', 'Pecyrillic.cm1', 'Pecyrillic.cm2', 
    'Softsigncyrillic.cm0', 'Softsigncyrillic.cm1', 'Softsigncyrillic.cm2', 
    'Tshecyrillic.cm0', 'Tshecyrillic.cm1', 'Tshecyrillic.cm2', 
    'Vecyrillic.cm0', 'Vecyrillic.cm1', 'Vecyrillic.cm2', 
    'Yericyrillic.cm0', 'Yericyrillic.cm1', 'Yericyrillic.cm2', 
    'Yicyrillic.cm0', 'Yicyrillic.cm1', 'Yicyrillic.cm2', 
    'Zecyrillic.cm0', 'Zecyrillic.cm1', 'Zecyrillic.cm2', 
    'Zhecyrillic.cm0', 'Zhecyrillic.cm1', 'Zhecyrillic.cm2', 
    'acyrillic.cm0', 'acyrillic.cm1', 'acyrillic.cm2', 
    'becyrillic.cm0', 'becyrillic.cm1', 'becyrillic.cm2', 
    'checyrillic.cm0', 'checyrillic.cm1', 'checyrillic.cm2', 
    'chedescendercyrillic.cm0', 'chedescendercyrillic.cm1', 'chedescendercyrillic.cm2', 
    'decyrillic.cm0', 'decyrillic.cm1', 'decyrillic.cm2', 
    'djecyrillic.cm0', 'djecyrillic.cm1', 'djecyrillic.cm2', 
    'dzecyrillic.cm0', 'dzecyrillic.cm1', 'dzecyrillic.cm2', 
    'dzhecyrillic.cm0', 'dzhecyrillic.cm1', 'dzhecyrillic.cm2', 
    'ecyrillic.cm0', 'ecyrillic.cm1', 'ecyrillic.cm2', 
    'elcyrillic.cm0', 'elcyrillic.cm1', 'elcyrillic.cm2', 
    'emcyrillic.cm0', 'emcyrillic.cm1', 'encyrillic.cm0', 'encyrillic.cm1', 'ercyrillic.cm0', 'ercyrillic.cm1', 'escyrillic.cm0', 'escyrillic.cm1', 'gecyrillic.cm0', 'gecyrillic.cm1', 'gjecyrillic.cm0', 'gjecyrillic.cm1', 'hadescendercyrillic.cm0', 'hadescendercyrillic.cm1', 'hardsigncyrillic.cm0', 'hardsigncyrillic.cm1', 'iacyrillic.cm0', 'iacyrillic.cm1', 'icyrillic.cm0', 'icyrillic.cm1', 'iecyrillic.cm0', 'iecyrillic.cm1', 'iegravecyrillic.cm0', 'iegravecyrillic.cm1', 'igravecyrillic.cm0', 'igravecyrillic.cm1', 'iicyrillic.cm0', 'iicyrillic.cm1', 'iishortcyrillic.cm0', 'iishortcyrillic.cm1', 'iocyrillic.cm0', 'iocyrillic.cm1', 'iucyrillic.cm0', 'iucyrillic.cm1', 'jecyrillic.cm0', 'jecyrillic.cm1', 'kacyrillic.cm0', 'kacyrillic.cm1', 'kadescendercyrillic.cm0', 'kadescendercyrillic.cm1', 'khacyrillic.cm0', 'khacyrillic.cm1', 'kjecyrillic.cm0', 'kjecyrillic.cm1', 'ljecyrillic.cm0', 'ljecyrillic.cm1', 'njecyrillic.cm0', 'njecyrillic.cm1', 'pecyrillic.cm0', 'pecyrillic.cm1', 'shacyrillic.cm0', 'shacyrillic.cm1', 'shchacyrillic.cm0', 'shchacyrillic.cm1', 'softsigncyrillic.cm0', 'softsigncyrillic.cm1', 'tecyrillic.cm0', 'tecyrillic.cm1', 'tsecyrillic.cm0', 'tsecyrillic.cm1', 'tshecyrillic.cm0', 'tshecyrillic.cm1', 'ucyrillic.cm0', 'ucyrillic.cm1', 'ushortcyrillic.cm0', 'ushortcyrillic.cm1', 'ustraightstrokecyrillic.cm0', 'ustraightstrokecyrillic.cm1', 'yericyrillic.cm0', 'yericyrillic.cm1', 'yicyrillic.cm0', 'yicyrillic.cm1', 'zecyrillic.cm0', 'zecyrillic.cm1', 'zhecyrillic.cm0', 'zhecyrillic.cm1', 'zhedescendercyrillic.cm0', 'zhedescendercyrillic.cm1')))
f.groups['public.kern1.ct_cy'] = sorted(set((
    'chedescendercyrillic.ct0', 'chedescendercyrillic.ct1', 'chedescendercyrillic.ct2',
    'ustraightstrokecyrillic.ct0', 'ustraightstrokecyrillic.ct1', 'ustraightstrokecyrillic.ct2',
    'kadescendercyrillic.ct0', 'kadescendercyrillic.ct1', 'kadescendercyrillic.ct2',
    'zhedescendercyrillic.ct0', 'zhedescendercyrillic.ct1', 'zhedescendercyrillic.ct2',
    'hadescendercyrillic.ct0', 'hadescendercyrillic.ct1', 'hadescendercyrillic.ct2',
    'dzhecyrillic.ct0', 'dzhecyrillic.ct1', 'dzhecyrillic.ct2',
    'tshecyrillic.ct0', 'tshecyrillic.ct1', 'tshecyrillic.ct2',
    'njecyrillic.ct0', 'njecyrillic.ct1', 'njecyrillic.ct2',
    'ljecyrillic.ct0', 'ljecyrillic.ct1', 'ljecyrillic.ct2',
    'jecyrillic.ct0', 'jecyrillic.ct1', 'jecyrillic.ct2',
    'yicyrillic.ct0', 'yicyrillic.ct1', 'yicyrillic.ct2',
    'icyrillic.ct0', 'icyrillic.ct1', 'icyrillic.ct2',
    'dzecyrillic.ct0', 'dzecyrillic.ct1', 'dzecyrillic.ct2',
    'ecyrillic.ct0', 'ecyrillic.ct1', 'ecyrillic.ct2',
    'djecyrillic.ct0', 'djecyrillic.ct1', 'djecyrillic.ct2',
    'iucyrillic.ct0', 'iucyrillic.ct1', 'iucyrillic.ct2',
    'iacyrillic.ct0', 'iacyrillic.ct1', 'iacyrillic.ct2',
    'ereversedcyrillic.ct0', 'ereversedcyrillic.ct1', 'ereversedcyrillic.ct2',
    'softsigncyrillic.ct0', 'softsigncyrillic.ct1', 'softsigncyrillic.ct2',
    'yericyrillic.ct0', 'yericyrillic.ct1', 'yericyrillic.ct2',
    'hardsigncyrillic.ct0', 'hardsigncyrillic.ct1', 'hardsigncyrillic.ct2',
    'shchacyrillic.ct0', 'shchacyrillic.ct1', 'shchacyrillic.ct2',
    'shacyrillic.ct0', 'shacyrillic.ct1', 'shacyrillic.ct2',
    'checyrillic.ct0', 'checyrillic.ct1', 'checyrillic.ct2',
    'tsecyrillic.ct0', 'tsecyrillic.ct1', 'tsecyrillic.ct2',
    'khacyrillic.ct0', 'khacyrillic.ct1', 'khacyrillic.ct2',
    'efcyrillic.ct0', 'efcyrillic.ct1', 'efcyrillic.ct2',
    'ushortcyrillic.ct0', 'ushortcyrillic.ct1', 'ushortcyrillic.ct2',
    'ucyrillic.ct0', 'ucyrillic.ct1', 'ucyrillic.ct2',
    'tecyrillic.ct0', 'tecyrillic.ct1', 'tecyrillic.ct2',
    'escyrillic.ct0', 'escyrillic.ct1', 'escyrillic.ct2',
    'ercyrillic.ct0', 'ercyrillic.ct1', 'ercyrillic.ct2',
    'pecyrillic.ct0', 'pecyrillic.ct1', 'pecyrillic.ct2',
    'ocyrillic.ct0', 'ocyrillic.ct1', 'ocyrillic.ct2',
    'encyrillic.ct0', 'encyrillic.ct1', 'encyrillic.ct2',
    'emcyrillic.ct0', 'emcyrillic.ct1', 'emcyrillic.ct2',
    'elcyrillic.ct0', 'elcyrillic.ct1', 'elcyrillic.ct2',
    'kjecyrillic.ct0', 'kjecyrillic.ct1', 'kjecyrillic.ct2',
    'kacyrillic.ct0', 'kacyrillic.ct1', 'kacyrillic.ct2',
    'igravecyrillic.ct0', 'igravecyrillic.ct1', 'igravecyrillic.ct2',
    'iishortcyrillic.ct0', 'iishortcyrillic.ct1', 'iishortcyrillic.ct2',
    'iicyrillic.ct0', 'iicyrillic.ct1', 'iicyrillic.ct2',
    'zecyrillic.ct0', 'zecyrillic.ct1', 'zecyrillic.ct2',
    'zhecyrillic.ct0', 'zhecyrillic.ct1', 'zhecyrillic.ct2',
    'iocyrillic.ct0', 'iocyrillic.ct1', 'iocyrillic.ct2',
    'iecyrillic.ct0', 'iecyrillic.ct1', 'iecyrillic.ct2',
    'iecyrillic.ct0', 'iecyrillic.ct1', 'iecyrillic.ct2',
    'decyrillic.ct0', 'decyrillic.ct1', 'decyrillic.ct2',
    'gjecyrillic.ct0', 'gjecyrillic.ct1', 'gjecyrillic.ct2',
    'gecyrillic.ct0', 'gecyrillic.ct1', 'gecyrillic.ct2',
    'vecyrillic.ct0', 'vecyrillic.ct1', 'vecyrillic.ct2',
    'becyrillic.ct0', 'becyrillic.ct1', 'becyrillic.ct2',
    'acyrillic.ct0', 'acyrillic.ct1', 'acyrillic.ct2',
    'IAcyrillic.ct0', 'IAcyrillic.ct1', 'IAcyrillic.ct2',
    'IUcyrillic.ct0', 'IUcyrillic.ct1', 'IUcyrillic.ct2',
    'Ereversedcyrillic.ct0', 'Ereversedcyrillic.ct1', 'Ereversedcyrillic.ct2',
    'Softsigncyrillic.ct0', 'Softsigncyrillic.ct1', 'Softsigncyrillic.ct2',
    'Yericyrillic.ct0', 'Yericyrillic.ct1', 'Yericyrillic.ct2',
    'Hardsigncyrillic.ct0', 'Hardsigncyrillic.ct1', 'Hardsigncyrillic.ct2',
    'Djecyrillic.ct0', 'Djecyrillic.ct1', 'Djecyrillic.ct2',
    'Dzecyrillic.ct0', 'Dzecyrillic.ct1', 'Dzecyrillic.ct2',
    'Icyrillic.ct0', 'Icyrillic.ct1', 'Icyrillic.ct2',
    'Yicyrillic.ct0', 'Yicyrillic.ct1', 'Yicyrillic.ct2',
    'Jecyrillic.ct0', 'Jecyrillic.ct1', 'Jecyrillic.ct2',
    'Ljecyrillic.ct0', 'Ljecyrillic.ct1', 'Ljecyrillic.ct2',
    'Njecyrillic.ct0', 'Njecyrillic.ct1', 'Njecyrillic.ct2',
    'Tshecyrillic.ct0', 'Tshecyrillic.ct1', 'Tshecyrillic.ct2',
    'Acyrillic.ct0', 'Acyrillic.ct1', 'Acyrillic.ct2',
    'Becyrillic.ct0', 'Becyrillic.ct1', 'Becyrillic.ct2',
    'Vecyrillic.ct0', 'Vecyrillic.ct1', 'Vecyrillic.ct2',
    'Iecyrillic.ct0', 'Iecyrillic.ct1', 'Iecyrillic.ct2',
    'IEgravecyrillic.ct0', 'IEgravecyrillic.ct1', 'IEgravecyrillic.ct2',
    'Iocyrillic.ct0', 'Iocyrillic.ct1', 'Iocyrillic.ct2',
    'Zhecyrillic.ct0', 'Zhecyrillic.ct1', 'Zhecyrillic.ct2',
    'Zecyrillic.ct0', 'Zecyrillic.ct1', 'Zecyrillic.ct2',
    'Iicyrillic.ct0', 'Iicyrillic.ct1', 'Iicyrillic.ct2',
    'Igravecyrillic.ct0', 'Igravecyrillic.ct1', 'Igravecyrillic.ct2',
    'Iishortcyrillic.ct0', 'Iishortcyrillic.ct1', 'Iishortcyrillic.ct2',
    'Kacyrillic.ct0', 'Kacyrillic.ct1', 'Kacyrillic.ct2',
    'Kjecyrillic.ct0', 'Kjecyrillic.ct1', 'Kjecyrillic.ct2',
    'Elcyrillic.ct0', 'Elcyrillic.ct1', 'Elcyrillic.ct2',
    'Emcyrillic.ct0', 'Emcyrillic.ct1', 'Emcyrillic.ct2',
    'Encyrillic.ct0', 'Encyrillic.ct1', 'Encyrillic.ct2',
    'Ocyrillic.ct0', 'Ocyrillic.ct1', 'Ocyrillic.ct2',
    'Pecyrillic.ct0', 'Pecyrillic.ct1', 'Pecyrillic.ct2',
    'Ercyrillic.ct0', 'Ercyrillic.ct1', 'Ercyrillic.ct2',
    'Escyrillic.ct0', 'Escyrillic.ct1', 'Escyrillic.ct2',
    'Tecyrillic.ct0', 'Tecyrillic.ct1', 'Tecyrillic.ct2',
    'Ucyrillic.ct0', 'Ucyrillic.ct1', 'Ucyrillic.ct2',
    'Efcyrillic.ct0', 'Efcyrillic.ct1', 'Efcyrillic.ct2',
    'Khacyrillic.ct0', 'Khacyrillic.ct1', 'Khacyrillic.ct2',
    'Checyrillic.ct0', 'Checyrillic.ct1', 'Checyrillic.ct2',
    'Ushortcyrillic.ct0', 'Ushortcyrillic.ct1', 'Ushortcyrillic.ct2',
    'Ushortcyrillic.ct0', 'Ushortcyrillic.ct1', 'Ushortcyrillic.ct2',
    'Ecyrillic.ct0', 'Ecyrillic.ct1', 'Djecyrillic.ct2', 'Acyrillic.ct0', 'Acyrillic.ct1', 'Acyrillic.ct2', 'Becyrillic.ct0', 'Becyrillic.ct1', 'Becyrillic.ct2', 'Checyrillic.ct0', 'Checyrillic.ct1', 'Checyrillic.ct2', 'Dzecyrillic.ct0', 'Dzecyrillic.ct1', 'Dzecyrillic.ct2', 'Ecyrillic.ct0', 'Ecyrillic.ct1', 'Ecyrillic.ct2', 'Elcyrillic.ct0', 'Elcyrillic.ct1', 'Elcyrillic.ct2', 'Emcyrillic.ct0', 'Emcyrillic.ct1', 'Emcyrillic.ct2', 'Encyrillic.ct0', 'Encyrillic.ct1', 'Encyrillic.ct2', 'Ercyrillic.ct0', 'Ercyrillic.ct1', 'Ercyrillic.ct2', 'Ereversedcyrillic.ct0', 'Ereversedcyrillic.ct1', 'Ereversedcyrillic.ct2', 'Escyrillic.ct0', 'Escyrillic.ct1', 'Escyrillic.ct2', 'Hardsigncyrillic.ct0', 'Hardsigncyrillic.ct1', 'Hardsigncyrillic.ct2', 'IAcyrillic.ct0', 'IAcyrillic.ct1', 'IAcyrillic.ct2', 'IEgravecyrillic.ct0', 'IEgravecyrillic.ct1', 'IEgravecyrillic.ct2', 'IUcyrillic.ct0', 'IUcyrillic.ct1', 'IUcyrillic.ct2', 'Icyrillic.ct0', 'Icyrillic.ct1', 'Icyrillic.ct2', 'Iecyrillic.ct0', 'Iecyrillic.ct1', 'Iecyrillic.ct2', 'Igravecyrillic.ct0', 'Igravecyrillic.ct1', 'Igravecyrillic.ct2', 'Iicyrillic.ct0', 'Iicyrillic.ct1', 'Iicyrillic.ct2', 'Iishortcyrillic.ct0', 'Iishortcyrillic.ct1', 'Iishortcyrillic.ct2', 'Iocyrillic.ct0', 'Iocyrillic.ct1', 'Iocyrillic.ct2', 'Jecyrillic.ct0', 'Jecyrillic.ct1', 'Jecyrillic.ct2', 'Kacyrillic.ct0', 'Kacyrillic.ct1', 'Kacyrillic.ct2', 'Khacyrillic.ct0', 'Khacyrillic.ct1', 'Khacyrillic.ct2', 'Kjecyrillic.ct0', 'Kjecyrillic.ct1', 'Kjecyrillic.ct2', 'Ljecyrillic.ct0', 'Ljecyrillic.ct1', 'Ljecyrillic.ct2', 'Njecyrillic.ct0', 'Njecyrillic.ct1', 'Njecyrillic.ct2', 'Ocyrillic.ct0', 'Ocyrillic.ct1', 'Ocyrillic.ct2', 'Pecyrillic.ct0', 'Pecyrillic.ct1', 'Pecyrillic.ct2', 'Softsigncyrillic.ct0', 'Softsigncyrillic.ct1', 'Softsigncyrillic.ct2', 'Tshecyrillic.ct0', 'Tshecyrillic.ct1', 'Tshecyrillic.ct2', 'Vecyrillic.ct0', 'Vecyrillic.ct1', 'Vecyrillic.ct2', 'Yericyrillic.ct0', 'Yericyrillic.ct1', 'Yericyrillic.ct2', 'Yicyrillic.ct0', 'Yicyrillic.ct1', 'Yicyrillic.ct2', 'Zecyrillic.ct0', 'Zecyrillic.ct1', 'Zecyrillic.ct2', 'Zhecyrillic.ct0', 'Zhecyrillic.ct1', 'Zhecyrillic.ct2', 'acyrillic.ct0', 'acyrillic.ct1', 'acyrillic.ct2', 'becyrillic.ct0', 'becyrillic.ct1', 'becyrillic.ct2', 'checyrillic.ct0', 'checyrillic.ct1', 'checyrillic.ct2', 'chedescendercyrillic.ct0', 'chedescendercyrillic.ct1', 'chedescendercyrillic.ct2', 'decyrillic.ct0', 'decyrillic.ct1', 'decyrillic.ct2', 'djecyrillic.ct0', 'djecyrillic.ct1', 'djecyrillic.ct2', 'dzecyrillic.ct0', 'dzecyrillic.ct1', 'dzecyrillic.ct2', 'dzhecyrillic.ct0', 'dzhecyrillic.ct1', 'dzhecyrillic.ct2', 'ecyrillic.ct0', 'ecyrillic.ct1', 'ecyrillic.ct2', 'efcyrillic.ct0', 'efcyrillic.ct1', 'efcyrillic.ct2', 'elcyrillic.ct0', 'elcyrillic.ct1', 'elcyrillic.ct2', 'emcyrillic.ct0', 'emcyrillic.ct1', 'emcyrillic.ct2', 'encyrillic.ct0', 'encyrillic.ct1', 'encyrillic.ct2', 'ercyrillic.ct0', 'ercyrillic.ct1', 'ercyrillic.ct2', 'escyrillic.ct0', 'escyrillic.ct1', 'escyrillic.ct2', 'gecyrillic.ct0', 'gecyrillic.ct1', 'gecyrillic.ct2', 'gjecyrillic.ct0', 'gjecyrillic.ct1', 'gjecyrillic.ct2', 'hadescendercyrillic.ct0', 'hadescendercyrillic.ct1', 'hadescendercyrillic.ct2', 'hardsigncyrillic.ct0', 'hardsigncyrillic.ct1', 'hardsigncyrillic.ct2', 'iacyrillic.ct0', 'iacyrillic.ct1', 'iacyrillic.ct2', 'icyrillic.ct0', 'icyrillic.ct1', 'icyrillic.ct2', 'iecyrillic.ct0', 'iecyrillic.ct1', 'iecyrillic.ct2', 'iegravecyrillic.ct0', 'iegravecyrillic.ct1', 'iegravecyrillic.ct2', 'igravecyrillic.ct0', 'igravecyrillic.ct1', 'igravecyrillic.ct2', 'iicyrillic.ct0', 'iicyrillic.ct1', 'iicyrillic.ct2', 'iishortcyrillic.ct0', 'iishortcyrillic.ct1', 'iishortcyrillic.ct2', 'iocyrillic.ct0', 'iocyrillic.ct1', 'iocyrillic.ct2', 'iucyrillic.ct0', 'iucyrillic.ct1', 'iucyrillic.ct2', 'jecyrillic.ct0', 'jecyrillic.ct1', 'jecyrillic.ct2', 'kacyrillic.ct0', 'kacyrillic.ct1', 'kacyrillic.ct2', 'kadescendercyrillic.ct0', 'kadescendercyrillic.ct1', 'kadescendercyrillic.ct2', 'khacyrillic.ct0', 'khacyrillic.ct1', 'khacyrillic.ct2', 'kjecyrillic.ct0', 'kjecyrillic.ct1', 'kjecyrillic.ct2', 'ljecyrillic.ct0', 'ljecyrillic.ct1', 'ljecyrillic.ct2', 'njecyrillic.ct0', 'njecyrillic.ct1', 'njecyrillic.ct2', 'ocyrillic.ct0', 'ocyrillic.ct1', 'ocyrillic.ct2', 'pecyrillic.ct0', 'pecyrillic.ct1', 'pecyrillic.ct2', 'shacyrillic.ct0', 'shacyrillic.ct1', 'shacyrillic.ct2', 'shchacyrillic.ct0', 'shchacyrillic.ct1', 'shchacyrillic.ct2', 'softsigncyrillic.ct0', 'softsigncyrillic.ct1', 'softsigncyrillic.ct2', 'tecyrillic.ct0', 'tecyrillic.ct1', 'tecyrillic.ct2', 'tsecyrillic.ct0', 'tsecyrillic.ct1', 'tsecyrillic.ct2', 'tshecyrillic.ct0', 'tshecyrillic.ct1', 'tshecyrillic.ct2', 'ucyrillic.ct0', 'ucyrillic.ct1', 'ucyrillic.ct2', 'ushortcyrillic.ct0', 'ushortcyrillic.ct1', 'ushortcyrillic.ct2', 'ustraightstrokecyrillic.ct0', 'ustraightstrokecyrillic.ct1', 'ustraightstrokecyrillic.ct2', 'vecyrillic.ct0', 'vecyrillic.ct1', 'vecyrillic.ct2', 'yericyrillic.ct0', 'yericyrillic.ct1', 'yericyrillic.ct2', 'yicyrillic.ct0', 'yicyrillic.ct1', 'yicyrillic.ct2', 'zecyrillic.ct0', 'zecyrillic.ct1', 'zecyrillic.ct2', 'zhecyrillic.ct0', 'zhecyrillic.ct1', 'zhecyrillic.ct2', 'zhedescendercyrillic.ct0', 'zhedescendercyrillic.ct1', 'zhedescendercyrillic.ct2')))

f.groups['public.kern1.cm_gr'] = sorted(set((
    'Upsilon.cm0', 'Upsilon.cm1', 'Upsilon.cm2',
    'Upsilondieresis.cm0', 'Upsilondieresis.cm1', 'Upsilondieresis.cm2',
    'Upsilontonos.cm0', 'Upsilontonos.cm1', 'Upsilontonos.cm2', 'Alpha.cm0', 'Alpha.cm1', 'Alpha.cm2', 'Alphatonos.cm0', 'Alphatonos.cm1', 'Alphatonos.cm2', 'Beta.cm0', 'Beta.cm1', 'Beta.cm2', 'Chi.cm0', 'Chi.cm1', 'Chi.cm2', 'Delta.cm0', 'Delta.cm1', 'Delta.cm2', 'Epsilon.cm0', 'Epsilon.cm1', 'Epsilon.cm2', 'Epsilontonos.cm0', 'Epsilontonos.cm1', 'Epsilontonos.cm2', 'Eta.cm0', 'Eta.cm1', 'Eta.cm2', 'Etatonos.cm0', 'Etatonos.cm1', 'Etatonos.cm2', 'Iota.cm0', 'Iota.cm1', 'Iota.cm2', 'Iotadieresis.cm0', 'Iotadieresis.cm1', 'Iotadieresis.cm2', 'Iotatonos.cm0', 'Iotatonos.cm1', 'Iotatonos.cm2', 'Kappa.cm0', 'Kappa.cm1', 'Kappa.cm2', 'Lambda.cm0', 'Lambda.cm1', 'Lambda.cm2', 'Mu.cm0', 'Mu.cm1', 'Mu.cm2', 'Nu.cm0', 'Nu.cm1', 'Nu.cm2', 'Omega.cm0', 'Omega.cm1', 'Omega.cm2', 'Omegatonos.cm0', 'Omegatonos.cm1', 'Omegatonos.cm2', 'Omicron.cm0', 'Omicron.cm1', 'Omicron.cm2', 'Omicrontonos.cm0', 'Omicrontonos.cm1', 'Omicrontonos.cm2', 'Pi.cm0', 'Pi.cm1', 'Pi.cm2', 'Psi.cm0', 'Psi.cm1', 'Psi.cm2', 'Rho.cm0', 'Rho.cm1', 'Rho.cm2', 'Sigma.cm0', 'Sigma.cm1', 'Sigma.cm2', 'Theta.cm0', 'Theta.cm1', 'Theta.cm2', 'Xi.cm0', 'Xi.cm1', 'Xi.cm2', 'Zeta.cm0', 'Zeta.cm1', 'Zeta.cm2', 'alpha.cm0', 'alpha.cm1', 'alpha.cm2', 'alphatonos.cm0', 'alphatonos.cm1', 'alphatonos.cm2', 'beta.cm0', 'beta.cm1', 'beta.cm2', 'chi.cm0', 'chi.cm1', 'chi.cm2', 'delta.cm0', 'delta.cm1', 'delta.cm2', 'epsilon.cm0', 'epsilon.cm1', 'epsilon.cm2', 'epsilontonos.cm0', 'epsilontonos.cm1', 'epsilontonos.cm2', 'eta.cm0', 'eta.cm1', 'eta.cm2', 'etatonos.cm0', 'etatonos.cm1', 'etatonos.cm2', 'gamma.cm0', 'gamma.cm1', 'gamma.cm2', 'iota.cm0', 'iota.cm1', 'iota.cm2', 'iotadieresis.cm0', 'iotadieresis.cm1', 'iotadieresis.cm2', 'iotadieresistonos.cm0', 'iotadieresistonos.cm1', 'iotadieresistonos.cm2', 'iotatonos.cm0', 'iotatonos.cm1', 'iotatonos.cm2', 'kappa.cm0', 'kappa.cm1', 'kappa.cm2', 'lambda.cm0', 'lambda.cm1', 'lambda.cm2', 'mu.cm0', 'mu.cm1', 'mu.cm2', 'nu.cm0', 'nu.cm1', 'nu.cm2', 'omega.cm0', 'omega.cm1', 'omega.cm2', 'omegatonos.cm0', 'omegatonos.cm1', 'omegatonos.cm2', 'omicron.cm0', 'omicron.cm1', 'omicron.cm2', 'omicrontonos.cm0', 'omicrontonos.cm1', 'omicrontonos.cm2', 'pi.cm0', 'pi.cm1', 'pi.cm2', 'psi.cm0', 'psi.cm1', 'psi.cm2', 'rho.cm0', 'rho.cm1', 'rho.cm2', 'sigma.cm0', 'sigma.cm1', 'sigma.cm2', 'tau.cm0', 'tau.cm1', 'tau.cm2', 'theta.cm0', 'theta.cm1', 'theta.cm2', 'xi.cm0', 'xi.cm1', 'xi.cm2', 'zeta.cm0', 'zeta.cm1', 'zeta.cm2')))

f.groups['public.kern1.ct_gr'] = sorted(set((
    'Upsilon.ct0', 'Upsilon.ct1', 'Upsilon.ct2',
    'Upsilondieresis.ct0', 'Upsilondieresis.ct1', 'Upsilondieresis.ct2',
    'Upsilontonos.ct0', 'Upsilontonos.ct1', 'Upsilontonos.ct2', 'Alpha.ct0', 'Alpha.ct1', 'Alpha.ct2', 'Alphatonos.ct0', 'Alphatonos.ct1', 'Alphatonos.ct2', 'Beta.ct0', 'Beta.ct1', 'Beta.ct2', 'Chi.ct0', 'Chi.ct1', 'Chi.ct2', 'Delta.ct0', 'Delta.ct1', 'Delta.ct2', 'Epsilon.ct0', 'Epsilon.ct1', 'Epsilon.ct2', 'Epsilontonos.ct0', 'Epsilontonos.ct1', 'Epsilontonos.ct2', 'Eta.ct0', 'Eta.ct1', 'Eta.ct2', 'Etatonos.ct0', 'Etatonos.ct1', 'Etatonos.ct2', 'Iota.ct0', 'Iota.ct1', 'Iota.ct2', 'Iotadieresis.ct0', 'Iotadieresis.ct1', 'Iotadieresis.ct2', 'Iotatonos.ct0', 'Iotatonos.ct1', 'Iotatonos.ct2', 'Kappa.ct0', 'Kappa.ct1', 'Kappa.ct2', 'Lambda.ct0', 'Lambda.ct1', 'Lambda.ct2', 'Mu.ct0', 'Mu.ct1', 'Mu.ct2', 'Nu.ct0', 'Nu.ct1', 'Nu.ct2', 'Omega.ct0', 'Omega.ct1', 'Omega.ct2', 'Omegatonos.ct0', 'Omegatonos.ct1', 'Omegatonos.ct2', 'Omicron.ct0', 'Omicron.ct1', 'Omicron.ct2', 'Omicrontonos.ct0', 'Omicrontonos.ct1', 'Omicrontonos.ct2', 'Pi.ct0', 'Pi.ct1', 'Pi.ct2', 'Psi.ct0', 'Psi.ct1', 'Psi.ct2', 'Rho.ct0', 'Rho.ct1', 'Rho.ct2', 'Sigma.ct0', 'Sigma.ct1', 'Sigma.ct2', 'Theta.ct0', 'Theta.ct1', 'Theta.ct2', 'Xi.ct0', 'Xi.ct1', 'Xi.ct2', 'Zeta.ct0', 'Zeta.ct1', 'Zeta.ct2', 'alpha.ct0', 'alpha.ct1', 'alpha.ct2', 'alphatonos.ct0', 'alphatonos.ct1', 'alphatonos.ct2', 'beta.ct0', 'beta.ct1', 'beta.ct2', 'chi.ct0', 'chi.ct1', 'chi.ct2', 'epsilon.ct0', 'epsilon.ct1', 'epsilon.ct2', 'epsilontonos.ct0', 'epsilontonos.ct1', 'epsilontonos.ct2', 'eta.ct0', 'eta.ct1', 'eta.ct2', 'etatonos.ct0', 'etatonos.ct1', 'etatonos.ct2', 'gamma.ct0', 'gamma.ct1', 'gamma.ct2', 'iota.ct0', 'iota.ct1', 'iota.ct2', 'iotadieresis.ct0', 'iotadieresis.ct1', 'iotadieresis.ct2', 'iotadieresistonos.ct0', 'iotadieresistonos.ct1', 'iotadieresistonos.ct2', 'iotatonos.ct0', 'iotatonos.ct1', 'iotatonos.ct2', 'kappa.ct0', 'kappa.ct1', 'kappa.ct2', 'lambda.ct0', 'lambda.ct1', 'lambda.ct2', 'mu.ct0', 'mu.ct1', 'mu.ct2', 'pi.ct0', 'pi.ct1', 'pi.ct2', 'rho.ct0', 'rho.ct1', 'rho.ct2', 'tau.ct0', 'tau.ct1', 'tau.ct2', 'theta.ct0', 'theta.ct1', 'theta.ct2', 'xi.ct0', 'xi.ct1', 'xi.ct2', 'zeta.ct0', 'zeta.ct1', 'zeta.ct2')))


if SAVE:
    f.save()
    f.close()
