# -*- coding: UTF-8 -*-
# ------------------------------------------------------------------------------
#     Copyright (c) 2023+ TYPETR
#     Usage by MIT License
# ..............................................................................

# Kerning samples as plain strings. These will be translated by the Kerning class into lists of glyph names.
# There we also can define alternative names and open type feature variants.

PRE = """HHOOHOHOVOXOXHnInOn hradišťský tchaj-ťi šťuka aukščiausiųjų ď.ď,ď:ď;ď?ď!ď”ď“ď™ď®ď)ď}ď]ť.ť,ť;ť:ť?ť!ť”ť“ť™ť®ť)ť}ť]ľ.ľ,ľ:ľ;ľ?ľ!ľ”ľ“ľ™ľ®ľ)ľ}ľ] ďaďáďkďmďnďoďsďtďuďžđďiďjď!ľ?ľ!ľiľjť?ť!ťiťjiťk ïlïbïkïl"ī"/ī/\\ī\\(ī)[ī]{ī}ïlïbïkïl"ï"/ï/\\ï\\(ï)[ï]{ï}fífìfîfïfīffĩfíffìffîffïffīffĩ fît(French), fìsica(Corsican), fīča(Latvian), ffïon(Welsh) L‌̧l‌̧M̧ajelm̧N‌̧n‌̧O̧o̧ĀāN̄n̄ŌōŪūĄąĄ́ą́ĘęĘ́ę́ĮįĮ́į́ǪǫǪ́ǫ́G̃g̃ lijst lĳst LIJST LĲST AªAºA F/F.F,FaFbFcFdFeFfFgFhFiFjFkFlFmFnFoFpFqFrFsFtFuFvFwFxFyFzFT/T.T,ToTnTsTuTnTvTzFuiFzFxFŝiFšiFsiFeiFoiFAiFàiFaiFâiFäiFăiF,iF.iFgiFmiFniFœFøFřT/T.T,TaTbTcTdTeTfTgThTiTjTkTlTmTnToTpTqTrTsTtTuTvTwTxTyTzTV/V.V,VaVbVcVdVeVfVgVhViVjVkVlVmVnVoVpVqVrVsVtVuVvVwVxVyVzVW/W.W,WaWbWcWdWeWfWgWhWiWjWkWlWmWnWoWpWqWrWsWtWuWvWwWxWyWzWY/Y.Y,YaYbYcYdYeYfYgYhYiYjYkYlYmYnYoYpYqYrYsYtYuYvYwYxYyYzY""" # Add as pre-test
LC = """aaeaoaiauacadahamanarasatabagafalapavawayajakaqaxazaeeoeieuecedehemeneresetebegefelepeveweyejekeqeexezeooiouocodohomonorosotobogofolopovowoyojokoqoxozoiiuicidihiminirisitibigifilipiviwiyijikiqixiziuucuduhumunurusutubugufulupuvuwuyujukuquxuzuccdchcmcncrcsctcbcgcfclcpcvcwcycjckcqcxczcddhdmdndrdsdtdbdgdfdldpdvdwdydjdkdqdxdzdhhmhnhrhshthbhghfhlhphvhwhyhjhkhqhxhzhmmmnmrmsmtmbmgmfmlmpmvmwmymjmkmqmxmzmnnrnsntnbngnfnlnpnvnwnynjnknqnxnznrrsrtrbrgrfrlrprvrwryrjrkrqrxrzrsstsbsgsfslspsvswsysjsksqsxszsttbtgtftltptvtwtytjtktqtxtztbbgbfblbpbvbwbybjbkbqbxbzbggfglgpgvgwgygjgkgqgxgzgfflfpfvfwfyfjfkfqfxfzfllplvlwlyljlkllqlxlzlppvpwpypjpkpqppxpzpvvwvyvjvkvqvxvzvyywyyyjykyqyxyzyjjkjqjxjzjkkkqkxkzkqqxqzqxxzxzzaaeaoaiauacadahamanaraasatabagafalapavawayajakaqaxaeazaeeoeieuecedehemeneresetebegefelepeveweyejekeqeexezeooiouocodohomonoroosotobogofolopovowoyojokoqooxozoiiuicidihiminirisiitibigifilipiviwiyijikiqixiziuucuduhumunurusutuubugufuulupuvuwuyujukuquxuzucccdchcmcncrcsctcbcgcfclccpcvcwcycjckcqcxczcddhdmdnddrdsdtdbdgdfdldpdvdwdydjddkdqdxdzdhhmhnhrhshthbhgfhlhphvhwhyhjhkhqhxhzhmmnmrmsmtmbmgmfmlmpmvmwmymmjmkmqmxmzmnnrnsntnbngnfnlnpnvnwnynjnknqnxnznrrsrrtrbrgrfrlrprvrwryrjrkrrqrxrzrsstsbsgsfslspsvswsyssjsksqsxszsttbtgtftltptvtwttytjtktqtxtztbbgbfblbpbbvbwbybjbkbqbxbzbggfglgpggvgwgygjgkgqgxgzgfflfpfvffwfyfjfkfqfxfzfllplvlwlyljllklqlxlzlppvpwpypjpkpqppxpzpvvwvyvjvkvqvxvzvyywyyyjykyqyxyzyjjkjqjxjzjkkkqkkxkzkqqxqzqxxzxzz he is but an it at the she do on his not like of the mare as they can both be for or be in with his too in from were by only some her have to after that than which you also had either.\n\n"""
LC_ACCENTS = """ááábáčáéáðáfáháiáíájákáláľáňáñáóářášátáťáþážăbăfăiăjălătățâbâfâğâiâkâlâtâțäääbäčäfäßähäiäjäkäläöätäťàààbàfàhàiàlàtābāčāfāģāiājākāķālāļāšātāžåååbåfåhåiåjåkålåtćbćfćićjćkćlčáčāčbčččėčēčfčičíčīčjčkčlčľčňčřčščtčúčūčůċċċħċiċjċkċlċtdádădâdädàdādådãdčdédědëdèdēdħdîdìdīdňdôdödòdődõdřdšdüdùdūdůdžďaďáďkďmďnďoďsďtďuďžđďiďjď!ľ?ľ!ľiľjť?ť!ťiťjiéáéâéåébéčéééèéðéféhéiéjékéléřéšétéüéžěběčěďěhějěkělěňěřěšětěťěžêiêlêtëbëfëhëiëjëkëlëtėčėiėjėšėtėžèbèfèièjèlètēbēfēģējēkēķēlēļēšētēžðáðíðóðöfáfăfâfäfàfāfåfãféfêfëfėfèfēfħfífīfňfóföfòfőfõfšfúfûfüfűfūfůğbğfğiğlğtğüģāģēģīġàġġġiġjġtġżßöháħġħħiáiâiäiàiāiåiãićičiċiđiéiêiëiėièiēiğiġiħiíiîiïiīiňiñióiôiöiòiőiõiřiśišiüiùiūiůiźižiżíáíbíčíéíðífíhíiíjíkílíľíňíñíóíříšítíťíþížîiîkîlîtîțïbïfïïïjïkïlïtìtībīčīfīģīhījīkīķīlīļīšītīžįėįšįžjájăjâjäjàjājåjãjčjċjéjëjėjèjējġjħjíjījňjójôjöjòjőjõjřjśjšjújüjūjůjžjżlálălâlälàlālålãlčlélêlëlèlēlğlħlîlìlīlńlňlôlölòlőlõlšlülùlūlůlžĺňĺžľaľbľčľdľgľhľjľkľmľnľňľoľrľsľšľtľuľúľvľžļāļēļīļķļšļūļžłółtńkňáňhňkňůñáñéñiñíñóóáóbóčóéóðófóhóióíójókólółóňóóóöóśótóþóúóüóźóžóżôbôčôhôjôkôlôľôňôšôtôťôžöäöböðöföğößöhöiöjökölöööõötőáőbőéőfőhőiőíőjőkőlőóőöőőőtőúőüõbõhõiõjõkõlõõõtřářbřčřhřiřířkřlřňřšřtřůřžśbśćślśńšášāšbšćščšéšėšēšģšhšišíšīšįšjškšķšlšľšļšňššštšťšúšüšūšůšžtátătâtätàtātåtãtċtétětêtëtėtètētħtîtìtītňtótôtötòtőtõtřtštütùtūtůtžťaťáťcťčťdťhťjťkťlťmťnťoťpťrťsťšťtťuťůțățâúáúbúčúðúfúhúiúíújúkúlúľúňúñúřúšútúťúžûlûtüäübüéüèüfüğüßühüiüíüjükülütüüűbűfűhűiűjűkűlűtūbūčūfūhūjūkūķūlūļūšūtūžůbůčůhůjůkůlůřůtůžýáýbýčýðýfýhýiýjýkýlýľýňýóýöýřýšýtýťýþýžzčźbźćźjźkźlźńžážäžāžbžčžđžéžėžēžfžģžhžižížīžįžjžkžlžľžňžšžtžúžüžūžůžžżèżiżjżóżżągąjąpçççgçpęgępgļgșįgįjįpjçjįjųķgļgļģļjļļļņļpņgņjņķņņņppșşçşgşpşşşyșpųjųpyçyş\n\n"""
LC_PUNCTUATIONS = """.a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z.,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/\\a\\b\\c\\d\\e\\f\\g\\h\\i\\j\\k\\l\\m\\n\\o\\p\\q\\r\\s\\t\\u\\v\\w\\x\\y\\z\\:a:b:c:d:e:f:g:h:i:j:k:l:m:n:o:p:q:r:s:t:u:v:w:x:y:z:;a;b;c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;¡!¡a!a¡b!b¡c!c¡d!d¡e!e¡f!f¡g!g¡h!h¡i!i¡j!j¡k!k¡l!l¡m!m¡n!n¡o!o¡p!p¡q!q¡r!r¡s!s¡t!t¡u!u¡v!v¡w!w¡x!x¡y!y¡z!z¿?¿a?a¿b?b¿c?c¿d?d¿e?e¿f?f¿g?g¿h?h¿i?i¿j?j¿k?k¿l?l¿m?m¿n?n¿o?o¿p?p¿q?q¿r?r¿s?s¿t?t¿u?u¿v?v¿w?w¿x?x¿y?y¿z?z(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)(l)(m)(n)(o)(p)(q)(r)(s)(t)(u)(v)(w)(x)(y)(z)[a][b][c][d][e][f][g][h][i][j][k][l][m][n][o][p][q][r][s][t][u][v][w][x][y][z]{a}{b}{c}{d}{e}{f}{g}{h}{i}{j}{k}{l}{m}{n}{o}{p}{q}{r}{s}{t}{u}{v}{w}{x}{y}{z}“.”.“,”,“:”:“;”;“-”-“–”–“—”—”“a”a“b”b“c”c“d”d“e”e“f”f“g”g“h”h“i”i“j”j“k”k“l”l“m”m“n”n“o”o“p”p“q”q“r”r“s”s“t”t“u”u“v”v“w”w“x”x“y”y“z”z‘a’‘b’‘c’‘d’‘e’‘f’‘g’‘h’‘i’‘j’‘k’‘l’‘m’‘n’‘o’‘p’‘q’‘r’‘s’‘t’‘u’‘v’‘w’‘x’‘y’‘z’’a’b’c’d’e’f’g’h’i’j’k’l’m’n’o’p’q’r’s’t’u’v’w’x’y’z’«a»«b»«c»«d»«e»«f»«g»«h»«i»«j»«k»«l»«m»«n»«o»«p»«q»«r»«s»«t»«u»«v»«w»«x»«y»«z»‹a›‹b›‹c›‹d›‹e›‹f›‹g›‹h›‹i›‹j›‹k›‹l›‹m›‹n›‹o›‹p›‹q›‹r›‹s›‹t›‹u›‹v›‹w›‹x›‹y›‹z›»a«»b«»c«»d«»e«»f«»g«»h«»i«»j«»k«»l«»m«»n«»o«»p«»q«»r«»s«»t«»u«»v«»w«»x«»y«»z«›a‹›b‹›c‹›d‹›e‹›f‹›g‹›h‹›i‹›j‹›k‹›l‹›m‹›n‹›o‹›p‹›q‹›r‹›s‹›t‹›u‹›v‹›w‹›x‹›y‹›z‹*a*b*c*d*e*f*g*h*i*j*k*l*m*n*o*p*q*r*s*t*u*v*w*x*y*z*®a®b®c®d®e®f®g®h®i®j®k®l®m®n®o®p®q®r®s®t®u®v®w®x®y®z®™a™b™c™d™e™f™g™h™i™j™k™l™m™n™o™p™q™r™s™t™u™v™w™x™y™z™&a&b&c&d&e&f&g&h&i&j&k&l&m&n&o&p&q&r&s&t&u&v&w&x&y&z&@a@a@b@c@d@e@f@g@h@i@j@k@l@m@n@o@p@q@r@s@t@u@v@w@x@y@z@-a-b-c-d-e-f-g-h-i-j-k-l-m-n-o-p-q-r-s-t-u-v-w-x-y-z--a-b-c-d-e-f-g-h-i-j-k-l-m-n-o-p-q-r-s-t-u-v-w-x-y-z-æaæbæcædææeæfægæhæiæjækælæmænæoææpæqæræsætæuævæwæxæyæzæœaœbœcœdœeœfœgœhœiœjœkœlœmœœnœoœpœqœrœsœtœuœvœwœxœyœzœßaßbßcßdßeßfßgßhßißjßkßßlßmßnßoßpßqßrßsßtßußvßwßxßyßzß\n\n"""
CAPS = """AAEAOAIAUACADAHAMANARASATABAGAFALAPAVAWAYAJAKAQAXAZAEEOEIEUECEDEHEMENERESETEBEGEFELEPEVEWEYEJEKEQEEXEZEOOIOUOCODOHOMONOROSOTOBOGOFOLOPOVOWOYOJOKOQOXOZOIIUICIDIHIMINIRISITIBIGIFILIPIVIWIYIJIKIQIXIZIUUCUDUHUMUNURUSUTUBUGUFULUPUVUWUYUJUKUQUXUZUCCDCHCMCNCRCSCTCBCGCFCLCPCVCWCYCJCKCQCXCZCDDHDMDNDRDSDTDBDGDFDLDPDVDWDYDJDKDQDXDZDHHMHNHRHSHTHBHGHFHLHPHVHWHYHJHKHQHXHZHMMMNMRMSMTMBMGMFMLMPMVMWMYMJMKMQMXMZMNNRNSNTNBNGNFNLNPNVNWNYNJNKNQNXNZNRRSRTRBRGRFRLRPRVRWRYRJRKRQRXRZRSSTSBSGSFSLSPSVSWSYSJSKSQSXSZSTTBTGTFTLTPTVTWTYTJTKTQTXTZTBBGBFBLBPBVBWBYBJBKBQBXBZBGGFGLGPGVGWGYGJGKGQGXGZGFFLFPFVFWFYFJFKFQFXFZFLLPLVLWLYLJLKLLQLXLZLPPVPWPYPJPKPQPPXPZPVVWVYVJVKVQVXVZVYYWYYYJYKYQYXYZYJJKJQJXJZJKKKQKXKZKQQXQZQXXZXZZAAEAOAIAUACADAHAMANARAASATABAGAFALAPAVAWAYAJAKAQAXAEAZAEEOEIEUECEDEHEMENERESETEBEGEFELEPEVEWEYEJEKEQEEXEZEOOIOUOCODOHOMONOROOSOTOBOGOFOLOPOVOWOYOJOKOQOOXOZOIIUICIDIHIMINIRISIITIBIGIFILIPIVIWIYIJIKIQIXIZIUUCUDUHUMUNURUSUTUUBUGUFULUPUVUWUYUJUKUQUXUZUCCCDCHCMCNCRCSCTCBCGCFCLCCPCVCWCYCJCKCQCXCZCDDHDMDNDDRDSDTDBDGDFDLDPDVDWDYDJDDKDQDXDZDHHMHNHRHSHTHBHGFHLHPHVHWHYHJHKHQHXHZHMMNMRMSMTMBMGMFMLMPMVMWMYMMJMKMQMXMZMNNRNSNTNBNGNFNLNPNVNWNYNJNKNQNXNZNRRSRRTRBRGRFRLRPRVRWRYRJRKRRQRXRZRSSTSBSGSFSLSPSVSWSYSSJSKSQSXSZSTTBTGTFTLTPTVTWTTYTJTKTQTXTZTBBGBFBLBPBBVBWBYBJBKBQBXBZBGGFGLGPGGVGWGYGJGKGQGXGZGFFLFPFVFFWFYFJFKFQFXFZFLLPLVLWLYLJLLKLQLXLZLPPVPWPYPJPKPQPPXPZPVVWVYVJVKVQVXVZVYYWYYYJYKYQYXYZYJJKJQJXJZJKKKQKKXKZKQQXQZQXXZXZZ ÞAÞBÞCÞDÞEÞFÞGÞHÞIÞJÞKÞLÞMÞNÞOÞPÞQÞRÞSÞTÞUÞVÞWÞXÞYÞZÞÆAÆBÆCÆDÆEÆFÆGÆHÆIÆJÆKÆLÆMÆNÆOÆPÆQÆRÆSÆTÆUÆVÆWÆXÆYÆZÆ HE IS BUT AN IT AT THE SHE DO ON HIS NOT LIKE OF THE MARE AS THEY CAN BOTH BEFORE OR BE IN WITH HIS TOO IN FROM WERE BY ONLY SOME HER HAVE TO AFTER THAT THAN WHICH YOU ALSO HAD EITHER.\n\n"""
CAPS_LC_ACCENTS = """BħBîBìBīBřCăCâCäCàCāCãCčCêCëCėCèCēCíCîCìCīCłCňCóCôCöCòCõCšCúCüCūCůCžĆfČāČčČėČēČfČíČīČňČřČšČúČūČůÇàÇãÇëÇóÇöÇòÇõÇúÇüĊċĊħDħDíDîDìDīDřĐiĐíEăEâEäEàEāEãEčEêEëEēEğEħEíEîEïEīEłEńEňEñEóEöEòEøEõEřEśEšEúEüEūEůEźEžEżÉâÉčÉèÉðÉřÉšÉüÉžĚčĚňĚřĚšĚzĚžĖčĖšĖžĒšĒžĘłĘśĘšĘźĘžĘżFáFăFâFäFàFāFåFãFéFêFëFėFèFēFħFíFīFňFóFöFòFőFõFšFúFûFüFűFūFůFýGăGâGäGàGāGåGãGéGêGëGėGèGēGġGħGíGìGīGłGóGôGöGòGőGõGřGšGúGüGùGűGūGůGýGžGżĞfĞiĞüĢāĢēĢīĠàĠfĠġĠiĠżHáHăHâHäHàHāHåHãHčHéHêHëHėHèHēHíHìHīHĺHłHňHóHôHöHòHőHõHřHśHšHúHüHűHūHůHýHžHżĦġĦħĦżIáIâIäIàIāIåIãIćIčIċIéIêIëIėIèIēIğIġIħIíIîIïIīIłIńIňIñIóIôIöIòIőIõIřIśIšIúIüIùIűIūIůIźIžIżÍáÍbÍčÍéÍfÍhÍiÍjÍkÍlÍľÍňÍñÍoÍóÍřÍšÍtÍťÍþÍžÎiÎkÎlÎtÎțÏbÏfÏïÏjÏkÏlÏtÌtĪbĪčĪfĪģĪhĪjĪkĪķĪlĪļĪšĪtĪžĮėĮšĮžJħJíJīJłJřKăKâKäKàKāKåKćKčKċKéKêKëKėKèKēKħKíKīKĺKłKňKóKôKöKòKőKøKõKřKśKšKúKüKűKūKůKýKžKżĶāĶēĶīĶšĶūĽbĽčĽdĽhĽjĽkĽňĽšĽtĽúĽvĽžŁwŁyMħMíMìMīMłMřNħNíNîNìNīÑiÑíOíOîOïOīOřÓíŐíØiØjØkØlPáPăPâPäPàPāPåPãPćPčPéPěPêPëPėPèPēPíPîPìPīPłPńPňPóPôPöPòPőPõPřPšPúPüPűPūPůPýPžRăRâRäRàRāRåRãRćRčRċRéRêRëRėRèRēRġRħRíRîRìRīRłRňRóRôRöRòRőRøRõRśRšRúRûRüRùRűRūRůRýRžRżŔčŔňŔšŔžŘáŘčŘiŘíŘňŘšŘůSáSăSâSäSàSāSåSãSčSéSêSëSėSèSēSħSíSîSìSīSłSňSóSôSöSòSőSõSšSúSûSüSùSűSūSůSýSžŚćŚńŠáŠāŠćŠčŠéŠėŠēŠģŠíŠīŠňŠšŠúŠüŠūŠůŠžŞöŞüȘăȘâTáTăTâTäTàTāTåTãTčTċTéTěTêTëTėTèTēTħTíTîTìTīTĺTłTňTóTôTöTòTőTøTõTřTšTúTüTùTűTūTůTýTžŤáŤčŤjŤkŤlŤšŤůȚăȚâUħUíUîUïUìUīUřÚiÚíÚřÜíŮřVáVăVâVäVàVāVåVãVčVéVěVêVëVėVèVēVíVìVīVĺVňVóVôVöVòVőVøVõVřVšVúVüVűVūVůVýVžWáWäWàWéWêWèWġWħWíWîWłWóWöWśWüWżXáXăXàXåXãXéXêXëXèXħXíXóXôXòXøXõXúXůXýYáYäYàYåYćYčYéYèYíYłYńYňYóYöYòYőYøYřYśYšYúYüYűYůYźYžYżÝaÝáÝbÝcÝčÝdÝðÝňÝóÝöÝřÝšÝþÝžZíZîZīZłZřZýŽíŽīŻłĄgĄjĄpÇçÇgÇpÇyĘgĘpĮgĮjĮpĶgĻgĻģĻjĻķĻļĻņĻpŅgŅģŅjŅķŅņŅpŞçŞgŞpŞşŞyȘpŲjŲp\n\n"""
CAPS_LC = """TaTbTcTdTeTfTgThTiTjTkTlTmTnToTpTqTrTsTtTuTvTwTxTyTzTœTæTßTfiTflVaVbVcVdVeVfVgVhViVjVkVlVmVnVoVpVqVrVsVtVuVvVwVxVyVzVœVæVßVfiVflWaWbWcWdWeWfWgWhWiWjWkWlWmWnWoWpWqWrWsWtWuWvWwWxWyWzWœWæWßWfiWflYaYbYcYdYeYfYgYhYiYjYkYlYmYnYoYpYqYrYsYtYuYvYwYxYyYzYœYæYßYfiYflKaKbKcKdKeKfKgKhKiKjKkKlKmKnKoKpKqKrKsKtKuKvKwKxKyKzRaRbRcRdReRfRgRhRiRjRkRlRmRnRoRpRqRrRsRtRuRvRwRxRyRzJaJbJcJdJeJfJgJhJiJjJkJlJmJnJoJpJqJrJsJtJuJvJwJxJyJzPaPbPcPdPePfPgPhPiPjPkPlPmPnPoPpPqPrPsPtPuPvPwPxPyPzFaFbFcFdFeFfFgFhFiFjFkFlFmFnFoFpFqFrFsFtFuFvFwFxFyFzAaAbAcAdAeAfAgAhAiAjAkAlAmAnAoApAqArAsAtAuAvAwAxAyAzAœAæAßAfiAflFœFæFßFfiFflKœKæKßKfiKflPœPæPßPfiPflLaLbLcLdLeLfLgLhLiLjLkLlLmLnLoLpLqLrLsLtLuLvLwLxLyLzLœLæLßLfiLflBaBbBcBdBeBfBgBhBiBjBkBlBmBnBoBpBqBrBsBtBuBvBwBxByBzBœBæBßBfiBflRœRæRßRfiRflSaSbScSdSeSfSgShSiSjSkSlSmSnSoSpSqSrSsStSuSvSwSxSySzSœSæSßSfiSflCaCbCcCdCeCfCgChCiCjCkClCmCnCoCpCqCrCsCtCuCvCwCxCyCzCœCæCßCfiCflDaDbDcDdDeDfDgDhDiDjDkDlDmDnDoDpDqDrDsDtDuDvDwDxDyDzDœDæDßDfiDflEaEbEcEdEeEfEgEhEiEjEkElEmEnEoEpEqErEsEtEuEvEwExEyEzEœEæEßEfiEflNaNbNcNdNeNfNgNhNiNjNkNlNmNnNoNpNqNrNsNtNuNvNwNxNyNzNœNæNßNfiNflGaGbGcGdGeGfGgGhGiGjGkGlGmGnGoGpGqGrGsGtGuGvGwGxGyGzGœGæGßGfiGflOaObOcOdOeOfOgOhOiOjOkOlOmOnOoOpOqOrOsOtOuOvOwOxOyOzOœOæOßOfiOflQaQbQcQdQeQfQgQhQiQjQkQlQmQnQoQpQqQrQsQtQuQvQwQxQyQzQœQæQßQfiQflHaHbHcHdHeHfHgHhHiHjHkHlHmHnHoHpHqHrHsHtHuHvHwHxHyHzHœHæHßHfiHflIaIbIcIdIeIfIgIhIiIjIkIlImInIoIpIqIrIsItIuIvIwIxIyIzIœIæIßIfiIflJœJæJßJfiJflMaMbMcMdMeMfMgMhMiMjMkMlMmMnMoMpMqMrMsMtMuMvMwMxMyMzMœMæMßMfiMflUaUbUcUdUeUfUgUhUiUjUkUlUmUnUoUpUqUrUsUtUuUvUwUxUyUzUœUæUßUfiUflXaXbXcXdXeXfXgXhXiXjXkXlXmXnXoXpXqXrXsXtXuXvXwXxXyXzXœXæXßXfiXflZaZbZcZdZeZfZgZhZiZjZkZlZmZnZoZpZqZrZsZtZuZvZwZxZyZzZœZæZßZfiZfl The His She Her It Some Only It’s Also That There Is He She They Any Who Which You What Where To On As At We If Any This In One Are After All How When Many My Do You Their.\n\n"""
CAPS_ACCENTS = LC_ACCENTS.upper()
CAPS_PUNCTUATIONS = """.“.”'A'B'C'D'E'F'G'H'I'J'K'L'M'N'O'P'Q'R'S'T'U'V'W'X'Y'Z'.A.B.C.D.E.F.G.H.I.J.K.L.M.N.O.P.Q.R.S.T.T.U.V.W.X.Y.Z.,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,/A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/U/V/W/X/Y/Z/\\A\\B\\C\\D\\E\\F\\G\\H\\I\\J\\K\\L\\M\\N\\O\\P\\Q\\R\\S\\T\\U\\V\\W\\X\\Y\\Z\\:A:B:C:D:E:F:G:H:I:J:K:L:M:N:O:P:Q:R:S:T:U:V:W:X:Y:Z:;A;B;C;D;E;F;G;H;I;J;K;L;M;N;O;P;Q;R;S;T;U;V;W;X;Y;Z;¡!¡A!A¡B!B¡C!C¡D!D¡E!E¡F!F¡G!G¡H!H¡I!I¡J!J¡K!K¡L!L¡M!M¡N!N¡O!O¡P!P¡Q!Q¡R!R¡S!S¡T!T¡U!U¡V!V¡W!W¡X!X¡Y!Y¡Z!Z¿?¿A?A¿B?B¿C?C¿D?D¿E?E¿F?F¿G?G¿H?H¿I?I¿J?J¿K?K¿L?L¿M?M¿N?N¿O?O¿P?P¿Q?Q¿R?R¿S?S¿T?T¿U?U¿V?V¿W?W¿X?X¿Y?Y¿Z?Z(A)(B)(C)(D)(E)(F)(G)(H)(I)(J)(K)(L)(M)(N)(O)(P)(Q)(R)(S)(T)(U)(V)(W)(X)(Y)(Z)[A][B][C][D][E][F][G][H][I][J][K][L][M][N][O][P][Q][R][S][T][U][V][W][X][Y][Z]{A}{B}{C}{D}{E}{F}{G}{H}{I}{J}{K}{L}{M}{N}{O}{P}{Q}{R}{S}{T}{U}{V}{W}{X}{Y}{Z}”“A”A“B”B“C”C“D”D“E”E“F”F“G”G“H”H“I”I“J”J“K”K“L”L“M”M“N”N“O”O“P”P“Q”Q“R”R“S”S“T”T“U”U“V”V“W”W“X”X“Y”Y“Z”Z”‘A’‘B’‘C’‘D’‘E’‘F’‘G’‘H’‘I’‘J’‘K’‘L’‘M’‘N’‘O’‘P’‘Q’‘R’‘S’‘T’‘U’‘V’‘W’‘X’‘Y’‘Z’’A’B’C’D’E’F’G’H’I’J’K’L’M’N’O’P’Q’R’S’T’U’V’W’X’Y’Z’«A»«B»«C»«D»«E»«F»«G»«H»«I»«J»«K»«L»«M»«N»«O»«P»«Q»«R»«S»«T»«U»«V»«W»«X»«Y»«Z»‹A›‹B›‹C›‹D›‹E›‹F›‹G›‹H›‹I›‹J›‹K›‹L›‹M›‹N›‹O›‹P›‹Q›‹R›‹S›‹T›‹U›‹V›‹W›‹X›‹Y›‹Z›»A«»B«»C«»D«»E«»F«»G«»H«»I«»J«»K«»L«»M«»N«»O«»P«»Q«»R«»S«»T«»U«»V«»W«»X«»Y«»Z«›A‹›B‹›C‹›D‹›E‹›F‹›G‹›H‹›I‹›J‹›K‹›L‹›M‹›N‹›O‹›P‹›Q‹›R‹›S‹›T‹›U‹›V‹›W‹›X‹›Y‹›Z‹*A*B*C*D*E*F*G*H*I*J*K*L*M*N*O*P*Q*R*S*T*U*V*W*X*Y*Z*®A®B®C®D®E®F®G®H®I®J®K®L®M®N®O®P®Q®R®S®T®U®V®W®X®Y®Z®™A™B™C™D™E™F™G™H™I™J™K™L™M™N™O™P™Q™R™S™T™U™V™W™X™Y™Z™&A&B&C&D&E&F&G&H&I&J&K&L&M&N&O&P&Q&R&S&T&U&V&W&X&Y&Z&@A@A@B@C@D@E@F@G@H@I@J@K@L@M@N@O@P@Q@R@S@T@U@V@W@X@Y@Z@-A-B-C-D-E-F-G-H-I-J-K-L-M-N-O-P-Q-R-S-T-U-V-W-X-Y-Z-æAæBæCæDææEæFæGæHæIæJæKæLæMæNæOææPæQæRæSæTæUæVæWæXæYæZæœAœBœCœDœEœFœGœHœIœJœKœLœMœœNœOœPœQœRœSœTœUœVœWœXœYœZœßAßBßCßDßEßFßGßHßIßJßKßßLßMßNßOßPßQßRßSßTßUßVßWßXßYßZß“¿Que?”“¡Que!”“nn.”“nn,”“nn”.“nn”, Fin.\n\n"""
FIGURES = """0102030405060708090.0,0;0:<0>0=0+0€0$0£0¥0f0ƒ0#0§0¶%0‰0¢0ª0º0°112131415161718191011.1,1;1:1<1>1=1+1€1$1£1¥1f1ƒ1#1§1¶11%1‰1¢1ª1º1°212232425262728292022.2,2;2:22<2>2=2+2€2$2£2¥2f2ƒ2#2§2¶22%2‰2¢2ª2º2°313233435363738393033.3,3;3:33<3>3=3+3€3$3£3¥3f3ƒ3#3§3¶33%3‰3¢3ª3º3°414243445464748494044.4,4;4:44<4>4=4+4€4$4£4¥4f4ƒ4#4§4¶44%4‰4¢4ª4º4°515253545565758595055.5,5;5:55<5>5=5+5€5$5£5¥5f5ƒ5#5§5¶55%5‰5¢5ª5º5°616263646566768696066.6,6;6:66<6>6=6+6€6$6£6¥6f6ƒ6#6§6¶66%6‰6¢6ª6º6°717273747576778797077.7,7;7:77<7>7=7+7€7$7£7¥7f7ƒ7#7§7¶77%7‰7¢7ª7º7°818283848586878898088.8,8;8:88<8>8=8+8€8$8£8¥8f8ƒ8#8§8¶88%8‰8¢8ª8º8°919293949596979899099.9,9;9:9<9>9=9+9€9$9£9¥9f9ƒ9#9§9¶99%9‰9¢9ª9º9°0/1/2/3/4/5/6/7/8/9/\n\n"""
FIGURES_FRACTIONS = """01234567890.,"""
FIGURE_WORDS = """$65.23 €65.23 Sale 23% 1.2357 Quick Brown Foxes 2022-04-31 12+34+56+78+90 123/456 12 Aardvarks 243 Ablutions 465 Adventures 687 Aeolians 876 Ahoys 955 Aileron 1433 America 869 Anecdotes 437 Aortas. TRÆR ÆRVERDIG FÆRRE SÆTH NÆST ØRBÆK LÆRING SÆD NÆR SKÆR
\n\n"""
CAP_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LC_CHARS = CAP_CHARS.lower()

DIACRITICS = """Tīri çağ, Fu-ťien or Ærø krikľúň fésű? Įjungti trionfò příď! Işçi literatūrinė »gefäß« fået vadībā reîntâlni. ÞÝÐA GROẞBUCH GRÜN BRØD MOĦĦ?! IJmuiden krągły ĉeĥe bæði ģīmis “īkšķi Třešť” veľko stýfður fīča „SDĽ“ lijst.
Înjurând pițigăiat, zoofobul comandă vexat whisky și tequila. Luís argüia à Júlia que «brações, fé, chá, óxido, pôr, zângão» eram palavras do português. Dość gróźb fuzją, klnę, pych i małżeństw! Pójdź w loch zbić małżeńską gęś futryn! Vår sære Zulu fra badeøya spilte jo whist og quickstep i min taxi. Įlinkdama fechtuotojo špaga sublykčiojusi pragręžė apvalų arbūzą. Muļķa hipiji mēģina brīvi nogaršot celofāna žņaudzējčūsku. Kæmi ný öxi hér, ykist þjófum nú bæði víl og ádrepa. Jó foxim és don Quijote húszwattos lámpánál ülve egy pár bűvös cipőt készít. Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich. Voix ambiguë d’un cœur qui au zéphyr préfère les jattes de kiwi. Bâchez la queue du wagon-taxi avec les pyjamas du fakir. Hyvän lorun sangen pieneksi hyödyksi jäi suomen kirjaimet. See väike mölder jõuab rongile hüpata. Eble ĉiu kvazaŭ-deca fuŝĥoraĵo ĝojigos homtipon. Høj bly gom vandt fræk sexquiz på wc. Příliš žluťoučký kůň úpěl ďábelské ódy. Hleď, toť přízračný kůň v mátožné póze šíleně úpí. Kŕdeľ ďatľov učí koňa žrať kôru. Hišničin bratec vzgaja polže pod fikusom. Això, il·lús company geniüt, ja és un lluït rètol blavís d’onze kWh. Gojazni đačić s biciklom drži hmelj i finu vatu u džepu nošnje. El veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja. Zəfər, jaketini də papağını da götür, bu axşam hava çox soyuq olacaq. Byxfjärmat föl gick på duvshowen. Öküz ajan hapse düştü yavrum, ocağı felç gibi.\n\n"""

SAMPLES = PRE + LC + LC_ACCENTS + LC_PUNCTUATIONS + CAPS + CAPS_LC_ACCENTS + CAPS_LC + CAPS_ACCENTS + CAPS_PUNCTUATIONS + FIGURES + FIGURES_FRACTIONS + FIGURE_WORDS

from .cyrillic import *
from .dutch import *
from .jills import *
from .spacing import *
from .ulcwords import *
